/**
 * Restaurant Chain Nutrition Data
 *
 * Manually curated nutrition data for major US restaurant chains.
 * FDA requires chains with 20+ locations to publish nutrition information.
 * Data sourced from each chain's official published nutrition guides.
 *
 * All nutrition values are per single menu item serving.
 */

export interface ChainMenuItem {
  name: string;
  category: string;
  serving_size: number;
  serving_unit: string;
  calories: number;
  total_fat: number;
  saturated_fat: number;
  trans_fat: number;
  cholesterol: number;
  sodium: number;
  total_carbohydrates: number;
  dietary_fiber: number;
  total_sugars: number;
  protein: number;
  ingredients_text?: string;
}

export interface ChainData {
  chain: string;
  items: ChainMenuItem[];
}

const mcdonalds: ChainData = {
  chain: "McDonald's",
  items: [
    { name: "Big Mac", category: "Burgers", serving_size: 200, serving_unit: "g", calories: 550, total_fat: 30, saturated_fat: 11, trans_fat: 1, cholesterol: 80, sodium: 1010, total_carbohydrates: 45, dietary_fiber: 3, total_sugars: 9, protein: 25, ingredients_text: "beef patty, enriched flour bun, sesame seeds, american cheese, lettuce, pickle, onion, big mac sauce (soybean oil, egg yolk, mustard, wheat)" },
    { name: "Quarter Pounder with Cheese", category: "Burgers", serving_size: 202, serving_unit: "g", calories: 520, total_fat: 26, saturated_fat: 12, trans_fat: 1.5, cholesterol: 95, sodium: 1140, total_carbohydrates: 42, dietary_fiber: 2, total_sugars: 10, protein: 30, ingredients_text: "beef patty, enriched flour bun, sesame seeds, american cheese, pickle, onion, ketchup, mustard, wheat" },
    { name: "McChicken", category: "Chicken & Sandwiches", serving_size: 143, serving_unit: "g", calories: 400, total_fat: 21, saturated_fat: 3.5, trans_fat: 0, cholesterol: 40, sodium: 560, total_carbohydrates: 39, dietary_fiber: 2, total_sugars: 5, protein: 14, ingredients_text: "chicken patty (chicken, wheat flour, water, salt), enriched flour bun, lettuce, mayonnaise (soybean oil, egg)" },
    { name: "10 Piece Chicken McNuggets", category: "Chicken & Sandwiches", serving_size: 162, serving_unit: "g", calories: 410, total_fat: 24, saturated_fat: 4, trans_fat: 0, cholesterol: 65, sodium: 900, total_carbohydrates: 26, dietary_fiber: 1, total_sugars: 0, protein: 23, ingredients_text: "chicken, water, enriched flour (wheat), corn flour, salt, leavening, spices, corn starch, soybean oil" },
    { name: "Filet-O-Fish", category: "Fish", serving_size: 136, serving_unit: "g", calories: 390, total_fat: 19, saturated_fat: 4, trans_fat: 0, cholesterol: 40, sodium: 580, total_carbohydrates: 39, dietary_fiber: 2, total_sugars: 5, protein: 16, ingredients_text: "fish fillet (pollock), enriched flour bun, tartar sauce (soybean oil, egg, pickle), american cheese, wheat" },
    { name: "Medium French Fries", category: "Sides", serving_size: 111, serving_unit: "g", calories: 320, total_fat: 15, saturated_fat: 2, trans_fat: 0, cholesterol: 0, sodium: 260, total_carbohydrates: 43, dietary_fiber: 4, total_sugars: 0, protein: 5, ingredients_text: "potatoes, vegetable oil (canola, soybean), salt, sodium acid pyrophosphate, dextrose" },
    { name: "Hash Browns", category: "Breakfast", serving_size: 56, serving_unit: "g", calories: 140, total_fat: 8, saturated_fat: 1, trans_fat: 0, cholesterol: 0, sodium: 300, total_carbohydrates: 16, dietary_fiber: 2, total_sugars: 0, protein: 1, ingredients_text: "potatoes, vegetable oil (canola, soybean, hydrogenated soybean oil), salt, dehydrated potato, sodium acid pyrophosphate" },
    { name: "Egg McMuffin", category: "Breakfast", serving_size: 137, serving_unit: "g", calories: 300, total_fat: 13, saturated_fat: 6, trans_fat: 0, cholesterol: 260, sodium: 770, total_carbohydrates: 26, dietary_fiber: 1, total_sugars: 3, protein: 17, ingredients_text: "english muffin (enriched flour, wheat), egg, canadian bacon (pork), american cheese, butter, wheat" },
    { name: "Sausage McMuffin with Egg", category: "Breakfast", serving_size: 165, serving_unit: "g", calories: 480, total_fat: 31, saturated_fat: 12, trans_fat: 0, cholesterol: 285, sodium: 830, total_carbohydrates: 29, dietary_fiber: 2, total_sugars: 3, protein: 21, ingredients_text: "english muffin (enriched flour, wheat), sausage patty (pork, salt, spices), egg, american cheese, butter" },
    { name: "Hotcakes", category: "Breakfast", serving_size: 221, serving_unit: "g", calories: 580, total_fat: 16, saturated_fat: 5, trans_fat: 0, cholesterol: 20, sodium: 600, total_carbohydrates: 101, dietary_fiber: 2, total_sugars: 45, protein: 9, ingredients_text: "enriched flour (wheat), water, sugar, eggs, butter, leavening, corn syrup, maple flavored syrup, milk" },
    { name: "McFlurry with OREO Cookies", category: "Desserts", serving_size: 285, serving_unit: "g", calories: 510, total_fat: 17, saturated_fat: 9, trans_fat: 0, cholesterol: 50, sodium: 280, total_carbohydrates: 80, dietary_fiber: 1, total_sugars: 63, protein: 11, ingredients_text: "vanilla reduced fat ice cream (milk, sugar, cream, corn syrup), oreo cookie pieces (wheat flour, sugar, palm oil, cocoa)" },
    { name: "Medium Coca-Cola", category: "Beverages", serving_size: 620, serving_unit: "ml", calories: 210, total_fat: 0, saturated_fat: 0, trans_fat: 0, cholesterol: 0, sodium: 5, total_carbohydrates: 58, dietary_fiber: 0, total_sugars: 58, protein: 0, ingredients_text: "carbonated water, high fructose corn syrup, caramel color, phosphoric acid, natural flavors, caffeine" },
    { name: "Apple Slices", category: "Sides", serving_size: 34, serving_unit: "g", calories: 15, total_fat: 0, saturated_fat: 0, trans_fat: 0, cholesterol: 0, sodium: 0, total_carbohydrates: 4, dietary_fiber: 0, total_sugars: 3, protein: 0, ingredients_text: "apples, calcium ascorbate" },
    { name: "Side Salad", category: "Salads", serving_size: 87, serving_unit: "g", calories: 15, total_fat: 0, saturated_fat: 0, trans_fat: 0, cholesterol: 0, sodium: 10, total_carbohydrates: 3, dietary_fiber: 1, total_sugars: 2, protein: 1, ingredients_text: "lettuce, tomato, carrot, red cabbage" },
    { name: "Double Cheeseburger", category: "Burgers", serving_size: 168, serving_unit: "g", calories: 450, total_fat: 24, saturated_fat: 11, trans_fat: 1.5, cholesterol: 85, sodium: 1120, total_carbohydrates: 34, dietary_fiber: 2, total_sugars: 7, protein: 25, ingredients_text: "beef patties, enriched flour bun, american cheese, pickle, onion, ketchup, mustard, wheat" },
    { name: "Crispy Chicken Sandwich", category: "Chicken & Sandwiches", serving_size: 209, serving_unit: "g", calories: 470, total_fat: 20, saturated_fat: 3.5, trans_fat: 0, cholesterol: 50, sodium: 1140, total_carbohydrates: 46, dietary_fiber: 2, total_sugars: 9, protein: 26, ingredients_text: "chicken fillet (chicken breast, wheat flour, water), potato roll (enriched flour, wheat), pickles, butter" },
    { name: "Vanilla Cone", category: "Desserts", serving_size: 142, serving_unit: "g", calories: 200, total_fat: 5, saturated_fat: 3.5, trans_fat: 0, cholesterol: 20, sodium: 80, total_carbohydrates: 33, dietary_fiber: 0, total_sugars: 24, protein: 5, ingredients_text: "vanilla reduced fat ice cream (milk, sugar, cream, corn syrup), cone (wheat flour, sugar)" },
    { name: "Baked Apple Pie", category: "Desserts", serving_size: 77, serving_unit: "g", calories: 230, total_fat: 11, saturated_fat: 5, trans_fat: 0, cholesterol: 0, sodium: 160, total_carbohydrates: 32, dietary_fiber: 1, total_sugars: 13, protein: 2, ingredients_text: "apples, enriched flour (wheat), palm oil, sugar, corn starch, cinnamon, salt" },
    { name: "Cheeseburger", category: "Burgers", serving_size: 119, serving_unit: "g", calories: 300, total_fat: 13, saturated_fat: 6, trans_fat: 0.5, cholesterol: 45, sodium: 720, total_carbohydrates: 32, dietary_fiber: 2, total_sugars: 7, protein: 15, ingredients_text: "beef patty, enriched flour bun, american cheese, pickle, onion, ketchup, mustard, wheat" },
    { name: "Large Iced Coffee", category: "Beverages", serving_size: 946, serving_unit: "ml", calories: 260, total_fat: 11, saturated_fat: 7, trans_fat: 0, cholesterol: 40, sodium: 80, total_carbohydrates: 40, dietary_fiber: 0, total_sugars: 38, protein: 4, ingredients_text: "ice, premium roast coffee, cream, liquid sugar" },
  ],
};

const chickFilA: ChainData = {
  chain: "Chick-fil-A",
  items: [
    { name: "Chick-fil-A Chicken Sandwich", category: "Sandwiches", serving_size: 178, serving_unit: "g", calories: 440, total_fat: 19, saturated_fat: 4, trans_fat: 0, cholesterol: 70, sodium: 1400, total_carbohydrates: 40, dietary_fiber: 1, total_sugars: 5, protein: 29, ingredients_text: "chicken breast fillet (chicken, wheat flour, peanut oil, milk, egg), enriched flour bun, pickle" },
    { name: "Chick-fil-A Deluxe Sandwich", category: "Sandwiches", serving_size: 213, serving_unit: "g", calories: 500, total_fat: 22, saturated_fat: 5, trans_fat: 0, cholesterol: 80, sodium: 1640, total_carbohydrates: 43, dietary_fiber: 2, total_sugars: 7, protein: 33, ingredients_text: "chicken breast fillet (chicken, wheat flour, peanut oil, milk, egg), enriched flour bun, lettuce, tomato, american cheese, pickle" },
    { name: "Spicy Chicken Sandwich", category: "Sandwiches", serving_size: 178, serving_unit: "g", calories: 450, total_fat: 19, saturated_fat: 4, trans_fat: 0, cholesterol: 70, sodium: 1620, total_carbohydrates: 41, dietary_fiber: 2, total_sugars: 5, protein: 29, ingredients_text: "spicy chicken breast fillet (chicken, wheat flour, spices, peanut oil, milk, egg), enriched flour bun, pickle" },
    { name: "Grilled Chicken Sandwich", category: "Sandwiches", serving_size: 213, serving_unit: "g", calories: 320, total_fat: 6, saturated_fat: 1.5, trans_fat: 0, cholesterol: 80, sodium: 800, total_carbohydrates: 41, dietary_fiber: 3, total_sugars: 9, protein: 28, ingredients_text: "grilled chicken breast, multigrain brioche bun (enriched flour, wheat), lettuce, tomato" },
    { name: "Chick-fil-A Nuggets (12 count)", category: "Entrees", serving_size: 170, serving_unit: "g", calories: 380, total_fat: 17, saturated_fat: 3.5, trans_fat: 0, cholesterol: 100, sodium: 1200, total_carbohydrates: 16, dietary_fiber: 0, total_sugars: 1, protein: 40, ingredients_text: "chicken breast, wheat flour, peanut oil, milk, egg, salt, spices" },
    { name: "Grilled Nuggets (12 count)", category: "Entrees", serving_size: 170, serving_unit: "g", calories: 200, total_fat: 5, saturated_fat: 1.5, trans_fat: 0, cholesterol: 120, sodium: 660, total_carbohydrates: 2, dietary_fiber: 0, total_sugars: 1, protein: 38, ingredients_text: "chicken breast, water, salt, spices, garlic" },
    { name: "Waffle Potato Fries (Medium)", category: "Sides", serving_size: 125, serving_unit: "g", calories: 420, total_fat: 24, saturated_fat: 4, trans_fat: 0, cholesterol: 0, sodium: 380, total_carbohydrates: 45, dietary_fiber: 5, total_sugars: 1, protein: 5, ingredients_text: "potatoes, canola oil, salt" },
    { name: "Chicken Biscuit", category: "Breakfast", serving_size: 179, serving_unit: "g", calories: 440, total_fat: 19, saturated_fat: 8, trans_fat: 0, cholesterol: 40, sodium: 1290, total_carbohydrates: 46, dietary_fiber: 2, total_sugars: 6, protein: 20, ingredients_text: "chicken breast fillet (chicken, wheat flour, peanut oil), biscuit (enriched flour, butter, milk, wheat)" },
    { name: "Hash Brown Scramble Burrito", category: "Breakfast", serving_size: 227, serving_unit: "g", calories: 680, total_fat: 38, saturated_fat: 15, trans_fat: 0, cholesterol: 315, sodium: 1370, total_carbohydrates: 50, dietary_fiber: 3, total_sugars: 2, protein: 31, ingredients_text: "flour tortilla (wheat), eggs, hash browns (potatoes, canola oil), chicken, cheese (milk)" },
    { name: "Cobb Salad", category: "Salads", serving_size: 447, serving_unit: "g", calories: 510, total_fat: 27, saturated_fat: 9, trans_fat: 0, cholesterol: 210, sodium: 1310, total_carbohydrates: 24, dietary_fiber: 4, total_sugars: 6, protein: 42, ingredients_text: "romaine lettuce, grilled chicken breast, bacon (pork), cheese (milk), corn, tomato, egg, carrot" },
    { name: "Chicken Soup", category: "Sides", serving_size: 348, serving_unit: "g", calories: 240, total_fat: 7, saturated_fat: 2, trans_fat: 0, cholesterol: 55, sodium: 1380, total_carbohydrates: 21, dietary_fiber: 3, total_sugars: 2, protein: 22, ingredients_text: "chicken broth, chicken, celery, carrot, potato, wheat noodles, onion, salt" },
    { name: "Chick-fil-A Sauce", category: "Sauces", serving_size: 28, serving_unit: "g", calories: 140, total_fat: 13, saturated_fat: 2, trans_fat: 0, cholesterol: 10, sodium: 180, total_carbohydrates: 6, dietary_fiber: 0, total_sugars: 5, protein: 0, ingredients_text: "soybean oil, sugar, mustard, egg yolk, vinegar, salt, onion, garlic" },
    { name: "Large Lemonade", category: "Beverages", serving_size: 591, serving_unit: "ml", calories: 330, total_fat: 0.5, saturated_fat: 0, trans_fat: 0, cholesterol: 0, sodium: 10, total_carbohydrates: 82, dietary_fiber: 0, total_sugars: 80, protein: 0, ingredients_text: "water, sugar, lemon juice" },
    { name: "Chocolate Milkshake", category: "Beverages", serving_size: 500, serving_unit: "ml", calories: 580, total_fat: 22, saturated_fat: 14, trans_fat: 1, cholesterol: 80, sodium: 500, total_carbohydrates: 86, dietary_fiber: 1, total_sugars: 79, protein: 14, ingredients_text: "whole milk, sugar, cream, cocoa, whey (milk), vanilla" },
    { name: "Fruit Cup", category: "Sides", serving_size: 133, serving_unit: "g", calories: 60, total_fat: 0, saturated_fat: 0, trans_fat: 0, cholesterol: 0, sodium: 0, total_carbohydrates: 16, dietary_fiber: 2, total_sugars: 13, protein: 0, ingredients_text: "strawberries, blueberries, red apples, mandarin oranges" },
    { name: "Mac & Cheese", category: "Sides", serving_size: 170, serving_unit: "g", calories: 350, total_fat: 17, saturated_fat: 7, trans_fat: 0, cholesterol: 35, sodium: 870, total_carbohydrates: 32, dietary_fiber: 1, total_sugars: 3, protein: 14, ingredients_text: "pasta (wheat), cheddar cheese (milk), butter, cream (milk), salt" },
    { name: "Chick-n-Strips (4 count)", category: "Entrees", serving_size: 188, serving_unit: "g", calories: 450, total_fat: 22, saturated_fat: 4, trans_fat: 0, cholesterol: 80, sodium: 1260, total_carbohydrates: 26, dietary_fiber: 1, total_sugars: 3, protein: 38, ingredients_text: "chicken breast, wheat flour, peanut oil, milk, egg, salt, spices" },
    { name: "Cool Wrap", category: "Wraps", serving_size: 325, serving_unit: "g", calories: 350, total_fat: 13, saturated_fat: 5, trans_fat: 0, cholesterol: 75, sodium: 1110, total_carbohydrates: 29, dietary_fiber: 15, total_sugars: 4, protein: 36, ingredients_text: "flaxseed flour wrap (wheat), grilled chicken breast, lettuce, red cabbage, carrot, cheese (milk)" },
    { name: "Spicy Southwest Salad", category: "Salads", serving_size: 360, serving_unit: "g", calories: 450, total_fat: 19, saturated_fat: 6, trans_fat: 0, cholesterol: 115, sodium: 1060, total_carbohydrates: 34, dietary_fiber: 6, total_sugars: 8, protein: 33, ingredients_text: "romaine lettuce, spicy chicken breast, tomato, corn, black beans, cheese (milk), tortilla strips (wheat, corn), peppers" },
    { name: "Chocolate Chunk Cookie", category: "Desserts", serving_size: 57, serving_unit: "g", calories: 370, total_fat: 18, saturated_fat: 10, trans_fat: 0, cholesterol: 30, sodium: 250, total_carbohydrates: 49, dietary_fiber: 2, total_sugars: 29, protein: 4, ingredients_text: "enriched flour (wheat), butter, sugar, chocolate chunks, eggs, vanilla, salt" },
  ],
};

const starbucks: ChainData = {
  chain: "Starbucks",
  items: [
    { name: "Caffè Latte (Grande)", category: "Hot Coffee", serving_size: 473, serving_unit: "ml", calories: 190, total_fat: 7, saturated_fat: 4.5, trans_fat: 0, cholesterol: 25, sodium: 170, total_carbohydrates: 19, dietary_fiber: 0, total_sugars: 17, protein: 13, ingredients_text: "milk, espresso" },
    { name: "Caramel Macchiato (Grande)", category: "Hot Coffee", serving_size: 473, serving_unit: "ml", calories: 250, total_fat: 7, saturated_fat: 4.5, trans_fat: 0, cholesterol: 25, sodium: 150, total_carbohydrates: 35, dietary_fiber: 0, total_sugars: 33, protein: 10, ingredients_text: "milk, espresso, vanilla syrup (sugar, water), caramel sauce (sugar, butter, cream)" },
    { name: "Pumpkin Spice Latte (Grande)", category: "Hot Coffee", serving_size: 473, serving_unit: "ml", calories: 380, total_fat: 14, saturated_fat: 8, trans_fat: 0, cholesterol: 50, sodium: 240, total_carbohydrates: 52, dietary_fiber: 0, total_sugars: 50, protein: 14, ingredients_text: "milk, espresso, pumpkin spice sauce (sugar, condensed milk, pumpkin puree, spices), whipped cream (cream)" },
    { name: "Mocha Frappuccino (Grande)", category: "Blended Beverages", serving_size: 473, serving_unit: "ml", calories: 370, total_fat: 15, saturated_fat: 9, trans_fat: 0, cholesterol: 50, sodium: 230, total_carbohydrates: 52, dietary_fiber: 1, total_sugars: 50, protein: 6, ingredients_text: "ice, milk, coffee frappuccino syrup (sugar, water), coffee, mocha sauce (sugar, cocoa, water), whipped cream (cream)" },
    { name: "Iced Caramel Macchiato (Grande)", category: "Iced Coffee", serving_size: 473, serving_unit: "ml", calories: 250, total_fat: 7, saturated_fat: 4.5, trans_fat: 0, cholesterol: 25, sodium: 150, total_carbohydrates: 34, dietary_fiber: 0, total_sugars: 33, protein: 10, ingredients_text: "ice, milk, espresso, vanilla syrup (sugar, water), caramel sauce" },
    { name: "Cold Brew Coffee (Grande)", category: "Iced Coffee", serving_size: 473, serving_unit: "ml", calories: 5, total_fat: 0, saturated_fat: 0, trans_fat: 0, cholesterol: 0, sodium: 15, total_carbohydrates: 0, dietary_fiber: 0, total_sugars: 0, protein: 0, ingredients_text: "ice, cold brew coffee (water, coffee)" },
    { name: "Vanilla Sweet Cream Cold Brew (Grande)", category: "Iced Coffee", serving_size: 473, serving_unit: "ml", calories: 200, total_fat: 10, saturated_fat: 7, trans_fat: 0, cholesterol: 35, sodium: 30, total_carbohydrates: 24, dietary_fiber: 0, total_sugars: 24, protein: 2, ingredients_text: "ice, cold brew coffee (water, coffee), vanilla sweet cream (cream, milk, vanilla syrup)" },
    { name: "Chai Tea Latte (Grande)", category: "Hot Tea", serving_size: 473, serving_unit: "ml", calories: 240, total_fat: 4.5, saturated_fat: 2, trans_fat: 0, cholesterol: 15, sodium: 115, total_carbohydrates: 42, dietary_fiber: 0, total_sugars: 42, protein: 8, ingredients_text: "milk, chai tea concentrate (water, sugar, black tea, spices, ginger, honey)" },
    { name: "Matcha Tea Latte (Grande)", category: "Hot Tea", serving_size: 473, serving_unit: "ml", calories: 240, total_fat: 7, saturated_fat: 4.5, trans_fat: 0, cholesterol: 25, sodium: 170, total_carbohydrates: 34, dietary_fiber: 1, total_sugars: 32, protein: 12, ingredients_text: "milk, matcha tea blend (sugar, ground japanese green tea)" },
    { name: "Pink Drink (Grande)", category: "Refreshers", serving_size: 473, serving_unit: "ml", calories: 140, total_fat: 2.5, saturated_fat: 2.5, trans_fat: 0, cholesterol: 0, sodium: 65, total_carbohydrates: 27, dietary_fiber: 1, total_sugars: 25, protein: 1, ingredients_text: "strawberry acai base (water, sugar, white grape juice concentrate, strawberry puree), coconut milk" },
    { name: "Bacon, Gouda & Egg Sandwich", category: "Breakfast Sandwiches", serving_size: 110, serving_unit: "g", calories: 370, total_fat: 19, saturated_fat: 7, trans_fat: 0, cholesterol: 155, sodium: 730, total_carbohydrates: 32, dietary_fiber: 1, total_sugars: 3, protein: 18, ingredients_text: "egg patty (eggs, butter), applewood smoked bacon (pork), gouda cheese (milk), wheat english muffin (enriched flour, wheat)" },
    { name: "Sausage, Cheddar & Egg Sandwich", category: "Breakfast Sandwiches", serving_size: 117, serving_unit: "g", calories: 480, total_fat: 27, saturated_fat: 10, trans_fat: 0, cholesterol: 180, sodium: 820, total_carbohydrates: 34, dietary_fiber: 1, total_sugars: 4, protein: 17, ingredients_text: "egg patty (eggs), sausage patty (pork, salt, spices), cheddar cheese (milk), wheat english muffin (enriched flour)" },
    { name: "Spinach, Feta & Egg White Wrap", category: "Breakfast Sandwiches", serving_size: 171, serving_unit: "g", calories: 290, total_fat: 10, saturated_fat: 3.5, trans_fat: 0, cholesterol: 20, sodium: 840, total_carbohydrates: 34, dietary_fiber: 3, total_sugars: 4, protein: 20, ingredients_text: "flour tortilla (wheat), egg whites, spinach, feta cheese (milk), tomato, sun-dried tomato" },
    { name: "Butter Croissant", category: "Bakery", serving_size: 71, serving_unit: "g", calories: 260, total_fat: 14, saturated_fat: 8, trans_fat: 0, cholesterol: 35, sodium: 300, total_carbohydrates: 28, dietary_fiber: 1, total_sugars: 4, protein: 5, ingredients_text: "enriched flour (wheat), butter, sugar, yeast, eggs, milk, salt" },
    { name: "Chocolate Chip Cookie", category: "Bakery", serving_size: 71, serving_unit: "g", calories: 360, total_fat: 16, saturated_fat: 10, trans_fat: 0, cholesterol: 25, sodium: 280, total_carbohydrates: 50, dietary_fiber: 2, total_sugars: 32, protein: 4, ingredients_text: "enriched flour (wheat), butter, sugar, chocolate chips, eggs, vanilla, salt" },
    { name: "Banana Nut Bread", category: "Bakery", serving_size: 120, serving_unit: "g", calories: 420, total_fat: 22, saturated_fat: 3, trans_fat: 0, cholesterol: 50, sodium: 430, total_carbohydrates: 52, dietary_fiber: 3, total_sugars: 28, protein: 6, ingredients_text: "enriched flour (wheat), banana, sugar, walnuts (tree nut), eggs, canola oil, sour cream (milk)" },
    { name: "Impossible Breakfast Sandwich", category: "Breakfast Sandwiches", serving_size: 142, serving_unit: "g", calories: 420, total_fat: 22, saturated_fat: 8, trans_fat: 0.5, cholesterol: 195, sodium: 620, total_carbohydrates: 34, dietary_fiber: 3, total_sugars: 5, protein: 22, ingredients_text: "ciabatta roll (enriched flour, wheat), impossible sausage (soy protein), cage-free egg, aged cheddar cheese (milk)" },
    { name: "Chicken & Bacon Panini", category: "Lunch", serving_size: 213, serving_unit: "g", calories: 560, total_fat: 26, saturated_fat: 8, trans_fat: 0, cholesterol: 95, sodium: 1140, total_carbohydrates: 44, dietary_fiber: 2, total_sugars: 5, protein: 36, ingredients_text: "ciabatta bread (wheat flour), grilled chicken breast, smoked bacon (pork), provolone cheese (milk), tomato" },
    { name: "Protein Box (Eggs & Cheese)", category: "Lunch", serving_size: 213, serving_unit: "g", calories: 470, total_fat: 26, saturated_fat: 7, trans_fat: 0, cholesterol: 205, sodium: 690, total_carbohydrates: 40, dietary_fiber: 2, total_sugars: 18, protein: 24, ingredients_text: "hard-boiled eggs, white cheddar cheese (milk), multigrain bread (wheat), apples, peanut butter (peanuts)" },
    { name: "Cake Pop (Birthday)", category: "Bakery", serving_size: 38, serving_unit: "g", calories: 160, total_fat: 8, saturated_fat: 5, trans_fat: 0, cholesterol: 15, sodium: 110, total_carbohydrates: 22, dietary_fiber: 0, total_sugars: 17, protein: 1, ingredients_text: "sugar, enriched flour (wheat), palm kernel oil, milk, eggs, butter, cocoa butter, vanilla" },
  ],
};

const chipotle: ChainData = {
  chain: "Chipotle",
  items: [
    { name: "Chicken Burrito", category: "Burritos", serving_size: 510, serving_unit: "g", calories: 1005, total_fat: 36, saturated_fat: 13, trans_fat: 0, cholesterol: 120, sodium: 2150, total_carbohydrates: 117, dietary_fiber: 15, total_sugars: 5, protein: 59, ingredients_text: "flour tortilla (wheat), chicken, cilantro-lime white rice, black beans, tomato salsa, sour cream (milk), cheese (milk)" },
    { name: "Steak Burrito Bowl", category: "Bowls", serving_size: 470, serving_unit: "g", calories: 920, total_fat: 32, saturated_fat: 11, trans_fat: 0, cholesterol: 105, sodium: 1960, total_carbohydrates: 100, dietary_fiber: 14, total_sugars: 5, protein: 55, ingredients_text: "steak (beef), cilantro-lime white rice, pinto beans, tomato salsa, sour cream (milk), cheese (milk), lettuce" },
    { name: "Barbacoa Bowl", category: "Bowls", serving_size: 470, serving_unit: "g", calories: 880, total_fat: 32, saturated_fat: 12, trans_fat: 0, cholesterol: 110, sodium: 2010, total_carbohydrates: 100, dietary_fiber: 14, total_sugars: 5, protein: 49, ingredients_text: "barbacoa (beef, chipotle peppers, spices), cilantro-lime white rice, black beans, tomato salsa, sour cream (milk), cheese (milk)" },
    { name: "Sofritas Bowl", category: "Bowls", serving_size: 450, serving_unit: "g", calories: 805, total_fat: 30, saturated_fat: 7, trans_fat: 0, cholesterol: 25, sodium: 1720, total_carbohydrates: 106, dietary_fiber: 16, total_sugars: 7, protein: 28, ingredients_text: "sofritas (tofu, chipotle peppers, spices), cilantro-lime white rice, black beans, tomato salsa, sour cream (milk), cheese (milk)" },
    { name: "Carnitas Tacos (3)", category: "Tacos", serving_size: 340, serving_unit: "g", calories: 690, total_fat: 24, saturated_fat: 8, trans_fat: 0, cholesterol: 85, sodium: 1305, total_carbohydrates: 73, dietary_fiber: 7, total_sugars: 2, protein: 38, ingredients_text: "corn tortillas, carnitas (pork, spices), tomato salsa, sour cream (milk), cheese (milk), lettuce" },
    { name: "Chicken Quesadilla", category: "Quesadillas", serving_size: 290, serving_unit: "g", calories: 750, total_fat: 37, saturated_fat: 17, trans_fat: 0, cholesterol: 130, sodium: 1520, total_carbohydrates: 58, dietary_fiber: 3, total_sugars: 3, protein: 48, ingredients_text: "flour tortilla (wheat), chicken, cheese (milk)" },
    { name: "Chips & Guacamole", category: "Sides", serving_size: 168, serving_unit: "g", calories: 770, total_fat: 44, saturated_fat: 7, trans_fat: 0, cholesterol: 0, sodium: 540, total_carbohydrates: 81, dietary_fiber: 12, total_sugars: 2, protein: 10, ingredients_text: "corn tortilla chips (corn, sunflower oil, salt), guacamole (avocado, lime juice, cilantro, onion, jalapeno, salt)" },
    { name: "Chips & Queso Blanco", category: "Sides", serving_size: 168, serving_unit: "g", calories: 780, total_fat: 41, saturated_fat: 11, trans_fat: 0, cholesterol: 30, sodium: 1100, total_carbohydrates: 84, dietary_fiber: 6, total_sugars: 2, protein: 14, ingredients_text: "corn tortilla chips (corn, sunflower oil, salt), queso blanco (cheese (milk), peppers, spices)" },
    { name: "Chicken Salad Bowl", category: "Salads", serving_size: 410, serving_unit: "g", calories: 675, total_fat: 28, saturated_fat: 8, trans_fat: 0, cholesterol: 100, sodium: 1480, total_carbohydrates: 57, dietary_fiber: 12, total_sugars: 7, protein: 50, ingredients_text: "romaine lettuce, chicken, black beans, corn salsa, tomato salsa, cheese (milk), chipotle-honey vinaigrette" },
    { name: "Side of Guacamole", category: "Sides", serving_size: 114, serving_unit: "g", calories: 230, total_fat: 22, saturated_fat: 3, trans_fat: 0, cholesterol: 0, sodium: 375, total_carbohydrates: 8, dietary_fiber: 7, total_sugars: 1, protein: 3, ingredients_text: "avocado, lime juice, cilantro, red onion, jalapeno, salt" },
    { name: "Cilantro-Lime White Rice", category: "Sides", serving_size: 130, serving_unit: "g", calories: 210, total_fat: 4, saturated_fat: 0.5, trans_fat: 0, cholesterol: 0, sodium: 310, total_carbohydrates: 40, dietary_fiber: 0, total_sugars: 0, protein: 4, ingredients_text: "rice, rice bran oil, lime juice, cilantro, salt" },
    { name: "Pinto Beans", category: "Sides", serving_size: 120, serving_unit: "g", calories: 130, total_fat: 1.5, saturated_fat: 0, trans_fat: 0, cholesterol: 0, sodium: 350, total_carbohydrates: 22, dietary_fiber: 6, total_sugars: 0, protein: 8, ingredients_text: "pinto beans, water, onion, garlic, oregano, salt, cumin" },
    { name: "Large Chips", category: "Sides", serving_size: 114, serving_unit: "g", calories: 540, total_fat: 22, saturated_fat: 4, trans_fat: 0, cholesterol: 0, sodium: 280, total_carbohydrates: 73, dietary_fiber: 5, total_sugars: 0, protein: 7, ingredients_text: "corn, sunflower oil, salt, lime juice" },
    { name: "Veggie Bowl", category: "Bowls", serving_size: 430, serving_unit: "g", calories: 750, total_fat: 28, saturated_fat: 9, trans_fat: 0, cholesterol: 25, sodium: 1520, total_carbohydrates: 105, dietary_fiber: 18, total_sugars: 6, protein: 22, ingredients_text: "cilantro-lime white rice, black beans, fajita veggies (peppers, onion), corn salsa, tomato salsa, sour cream (milk), cheese (milk), guacamole (avocado)" },
    { name: "Steak Tacos (3)", category: "Tacos", serving_size: 340, serving_unit: "g", calories: 685, total_fat: 22, saturated_fat: 7, trans_fat: 0, cholesterol: 75, sodium: 1205, total_carbohydrates: 73, dietary_fiber: 7, total_sugars: 2, protein: 40, ingredients_text: "corn tortillas, steak (beef, spices), tomato salsa, sour cream (milk), cheese (milk), lettuce" },
    { name: "Chicken Bowl (Whole30)", category: "Bowls", serving_size: 390, serving_unit: "g", calories: 445, total_fat: 16, saturated_fat: 3, trans_fat: 0, cholesterol: 95, sodium: 960, total_carbohydrates: 36, dietary_fiber: 10, total_sugars: 6, protein: 44, ingredients_text: "chicken, romaine lettuce, fajita veggies (peppers, onion), tomato salsa" },
    { name: "Side of Queso Blanco", category: "Sides", serving_size: 73, serving_unit: "g", calories: 120, total_fat: 8, saturated_fat: 4, trans_fat: 0, cholesterol: 20, sodium: 510, total_carbohydrates: 4, dietary_fiber: 0, total_sugars: 1, protein: 5, ingredients_text: "white cheddar cheese (milk), serrano peppers, poblano peppers, cumin" },
    { name: "Tomato Salsa (Fresh)", category: "Sides", serving_size: 114, serving_unit: "g", calories: 25, total_fat: 0, saturated_fat: 0, trans_fat: 0, cholesterol: 0, sodium: 550, total_carbohydrates: 4, dietary_fiber: 1, total_sugars: 3, protein: 2, ingredients_text: "tomato, red onion, cilantro, jalapeno, lemon juice, salt" },
    { name: "Corn Salsa", category: "Sides", serving_size: 114, serving_unit: "g", calories: 80, total_fat: 1.5, saturated_fat: 0, trans_fat: 0, cholesterol: 0, sodium: 290, total_carbohydrates: 15, dietary_fiber: 2, total_sugars: 4, protein: 3, ingredients_text: "roasted corn, jalapeno, red onion, cilantro, lime juice, salt" },
    { name: "Sour Cream", category: "Sides", serving_size: 57, serving_unit: "g", calories: 110, total_fat: 9, saturated_fat: 6, trans_fat: 0, cholesterol: 25, sodium: 30, total_carbohydrates: 2, dietary_fiber: 0, total_sugars: 2, protein: 2, ingredients_text: "cultured cream (milk), enzymes" },
  ],
};

const subway: ChainData = {
  chain: "Subway",
  items: [
    { name: "Italian B.M.T. (6 inch)", category: "Sandwiches", serving_size: 232, serving_unit: "g", calories: 360, total_fat: 14, saturated_fat: 5, trans_fat: 0, cholesterol: 45, sodium: 1260, total_carbohydrates: 38, dietary_fiber: 2, total_sugars: 6, protein: 17, ingredients_text: "italian bread (enriched flour, wheat), salami (pork, beef), pepperoni (pork, beef), ham (pork), lettuce, tomato, onion, green pepper" },
    { name: "Turkey Breast (6 inch)", category: "Sandwiches", serving_size: 219, serving_unit: "g", calories: 270, total_fat: 3.5, saturated_fat: 0.5, trans_fat: 0, cholesterol: 25, sodium: 810, total_carbohydrates: 40, dietary_fiber: 3, total_sugars: 6, protein: 18, ingredients_text: "italian bread (enriched flour, wheat), turkey breast, lettuce, tomato, onion, green pepper" },
    { name: "Meatball Marinara (6 inch)", category: "Sandwiches", serving_size: 306, serving_unit: "g", calories: 480, total_fat: 18, saturated_fat: 7, trans_fat: 0.5, cholesterol: 45, sodium: 1180, total_carbohydrates: 55, dietary_fiber: 5, total_sugars: 13, protein: 22, ingredients_text: "italian bread (enriched flour, wheat), meatballs (beef, pork, breadcrumbs (wheat)), marinara sauce (tomato, garlic), parmesan cheese (milk)" },
    { name: "Chicken Teriyaki (6 inch)", category: "Sandwiches", serving_size: 268, serving_unit: "g", calories: 340, total_fat: 5, saturated_fat: 1.5, trans_fat: 0, cholesterol: 50, sodium: 960, total_carbohydrates: 46, dietary_fiber: 3, total_sugars: 12, protein: 25, ingredients_text: "italian bread (enriched flour, wheat), chicken strips, teriyaki sauce (soy sauce, sugar), lettuce, tomato, onion, green pepper" },
    { name: "Tuna (6 inch)", category: "Sandwiches", serving_size: 243, serving_unit: "g", calories: 480, total_fat: 25, saturated_fat: 4.5, trans_fat: 0, cholesterol: 35, sodium: 720, total_carbohydrates: 40, dietary_fiber: 2, total_sugars: 6, protein: 20, ingredients_text: "italian bread (enriched flour, wheat), tuna (fish), mayonnaise (soybean oil, egg), lettuce, tomato, onion" },
    { name: "Spicy Italian (6 inch)", category: "Sandwiches", serving_size: 223, serving_unit: "g", calories: 480, total_fat: 26, saturated_fat: 10, trans_fat: 0, cholesterol: 60, sodium: 1510, total_carbohydrates: 38, dietary_fiber: 2, total_sugars: 6, protein: 19, ingredients_text: "italian bread (enriched flour, wheat), pepperoni (pork, beef), salami (pork, beef), lettuce, tomato, onion, green pepper" },
    { name: "Cold Cut Combo (6 inch)", category: "Sandwiches", serving_size: 232, serving_unit: "g", calories: 350, total_fat: 13, saturated_fat: 4.5, trans_fat: 0, cholesterol: 50, sodium: 1060, total_carbohydrates: 39, dietary_fiber: 2, total_sugars: 5, protein: 17, ingredients_text: "italian bread (enriched flour, wheat), bologna (pork, chicken), ham (pork), salami (pork, beef), lettuce, tomato" },
    { name: "Steak & Cheese (6 inch)", category: "Sandwiches", serving_size: 249, serving_unit: "g", calories: 380, total_fat: 12, saturated_fat: 5, trans_fat: 0, cholesterol: 50, sodium: 1000, total_carbohydrates: 40, dietary_fiber: 3, total_sugars: 7, protein: 26, ingredients_text: "italian bread (enriched flour, wheat), steak (beef), american cheese (milk), lettuce, tomato, onion, green pepper" },
    { name: "Veggie Delite (6 inch)", category: "Sandwiches", serving_size: 163, serving_unit: "g", calories: 200, total_fat: 2, saturated_fat: 0, trans_fat: 0, cholesterol: 0, sodium: 300, total_carbohydrates: 38, dietary_fiber: 3, total_sugars: 5, protein: 7, ingredients_text: "italian bread (enriched flour, wheat), lettuce, tomato, onion, green pepper, cucumber, olive" },
    { name: "Rotisserie-Style Chicken (6 inch)", category: "Sandwiches", serving_size: 236, serving_unit: "g", calories: 300, total_fat: 5, saturated_fat: 1.5, trans_fat: 0, cholesterol: 55, sodium: 750, total_carbohydrates: 38, dietary_fiber: 2, total_sugars: 5, protein: 26, ingredients_text: "italian bread (enriched flour, wheat), rotisserie-style chicken, lettuce, tomato, onion, green pepper" },
    { name: "Black Forest Ham (6 inch)", category: "Sandwiches", serving_size: 219, serving_unit: "g", calories: 270, total_fat: 4, saturated_fat: 1, trans_fat: 0, cholesterol: 30, sodium: 1000, total_carbohydrates: 39, dietary_fiber: 3, total_sugars: 6, protein: 17, ingredients_text: "italian bread (enriched flour, wheat), black forest ham (pork), lettuce, tomato, onion, green pepper" },
    { name: "Chocolate Chip Cookie", category: "Desserts", serving_size: 45, serving_unit: "g", calories: 210, total_fat: 10, saturated_fat: 5, trans_fat: 0, cholesterol: 15, sodium: 130, total_carbohydrates: 29, dietary_fiber: 1, total_sugars: 17, protein: 2, ingredients_text: "enriched flour (wheat), sugar, chocolate chips, butter, eggs, vanilla, salt" },
    { name: "Chicken & Bacon Ranch (6 inch)", category: "Sandwiches", serving_size: 275, serving_unit: "g", calories: 570, total_fat: 28, saturated_fat: 10, trans_fat: 0, cholesterol: 90, sodium: 1310, total_carbohydrates: 40, dietary_fiber: 2, total_sugars: 6, protein: 36, ingredients_text: "italian bread (enriched flour, wheat), chicken strips, bacon (pork), ranch dressing (soybean oil, buttermilk (milk), egg), cheese (milk)" },
    { name: "Buffalo Chicken (6 inch)", category: "Sandwiches", serving_size: 268, serving_unit: "g", calories: 370, total_fat: 11, saturated_fat: 3, trans_fat: 0, cholesterol: 60, sodium: 1280, total_carbohydrates: 42, dietary_fiber: 3, total_sugars: 7, protein: 24, ingredients_text: "italian bread (enriched flour, wheat), chicken strips, buffalo sauce (cayenne pepper, vinegar, butter), lettuce, tomato" },
    { name: "Egg & Cheese (6 inch)", category: "Breakfast", serving_size: 174, serving_unit: "g", calories: 360, total_fat: 15, saturated_fat: 5, trans_fat: 0, cholesterol: 180, sodium: 780, total_carbohydrates: 38, dietary_fiber: 2, total_sugars: 5, protein: 17, ingredients_text: "italian bread (enriched flour, wheat), eggs, american cheese (milk)" },
    { name: "Baja Chicken (6 inch)", category: "Sandwiches", serving_size: 268, serving_unit: "g", calories: 410, total_fat: 16, saturated_fat: 4, trans_fat: 0, cholesterol: 65, sodium: 1060, total_carbohydrates: 42, dietary_fiber: 3, total_sugars: 7, protein: 26, ingredients_text: "italian bread (enriched flour, wheat), chicken strips, pepper jack cheese (milk), smashed avocado, peppercorn ranch sauce (soybean oil, milk)" },
    { name: "Oven Roasted Turkey & Ham (6 inch)", category: "Sandwiches", serving_size: 229, serving_unit: "g", calories: 260, total_fat: 3.5, saturated_fat: 0.5, trans_fat: 0, cholesterol: 30, sodium: 870, total_carbohydrates: 38, dietary_fiber: 2, total_sugars: 6, protein: 19, ingredients_text: "italian bread (enriched flour, wheat), turkey breast, black forest ham (pork), lettuce, tomato, onion" },
    { name: "Italian Herbs & Cheese Bread (6 inch)", category: "Bread", serving_size: 84, serving_unit: "g", calories: 240, total_fat: 5, saturated_fat: 2, trans_fat: 0, cholesterol: 5, sodium: 500, total_carbohydrates: 40, dietary_fiber: 2, total_sugars: 5, protein: 9, ingredients_text: "enriched flour (wheat), water, yeast, sugar, parmesan cheese (milk), oregano, garlic" },
    { name: "Chipotle Southwest Sauce", category: "Sauces", serving_size: 21, serving_unit: "g", calories: 100, total_fat: 10, saturated_fat: 1.5, trans_fat: 0, cholesterol: 10, sodium: 220, total_carbohydrates: 1, dietary_fiber: 0, total_sugars: 1, protein: 0, ingredients_text: "soybean oil, chipotle pepper, egg yolk, vinegar, garlic, onion, sugar, salt" },
    { name: "White Chip Macadamia Nut Cookie", category: "Desserts", serving_size: 45, serving_unit: "g", calories: 210, total_fat: 10, saturated_fat: 4, trans_fat: 0, cholesterol: 15, sodium: 130, total_carbohydrates: 28, dietary_fiber: 0, total_sugars: 17, protein: 2, ingredients_text: "enriched flour (wheat), sugar, white chocolate chips (sugar, cocoa butter, milk), macadamia nuts (tree nuts), butter, eggs" },
  ],
};

const tacoBell: ChainData = {
  chain: "Taco Bell",
  items: [
    { name: "Crunchy Taco", category: "Tacos", serving_size: 78, serving_unit: "g", calories: 170, total_fat: 9, saturated_fat: 3.5, trans_fat: 0, cholesterol: 25, sodium: 310, total_carbohydrates: 13, dietary_fiber: 3, total_sugars: 1, protein: 8, ingredients_text: "corn taco shell, seasoned beef (beef, water, oats, seasoning), lettuce, cheddar cheese (milk)" },
    { name: "Crunchy Taco Supreme", category: "Tacos", serving_size: 106, serving_unit: "g", calories: 210, total_fat: 12, saturated_fat: 5, trans_fat: 0, cholesterol: 30, sodium: 360, total_carbohydrates: 15, dietary_fiber: 3, total_sugars: 2, protein: 9, ingredients_text: "corn taco shell, seasoned beef (beef, water, oats, seasoning), lettuce, cheddar cheese (milk), sour cream (milk), tomato" },
    { name: "Soft Taco", category: "Tacos", serving_size: 99, serving_unit: "g", calories: 180, total_fat: 8, saturated_fat: 3.5, trans_fat: 0, cholesterol: 25, sodium: 530, total_carbohydrates: 18, dietary_fiber: 2, total_sugars: 1, protein: 9, ingredients_text: "flour tortilla (wheat), seasoned beef (beef, water, oats, seasoning), lettuce, cheddar cheese (milk)" },
    { name: "Doritos Locos Taco", category: "Tacos", serving_size: 78, serving_unit: "g", calories: 170, total_fat: 9, saturated_fat: 3.5, trans_fat: 0, cholesterol: 25, sodium: 350, total_carbohydrates: 13, dietary_fiber: 3, total_sugars: 1, protein: 8, ingredients_text: "nacho cheese doritos shell (corn, seasoning), seasoned beef (beef, water, oats, seasoning), lettuce, cheddar cheese (milk)" },
    { name: "Bean Burrito", category: "Burritos", serving_size: 198, serving_unit: "g", calories: 380, total_fat: 11, saturated_fat: 3.5, trans_fat: 0.5, cholesterol: 10, sodium: 1060, total_carbohydrates: 55, dietary_fiber: 8, total_sugars: 3, protein: 14, ingredients_text: "flour tortilla (wheat), refried beans, cheddar cheese (milk), red sauce (tomato, chili pepper), onion" },
    { name: "Burrito Supreme - Beef", category: "Burritos", serving_size: 248, serving_unit: "g", calories: 390, total_fat: 14, saturated_fat: 6, trans_fat: 0.5, cholesterol: 35, sodium: 1090, total_carbohydrates: 49, dietary_fiber: 6, total_sugars: 4, protein: 16, ingredients_text: "flour tortilla (wheat), seasoned beef (beef), refried beans, lettuce, tomato, sour cream (milk), cheddar cheese (milk), red sauce" },
    { name: "Crunchwrap Supreme", category: "Specialties", serving_size: 254, serving_unit: "g", calories: 530, total_fat: 21, saturated_fat: 7, trans_fat: 0.5, cholesterol: 40, sodium: 1210, total_carbohydrates: 71, dietary_fiber: 5, total_sugars: 6, protein: 16, ingredients_text: "flour tortilla (wheat), seasoned beef (beef), nacho cheese sauce (milk, cheese), corn tostada shell, lettuce, tomato, sour cream (milk)" },
    { name: "Cheesy Gordita Crunch", category: "Specialties", serving_size: 153, serving_unit: "g", calories: 490, total_fat: 28, saturated_fat: 9, trans_fat: 0.5, cholesterol: 45, sodium: 800, total_carbohydrates: 40, dietary_fiber: 4, total_sugars: 5, protein: 18, ingredients_text: "flatbread (wheat), corn taco shell, seasoned beef (beef), pepper jack sauce (milk), lettuce, three-cheese blend (milk)" },
    { name: "Mexican Pizza", category: "Specialties", serving_size: 213, serving_unit: "g", calories: 540, total_fat: 28, saturated_fat: 8, trans_fat: 1, cholesterol: 40, sodium: 1030, total_carbohydrates: 52, dietary_fiber: 6, total_sugars: 3, protein: 19, ingredients_text: "fried flour tortilla shells (wheat), seasoned beef (beef), refried beans, mexican pizza sauce (tomato), three-cheese blend (milk), tomato" },
    { name: "Nachos BellGrande", category: "Specialties", serving_size: 308, serving_unit: "g", calories: 740, total_fat: 38, saturated_fat: 7, trans_fat: 0.5, cholesterol: 35, sodium: 1150, total_carbohydrates: 80, dietary_fiber: 10, total_sugars: 4, protein: 16, ingredients_text: "tortilla chips (corn), seasoned beef (beef), nacho cheese sauce (milk), refried beans, sour cream (milk), tomato" },
    { name: "Quesadilla - Chicken", category: "Quesadillas", serving_size: 184, serving_unit: "g", calories: 500, total_fat: 26, saturated_fat: 12, trans_fat: 0.5, cholesterol: 70, sodium: 1190, total_carbohydrates: 37, dietary_fiber: 3, total_sugars: 4, protein: 27, ingredients_text: "flour tortilla (wheat), grilled chicken, three-cheese blend (milk), jalapeño sauce, creamy jalapeño sauce (soybean oil, milk)" },
    { name: "Chicken Chalupa Supreme", category: "Chalupas", serving_size: 153, serving_unit: "g", calories: 340, total_fat: 18, saturated_fat: 4.5, trans_fat: 0, cholesterol: 40, sodium: 640, total_carbohydrates: 29, dietary_fiber: 3, total_sugars: 3, protein: 16, ingredients_text: "chalupa shell (wheat flour, corn), grilled chicken, lettuce, tomato, sour cream (milk), three-cheese blend (milk)" },
    { name: "Beefy 5-Layer Burrito", category: "Burritos", serving_size: 248, serving_unit: "g", calories: 490, total_fat: 18, saturated_fat: 7, trans_fat: 0.5, cholesterol: 40, sodium: 1300, total_carbohydrates: 63, dietary_fiber: 7, total_sugars: 4, protein: 19, ingredients_text: "flour tortilla (wheat), seasoned beef (beef), refried beans, nacho cheese sauce (milk), sour cream (milk)" },
    { name: "Cheesy Bean & Rice Burrito", category: "Burritos", serving_size: 198, serving_unit: "g", calories: 420, total_fat: 14, saturated_fat: 3.5, trans_fat: 0, cholesterol: 15, sodium: 1080, total_carbohydrates: 62, dietary_fiber: 5, total_sugars: 3, protein: 12, ingredients_text: "flour tortilla (wheat), seasoned rice, refried beans, nacho cheese sauce (milk), jalapeño sauce, sour cream (milk)" },
    { name: "Fiesta Veggie Burrito", category: "Burritos", serving_size: 198, serving_unit: "g", calories: 430, total_fat: 15, saturated_fat: 4, trans_fat: 0, cholesterol: 15, sodium: 1030, total_carbohydrates: 62, dietary_fiber: 7, total_sugars: 4, protein: 12, ingredients_text: "flour tortilla (wheat), black beans, seasoned rice, guacamole (avocado), chipotle sauce, sour cream (milk)" },
    { name: "Cinnamon Twists", category: "Desserts", serving_size: 35, serving_unit: "g", calories: 170, total_fat: 7, saturated_fat: 0, trans_fat: 0, cholesterol: 0, sodium: 210, total_carbohydrates: 26, dietary_fiber: 1, total_sugars: 5, protein: 1, ingredients_text: "corn meal, rice flour, vegetable oil, cinnamon, sugar" },
    { name: "Chips & Nacho Cheese Sauce", category: "Sides", serving_size: 99, serving_unit: "g", calories: 320, total_fat: 17, saturated_fat: 3, trans_fat: 0, cholesterol: 10, sodium: 560, total_carbohydrates: 36, dietary_fiber: 3, total_sugars: 2, protein: 4, ingredients_text: "tortilla chips (corn), nacho cheese sauce (milk, cheese, jalapeño)" },
    { name: "Power Menu Bowl - Chicken", category: "Bowls", serving_size: 340, serving_unit: "g", calories: 470, total_fat: 17, saturated_fat: 5, trans_fat: 0, cholesterol: 55, sodium: 1250, total_carbohydrates: 50, dietary_fiber: 6, total_sugars: 3, protein: 26, ingredients_text: "seasoned rice, black beans, grilled chicken, guacamole (avocado), sour cream (milk), lettuce, tomato, cheese (milk)" },
    { name: "Chalupa Supreme - Beef", category: "Chalupas", serving_size: 153, serving_unit: "g", calories: 350, total_fat: 19, saturated_fat: 5, trans_fat: 0, cholesterol: 30, sodium: 610, total_carbohydrates: 30, dietary_fiber: 4, total_sugars: 3, protein: 14, ingredients_text: "chalupa shell (wheat flour, corn), seasoned beef (beef), lettuce, tomato, sour cream (milk), three-cheese blend (milk)" },
    { name: "Large Mountain Dew Baja Blast", category: "Beverages", serving_size: 887, serving_unit: "ml", calories: 420, total_fat: 0, saturated_fat: 0, trans_fat: 0, cholesterol: 0, sodium: 95, total_carbohydrates: 114, dietary_fiber: 0, total_sugars: 114, protein: 0, ingredients_text: "carbonated water, high fructose corn syrup, natural and artificial flavors, citric acid, sodium benzoate, caffeine" },
  ],
};

const wendys: ChainData = {
  chain: "Wendy's",
  items: [
    { name: "Dave's Single", category: "Burgers", serving_size: 207, serving_unit: "g", calories: 570, total_fat: 34, saturated_fat: 14, trans_fat: 1.5, cholesterol: 100, sodium: 1180, total_carbohydrates: 32, dietary_fiber: 1, total_sugars: 8, protein: 30, ingredients_text: "beef patty, premium bun (enriched flour, wheat), american cheese (milk), lettuce, tomato, pickle, onion, ketchup, mayo (soybean oil, egg)" },
    { name: "Dave's Double", category: "Burgers", serving_size: 306, serving_unit: "g", calories: 820, total_fat: 51, saturated_fat: 22, trans_fat: 3, cholesterol: 175, sodium: 1520, total_carbohydrates: 32, dietary_fiber: 1, total_sugars: 8, protein: 50, ingredients_text: "beef patties, premium bun (enriched flour, wheat), american cheese (milk), lettuce, tomato, pickle, onion, ketchup, mayo (soybean oil, egg)" },
    { name: "Baconator", category: "Burgers", serving_size: 282, serving_unit: "g", calories: 930, total_fat: 60, saturated_fat: 25, trans_fat: 3.5, cholesterol: 205, sodium: 1700, total_carbohydrates: 33, dietary_fiber: 1, total_sugars: 8, protein: 55, ingredients_text: "beef patties, premium bun (enriched flour, wheat), american cheese (milk), applewood smoked bacon (pork), ketchup, mayo (soybean oil, egg)" },
    { name: "Jr. Bacon Cheeseburger", category: "Burgers", serving_size: 151, serving_unit: "g", calories: 380, total_fat: 22, saturated_fat: 8, trans_fat: 0.5, cholesterol: 65, sodium: 820, total_carbohydrates: 26, dietary_fiber: 1, total_sugars: 5, protein: 19, ingredients_text: "beef patty, premium bun (enriched flour, wheat), american cheese (milk), bacon (pork), lettuce, tomato, mayo (soybean oil, egg)" },
    { name: "Classic Chicken Sandwich", category: "Chicken Sandwiches", serving_size: 228, serving_unit: "g", calories: 490, total_fat: 21, saturated_fat: 3.5, trans_fat: 0, cholesterol: 55, sodium: 1140, total_carbohydrates: 49, dietary_fiber: 2, total_sugars: 7, protein: 27, ingredients_text: "chicken breast (chicken, wheat flour), premium bun (enriched flour, wheat), lettuce, tomato, mayo (soybean oil, egg)" },
    { name: "Spicy Chicken Sandwich", category: "Chicken Sandwiches", serving_size: 228, serving_unit: "g", calories: 490, total_fat: 21, saturated_fat: 3.5, trans_fat: 0, cholesterol: 55, sodium: 1140, total_carbohydrates: 49, dietary_fiber: 2, total_sugars: 7, protein: 27, ingredients_text: "spicy chicken breast (chicken, wheat flour, cayenne pepper), premium bun (enriched flour, wheat), lettuce, tomato, mayo (soybean oil, egg)" },
    { name: "10 Piece Chicken Nuggets", category: "Chicken", serving_size: 159, serving_unit: "g", calories: 450, total_fat: 29, saturated_fat: 6, trans_fat: 0, cholesterol: 70, sodium: 870, total_carbohydrates: 25, dietary_fiber: 0, total_sugars: 0, protein: 22, ingredients_text: "chicken breast, wheat flour, water, corn starch, salt, spices, leavening, vegetable oil" },
    { name: "Medium Natural Cut Fries", category: "Sides", serving_size: 142, serving_unit: "g", calories: 350, total_fat: 16, saturated_fat: 2.5, trans_fat: 0, cholesterol: 0, sodium: 380, total_carbohydrates: 47, dietary_fiber: 4, total_sugars: 0, protein: 5, ingredients_text: "potatoes, vegetable oil (soybean, canola), sea salt, sodium acid pyrophosphate" },
    { name: "Chili (Large)", category: "Sides", serving_size: 340, serving_unit: "g", calories: 330, total_fat: 13, saturated_fat: 5, trans_fat: 1, cholesterol: 65, sodium: 1170, total_carbohydrates: 26, dietary_fiber: 7, total_sugars: 7, protein: 26, ingredients_text: "beef, tomato, kidney beans, onion, celery, green pepper, chili pepper, garlic, cumin, salt" },
    { name: "Apple Pecan Salad (Full)", category: "Salads", serving_size: 360, serving_unit: "g", calories: 560, total_fat: 26, saturated_fat: 8, trans_fat: 0, cholesterol: 100, sodium: 1020, total_carbohydrates: 50, dietary_fiber: 5, total_sugars: 37, protein: 33, ingredients_text: "romaine lettuce, grilled chicken breast, apple, cranberry, blue cheese (milk), pecans (tree nuts), pomegranate vinaigrette" },
    { name: "Medium Chocolate Frosty", category: "Desserts", serving_size: 298, serving_unit: "g", calories: 340, total_fat: 9, saturated_fat: 6, trans_fat: 0, cholesterol: 35, sodium: 200, total_carbohydrates: 57, dietary_fiber: 1, total_sugars: 47, protein: 9, ingredients_text: "milk, sugar, cream, cocoa, whey (milk), corn syrup, vanilla" },
    { name: "Medium Vanilla Frosty", category: "Desserts", serving_size: 298, serving_unit: "g", calories: 340, total_fat: 9, saturated_fat: 6, trans_fat: 0, cholesterol: 35, sodium: 200, total_carbohydrates: 56, dietary_fiber: 0, total_sugars: 48, protein: 9, ingredients_text: "milk, sugar, cream, whey (milk), corn syrup, vanilla" },
    { name: "Baked Potato with Cheese", category: "Sides", serving_size: 369, serving_unit: "g", calories: 450, total_fat: 14, saturated_fat: 5, trans_fat: 0, cholesterol: 15, sodium: 680, total_carbohydrates: 68, dietary_fiber: 6, total_sugars: 4, protein: 14, ingredients_text: "russet potato, cheddar cheese sauce (milk, cheese), butter" },
    { name: "Sausage, Egg & Cheese Biscuit", category: "Breakfast", serving_size: 179, serving_unit: "g", calories: 580, total_fat: 39, saturated_fat: 16, trans_fat: 0, cholesterol: 240, sodium: 1290, total_carbohydrates: 34, dietary_fiber: 1, total_sugars: 4, protein: 20, ingredients_text: "biscuit (enriched flour, wheat, butter), sausage patty (pork), egg, american cheese (milk)" },
    { name: "Pretzel Bacon Pub Cheeseburger", category: "Burgers", serving_size: 306, serving_unit: "g", calories: 800, total_fat: 44, saturated_fat: 18, trans_fat: 2, cholesterol: 155, sodium: 1530, total_carbohydrates: 50, dietary_fiber: 2, total_sugars: 10, protein: 48, ingredients_text: "beef patty, pretzel bun (enriched flour, wheat), smoked bacon (pork), beer cheese sauce (milk, cheese), pickled onion, honey mustard" },
    { name: "Parmesan Caesar Salad (Full)", category: "Salads", serving_size: 342, serving_unit: "g", calories: 530, total_fat: 29, saturated_fat: 8, trans_fat: 0, cholesterol: 110, sodium: 1220, total_carbohydrates: 26, dietary_fiber: 4, total_sugars: 4, protein: 40, ingredients_text: "romaine lettuce, grilled chicken breast, parmesan cheese (milk), croutons (wheat flour), caesar dressing (soybean oil, parmesan, egg, anchovy)" },
    { name: "Southwest Avocado Chicken Salad", category: "Salads", serving_size: 385, serving_unit: "g", calories: 520, total_fat: 28, saturated_fat: 8, trans_fat: 0, cholesterol: 100, sodium: 1060, total_carbohydrates: 30, dietary_fiber: 8, total_sugars: 8, protein: 38, ingredients_text: "romaine lettuce, grilled chicken breast, avocado, bacon (pork), tomato, corn, cheese (milk), tortilla strips (wheat, corn)" },
    { name: "Medium Lemonade", category: "Beverages", serving_size: 591, serving_unit: "ml", calories: 200, total_fat: 0, saturated_fat: 0, trans_fat: 0, cholesterol: 0, sodium: 15, total_carbohydrates: 54, dietary_fiber: 0, total_sugars: 51, protein: 0, ingredients_text: "water, sugar, lemon juice concentrate, natural flavor" },
    { name: "Crispy Chicken BLT (6 count)", category: "Chicken", serving_size: 240, serving_unit: "g", calories: 580, total_fat: 30, saturated_fat: 9, trans_fat: 0.5, cholesterol: 85, sodium: 1320, total_carbohydrates: 46, dietary_fiber: 2, total_sugars: 7, protein: 31, ingredients_text: "chicken breast (chicken, wheat flour), premium bun (enriched flour, wheat), bacon (pork), lettuce, tomato, cheese (milk), mayo (soybean oil, egg)" },
    { name: "Jr. Cheeseburger", category: "Burgers", serving_size: 129, serving_unit: "g", calories: 290, total_fat: 14, saturated_fat: 6, trans_fat: 0.5, cholesterol: 50, sodium: 670, total_carbohydrates: 26, dietary_fiber: 1, total_sugars: 5, protein: 15, ingredients_text: "beef patty, premium bun (enriched flour, wheat), american cheese (milk), pickle, onion, ketchup, mustard" },
  ],
};

const pandaExpress: ChainData = {
  chain: "Panda Express",
  items: [
    { name: "Orange Chicken", category: "Chicken Entrees", serving_size: 162, serving_unit: "g", calories: 490, total_fat: 23, saturated_fat: 5, trans_fat: 0, cholesterol: 80, sodium: 820, total_carbohydrates: 51, dietary_fiber: 0, total_sugars: 19, protein: 25, ingredients_text: "chicken, wheat flour, corn starch, soybean oil, sugar, vinegar, soy sauce (wheat, soy), orange peel, garlic, ginger, chili" },
    { name: "Beijing Beef", category: "Beef Entrees", serving_size: 162, serving_unit: "g", calories: 470, total_fat: 26, saturated_fat: 5, trans_fat: 0, cholesterol: 35, sodium: 660, total_carbohydrates: 46, dietary_fiber: 1, total_sugars: 25, protein: 14, ingredients_text: "beef, wheat flour, corn starch, soybean oil, sugar, bell pepper, onion, soy sauce (wheat, soy), vinegar, garlic" },
    { name: "Kung Pao Chicken", category: "Chicken Entrees", serving_size: 162, serving_unit: "g", calories: 290, total_fat: 19, saturated_fat: 3.5, trans_fat: 0, cholesterol: 70, sodium: 770, total_carbohydrates: 14, dietary_fiber: 2, total_sugars: 5, protein: 16, ingredients_text: "chicken, peanuts, zucchini, red bell pepper, soybean oil, soy sauce (wheat, soy), chili pepper, garlic, ginger, corn starch" },
    { name: "Broccoli Beef", category: "Beef Entrees", serving_size: 162, serving_unit: "g", calories: 150, total_fat: 7, saturated_fat: 1.5, trans_fat: 0, cholesterol: 15, sodium: 520, total_carbohydrates: 12, dietary_fiber: 2, total_sugars: 3, protein: 9, ingredients_text: "beef, broccoli, soy sauce (wheat, soy), ginger, garlic, corn starch, soybean oil" },
    { name: "Honey Walnut Shrimp", category: "Seafood Entrees", serving_size: 162, serving_unit: "g", calories: 360, total_fat: 23, saturated_fat: 3.5, trans_fat: 0, cholesterol: 110, sodium: 440, total_carbohydrates: 27, dietary_fiber: 1, total_sugars: 9, protein: 13, ingredients_text: "shrimp, walnuts (tree nuts), wheat flour, corn starch, mayonnaise (soybean oil, egg), sugar, condensed milk" },
    { name: "Grilled Teriyaki Chicken", category: "Chicken Entrees", serving_size: 162, serving_unit: "g", calories: 300, total_fat: 13, saturated_fat: 3, trans_fat: 0, cholesterol: 80, sodium: 530, total_carbohydrates: 8, dietary_fiber: 0, total_sugars: 8, protein: 36, ingredients_text: "chicken thigh, soy sauce (wheat, soy), sugar, garlic, ginger, corn starch" },
    { name: "Mushroom Chicken", category: "Chicken Entrees", serving_size: 162, serving_unit: "g", calories: 220, total_fat: 13, saturated_fat: 3, trans_fat: 0, cholesterol: 70, sodium: 760, total_carbohydrates: 10, dietary_fiber: 1, total_sugars: 4, protein: 16, ingredients_text: "chicken, mushroom, zucchini, soy sauce (wheat, soy), garlic, ginger, corn starch, soybean oil" },
    { name: "SweetFire Chicken Breast", category: "Chicken Entrees", serving_size: 162, serving_unit: "g", calories: 380, total_fat: 15, saturated_fat: 3, trans_fat: 0, cholesterol: 50, sodium: 370, total_carbohydrates: 43, dietary_fiber: 1, total_sugars: 20, protein: 17, ingredients_text: "chicken breast, wheat flour, corn starch, pineapple, red bell pepper, onion, soybean oil, sugar, chili garlic sauce, soy sauce (wheat, soy)" },
    { name: "Black Pepper Angus Steak", category: "Beef Entrees", serving_size: 162, serving_unit: "g", calories: 180, total_fat: 7, saturated_fat: 2.5, trans_fat: 0, cholesterol: 40, sodium: 740, total_carbohydrates: 12, dietary_fiber: 1, total_sugars: 5, protein: 19, ingredients_text: "angus steak (beef), onion, celery, red bell pepper, soy sauce (wheat, soy), black pepper, garlic, corn starch, soybean oil" },
    { name: "Honey Sesame Chicken Breast", category: "Chicken Entrees", serving_size: 162, serving_unit: "g", calories: 420, total_fat: 21, saturated_fat: 4, trans_fat: 0, cholesterol: 55, sodium: 500, total_carbohydrates: 38, dietary_fiber: 1, total_sugars: 19, protein: 17, ingredients_text: "chicken breast, wheat flour, corn starch, soybean oil, honey, sesame seeds (sesame), string beans, soy sauce (wheat, soy)" },
    { name: "Fried Rice", category: "Sides", serving_size: 227, serving_unit: "g", calories: 520, total_fat: 16, saturated_fat: 3, trans_fat: 0, cholesterol: 115, sodium: 850, total_carbohydrates: 85, dietary_fiber: 1, total_sugars: 3, protein: 11, ingredients_text: "rice, soybean oil, egg, peas, carrot, onion, soy sauce (wheat, soy), salt" },
    { name: "Chow Mein", category: "Sides", serving_size: 227, serving_unit: "g", calories: 510, total_fat: 22, saturated_fat: 4, trans_fat: 0, cholesterol: 0, sodium: 860, total_carbohydrates: 65, dietary_fiber: 6, total_sugars: 5, protein: 13, ingredients_text: "noodles (wheat flour), cabbage, celery, onion, soybean oil, soy sauce (wheat, soy), garlic, sesame oil (sesame)" },
    { name: "White Steamed Rice", category: "Sides", serving_size: 227, serving_unit: "g", calories: 380, total_fat: 0, saturated_fat: 0, trans_fat: 0, cholesterol: 0, sodium: 0, total_carbohydrates: 87, dietary_fiber: 0, total_sugars: 0, protein: 7, ingredients_text: "enriched long grain rice" },
    { name: "Super Greens", category: "Sides", serving_size: 198, serving_unit: "g", calories: 90, total_fat: 3, saturated_fat: 0.5, trans_fat: 0, cholesterol: 0, sodium: 280, total_carbohydrates: 10, dietary_fiber: 5, total_sugars: 2, protein: 6, ingredients_text: "broccoli, kale, cabbage, garlic, soybean oil, salt" },
    { name: "Cream Cheese Rangoon (3 ct)", category: "Appetizers", serving_size: 64, serving_unit: "g", calories: 190, total_fat: 8, saturated_fat: 5, trans_fat: 0, cholesterol: 35, sodium: 180, total_carbohydrates: 24, dietary_fiber: 2, total_sugars: 1, protein: 5, ingredients_text: "wonton wrapper (wheat flour), cream cheese (milk), green onion, garlic, soybean oil" },
    { name: "Chicken Egg Roll (1)", category: "Appetizers", serving_size: 79, serving_unit: "g", calories: 200, total_fat: 10, saturated_fat: 2, trans_fat: 0, cholesterol: 20, sodium: 390, total_carbohydrates: 20, dietary_fiber: 2, total_sugars: 2, protein: 8, ingredients_text: "wheat flour wrapper, chicken, cabbage, celery, onion, carrot, soybean oil, soy sauce (wheat, soy)" },
    { name: "Veggie Spring Roll (2 ct)", category: "Appetizers", serving_size: 64, serving_unit: "g", calories: 190, total_fat: 7, saturated_fat: 1.5, trans_fat: 0, cholesterol: 0, sodium: 540, total_carbohydrates: 22, dietary_fiber: 4, total_sugars: 2, protein: 5, ingredients_text: "rice paper wrapper, cabbage, celery, carrot, green onion, soy sauce (wheat, soy), soybean oil" },
    { name: "String Bean Chicken Breast", category: "Chicken Entrees", serving_size: 162, serving_unit: "g", calories: 190, total_fat: 9, saturated_fat: 2, trans_fat: 0, cholesterol: 50, sodium: 570, total_carbohydrates: 13, dietary_fiber: 2, total_sugars: 5, protein: 14, ingredients_text: "chicken breast, string beans, onion, soy sauce (wheat, soy), garlic, corn starch, soybean oil" },
    { name: "Plate (1 entree + 1 side)", category: "Combos", serving_size: 389, serving_unit: "g", calories: 870, total_fat: 39, saturated_fat: 8, trans_fat: 0, cholesterol: 80, sodium: 1670, total_carbohydrates: 96, dietary_fiber: 1, total_sugars: 22, protein: 36, ingredients_text: "orange chicken (chicken, wheat flour, soy, sugar), fried rice (rice, egg, soy, wheat)" },
    { name: "Apple Pie Roll", category: "Desserts", serving_size: 79, serving_unit: "g", calories: 150, total_fat: 3, saturated_fat: 0, trans_fat: 0, cholesterol: 0, sodium: 170, total_carbohydrates: 30, dietary_fiber: 1, total_sugars: 10, protein: 2, ingredients_text: "apple, wheat flour wrapper, sugar, cinnamon, soybean oil" },
  ],
};

const popeyes: ChainData = {
  chain: "Popeyes",
  items: [
    { name: "Chicken Sandwich (Classic)", category: "Sandwiches", serving_size: 220, serving_unit: "g", calories: 700, total_fat: 42, saturated_fat: 14, trans_fat: 2, cholesterol: 60, sodium: 1440, total_carbohydrates: 50, dietary_fiber: 2, total_sugars: 8, protein: 28, ingredients_text: "chicken breast (chicken, wheat flour, spices), brioche bun (enriched flour, wheat, butter, milk, egg), pickles, mayo (soybean oil, egg)" },
    { name: "Chicken Sandwich (Spicy)", category: "Sandwiches", serving_size: 220, serving_unit: "g", calories: 700, total_fat: 42, saturated_fat: 14, trans_fat: 2, cholesterol: 60, sodium: 1700, total_carbohydrates: 50, dietary_fiber: 2, total_sugars: 8, protein: 28, ingredients_text: "spicy chicken breast (chicken, wheat flour, cayenne pepper, spices), brioche bun (enriched flour, wheat, butter, milk, egg), pickles, spicy mayo (soybean oil, egg)" },
    { name: "3 Piece Mixed Chicken (Mild)", category: "Chicken", serving_size: 340, serving_unit: "g", calories: 740, total_fat: 43, saturated_fat: 15, trans_fat: 2.5, cholesterol: 255, sodium: 1850, total_carbohydrates: 27, dietary_fiber: 2, total_sugars: 0, protein: 59, ingredients_text: "chicken (leg, thigh, breast), wheat flour, spices, salt, garlic, onion, vegetable oil" },
    { name: "3 Piece Tenders (Mild)", category: "Chicken", serving_size: 155, serving_unit: "g", calories: 410, total_fat: 19, saturated_fat: 7, trans_fat: 1, cholesterol: 90, sodium: 1430, total_carbohydrates: 26, dietary_fiber: 2, total_sugars: 0, protein: 32, ingredients_text: "chicken breast tenders, wheat flour, spices, salt, garlic, onion, vegetable oil" },
    { name: "5 Piece Tenders (Mild)", category: "Chicken", serving_size: 258, serving_unit: "g", calories: 680, total_fat: 32, saturated_fat: 12, trans_fat: 2, cholesterol: 150, sodium: 2380, total_carbohydrates: 43, dietary_fiber: 3, total_sugars: 0, protein: 53, ingredients_text: "chicken breast tenders, wheat flour, spices, salt, garlic, onion, vegetable oil" },
    { name: "Popcorn Shrimp (Regular)", category: "Seafood", serving_size: 114, serving_unit: "g", calories: 330, total_fat: 19, saturated_fat: 7, trans_fat: 1, cholesterol: 80, sodium: 1080, total_carbohydrates: 27, dietary_fiber: 1, total_sugars: 0, protein: 13, ingredients_text: "shrimp, wheat flour, corn flour, spices, salt, vegetable oil" },
    { name: "Cajun Fries (Regular)", category: "Sides", serving_size: 99, serving_unit: "g", calories: 260, total_fat: 14, saturated_fat: 5, trans_fat: 1, cholesterol: 0, sodium: 610, total_carbohydrates: 30, dietary_fiber: 3, total_sugars: 0, protein: 3, ingredients_text: "potatoes, vegetable oil, cajun seasoning (salt, garlic, paprika, onion, black pepper, cayenne pepper)" },
    { name: "Red Beans & Rice (Regular)", category: "Sides", serving_size: 167, serving_unit: "g", calories: 230, total_fat: 7, saturated_fat: 3, trans_fat: 0, cholesterol: 10, sodium: 680, total_carbohydrates: 30, dietary_fiber: 7, total_sugars: 1, protein: 9, ingredients_text: "red kidney beans, rice, pork, onion, celery, green pepper, garlic, spices, salt" },
    { name: "Mashed Potatoes with Cajun Gravy", category: "Sides", serving_size: 170, serving_unit: "g", calories: 110, total_fat: 4.5, saturated_fat: 2, trans_fat: 0, cholesterol: 5, sodium: 580, total_carbohydrates: 15, dietary_fiber: 1, total_sugars: 0, protein: 2, ingredients_text: "potatoes, butter (milk), milk, salt, pepper, cajun gravy (wheat flour, spices)" },
    { name: "Coleslaw (Regular)", category: "Sides", serving_size: 142, serving_unit: "g", calories: 170, total_fat: 11, saturated_fat: 2, trans_fat: 0, cholesterol: 15, sodium: 260, total_carbohydrates: 17, dietary_fiber: 2, total_sugars: 13, protein: 1, ingredients_text: "cabbage, carrot, mayonnaise (soybean oil, egg), sugar, vinegar, onion, celery seed" },
    { name: "Biscuit", category: "Sides", serving_size: 60, serving_unit: "g", calories: 200, total_fat: 9, saturated_fat: 5, trans_fat: 0, cholesterol: 0, sodium: 500, total_carbohydrates: 26, dietary_fiber: 1, total_sugars: 3, protein: 3, ingredients_text: "enriched flour (wheat), buttermilk (milk), butter, leavening, sugar, salt" },
    { name: "Cajun Rice (Regular)", category: "Sides", serving_size: 142, serving_unit: "g", calories: 180, total_fat: 7, saturated_fat: 2.5, trans_fat: 0, cholesterol: 25, sodium: 520, total_carbohydrates: 22, dietary_fiber: 1, total_sugars: 0, protein: 7, ingredients_text: "rice, pork, celery, green pepper, onion, cajun seasoning (salt, garlic, paprika, spices)" },
    { name: "Chicken Nuggets (8 piece)", category: "Chicken", serving_size: 136, serving_unit: "g", calories: 290, total_fat: 14, saturated_fat: 5, trans_fat: 0.5, cholesterol: 45, sodium: 720, total_carbohydrates: 22, dietary_fiber: 1, total_sugars: 0, protein: 18, ingredients_text: "chicken breast, wheat flour, corn starch, spices, salt, garlic, vegetable oil" },
    { name: "Butterfly Shrimp (8 piece)", category: "Seafood", serving_size: 113, serving_unit: "g", calories: 310, total_fat: 16, saturated_fat: 6, trans_fat: 1, cholesterol: 95, sodium: 870, total_carbohydrates: 25, dietary_fiber: 1, total_sugars: 0, protein: 16, ingredients_text: "shrimp, wheat flour, corn flour, spices, salt, vegetable oil" },
    { name: "2 Piece Leg & Thigh Combo", category: "Combos", serving_size: 280, serving_unit: "g", calories: 600, total_fat: 32, saturated_fat: 11, trans_fat: 1.5, cholesterol: 175, sodium: 1490, total_carbohydrates: 37, dietary_fiber: 4, total_sugars: 0, protein: 39, ingredients_text: "chicken (leg, thigh), wheat flour, spices, salt, vegetable oil, cajun fries (potatoes), biscuit (wheat flour, butter)" },
    { name: "Strawberry Biscuit", category: "Desserts", serving_size: 99, serving_unit: "g", calories: 310, total_fat: 11, saturated_fat: 6, trans_fat: 0, cholesterol: 5, sodium: 500, total_carbohydrates: 49, dietary_fiber: 1, total_sugars: 22, protein: 3, ingredients_text: "enriched flour (wheat), buttermilk (milk), butter, strawberry jam (strawberries, sugar), icing (sugar)" },
    { name: "Mac & Cheese", category: "Sides", serving_size: 142, serving_unit: "g", calories: 200, total_fat: 9, saturated_fat: 5, trans_fat: 0, cholesterol: 20, sodium: 710, total_carbohydrates: 22, dietary_fiber: 1, total_sugars: 2, protein: 8, ingredients_text: "pasta (wheat), cheddar cheese (milk), butter, milk, salt" },
    { name: "Corn on the Cob", category: "Sides", serving_size: 104, serving_unit: "g", calories: 190, total_fat: 5, saturated_fat: 1.5, trans_fat: 0, cholesterol: 0, sodium: 230, total_carbohydrates: 29, dietary_fiber: 3, total_sugars: 8, protein: 5, ingredients_text: "corn, butter, salt" },
    { name: "Green Beans", category: "Sides", serving_size: 142, serving_unit: "g", calories: 50, total_fat: 1.5, saturated_fat: 0.5, trans_fat: 0, cholesterol: 5, sodium: 340, total_carbohydrates: 7, dietary_fiber: 2, total_sugars: 2, protein: 2, ingredients_text: "green beans, turkey bacon, onion, garlic, salt, pepper" },
    { name: "Cinnamon Apple Pie", category: "Desserts", serving_size: 96, serving_unit: "g", calories: 250, total_fat: 12, saturated_fat: 5, trans_fat: 0, cholesterol: 5, sodium: 250, total_carbohydrates: 34, dietary_fiber: 1, total_sugars: 14, protein: 2, ingredients_text: "apples, enriched flour (wheat), sugar, cinnamon, palm oil, butter, salt" },
  ],
};

const dunkin: ChainData = {
  chain: "Dunkin'",
  items: [
    { name: "Medium Original Blend Iced Coffee", category: "Iced Coffee", serving_size: 680, serving_unit: "ml", calories: 15, total_fat: 0, saturated_fat: 0, trans_fat: 0, cholesterol: 0, sodium: 25, total_carbohydrates: 2, dietary_fiber: 0, total_sugars: 0, protein: 1, ingredients_text: "ice, brewed coffee (water, coffee)" },
    { name: "Medium Caramel Swirl Iced Latte", category: "Iced Coffee", serving_size: 680, serving_unit: "ml", calories: 320, total_fat: 9, saturated_fat: 5, trans_fat: 0, cholesterol: 30, sodium: 190, total_carbohydrates: 51, dietary_fiber: 0, total_sugars: 49, protein: 8, ingredients_text: "ice, milk, espresso, caramel swirl syrup (corn syrup, sweetened condensed milk, sugar, butter, salt)" },
    { name: "Medium Hot Latte", category: "Hot Coffee", serving_size: 473, serving_unit: "ml", calories: 120, total_fat: 4.5, saturated_fat: 2.5, trans_fat: 0, cholesterol: 15, sodium: 170, total_carbohydrates: 13, dietary_fiber: 0, total_sugars: 11, protein: 10, ingredients_text: "milk, espresso" },
    { name: "Medium Frozen Coffee (Cream)", category: "Frozen Beverages", serving_size: 680, serving_unit: "ml", calories: 420, total_fat: 17, saturated_fat: 11, trans_fat: 0, cholesterol: 50, sodium: 210, total_carbohydrates: 65, dietary_fiber: 0, total_sugars: 63, protein: 4, ingredients_text: "frozen coffee base (sugar, water, cream, coffee extract), milk, whipped cream (cream)" },
    { name: "Glazed Donut", category: "Donuts", serving_size: 63, serving_unit: "g", calories: 240, total_fat: 11, saturated_fat: 5, trans_fat: 0, cholesterol: 0, sodium: 340, total_carbohydrates: 33, dietary_fiber: 1, total_sugars: 12, protein: 3, ingredients_text: "enriched flour (wheat), palm oil, sugar, water, yeast, soy lecithin, milk, salt, glaze (sugar)" },
    { name: "Boston Kreme Donut", category: "Donuts", serving_size: 99, serving_unit: "g", calories: 300, total_fat: 15, saturated_fat: 7, trans_fat: 0, cholesterol: 20, sodium: 370, total_carbohydrates: 38, dietary_fiber: 1, total_sugars: 17, protein: 3, ingredients_text: "enriched flour (wheat), palm oil, sugar, bavarian kreme (sugar, water, corn starch, milk), chocolate icing (sugar, cocoa, palm oil)" },
    { name: "Chocolate Frosted Donut", category: "Donuts", serving_size: 71, serving_unit: "g", calories: 270, total_fat: 13, saturated_fat: 6, trans_fat: 0, cholesterol: 0, sodium: 340, total_carbohydrates: 35, dietary_fiber: 1, total_sugars: 15, protein: 3, ingredients_text: "enriched flour (wheat), palm oil, sugar, chocolate frosting (sugar, cocoa, palm oil, milk), yeast, soy lecithin" },
    { name: "Strawberry Frosted Donut with Sprinkles", category: "Donuts", serving_size: 74, serving_unit: "g", calories: 280, total_fat: 12, saturated_fat: 5, trans_fat: 0, cholesterol: 0, sodium: 340, total_carbohydrates: 40, dietary_fiber: 1, total_sugars: 19, protein: 3, ingredients_text: "enriched flour (wheat), palm oil, sugar, strawberry frosting (sugar, palm oil, artificial flavors), sprinkles (sugar), yeast" },
    { name: "Bacon, Egg & Cheese on Croissant", category: "Breakfast Sandwiches", serving_size: 152, serving_unit: "g", calories: 510, total_fat: 30, saturated_fat: 14, trans_fat: 0, cholesterol: 195, sodium: 1010, total_carbohydrates: 37, dietary_fiber: 1, total_sugars: 5, protein: 19, ingredients_text: "croissant (enriched flour, wheat, butter), egg, american cheese (milk), bacon (pork)" },
    { name: "Sausage, Egg & Cheese on English Muffin", category: "Breakfast Sandwiches", serving_size: 155, serving_unit: "g", calories: 480, total_fat: 28, saturated_fat: 12, trans_fat: 0, cholesterol: 205, sodium: 1080, total_carbohydrates: 34, dietary_fiber: 2, total_sugars: 3, protein: 21, ingredients_text: "english muffin (enriched flour, wheat), sausage patty (pork, salt, spices), egg, american cheese (milk)" },
    { name: "Turkey Sausage, Egg & Cheese on English Muffin", category: "Breakfast Sandwiches", serving_size: 155, serving_unit: "g", calories: 380, total_fat: 17, saturated_fat: 7, trans_fat: 0, cholesterol: 195, sodium: 980, total_carbohydrates: 33, dietary_fiber: 2, total_sugars: 2, protein: 21, ingredients_text: "english muffin (enriched flour, wheat), turkey sausage patty (turkey, salt, spices), egg, american cheese (milk)" },
    { name: "Hash Browns (6 piece)", category: "Sides", serving_size: 88, serving_unit: "g", calories: 250, total_fat: 17, saturated_fat: 2, trans_fat: 0, cholesterol: 0, sodium: 580, total_carbohydrates: 22, dietary_fiber: 2, total_sugars: 0, protein: 2, ingredients_text: "potatoes, vegetable oil (canola, soybean), salt, dehydrated potato" },
    { name: "Blueberry Muffin", category: "Bakery", serving_size: 131, serving_unit: "g", calories: 460, total_fat: 16, saturated_fat: 2.5, trans_fat: 0, cholesterol: 55, sodium: 460, total_carbohydrates: 72, dietary_fiber: 1, total_sugars: 40, protein: 6, ingredients_text: "enriched flour (wheat), sugar, blueberries, soybean oil, eggs, milk, leavening" },
    { name: "Chocolate Chip Muffin", category: "Bakery", serving_size: 131, serving_unit: "g", calories: 550, total_fat: 22, saturated_fat: 8, trans_fat: 0, cholesterol: 60, sodium: 440, total_carbohydrates: 80, dietary_fiber: 2, total_sugars: 46, protein: 7, ingredients_text: "enriched flour (wheat), sugar, chocolate chips, soybean oil, eggs, milk, leavening" },
    { name: "Bagel with Cream Cheese", category: "Bakery", serving_size: 155, serving_unit: "g", calories: 400, total_fat: 12, saturated_fat: 6, trans_fat: 0, cholesterol: 30, sodium: 680, total_carbohydrates: 61, dietary_fiber: 3, total_sugars: 9, protein: 13, ingredients_text: "bagel (enriched flour, wheat, water, sugar, salt, yeast), cream cheese (milk, cream, salt)" },
    { name: "Wake-Up Wrap (Bacon, Egg & Cheese)", category: "Wraps", serving_size: 92, serving_unit: "g", calories: 240, total_fat: 14, saturated_fat: 6, trans_fat: 0, cholesterol: 100, sodium: 580, total_carbohydrates: 15, dietary_fiber: 0, total_sugars: 1, protein: 11, ingredients_text: "flour tortilla (wheat), egg, american cheese (milk), bacon (pork)" },
    { name: "Medium Matcha Latte", category: "Hot Tea", serving_size: 473, serving_unit: "ml", calories: 200, total_fat: 5, saturated_fat: 3, trans_fat: 0, cholesterol: 20, sodium: 170, total_carbohydrates: 33, dietary_fiber: 1, total_sugars: 31, protein: 8, ingredients_text: "milk, matcha powder (sugar, green tea)" },
    { name: "Medium Chai Latte", category: "Hot Tea", serving_size: 473, serving_unit: "ml", calories: 230, total_fat: 5, saturated_fat: 3, trans_fat: 0, cholesterol: 20, sodium: 160, total_carbohydrates: 40, dietary_fiber: 0, total_sugars: 38, protein: 7, ingredients_text: "milk, chai concentrate (water, sugar, black tea, spices, ginger, honey)" },
    { name: "Coolatta (Strawberry, Medium)", category: "Frozen Beverages", serving_size: 680, serving_unit: "ml", calories: 350, total_fat: 0, saturated_fat: 0, trans_fat: 0, cholesterol: 0, sodium: 35, total_carbohydrates: 88, dietary_fiber: 0, total_sugars: 84, protein: 0, ingredients_text: "strawberry coolatta base (sugar, water, strawberry puree, citric acid, natural flavors)" },
    { name: "Avocado Toast", category: "Breakfast", serving_size: 142, serving_unit: "g", calories: 250, total_fat: 12, saturated_fat: 2, trans_fat: 0, cholesterol: 0, sodium: 440, total_carbohydrates: 30, dietary_fiber: 5, total_sugars: 3, protein: 6, ingredients_text: "sourdough bread (wheat flour, water, salt, yeast), avocado, everything seasoning (sesame seeds, salt)" },
  ],
};

export const ALL_CHAINS: ChainData[] = [
  mcdonalds,
  chickFilA,
  starbucks,
  chipotle,
  subway,
  tacoBell,
  wendys,
  pandaExpress,
  popeyes,
  dunkin,
];

/**
 * Returns all chain data. In a future version, this could fetch
 * from actual chain APIs or scrape published PDFs.
 */
export function getAllChainData(): ChainData[] {
  return ALL_CHAINS;
}
