/**
 * Restaurant Chain Nutrition Data Import — Remaining Major Chains
 *
 * Imports nutrition data for US restaurant chains not yet covered by
 * import-restaurants.ts or import-chains-batch1 through batch7.
 *
 * Chains added here:
 *   Popeyes, Hardee's, Rally's/Checkers, Moe's Southwest Grill,
 *   McAlister's Deli, Jason's Deli, Marco's Pizza, Dunkin',
 *   Hooters, Yard House, Baja Fresh, Taco Cabana, Torchy's Tacos,
 *   Pei Wei, Buc-ee's, Sweetgreen
 *
 * Sources: Published nutrition info from each chain's website (FDA-mandated).
 *   - popeyes.com/nutrition
 *   - hardees.com/nutrition
 *   - checkers.com/nutrition
 *   - moes.com/nutrition
 *   - mcalistersdeli.com/nutrition
 *   - jasonsdeli.com/nutrition
 *   - marcos.com/nutrition
 *   - dunkindonuts.com/en/food-drinks/nutrition
 *   - hooters.com/nutrition
 *   - yardhouse.com/nutrition
 *   - bajafresh.com/nutrition
 *   - tacocabana.com/nutrition
 *   - torchystacos.com/nutrition
 *   - peiwei.com/nutrition
 *   - buc-ees.com (limited published data)
 *   - sweetgreen.com/menu
 *
 * Usage:
 *   npx ts-node scripts/import-all-chains.ts
 */

import db from "../src/data/database";
import { calculateNutriScore } from "../src/services/nutrition-score";
import { calculatePersonalHealthScore } from "../src/services/health-score";
import { detectAllergens, detectDietaryTags } from "../src/services/food-analysis";
import { generateApiKey } from "../src/middleware/auth";

// ─── Types ───────────────────────────────────────────────────────────────────

interface MenuItem {
  name: string;
  category: string;
  serving_size: number;
  serving_unit: string;
  calories: number;
  total_fat: number;
  saturated_fat: number;
  trans_fat: number;
  cholesterol: number;
  sodium: number;
  total_carbohydrates: number;
  dietary_fiber: number;
  total_sugars: number;
  protein: number;
  ingredients_text?: string;
}

interface ChainData {
  chain: string;
  items: MenuItem[];
}

// ─── SQL Statements ──────────────────────────────────────────────────────────

const upsertVendor = db.prepare(`
  INSERT INTO vendors (id, name, type, api_key)
  VALUES (@id, @name, @type, @api_key)
  ON CONFLICT(id) DO UPDATE SET
    name = excluded.name,
    type = excluded.type
`);

const upsertFood = db.prepare(`
  INSERT INTO foods (id, name, brand, category, serving_size, serving_unit, source, vendor_id,
    calories, total_fat, saturated_fat, trans_fat, cholesterol, sodium,
    total_carbohydrates, dietary_fiber, total_sugars, protein,
    ingredients_text, allergens, dietary_tags, nutri_score, nutri_grade, culture_score,
    updated_at)
  VALUES (@id, @name, @brand, @category, @serving_size, @serving_unit, 'vendor', @vendor_id,
    @calories, @total_fat, @saturated_fat, @trans_fat, @cholesterol, @sodium,
    @total_carbohydrates, @dietary_fiber, @total_sugars, @protein,
    @ingredients_text, @allergens, @dietary_tags, @nutri_score, @nutri_grade, @culture_score,
    datetime('now'))
  ON CONFLICT(id) DO UPDATE SET
    name = excluded.name,
    brand = excluded.brand,
    category = excluded.category,
    serving_size = excluded.serving_size,
    serving_unit = excluded.serving_unit,
    vendor_id = excluded.vendor_id,
    calories = excluded.calories,
    total_fat = excluded.total_fat,
    saturated_fat = excluded.saturated_fat,
    trans_fat = excluded.trans_fat,
    cholesterol = excluded.cholesterol,
    sodium = excluded.sodium,
    total_carbohydrates = excluded.total_carbohydrates,
    dietary_fiber = excluded.dietary_fiber,
    total_sugars = excluded.total_sugars,
    protein = excluded.protein,
    ingredients_text = excluded.ingredients_text,
    allergens = excluded.allergens,
    dietary_tags = excluded.dietary_tags,
    nutri_score = excluded.nutri_score,
    nutri_grade = excluded.nutri_grade,
    culture_score = excluded.culture_score,
    updated_at = datetime('now')
`);

// ─── Helpers ─────────────────────────────────────────────────────────────────

function slugify(name: string): string {
  return name
    .toLowerCase()
    .replace(/['']/g, "")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

function buildFoodRecord(item: MenuItem, chainName: string, vendorId: string) {
  const chainSlug = slugify(chainName);
  const itemSlug = slugify(item.name);
  const id = `chain-${chainSlug}-${itemSlug}`;

  const servingG = item.serving_unit === "g" ? item.serving_size : item.serving_size * 1;
  const factor = servingG > 0 ? 100 / servingG : 1;

  const nutriResult = calculateNutriScore(
    {
      calories: item.calories * factor,
      totalSugars: item.total_sugars * factor,
      saturatedFat: item.saturated_fat * factor,
      sodium: item.sodium * factor,
      dietaryFiber: item.dietary_fiber * factor,
      protein: item.protein * factor,
    },
    item.category
  );

  const ingredientsText = item.ingredients_text || null;
  const allergens = ingredientsText ? detectAllergens(ingredientsText) : [];
  const dietaryTags = detectDietaryTags(ingredientsText || "", {
    total_carbohydrates: item.total_carbohydrates,
    protein: item.protein,
    total_fat: item.total_fat,
    total_sugars: item.total_sugars,
    dietary_fiber: item.dietary_fiber,
  });

  const cultureScore = calculatePersonalHealthScore(
    {
      calories: item.calories,
      protein: item.protein,
      dietary_fiber: item.dietary_fiber,
      saturated_fat: item.saturated_fat,
      sodium: item.sodium,
      total_sugars: item.total_sugars,
      total_fat: item.total_fat,
      total_carbohydrates: item.total_carbohydrates,
      cholesterol: item.cholesterol,
      trans_fat: item.trans_fat,
    },
    null
  ).score;

  return {
    id,
    name: item.name,
    brand: chainName,
    category: item.category,
    serving_size: item.serving_size,
    serving_unit: item.serving_unit,
    vendor_id: vendorId,
    calories: item.calories,
    total_fat: item.total_fat,
    saturated_fat: item.saturated_fat,
    trans_fat: item.trans_fat,
    cholesterol: item.cholesterol,
    sodium: item.sodium,
    total_carbohydrates: item.total_carbohydrates,
    dietary_fiber: item.dietary_fiber,
    total_sugars: item.total_sugars,
    protein: item.protein,
    ingredients_text: ingredientsText,
    allergens: allergens.length > 0 ? allergens.join(",") : null,
    dietary_tags: dietaryTags.length > 0 ? dietaryTags.join(",") : null,
    nutri_score: nutriResult.score,
    nutri_grade: nutriResult.grade,
    culture_score: cultureScore,
  };
}

// ═══════════════════════════════════════════════════════════════════════════════
// Chain Menu Data — Real published nutrition facts
// ═══════════════════════════════════════════════════════════════════════════════

// ─── Popeyes ─────────────────────────────────────────────────────────────────
// Source: popeyes.com/nutrition

const popeyes: ChainData = {
  chain: "Popeyes",
  items: [
    {
      name: "Classic Chicken Sandwich",
      category: "chicken",
      serving_size: 225,
      serving_unit: "g",
      calories: 700,
      total_fat: 42,
      saturated_fat: 14,
      trans_fat: 1,
      cholesterol: 60,
      sodium: 1440,
      total_carbohydrates: 50,
      dietary_fiber: 2,
      total_sugars: 8,
      protein: 28,
      ingredients_text:
        "Chicken breast fillet (chicken, water, salt, sodium phosphates), flour (bleached wheat flour, niacin, iron, thiamine, riboflavin, folic acid), buttermilk batter (water, wheat flour, salt, spices, garlic powder, onion powder), brioche bun (enriched flour, water, sugar, butter, eggs, yeast, salt), barrel cured pickles, mayo (soybean oil, egg yolks, vinegar)",
    },
    {
      name: "Spicy Chicken Sandwich",
      category: "chicken",
      serving_size: 225,
      serving_unit: "g",
      calories: 700,
      total_fat: 42,
      saturated_fat: 14,
      trans_fat: 1,
      cholesterol: 60,
      sodium: 1700,
      total_carbohydrates: 50,
      dietary_fiber: 3,
      total_sugars: 8,
      protein: 28,
      ingredients_text:
        "Chicken breast fillet (chicken, water, salt, sodium phosphates), spicy flour (bleached wheat flour, spices, cayenne pepper, garlic powder, salt), buttermilk batter, brioche bun (enriched flour, water, sugar, butter, eggs, yeast, salt), barrel cured pickles, spicy mayo (soybean oil, egg yolks, vinegar, cayenne)",
    },
    {
      name: "3pc Chicken Tenders",
      category: "chicken",
      serving_size: 153,
      serving_unit: "g",
      calories: 410,
      total_fat: 22,
      saturated_fat: 7,
      trans_fat: 0.5,
      cholesterol: 85,
      sodium: 1230,
      total_carbohydrates: 22,
      dietary_fiber: 1,
      total_sugars: 0,
      protein: 30,
      ingredients_text:
        "Chicken tenderloins (chicken, water, salt, sodium phosphates), seasoned coating (wheat flour, salt, spices, garlic powder, onion powder, leavening), frying oil (palm oil, canola oil)",
    },
    {
      name: "5pc Chicken Tenders",
      category: "chicken",
      serving_size: 255,
      serving_unit: "g",
      calories: 680,
      total_fat: 37,
      saturated_fat: 12,
      trans_fat: 1,
      cholesterol: 140,
      sodium: 2050,
      total_carbohydrates: 37,
      dietary_fiber: 1,
      total_sugars: 0,
      protein: 50,
      ingredients_text:
        "Chicken tenderloins (chicken, water, salt, sodium phosphates), seasoned coating (wheat flour, salt, spices, garlic powder, onion powder, leavening), frying oil (palm oil, canola oil)",
    },
    {
      name: "Mild Chicken Leg",
      category: "chicken",
      serving_size: 81,
      serving_unit: "g",
      calories: 160,
      total_fat: 9,
      saturated_fat: 3.5,
      trans_fat: 0,
      cholesterol: 70,
      sodium: 460,
      total_carbohydrates: 5,
      dietary_fiber: 0,
      total_sugars: 0,
      protein: 14,
      ingredients_text:
        "Chicken leg, seasoned flour (wheat flour, salt, spices, garlic powder, onion powder), frying oil",
    },
    {
      name: "Mild Chicken Breast",
      category: "chicken",
      serving_size: 175,
      serving_unit: "g",
      calories: 380,
      total_fat: 21,
      saturated_fat: 8,
      trans_fat: 0.5,
      cholesterol: 150,
      sodium: 1230,
      total_carbohydrates: 14,
      dietary_fiber: 1,
      total_sugars: 0,
      protein: 34,
      ingredients_text:
        "Chicken breast, seasoned flour (wheat flour, salt, spices, garlic powder, onion powder, paprika), frying oil (palm oil, canola oil)",
    },
    {
      name: "Spicy Chicken Thigh",
      category: "chicken",
      serving_size: 131,
      serving_unit: "g",
      calories: 290,
      total_fat: 19,
      saturated_fat: 7,
      trans_fat: 0,
      cholesterol: 90,
      sodium: 700,
      total_carbohydrates: 8,
      dietary_fiber: 0,
      total_sugars: 0,
      protein: 21,
      ingredients_text:
        "Chicken thigh, spicy seasoned flour (wheat flour, salt, cayenne pepper, spices, garlic powder, onion powder), frying oil",
    },
    {
      name: "Red Beans and Rice (Regular)",
      category: "side",
      serving_size: 198,
      serving_unit: "g",
      calories: 230,
      total_fat: 6,
      saturated_fat: 2.5,
      trans_fat: 0,
      cholesterol: 15,
      sodium: 690,
      total_carbohydrates: 34,
      dietary_fiber: 6,
      total_sugars: 1,
      protein: 9,
      ingredients_text:
        "Red kidney beans, rice, water, pork fat, seasoning (salt, spices, onion powder, garlic powder)",
    },
    {
      name: "Cajun Fries (Regular)",
      category: "side",
      serving_size: 113,
      serving_unit: "g",
      calories: 260,
      total_fat: 14,
      saturated_fat: 3,
      trans_fat: 0,
      cholesterol: 0,
      sodium: 780,
      total_carbohydrates: 30,
      dietary_fiber: 3,
      total_sugars: 0,
      protein: 3,
      ingredients_text:
        "Potatoes, vegetable oil (palm, canola), cajun seasoning (salt, garlic powder, paprika, spices, onion powder)",
    },
    {
      name: "Biscuit",
      category: "bread",
      serving_size: 62,
      serving_unit: "g",
      calories: 200,
      total_fat: 10,
      saturated_fat: 5,
      trans_fat: 0,
      cholesterol: 0,
      sodium: 510,
      total_carbohydrates: 26,
      dietary_fiber: 1,
      total_sugars: 3,
      protein: 3,
      ingredients_text:
        "Enriched flour (wheat flour, niacin, iron, thiamine, riboflavin, folic acid), buttermilk, butter, sugar, salt, leavening (baking soda, sodium aluminum phosphate)",
    },
    {
      name: "Mashed Potatoes with Cajun Gravy (Regular)",
      category: "side",
      serving_size: 170,
      serving_unit: "g",
      calories: 110,
      total_fat: 4,
      saturated_fat: 1.5,
      trans_fat: 0,
      cholesterol: 5,
      sodium: 570,
      total_carbohydrates: 16,
      dietary_fiber: 2,
      total_sugars: 1,
      protein: 2,
      ingredients_text:
        "Potatoes (potatoes, water, butter, salt, milk), cajun gravy (water, modified corn starch, chicken fat, salt, spices, onion powder, garlic powder)",
    },
    {
      name: "Coleslaw (Regular)",
      category: "side",
      serving_size: 124,
      serving_unit: "g",
      calories: 170,
      total_fat: 11,
      saturated_fat: 2,
      trans_fat: 0,
      cholesterol: 10,
      sodium: 210,
      total_carbohydrates: 18,
      dietary_fiber: 1,
      total_sugars: 14,
      protein: 1,
      ingredients_text:
        "Cabbage, carrots, sugar, soybean oil, vinegar, egg yolks, salt, spices",
    },
    {
      name: "Chicken Nuggets 8pc",
      category: "chicken",
      serving_size: 128,
      serving_unit: "g",
      calories: 280,
      total_fat: 16,
      saturated_fat: 5,
      trans_fat: 0,
      cholesterol: 50,
      sodium: 810,
      total_carbohydrates: 15,
      dietary_fiber: 1,
      total_sugars: 0,
      protein: 19,
      ingredients_text:
        "Chicken breast meat, water, seasoned flour (wheat flour, salt, spices), frying oil (palm oil, canola oil)",
    },
  ],
};

// ─── Hardee's ────────────────────────────────────────────────────────────────
// Source: hardees.com/nutrition

const hardees: ChainData = {
  chain: "Hardee's",
  items: [
    {
      name: "Famous Star with Cheese",
      category: "burger",
      serving_size: 278,
      serving_unit: "g",
      calories: 680,
      total_fat: 39,
      saturated_fat: 14,
      trans_fat: 1,
      cholesterol: 85,
      sodium: 1210,
      total_carbohydrates: 53,
      dietary_fiber: 2,
      total_sugars: 11,
      protein: 29,
      ingredients_text:
        "Beef patty, sesame seed bun (enriched flour, water, sugar, soybean oil, yeast, sesame seeds, salt), American cheese (milk, cream, sodium citrate, salt), lettuce, tomato, onion, pickles, ketchup, mayo (soybean oil, egg yolks, vinegar), mustard",
    },
    {
      name: "Thickburger (1/3 lb)",
      category: "burger",
      serving_size: 326,
      serving_unit: "g",
      calories: 850,
      total_fat: 57,
      saturated_fat: 22,
      trans_fat: 2,
      cholesterol: 130,
      sodium: 1470,
      total_carbohydrates: 49,
      dietary_fiber: 2,
      total_sugars: 10,
      protein: 36,
      ingredients_text:
        "Beef patty (1/3 lb), sesame seed bun, American cheese (2 slices, milk, cream, salt), lettuce, tomato, onion, pickles, ketchup, mayo, mustard",
    },
    {
      name: "Frisco Thickburger",
      category: "burger",
      serving_size: 338,
      serving_unit: "g",
      calories: 920,
      total_fat: 60,
      saturated_fat: 24,
      trans_fat: 2,
      cholesterol: 140,
      sodium: 1690,
      total_carbohydrates: 53,
      dietary_fiber: 2,
      total_sugars: 10,
      protein: 41,
      ingredients_text:
        "Beef patty (1/3 lb), sourdough bun, Swiss cheese (milk, cultures, salt, enzymes), American cheese, tomato, Frisco sauce (soybean oil, vinegar, sugar, spices), bacon (cured with water, salt, sugar, sodium phosphate, sodium nitrite)",
    },
    {
      name: "Big Hot Ham 'N' Cheese",
      category: "sandwich",
      serving_size: 263,
      serving_unit: "g",
      calories: 530,
      total_fat: 24,
      saturated_fat: 10,
      trans_fat: 0.5,
      cholesterol: 80,
      sodium: 1810,
      total_carbohydrates: 43,
      dietary_fiber: 2,
      total_sugars: 7,
      protein: 32,
      ingredients_text:
        "Ham (cured with water, salt, dextrose, sodium phosphates), Swiss cheese (milk, cultures, salt, enzymes), sesame seed bun (enriched flour, water, sugar, yeast, salt), mayo, lettuce, tomato",
    },
    {
      name: "Hand-Breaded Chicken Tenders (3pc)",
      category: "chicken",
      serving_size: 140,
      serving_unit: "g",
      calories: 360,
      total_fat: 18,
      saturated_fat: 3,
      trans_fat: 0,
      cholesterol: 60,
      sodium: 1100,
      total_carbohydrates: 26,
      dietary_fiber: 1,
      total_sugars: 0,
      protein: 24,
      ingredients_text:
        "Chicken tenderloins, seasoned flour (wheat flour, salt, spices, garlic powder, onion powder, leavening), frying oil (soybean oil)",
    },
    {
      name: "Made from Scratch Biscuit",
      category: "bread",
      serving_size: 88,
      serving_unit: "g",
      calories: 370,
      total_fat: 23,
      saturated_fat: 7,
      trans_fat: 0,
      cholesterol: 0,
      sodium: 900,
      total_carbohydrates: 35,
      dietary_fiber: 1,
      total_sugars: 4,
      protein: 5,
      ingredients_text:
        "Enriched flour (wheat flour, niacin, iron, thiamine, riboflavin, folic acid), buttermilk, vegetable shortening (palm, soybean), sugar, salt, leavening (baking soda, sodium aluminum phosphate)",
    },
    {
      name: "Biscuit 'N' Gravy",
      category: "breakfast",
      serving_size: 213,
      serving_unit: "g",
      calories: 510,
      total_fat: 31,
      saturated_fat: 11,
      trans_fat: 0,
      cholesterol: 15,
      sodium: 1560,
      total_carbohydrates: 44,
      dietary_fiber: 1,
      total_sugars: 5,
      protein: 13,
      ingredients_text:
        "Biscuit (enriched flour, buttermilk, shortening, sugar, salt, leavening), sausage gravy (water, pork sausage, enriched flour, pork fat, salt, spices, black pepper)",
    },
    {
      name: "Bacon, Egg & Cheese Biscuit",
      category: "breakfast",
      serving_size: 167,
      serving_unit: "g",
      calories: 560,
      total_fat: 38,
      saturated_fat: 14,
      trans_fat: 0,
      cholesterol: 245,
      sodium: 1320,
      total_carbohydrates: 36,
      dietary_fiber: 1,
      total_sugars: 4,
      protein: 19,
      ingredients_text:
        "Biscuit (enriched flour, buttermilk, shortening, sugar, salt, leavening), bacon (cured with water, salt, sugar, sodium nitrite), egg, American cheese (milk, cream, salt)",
    },
    {
      name: "Hash Rounds (Medium)",
      category: "side",
      serving_size: 108,
      serving_unit: "g",
      calories: 340,
      total_fat: 20,
      saturated_fat: 4,
      trans_fat: 0,
      cholesterol: 0,
      sodium: 560,
      total_carbohydrates: 36,
      dietary_fiber: 3,
      total_sugars: 0,
      protein: 3,
      ingredients_text:
        "Potatoes (dehydrated potatoes, dextrose, sodium acid pyrophosphate), vegetable oil (soybean oil, palm oil), salt",
    },
    {
      name: "Natural-Cut French Fries (Medium)",
      category: "side",
      serving_size: 142,
      serving_unit: "g",
      calories: 430,
      total_fat: 22,
      saturated_fat: 4,
      trans_fat: 0,
      cholesterol: 0,
      sodium: 460,
      total_carbohydrates: 53,
      dietary_fiber: 5,
      total_sugars: 0,
      protein: 5,
      ingredients_text:
        "Potatoes, vegetable oil (soybean oil, canola oil), dextrose, sodium acid pyrophosphate, salt",
    },
  ],
};

// ─── Rally's / Checkers ──────────────────────────────────────────────────────
// Source: checkers.com/nutrition

const rallysCheckers: ChainData = {
  chain: "Rally's/Checkers",
  items: [
    {
      name: "Big Buford",
      category: "burger",
      serving_size: 314,
      serving_unit: "g",
      calories: 860,
      total_fat: 53,
      saturated_fat: 22,
      trans_fat: 2.5,
      cholesterol: 140,
      sodium: 1170,
      total_carbohydrates: 53,
      dietary_fiber: 2,
      total_sugars: 10,
      protein: 42,
      ingredients_text:
        "Two beef patties, sesame seed bun (enriched flour, water, sugar, yeast, soybean oil, salt, sesame seeds), American cheese (2 slices, milk, cream, sodium citrate), lettuce, tomato, onion, pickles, ketchup, mayo, mustard",
    },
    {
      name: "Checkerburger",
      category: "burger",
      serving_size: 172,
      serving_unit: "g",
      calories: 410,
      total_fat: 22,
      saturated_fat: 9,
      trans_fat: 1,
      cholesterol: 65,
      sodium: 720,
      total_carbohydrates: 34,
      dietary_fiber: 2,
      total_sugars: 7,
      protein: 20,
      ingredients_text:
        "Beef patty, sesame seed bun (enriched flour, water, sugar, yeast, soybean oil, salt), American cheese, lettuce, tomato, onion, pickles, ketchup, mayo, mustard",
    },
    {
      name: "Baconzilla",
      category: "burger",
      serving_size: 354,
      serving_unit: "g",
      calories: 1040,
      total_fat: 69,
      saturated_fat: 30,
      trans_fat: 3,
      cholesterol: 180,
      sodium: 1750,
      total_carbohydrates: 53,
      dietary_fiber: 2,
      total_sugars: 11,
      protein: 53,
      ingredients_text:
        "Two beef patties, sesame seed bun, bacon (cured pork, water, salt, sugar, sodium nitrite), American cheese (2 slices), ketchup, mayo, mustard",
    },
    {
      name: "Spicy Chicken Sandwich",
      category: "chicken",
      serving_size: 192,
      serving_unit: "g",
      calories: 540,
      total_fat: 28,
      saturated_fat: 5,
      trans_fat: 0,
      cholesterol: 55,
      sodium: 1110,
      total_carbohydrates: 52,
      dietary_fiber: 2,
      total_sugars: 6,
      protein: 22,
      ingredients_text:
        "Chicken breast fillet (chicken, water, salt, spices, sodium phosphates), seasoned flour (wheat flour, salt, cayenne pepper, spices), bun (enriched flour, water, sugar, yeast, salt), lettuce, mayo",
    },
    {
      name: "Famous Seasoned Fries (Medium)",
      category: "side",
      serving_size: 142,
      serving_unit: "g",
      calories: 380,
      total_fat: 19,
      saturated_fat: 4,
      trans_fat: 0,
      cholesterol: 0,
      sodium: 870,
      total_carbohydrates: 48,
      dietary_fiber: 4,
      total_sugars: 0,
      protein: 4,
      ingredients_text:
        "Potatoes, vegetable oil (canola, soybean), seasoning (salt, paprika, garlic powder, onion powder, spices), dextrose, sodium acid pyrophosphate",
    },
    {
      name: "Fully Loaded Fries",
      category: "side",
      serving_size: 270,
      serving_unit: "g",
      calories: 610,
      total_fat: 35,
      saturated_fat: 11,
      trans_fat: 0,
      cholesterol: 45,
      sodium: 1490,
      total_carbohydrates: 56,
      dietary_fiber: 4,
      total_sugars: 3,
      protein: 16,
      ingredients_text:
        "Seasoned fries (potatoes, vegetable oil, seasoning), cheddar cheese sauce (water, cheddar cheese, milk, sodium phosphate), bacon (cured pork, salt, sugar), ranch dressing (soybean oil, buttermilk, egg yolk, vinegar, salt)",
    },
    {
      name: "Crispy Fish Sandwich",
      category: "seafood",
      serving_size: 184,
      serving_unit: "g",
      calories: 490,
      total_fat: 26,
      saturated_fat: 5,
      trans_fat: 0,
      cholesterol: 40,
      sodium: 950,
      total_carbohydrates: 48,
      dietary_fiber: 2,
      total_sugars: 6,
      protein: 17,
      ingredients_text:
        "Fish fillet (pollock, wheat flour, water, salt, spices), bun (enriched flour, water, sugar, yeast, salt), tartar sauce (soybean oil, pickle relish, egg yolks, vinegar), lettuce",
    },
    {
      name: "Banana Milkshake (Medium)",
      category: "dessert",
      serving_size: 453,
      serving_unit: "g",
      calories: 660,
      total_fat: 25,
      saturated_fat: 16,
      trans_fat: 1,
      cholesterol: 95,
      sodium: 380,
      total_carbohydrates: 97,
      dietary_fiber: 0,
      total_sugars: 80,
      protein: 13,
      ingredients_text:
        "Vanilla ice cream (milk, cream, sugar, corn syrup, whey, mono and diglycerides, vanilla extract), banana flavoring, whipped cream",
    },
    {
      name: "Mother Cruncher Chicken Sandwich",
      category: "chicken",
      serving_size: 224,
      serving_unit: "g",
      calories: 640,
      total_fat: 35,
      saturated_fat: 7,
      trans_fat: 0,
      cholesterol: 65,
      sodium: 1280,
      total_carbohydrates: 56,
      dietary_fiber: 3,
      total_sugars: 7,
      protein: 26,
      ingredients_text:
        "Chicken breast fillet (chicken, water, salt, sodium phosphates), seasoned breading (wheat flour, salt, spices, garlic powder), bun (enriched flour, water, sugar, yeast, salt), pickles, mayo, lettuce",
    },
    {
      name: "Deep Sea Double Fish",
      category: "seafood",
      serving_size: 270,
      serving_unit: "g",
      calories: 750,
      total_fat: 41,
      saturated_fat: 9,
      trans_fat: 0,
      cholesterol: 65,
      sodium: 1510,
      total_carbohydrates: 64,
      dietary_fiber: 3,
      total_sugars: 7,
      protein: 28,
      ingredients_text:
        "Two fish fillets (pollock, wheat flour, water, salt), bun (enriched flour, water, sugar, yeast, salt), American cheese, tartar sauce, lettuce",
    },
  ],
};

// ─── Moe's Southwest Grill ──────────────────────────────────────────────────
// Source: moes.com/nutrition

const moes: ChainData = {
  chain: "Moe's Southwest Grill",
  items: [
    {
      name: "Homewrecker Burrito (Chicken)",
      category: "entree",
      serving_size: 595,
      serving_unit: "g",
      calories: 920,
      total_fat: 36,
      saturated_fat: 15,
      trans_fat: 0,
      cholesterol: 130,
      sodium: 2280,
      total_carbohydrates: 97,
      dietary_fiber: 13,
      total_sugars: 5,
      protein: 53,
      ingredients_text:
        "Flour tortilla (enriched flour, water, vegetable shortening, salt, leavening), grilled chicken (chicken, water, seasoning, soybean oil), seasoned rice, black beans, shredded cheese (cheddar, jack; milk, cultures, salt, enzymes), pico de gallo, sour cream, shredded lettuce, guacamole",
    },
    {
      name: "Homewrecker Burrito (Steak)",
      category: "entree",
      serving_size: 595,
      serving_unit: "g",
      calories: 960,
      total_fat: 40,
      saturated_fat: 17,
      trans_fat: 0.5,
      cholesterol: 140,
      sodium: 2290,
      total_carbohydrates: 97,
      dietary_fiber: 13,
      total_sugars: 5,
      protein: 53,
      ingredients_text:
        "Flour tortilla (enriched flour, water, vegetable shortening, salt, leavening), grilled steak (beef, water, seasoning, soybean oil), seasoned rice, black beans, shredded cheese, pico de gallo, sour cream, shredded lettuce, guacamole",
    },
    {
      name: "Joey Bag of Donuts Burrito (Chicken)",
      category: "entree",
      serving_size: 445,
      serving_unit: "g",
      calories: 690,
      total_fat: 26,
      saturated_fat: 11,
      trans_fat: 0,
      cholesterol: 100,
      sodium: 1850,
      total_carbohydrates: 72,
      dietary_fiber: 8,
      total_sugars: 3,
      protein: 40,
      ingredients_text:
        "Flour tortilla, grilled chicken, seasoned rice, shredded cheese (cheddar, jack; milk, cultures, salt, enzymes), pico de gallo, sour cream, shredded lettuce",
    },
    {
      name: "Close Talker Quesadilla (Chicken)",
      category: "entree",
      serving_size: 334,
      serving_unit: "g",
      calories: 780,
      total_fat: 42,
      saturated_fat: 20,
      trans_fat: 0.5,
      cholesterol: 140,
      sodium: 1780,
      total_carbohydrates: 52,
      dietary_fiber: 4,
      total_sugars: 2,
      protein: 48,
      ingredients_text:
        "Flour tortilla (enriched flour, water, shortening, salt), grilled chicken, shredded cheese (cheddar, jack; milk, cultures, salt, enzymes), pico de gallo, sour cream",
    },
    {
      name: "Stack (Chicken)",
      category: "entree",
      serving_size: 280,
      serving_unit: "g",
      calories: 500,
      total_fat: 24,
      saturated_fat: 10,
      trans_fat: 0,
      cholesterol: 95,
      sodium: 1130,
      total_carbohydrates: 42,
      dietary_fiber: 3,
      total_sugars: 3,
      protein: 30,
      ingredients_text:
        "Two corn tortillas (ground corn, water, lime), grilled chicken, shredded cheese (cheddar, jack; milk, cultures, salt, enzymes), pico de gallo, shredded lettuce, sour cream",
    },
    {
      name: "Nachos (Chicken)",
      category: "entree",
      serving_size: 480,
      serving_unit: "g",
      calories: 1020,
      total_fat: 52,
      saturated_fat: 22,
      trans_fat: 0.5,
      cholesterol: 130,
      sodium: 2050,
      total_carbohydrates: 90,
      dietary_fiber: 10,
      total_sugars: 4,
      protein: 48,
      ingredients_text:
        "Tortilla chips (corn, vegetable oil, salt), grilled chicken, queso (water, cheddar cheese, milk, sodium phosphate), black beans, pico de gallo, sour cream, guacamole, jalapeños",
    },
    {
      name: "Queso (Side)",
      category: "side",
      serving_size: 85,
      serving_unit: "g",
      calories: 140,
      total_fat: 10,
      saturated_fat: 5,
      trans_fat: 0,
      cholesterol: 25,
      sodium: 580,
      total_carbohydrates: 6,
      dietary_fiber: 0,
      total_sugars: 2,
      protein: 6,
      ingredients_text:
        "Water, cheddar cheese (milk, cultures, salt, enzymes), milk, sodium phosphate, jalapeños, salt, spices",
    },
    {
      name: "Chips and Salsa",
      category: "side",
      serving_size: 170,
      serving_unit: "g",
      calories: 390,
      total_fat: 18,
      saturated_fat: 2.5,
      trans_fat: 0,
      cholesterol: 0,
      sodium: 560,
      total_carbohydrates: 52,
      dietary_fiber: 4,
      total_sugars: 3,
      protein: 5,
      ingredients_text:
        "Tortilla chips (corn, vegetable oil, salt), salsa (tomatoes, onion, jalapeño, cilantro, lime juice, salt)",
    },
    {
      name: "Power Bowl (Chicken)",
      category: "entree",
      serving_size: 480,
      serving_unit: "g",
      calories: 590,
      total_fat: 21,
      saturated_fat: 7,
      trans_fat: 0,
      cholesterol: 100,
      sodium: 1530,
      total_carbohydrates: 62,
      dietary_fiber: 10,
      total_sugars: 4,
      protein: 42,
      ingredients_text:
        "Seasoned rice, grilled chicken, black beans, shredded cheese (cheddar, jack; milk, cultures, salt, enzymes), pico de gallo, shredded lettuce, guacamole",
    },
    {
      name: "Stacked Queso Burrito (Chicken)",
      category: "entree",
      serving_size: 510,
      serving_unit: "g",
      calories: 870,
      total_fat: 40,
      saturated_fat: 17,
      trans_fat: 0,
      cholesterol: 130,
      sodium: 2480,
      total_carbohydrates: 82,
      dietary_fiber: 7,
      total_sugars: 4,
      protein: 46,
      ingredients_text:
        "Flour tortilla, grilled chicken, queso, seasoned rice, black beans, shredded cheese, pico de gallo, sour cream",
    },
  ],
};

// ─── McAlister's Deli ────────────────────────────────────────────────────────
// Source: mcalistersdeli.com/nutrition

const mcalisters: ChainData = {
  chain: "McAlister's Deli",
  items: [
    {
      name: "McAlister's Club",
      category: "sandwich",
      serving_size: 375,
      serving_unit: "g",
      calories: 840,
      total_fat: 44,
      saturated_fat: 11,
      trans_fat: 0,
      cholesterol: 105,
      sodium: 2260,
      total_carbohydrates: 69,
      dietary_fiber: 4,
      total_sugars: 7,
      protein: 40,
      ingredients_text:
        "Wheat bread, turkey breast (turkey, water, salt, dextrose), ham (cured pork, water, salt, sugar, sodium nitrite), bacon (cured pork, salt, sugar, sodium nitrite), Swiss cheese (milk, cultures, salt, enzymes), lettuce, tomato, mayo (soybean oil, egg yolks, vinegar)",
    },
    {
      name: "King Club",
      category: "sandwich",
      serving_size: 430,
      serving_unit: "g",
      calories: 1020,
      total_fat: 54,
      saturated_fat: 14,
      trans_fat: 0,
      cholesterol: 140,
      sodium: 2880,
      total_carbohydrates: 78,
      dietary_fiber: 5,
      total_sugars: 9,
      protein: 52,
      ingredients_text:
        "Wheat bread, double turkey, ham, bacon, Swiss cheese, American cheese, lettuce, tomato, mayo",
    },
    {
      name: "The Spud Max (Loaded Baked Potato)",
      category: "entree",
      serving_size: 510,
      serving_unit: "g",
      calories: 870,
      total_fat: 38,
      saturated_fat: 18,
      trans_fat: 0.5,
      cholesterol: 85,
      sodium: 1630,
      total_carbohydrates: 99,
      dietary_fiber: 8,
      total_sugars: 8,
      protein: 30,
      ingredients_text:
        "Baked potato, butter, cheddar cheese (milk, cultures, salt, enzymes), bacon (cured pork, salt, sugar), sour cream, broccoli, chives",
    },
    {
      name: "Chicken Tortilla Soup (Cup)",
      category: "soup",
      serving_size: 227,
      serving_unit: "g",
      calories: 180,
      total_fat: 8,
      saturated_fat: 2.5,
      trans_fat: 0,
      cholesterol: 30,
      sodium: 890,
      total_carbohydrates: 17,
      dietary_fiber: 2,
      total_sugars: 3,
      protein: 10,
      ingredients_text:
        "Chicken broth, chicken, tomatoes, corn, black beans, onion, jalapeño, corn tortilla strips, seasoning (chili powder, cumin, garlic, salt, pepper)",
    },
    {
      name: "Broccoli Cheddar Soup (Cup)",
      category: "soup",
      serving_size: 227,
      serving_unit: "g",
      calories: 230,
      total_fat: 16,
      saturated_fat: 8,
      trans_fat: 0,
      cholesterol: 35,
      sodium: 820,
      total_carbohydrates: 12,
      dietary_fiber: 1,
      total_sugars: 4,
      protein: 8,
      ingredients_text:
        "Water, cheddar cheese (milk, cultures, salt, enzymes), broccoli, cream, modified corn starch, salt, spices",
    },
    {
      name: "Harvest Chicken Salad Sandwich",
      category: "sandwich",
      serving_size: 340,
      serving_unit: "g",
      calories: 710,
      total_fat: 29,
      saturated_fat: 5,
      trans_fat: 0,
      cholesterol: 80,
      sodium: 1370,
      total_carbohydrates: 80,
      dietary_fiber: 6,
      total_sugars: 20,
      protein: 28,
      ingredients_text:
        "Wheat bread, chicken salad (chicken, mayo, grapes, celery, pecans, salt, pepper), lettuce, tomato",
    },
    {
      name: "Italian Sandwich",
      category: "sandwich",
      serving_size: 350,
      serving_unit: "g",
      calories: 780,
      total_fat: 40,
      saturated_fat: 14,
      trans_fat: 0,
      cholesterol: 95,
      sodium: 2580,
      total_carbohydrates: 64,
      dietary_fiber: 3,
      total_sugars: 6,
      protein: 38,
      ingredients_text:
        "Wheat bread, salami (pork, salt, spices, garlic, sodium nitrite), ham (cured pork), provolone cheese (milk, cultures, salt, enzymes), lettuce, tomato, onion, Italian dressing (soybean oil, vinegar, spices)",
    },
    {
      name: "Sweet Chipotle Chicken Sub",
      category: "sandwich",
      serving_size: 340,
      serving_unit: "g",
      calories: 780,
      total_fat: 32,
      saturated_fat: 8,
      trans_fat: 0,
      cholesterol: 80,
      sodium: 1970,
      total_carbohydrates: 83,
      dietary_fiber: 4,
      total_sugars: 16,
      protein: 36,
      ingredients_text:
        "Sub roll (enriched flour, water, sugar, yeast, salt), grilled chicken, cheddar cheese, bacon, lettuce, tomato, sweet chipotle sauce (sugar, tomato paste, chipotle peppers, vinegar, spices)",
    },
    {
      name: "Choose Two (Half Club + Cup Soup)",
      category: "combo",
      serving_size: 415,
      serving_unit: "g",
      calories: 600,
      total_fat: 30,
      saturated_fat: 8,
      trans_fat: 0,
      cholesterol: 70,
      sodium: 1950,
      total_carbohydrates: 55,
      dietary_fiber: 3,
      total_sugars: 7,
      protein: 28,
      ingredients_text:
        "Half McAlister's Club (wheat bread, turkey, ham, bacon, Swiss cheese, lettuce, tomato, mayo), cup of chicken tortilla soup",
    },
    {
      name: "Sweet Tea (Large)",
      category: "beverage",
      serving_size: 887,
      serving_unit: "g",
      calories: 280,
      total_fat: 0,
      saturated_fat: 0,
      trans_fat: 0,
      cholesterol: 0,
      sodium: 10,
      total_carbohydrates: 70,
      dietary_fiber: 0,
      total_sugars: 68,
      protein: 0,
      ingredients_text:
        "Brewed tea, sugar, water",
    },
  ],
};

// ─── Jason's Deli ────────────────────────────────────────────────────────────
// Source: jasonsdeli.com/nutrition

const jasonsDeli: ChainData = {
  chain: "Jason's Deli",
  items: [
    {
      name: "Reuben the Great",
      category: "sandwich",
      serving_size: 380,
      serving_unit: "g",
      calories: 940,
      total_fat: 53,
      saturated_fat: 19,
      trans_fat: 1,
      cholesterol: 155,
      sodium: 2710,
      total_carbohydrates: 67,
      dietary_fiber: 7,
      total_sugars: 12,
      protein: 49,
      ingredients_text:
        "Rye bread, corned beef (beef, water, salt, sugar, sodium nitrite, spices), Swiss cheese (milk, cultures, salt, enzymes), sauerkraut (cabbage, salt), Thousand Island dressing (soybean oil, sugar, tomato paste, vinegar, egg yolks, pickles, salt, spices)",
    },
    {
      name: "The New York Yankee Sandwich",
      category: "sandwich",
      serving_size: 340,
      serving_unit: "g",
      calories: 730,
      total_fat: 34,
      saturated_fat: 12,
      trans_fat: 0,
      cholesterol: 100,
      sodium: 2190,
      total_carbohydrates: 64,
      dietary_fiber: 5,
      total_sugars: 8,
      protein: 40,
      ingredients_text:
        "Wheat bread, corned beef, Swiss cheese, cole slaw, spicy mustard",
    },
    {
      name: "Club Royale",
      category: "sandwich",
      serving_size: 395,
      serving_unit: "g",
      calories: 850,
      total_fat: 43,
      saturated_fat: 13,
      trans_fat: 0,
      cholesterol: 115,
      sodium: 2350,
      total_carbohydrates: 66,
      dietary_fiber: 5,
      total_sugars: 8,
      protein: 48,
      ingredients_text:
        "Wheat bread, turkey breast, ham, roast beef, Swiss cheese, American cheese, bacon, lettuce, tomato, mayo",
    },
    {
      name: "Salad Bar Plate (Avg Serving)",
      category: "salad",
      serving_size: 340,
      serving_unit: "g",
      calories: 450,
      total_fat: 22,
      saturated_fat: 5,
      trans_fat: 0,
      cholesterol: 30,
      sodium: 780,
      total_carbohydrates: 42,
      dietary_fiber: 8,
      total_sugars: 12,
      protein: 18,
      ingredients_text:
        "Mixed greens, cherry tomatoes, cucumbers, red onion, croutons, cheddar cheese, egg, sunflower seeds, ranch dressing",
    },
    {
      name: "Chicken Club Wrap",
      category: "sandwich",
      serving_size: 355,
      serving_unit: "g",
      calories: 790,
      total_fat: 42,
      saturated_fat: 12,
      trans_fat: 0,
      cholesterol: 110,
      sodium: 1880,
      total_carbohydrates: 57,
      dietary_fiber: 4,
      total_sugars: 4,
      protein: 42,
      ingredients_text:
        "Flour tortilla (enriched flour, water, shortening, salt), grilled chicken, bacon, Swiss cheese, lettuce, tomato, ranch dressing (soybean oil, buttermilk, egg yolk, vinegar, salt, spices)",
    },
    {
      name: "Muffaletta (Half)",
      category: "sandwich",
      serving_size: 315,
      serving_unit: "g",
      calories: 770,
      total_fat: 43,
      saturated_fat: 14,
      trans_fat: 0,
      cholesterol: 100,
      sodium: 2550,
      total_carbohydrates: 56,
      dietary_fiber: 3,
      total_sugars: 5,
      protein: 38,
      ingredients_text:
        "Muffaletta bread (enriched flour, water, sesame seeds, yeast, salt), salami, ham, turkey, provolone cheese, olive mix (green olives, kalamata olives, capers, celery, cauliflower, olive oil, vinegar, spices)",
    },
    {
      name: "Chicken Pot Pie Soup (Cup)",
      category: "soup",
      serving_size: 227,
      serving_unit: "g",
      calories: 250,
      total_fat: 15,
      saturated_fat: 7,
      trans_fat: 0,
      cholesterol: 45,
      sodium: 710,
      total_carbohydrates: 18,
      dietary_fiber: 1,
      total_sugars: 3,
      protein: 11,
      ingredients_text:
        "Chicken broth, chicken, cream, potatoes, carrots, peas, celery, onion, modified corn starch, butter, salt, spices",
    },
    {
      name: "Organic Chicken Tortilla Soup (Cup)",
      category: "soup",
      serving_size: 227,
      serving_unit: "g",
      calories: 140,
      total_fat: 5,
      saturated_fat: 1,
      trans_fat: 0,
      cholesterol: 25,
      sodium: 690,
      total_carbohydrates: 14,
      dietary_fiber: 3,
      total_sugars: 3,
      protein: 10,
      ingredients_text:
        "Organic chicken broth, organic chicken, tomatoes, corn, black beans, onion, jalapeño peppers, tortilla strips, seasoning",
    },
    {
      name: "Nutty Mixed-Up Salad",
      category: "salad",
      serving_size: 400,
      serving_unit: "g",
      calories: 640,
      total_fat: 40,
      saturated_fat: 9,
      trans_fat: 0,
      cholesterol: 75,
      sodium: 1150,
      total_carbohydrates: 39,
      dietary_fiber: 8,
      total_sugars: 18,
      protein: 34,
      ingredients_text:
        "Mixed organic greens, grilled chicken, Gorgonzola cheese (milk, cultures, salt, enzymes), glazed pecans (pecans, sugar), dried cranberries, apple slices, balsamic vinaigrette (balsamic vinegar, olive oil, sugar, salt)",
    },
    {
      name: "Plain Jane Potato",
      category: "side",
      serving_size: 312,
      serving_unit: "g",
      calories: 280,
      total_fat: 0,
      saturated_fat: 0,
      trans_fat: 0,
      cholesterol: 0,
      sodium: 20,
      total_carbohydrates: 63,
      dietary_fiber: 7,
      total_sugars: 3,
      protein: 7,
      ingredients_text:
        "Russet potato",
    },
  ],
};

// ─── Marco's Pizza ───────────────────────────────────────────────────────────
// Source: marcos.com/nutrition (per slice, large pizza unless noted)

const marcosPizza: ChainData = {
  chain: "Marco's Pizza",
  items: [
    {
      name: "Pepperoni Pizza (Large, 1 slice)",
      category: "pizza",
      serving_size: 130,
      serving_unit: "g",
      calories: 310,
      total_fat: 14,
      saturated_fat: 6,
      trans_fat: 0,
      cholesterol: 30,
      sodium: 730,
      total_carbohydrates: 32,
      dietary_fiber: 1,
      total_sugars: 3,
      protein: 13,
      ingredients_text:
        "Pizza dough (enriched flour, water, sugar, yeast, soybean oil, salt), pizza sauce (tomatoes, water, salt, spices, garlic), mozzarella cheese (milk, cultures, salt, enzymes), pepperoni (pork, beef, salt, spices, dextrose, lactic acid, paprika, sodium nitrite)",
    },
    {
      name: "Cheese Pizza (Large, 1 slice)",
      category: "pizza",
      serving_size: 115,
      serving_unit: "g",
      calories: 260,
      total_fat: 10,
      saturated_fat: 5,
      trans_fat: 0,
      cholesterol: 25,
      sodium: 570,
      total_carbohydrates: 32,
      dietary_fiber: 1,
      total_sugars: 3,
      protein: 11,
      ingredients_text:
        "Pizza dough (enriched flour, water, sugar, yeast, soybean oil, salt), pizza sauce (tomatoes, water, salt, spices, garlic), mozzarella cheese (milk, cultures, salt, enzymes)",
    },
    {
      name: "White Cheezy Pizza (Large, 1 slice)",
      category: "pizza",
      serving_size: 138,
      serving_unit: "g",
      calories: 340,
      total_fat: 17,
      saturated_fat: 8,
      trans_fat: 0,
      cholesterol: 35,
      sodium: 640,
      total_carbohydrates: 31,
      dietary_fiber: 1,
      total_sugars: 2,
      protein: 15,
      ingredients_text:
        "Pizza dough (enriched flour, water, sugar, yeast, soybean oil, salt), Alfredo sauce (cream, butter, Parmesan cheese, garlic, salt), mozzarella, ricotta (milk, whey, citric acid), Parmesan, Romano",
    },
    {
      name: "Deluxe Uno Pizza (Large, 1 slice)",
      category: "pizza",
      serving_size: 160,
      serving_unit: "g",
      calories: 350,
      total_fat: 17,
      saturated_fat: 7,
      trans_fat: 0,
      cholesterol: 35,
      sodium: 820,
      total_carbohydrates: 33,
      dietary_fiber: 2,
      total_sugars: 4,
      protein: 15,
      ingredients_text:
        "Pizza dough, pizza sauce, mozzarella cheese, pepperoni, Italian sausage (pork, salt, spices), mushrooms, green peppers, onions",
    },
    {
      name: "Garden Pizza (Large, 1 slice)",
      category: "pizza",
      serving_size: 155,
      serving_unit: "g",
      calories: 290,
      total_fat: 11,
      saturated_fat: 5,
      trans_fat: 0,
      cholesterol: 25,
      sodium: 620,
      total_carbohydrates: 34,
      dietary_fiber: 2,
      total_sugars: 4,
      protein: 12,
      ingredients_text:
        "Pizza dough, pizza sauce, mozzarella cheese, mushrooms, green peppers, onions, black olives, tomatoes",
    },
    {
      name: "CheezyBread (1 piece)",
      category: "side",
      serving_size: 52,
      serving_unit: "g",
      calories: 150,
      total_fat: 7,
      saturated_fat: 3,
      trans_fat: 0,
      cholesterol: 10,
      sodium: 270,
      total_carbohydrates: 16,
      dietary_fiber: 1,
      total_sugars: 1,
      protein: 6,
      ingredients_text:
        "Pizza dough (enriched flour, water, sugar, yeast, soybean oil, salt), mozzarella cheese (milk, cultures, salt, enzymes), Parmesan cheese, garlic butter (butter, garlic, salt)",
    },
    {
      name: "Pizza Bowl - Pepperoni",
      category: "entree",
      serving_size: 340,
      serving_unit: "g",
      calories: 560,
      total_fat: 34,
      saturated_fat: 16,
      trans_fat: 0.5,
      cholesterol: 80,
      sodium: 1470,
      total_carbohydrates: 30,
      dietary_fiber: 3,
      total_sugars: 6,
      protein: 34,
      ingredients_text:
        "Pizza sauce, mozzarella cheese, ricotta cheese, pepperoni, Italian sausage, mushrooms, Parmesan cheese, Italian seasoning",
    },
    {
      name: "Chicken Dippers (6pc)",
      category: "chicken",
      serving_size: 160,
      serving_unit: "g",
      calories: 350,
      total_fat: 18,
      saturated_fat: 3,
      trans_fat: 0,
      cholesterol: 55,
      sodium: 920,
      total_carbohydrates: 24,
      dietary_fiber: 1,
      total_sugars: 0,
      protein: 22,
      ingredients_text:
        "Chicken breast meat, wheat flour, water, salt, seasoning (garlic powder, onion powder, spices), frying oil (soybean oil)",
    },
    {
      name: "CinnaSquares (2pc)",
      category: "dessert",
      serving_size: 90,
      serving_unit: "g",
      calories: 290,
      total_fat: 10,
      saturated_fat: 3,
      trans_fat: 0,
      cholesterol: 0,
      sodium: 260,
      total_carbohydrates: 46,
      dietary_fiber: 1,
      total_sugars: 19,
      protein: 4,
      ingredients_text:
        "Pizza dough (enriched flour, water, sugar, yeast, soybean oil, salt), cinnamon sugar, cream cheese icing (cream cheese, sugar, butter, vanilla)",
    },
    {
      name: "Boneless Wings (8pc)",
      category: "chicken",
      serving_size: 200,
      serving_unit: "g",
      calories: 460,
      total_fat: 24,
      saturated_fat: 5,
      trans_fat: 0,
      cholesterol: 70,
      sodium: 1380,
      total_carbohydrates: 30,
      dietary_fiber: 1,
      total_sugars: 5,
      protein: 28,
      ingredients_text:
        "Chicken breast meat, wheat flour, water, seasoning, frying oil (soybean oil), Buffalo sauce (cayenne pepper, vinegar, butter, garlic)",
    },
  ],
};

// ─── Dunkin' ─────────────────────────────────────────────────────────────────
// Source: dunkindonuts.com/en/food-drinks/nutrition

const dunkin: ChainData = {
  chain: "Dunkin'",
  items: [
    {
      name: "Glazed Donut",
      category: "bakery",
      serving_size: 63,
      serving_unit: "g",
      calories: 240,
      total_fat: 11,
      saturated_fat: 5,
      trans_fat: 0,
      cholesterol: 0,
      sodium: 340,
      total_carbohydrates: 33,
      dietary_fiber: 1,
      total_sugars: 12,
      protein: 4,
      ingredients_text:
        "Enriched wheat flour (wheat flour, niacin, iron, thiamine, riboflavin, folic acid), water, palm oil, sugar, yeast, soy lecithin, salt, dextrose, nonfat milk, egg yolks, glaze (sugar, water, corn starch)",
    },
    {
      name: "Boston Kreme Donut",
      category: "bakery",
      serving_size: 99,
      serving_unit: "g",
      calories: 300,
      total_fat: 15,
      saturated_fat: 7,
      trans_fat: 0,
      cholesterol: 30,
      sodium: 370,
      total_carbohydrates: 38,
      dietary_fiber: 1,
      total_sugars: 17,
      protein: 4,
      ingredients_text:
        "Enriched wheat flour, water, palm oil, sugar, yeast, soy lecithin, salt, egg yolks, Bavarian kreme filling (water, sugar, modified corn starch, palm oil, natural and artificial flavor), chocolate icing (sugar, water, cocoa, corn syrup, palm oil)",
    },
    {
      name: "Chocolate Frosted Donut",
      category: "bakery",
      serving_size: 71,
      serving_unit: "g",
      calories: 270,
      total_fat: 13,
      saturated_fat: 6,
      trans_fat: 0,
      cholesterol: 0,
      sodium: 340,
      total_carbohydrates: 35,
      dietary_fiber: 1,
      total_sugars: 16,
      protein: 4,
      ingredients_text:
        "Enriched wheat flour, water, palm oil, sugar, yeast, salt, egg yolks, chocolate icing (sugar, water, cocoa, corn syrup, palm oil, soy lecithin)",
    },
    {
      name: "Munchkins (5pc Glazed)",
      category: "bakery",
      serving_size: 71,
      serving_unit: "g",
      calories: 270,
      total_fat: 13,
      saturated_fat: 6,
      trans_fat: 0,
      cholesterol: 0,
      sodium: 330,
      total_carbohydrates: 35,
      dietary_fiber: 1,
      total_sugars: 14,
      protein: 4,
      ingredients_text:
        "Enriched wheat flour, water, palm oil, sugar, yeast, soy lecithin, salt, dextrose, glaze (sugar, water)",
    },
    {
      name: "Plain Bagel",
      category: "bakery",
      serving_size: 121,
      serving_unit: "g",
      calories: 310,
      total_fat: 2,
      saturated_fat: 0.5,
      trans_fat: 0,
      cholesterol: 0,
      sodium: 580,
      total_carbohydrates: 62,
      dietary_fiber: 3,
      total_sugars: 7,
      protein: 11,
      ingredients_text:
        "Enriched wheat flour (wheat flour, niacin, iron, thiamine, riboflavin, folic acid), water, sugar, salt, yeast, malt syrup, cornmeal",
    },
    {
      name: "Everything Bagel with Cream Cheese",
      category: "bakery",
      serving_size: 155,
      serving_unit: "g",
      calories: 440,
      total_fat: 14,
      saturated_fat: 7,
      trans_fat: 0,
      cholesterol: 40,
      sodium: 870,
      total_carbohydrates: 63,
      dietary_fiber: 3,
      total_sugars: 8,
      protein: 14,
      ingredients_text:
        "Everything bagel (enriched flour, water, sugar, salt, yeast, sesame seeds, poppy seeds, onion, garlic), cream cheese (pasteurized milk, cream, cheese culture, salt, carob bean gum)",
    },
    {
      name: "Bacon, Egg & Cheese on Croissant",
      category: "breakfast",
      serving_size: 164,
      serving_unit: "g",
      calories: 530,
      total_fat: 33,
      saturated_fat: 15,
      trans_fat: 0,
      cholesterol: 200,
      sodium: 1010,
      total_carbohydrates: 37,
      dietary_fiber: 1,
      total_sugars: 5,
      protein: 21,
      ingredients_text:
        "Croissant (enriched flour, butter, water, sugar, yeast, salt, eggs, milk), bacon (cured pork belly, salt, sugar, sodium nitrite), egg, American cheese (milk, cream, sodium citrate, salt)",
    },
    {
      name: "Sausage, Egg & Cheese on English Muffin",
      category: "breakfast",
      serving_size: 175,
      serving_unit: "g",
      calories: 530,
      total_fat: 33,
      saturated_fat: 14,
      trans_fat: 0,
      cholesterol: 210,
      sodium: 1110,
      total_carbohydrates: 34,
      dietary_fiber: 2,
      total_sugars: 3,
      protein: 24,
      ingredients_text:
        "English muffin (enriched flour, water, yeast, sugar, salt), sausage patty (pork, water, salt, spices, sugar, dextrose), egg, American cheese (milk, cream, salt)",
    },
    {
      name: "Medium Iced Coffee (with cream & sugar)",
      category: "beverage",
      serving_size: 680,
      serving_unit: "g",
      calories: 230,
      total_fat: 9,
      saturated_fat: 6,
      trans_fat: 0,
      cholesterol: 35,
      sodium: 65,
      total_carbohydrates: 36,
      dietary_fiber: 0,
      total_sugars: 34,
      protein: 2,
      ingredients_text:
        "Brewed coffee, ice, cream, liquid sugar",
    },
    {
      name: "Medium Latte",
      category: "beverage",
      serving_size: 480,
      serving_unit: "g",
      calories: 150,
      total_fat: 7,
      saturated_fat: 4.5,
      trans_fat: 0,
      cholesterol: 25,
      sodium: 160,
      total_carbohydrates: 14,
      dietary_fiber: 0,
      total_sugars: 13,
      protein: 9,
      ingredients_text:
        "Espresso, steamed whole milk",
    },
    {
      name: "Wake-Up Wrap (Bacon, Egg & Cheese)",
      category: "breakfast",
      serving_size: 97,
      serving_unit: "g",
      calories: 290,
      total_fat: 18,
      saturated_fat: 8,
      trans_fat: 0,
      cholesterol: 120,
      sodium: 670,
      total_carbohydrates: 19,
      dietary_fiber: 0,
      total_sugars: 1,
      protein: 12,
      ingredients_text:
        "Flour tortilla (enriched flour, water, shortening, salt), bacon, egg, American cheese",
    },
    {
      name: "Hash Browns (6pc)",
      category: "side",
      serving_size: 88,
      serving_unit: "g",
      calories: 250,
      total_fat: 15,
      saturated_fat: 2.5,
      trans_fat: 0,
      cholesterol: 0,
      sodium: 540,
      total_carbohydrates: 25,
      dietary_fiber: 2,
      total_sugars: 0,
      protein: 2,
      ingredients_text:
        "Potatoes (dehydrated potatoes, salt, dextrose, sodium acid pyrophosphate), vegetable oil (canola, soybean), seasoning",
    },
    {
      name: "Strawberry Frosted Donut",
      category: "bakery",
      serving_size: 74,
      serving_unit: "g",
      calories: 280,
      total_fat: 13,
      saturated_fat: 6,
      trans_fat: 0,
      cholesterol: 0,
      sodium: 340,
      total_carbohydrates: 37,
      dietary_fiber: 1,
      total_sugars: 18,
      protein: 4,
      ingredients_text:
        "Enriched wheat flour, water, palm oil, sugar, yeast, salt, strawberry frosting (sugar, water, corn syrup, palm oil, natural strawberry flavor, red 40)",
    },
  ],
};

// ─── Hooters ─────────────────────────────────────────────────────────────────
// Source: hooters.com/nutrition

const hooters: ChainData = {
  chain: "Hooters",
  items: [
    {
      name: "10 Piece Original Wings (Naked)",
      category: "chicken",
      serving_size: 284,
      serving_unit: "g",
      calories: 430,
      total_fat: 24,
      saturated_fat: 8,
      trans_fat: 0,
      cholesterol: 240,
      sodium: 1700,
      total_carbohydrates: 2,
      dietary_fiber: 0,
      total_sugars: 0,
      protein: 52,
      ingredients_text:
        "Chicken wings (chicken, water, salt), seasoning (salt, spices, garlic powder, onion powder, paprika)",
    },
    {
      name: "10 Piece Breaded Wings",
      category: "chicken",
      serving_size: 340,
      serving_unit: "g",
      calories: 690,
      total_fat: 38,
      saturated_fat: 10,
      trans_fat: 0,
      cholesterol: 240,
      sodium: 2130,
      total_carbohydrates: 34,
      dietary_fiber: 2,
      total_sugars: 0,
      protein: 54,
      ingredients_text:
        "Chicken wings, seasoned breading (wheat flour, salt, spices, garlic powder, onion powder), frying oil (soybean oil)",
    },
    {
      name: "Fried Pickles",
      category: "appetizer",
      serving_size: 170,
      serving_unit: "g",
      calories: 450,
      total_fat: 27,
      saturated_fat: 5,
      trans_fat: 0,
      cholesterol: 20,
      sodium: 1990,
      total_carbohydrates: 42,
      dietary_fiber: 2,
      total_sugars: 4,
      protein: 8,
      ingredients_text:
        "Dill pickle chips (cucumbers, water, vinegar, salt, calcium chloride, alum, natural flavors, polysorbate 80, turmeric), seasoned batter (wheat flour, corn starch, salt, spices, leavening), frying oil, ranch dressing",
    },
    {
      name: "Hooters Sliders (3pc)",
      category: "burger",
      serving_size: 255,
      serving_unit: "g",
      calories: 590,
      total_fat: 33,
      saturated_fat: 14,
      trans_fat: 1,
      cholesterol: 90,
      sodium: 1140,
      total_carbohydrates: 44,
      dietary_fiber: 2,
      total_sugars: 6,
      protein: 28,
      ingredients_text:
        "Beef patties (3), slider buns (enriched flour, water, sugar, yeast, salt), American cheese (milk, cream, salt), pickles, onion, ketchup, mustard",
    },
    {
      name: "Hooters Original Buffalo Shrimp",
      category: "seafood",
      serving_size: 198,
      serving_unit: "g",
      calories: 380,
      total_fat: 18,
      saturated_fat: 3,
      trans_fat: 0,
      cholesterol: 260,
      sodium: 2020,
      total_carbohydrates: 30,
      dietary_fiber: 1,
      total_sugars: 2,
      protein: 24,
      ingredients_text:
        "Shrimp (shrimp, water, salt, sodium tripolyphosphate), seasoned batter (wheat flour, corn starch, salt, spices), frying oil, Buffalo sauce (cayenne pepper, vinegar, butter, salt, garlic)",
    },
    {
      name: "Lots-A-Tots",
      category: "side",
      serving_size: 230,
      serving_unit: "g",
      calories: 620,
      total_fat: 36,
      saturated_fat: 12,
      trans_fat: 0,
      cholesterol: 40,
      sodium: 1360,
      total_carbohydrates: 54,
      dietary_fiber: 4,
      total_sugars: 2,
      protein: 16,
      ingredients_text:
        "Tater tots (potatoes, vegetable oil, salt), cheddar cheese (milk, cultures, salt, enzymes), bacon, sour cream, chives",
    },
    {
      name: "Big Hoot Burger",
      category: "burger",
      serving_size: 340,
      serving_unit: "g",
      calories: 890,
      total_fat: 56,
      saturated_fat: 22,
      trans_fat: 2,
      cholesterol: 135,
      sodium: 1480,
      total_carbohydrates: 50,
      dietary_fiber: 2,
      total_sugars: 9,
      protein: 44,
      ingredients_text:
        "Beef patty (1/2 lb), brioche bun (enriched flour, water, sugar, butter, eggs, yeast, salt), American cheese (2 slices), bacon, lettuce, tomato, onion, pickles, mayo",
    },
    {
      name: "Chicken Strip Basket (5pc)",
      category: "chicken",
      serving_size: 255,
      serving_unit: "g",
      calories: 680,
      total_fat: 36,
      saturated_fat: 6,
      trans_fat: 0,
      cholesterol: 85,
      sodium: 1750,
      total_carbohydrates: 48,
      dietary_fiber: 2,
      total_sugars: 0,
      protein: 40,
      ingredients_text:
        "Chicken tenderloins, seasoned breading (wheat flour, salt, spices, garlic powder), frying oil, served with fries",
    },
    {
      name: "Caesar Salad (Side)",
      category: "salad",
      serving_size: 170,
      serving_unit: "g",
      calories: 310,
      total_fat: 24,
      saturated_fat: 5,
      trans_fat: 0,
      cholesterol: 20,
      sodium: 620,
      total_carbohydrates: 14,
      dietary_fiber: 2,
      total_sugars: 2,
      protein: 8,
      ingredients_text:
        "Romaine lettuce, Parmesan cheese (milk, cultures, salt, enzymes), croutons (enriched flour, butter, garlic, salt), Caesar dressing (soybean oil, Parmesan cheese, lemon juice, egg yolks, anchovy paste, garlic, vinegar, salt)",
    },
    {
      name: "Curly Fries",
      category: "side",
      serving_size: 142,
      serving_unit: "g",
      calories: 420,
      total_fat: 22,
      saturated_fat: 4,
      trans_fat: 0,
      cholesterol: 0,
      sodium: 960,
      total_carbohydrates: 50,
      dietary_fiber: 4,
      total_sugars: 0,
      protein: 5,
      ingredients_text:
        "Potatoes, vegetable oil (canola, soybean), seasoning (salt, paprika, garlic powder, onion powder, spices), modified corn starch",
    },
  ],
};

// ─── Yard House ──────────────────────────────────────────────────────────────
// Source: yardhouse.com/nutrition

const yardHouse: ChainData = {
  chain: "Yard House",
  items: [
    {
      name: "Classic Cheeseburger",
      category: "burger",
      serving_size: 370,
      serving_unit: "g",
      calories: 1050,
      total_fat: 64,
      saturated_fat: 24,
      trans_fat: 2,
      cholesterol: 160,
      sodium: 1480,
      total_carbohydrates: 64,
      dietary_fiber: 3,
      total_sugars: 12,
      protein: 52,
      ingredients_text:
        "Beef patty (1/2 lb), brioche bun, American cheese, lettuce, tomato, onion, pickles, Thousand Island dressing, served with fries",
    },
    {
      name: "Pepperoni Pizza",
      category: "pizza",
      serving_size: 475,
      serving_unit: "g",
      calories: 1160,
      total_fat: 52,
      saturated_fat: 22,
      trans_fat: 1,
      cholesterol: 100,
      sodium: 2620,
      total_carbohydrates: 118,
      dietary_fiber: 5,
      total_sugars: 10,
      protein: 48,
      ingredients_text:
        "Pizza dough (enriched flour, water, yeast, olive oil, salt, sugar), pizza sauce (tomatoes, garlic, olive oil, salt), mozzarella cheese, pepperoni",
    },
    {
      name: "Truffle Fries",
      category: "side",
      serving_size: 280,
      serving_unit: "g",
      calories: 750,
      total_fat: 44,
      saturated_fat: 12,
      trans_fat: 0,
      cholesterol: 20,
      sodium: 1070,
      total_carbohydrates: 78,
      dietary_fiber: 6,
      total_sugars: 1,
      protein: 10,
      ingredients_text:
        "Potatoes, vegetable oil, truffle oil, Parmesan cheese, parsley, garlic, salt",
    },
    {
      name: "Nashville Hot Chicken Sandwich",
      category: "chicken",
      serving_size: 340,
      serving_unit: "g",
      calories: 1130,
      total_fat: 60,
      saturated_fat: 12,
      trans_fat: 0,
      cholesterol: 110,
      sodium: 2310,
      total_carbohydrates: 95,
      dietary_fiber: 4,
      total_sugars: 14,
      protein: 48,
      ingredients_text:
        "Chicken breast (chicken, water, salt), seasoned breading (wheat flour, spices, cayenne), brioche bun, coleslaw, pickles, Nashville hot sauce, served with fries",
    },
    {
      name: "Mac and Cheese",
      category: "entree",
      serving_size: 396,
      serving_unit: "g",
      calories: 1210,
      total_fat: 72,
      saturated_fat: 38,
      trans_fat: 1.5,
      cholesterol: 190,
      sodium: 1640,
      total_carbohydrates: 92,
      dietary_fiber: 4,
      total_sugars: 8,
      protein: 44,
      ingredients_text:
        "Cavatappi pasta (semolina flour, water), cheddar cheese sauce (cheddar cheese, cream, butter, milk, flour, salt), Parmesan crust (Parmesan cheese, breadcrumbs, butter), bacon, truffle oil",
    },
    {
      name: "Grilled Chicken and Avocado Sandwich",
      category: "sandwich",
      serving_size: 360,
      serving_unit: "g",
      calories: 890,
      total_fat: 46,
      saturated_fat: 12,
      trans_fat: 0,
      cholesterol: 110,
      sodium: 1670,
      total_carbohydrates: 68,
      dietary_fiber: 6,
      total_sugars: 10,
      protein: 48,
      ingredients_text:
        "Grilled chicken breast, ciabatta bun, avocado, bacon, Swiss cheese, lettuce, tomato, chipotle mayo, served with fries",
    },
    {
      name: "Gardein Burger",
      category: "burger",
      serving_size: 340,
      serving_unit: "g",
      calories: 790,
      total_fat: 38,
      saturated_fat: 8,
      trans_fat: 0,
      cholesterol: 15,
      sodium: 1540,
      total_carbohydrates: 82,
      dietary_fiber: 8,
      total_sugars: 14,
      protein: 28,
      ingredients_text:
        "Gardein patty (soy protein, wheat gluten, vegetables), brioche bun, lettuce, tomato, onion, pickles, vegan mayo, served with fries",
    },
    {
      name: "Fish and Chips",
      category: "seafood",
      serving_size: 450,
      serving_unit: "g",
      calories: 1380,
      total_fat: 80,
      saturated_fat: 12,
      trans_fat: 0,
      cholesterol: 100,
      sodium: 2020,
      total_carbohydrates: 114,
      dietary_fiber: 6,
      total_sugars: 3,
      protein: 48,
      ingredients_text:
        "Cod fillets (cod, wheat flour, beer batter, salt), fries (potatoes, vegetable oil, salt), coleslaw, tartar sauce, lemon",
    },
    {
      name: "Wings (Traditional, 12pc)",
      category: "chicken",
      serving_size: 400,
      serving_unit: "g",
      calories: 960,
      total_fat: 62,
      saturated_fat: 18,
      trans_fat: 0,
      cholesterol: 300,
      sodium: 2500,
      total_carbohydrates: 12,
      dietary_fiber: 0,
      total_sugars: 2,
      protein: 84,
      ingredients_text:
        "Chicken wings, choice of sauce (Buffalo, BBQ, garlic Parmesan, teriyaki), served with celery and ranch or bleu cheese",
    },
    {
      name: "House Salad",
      category: "salad",
      serving_size: 255,
      serving_unit: "g",
      calories: 310,
      total_fat: 20,
      saturated_fat: 6,
      trans_fat: 0,
      cholesterol: 25,
      sodium: 520,
      total_carbohydrates: 20,
      dietary_fiber: 4,
      total_sugars: 8,
      protein: 12,
      ingredients_text:
        "Mixed greens, cherry tomatoes, cucumber, red onion, croutons, Parmesan cheese, choice of dressing",
    },
  ],
};

// ─── Baja Fresh ──────────────────────────────────────────────────────────────
// Source: bajafresh.com/nutrition

const bajaFresh: ChainData = {
  chain: "Baja Fresh",
  items: [
    {
      name: "Baja Burrito (Chicken)",
      category: "entree",
      serving_size: 475,
      serving_unit: "g",
      calories: 790,
      total_fat: 38,
      saturated_fat: 13,
      trans_fat: 0,
      cholesterol: 120,
      sodium: 1550,
      total_carbohydrates: 67,
      dietary_fiber: 8,
      total_sugars: 4,
      protein: 47,
      ingredients_text:
        "Flour tortilla (enriched flour, water, vegetable shortening, salt), grilled chicken, pinto beans, rice, guacamole (avocado, lime, cilantro, onion, salt), pico de gallo, sour cream, cheese",
    },
    {
      name: "Burrito Ultimo (Steak)",
      category: "entree",
      serving_size: 550,
      serving_unit: "g",
      calories: 920,
      total_fat: 42,
      saturated_fat: 17,
      trans_fat: 0.5,
      cholesterol: 145,
      sodium: 2030,
      total_carbohydrates: 82,
      dietary_fiber: 9,
      total_sugars: 5,
      protein: 52,
      ingredients_text:
        "Flour tortilla, carne asada (beef, seasoning), rice, beans, cheese, sour cream, guacamole, pico de gallo, salsa verde",
    },
    {
      name: "Original Baja Taco (Chicken)",
      category: "entree",
      serving_size: 152,
      serving_unit: "g",
      calories: 230,
      total_fat: 8,
      saturated_fat: 2,
      trans_fat: 0,
      cholesterol: 50,
      sodium: 480,
      total_carbohydrates: 22,
      dietary_fiber: 3,
      total_sugars: 2,
      protein: 17,
      ingredients_text:
        "Corn tortilla (ground corn, water, lime), grilled chicken, pico de gallo, cabbage, salsa",
    },
    {
      name: "Nachos (Chicken)",
      category: "entree",
      serving_size: 540,
      serving_unit: "g",
      calories: 1240,
      total_fat: 68,
      saturated_fat: 26,
      trans_fat: 0.5,
      cholesterol: 140,
      sodium: 1910,
      total_carbohydrates: 103,
      dietary_fiber: 14,
      total_sugars: 6,
      protein: 52,
      ingredients_text:
        "Tortilla chips (corn, vegetable oil, salt), grilled chicken, pinto beans, cheese (cheddar, jack; milk, cultures, salt, enzymes), guacamole, pico de gallo, sour cream, jalapeños",
    },
    {
      name: "Quesadilla (Cheese)",
      category: "entree",
      serving_size: 228,
      serving_unit: "g",
      calories: 660,
      total_fat: 36,
      saturated_fat: 18,
      trans_fat: 0.5,
      cholesterol: 75,
      sodium: 1210,
      total_carbohydrates: 54,
      dietary_fiber: 4,
      total_sugars: 2,
      protein: 28,
      ingredients_text:
        "Flour tortilla, cheddar and jack cheese (milk, cultures, salt, enzymes), pico de gallo, sour cream, guacamole",
    },
    {
      name: "Taquitos (Chicken, 3pc with Guac)",
      category: "appetizer",
      serving_size: 230,
      serving_unit: "g",
      calories: 610,
      total_fat: 34,
      saturated_fat: 9,
      trans_fat: 0,
      cholesterol: 65,
      sodium: 970,
      total_carbohydrates: 52,
      dietary_fiber: 5,
      total_sugars: 2,
      protein: 24,
      ingredients_text:
        "Corn tortillas (ground corn, water, lime), chicken, cheese, frying oil (soybean oil), guacamole (avocado, lime, cilantro, salt)",
    },
    {
      name: "Grilled Veggie Burrito",
      category: "entree",
      serving_size: 500,
      serving_unit: "g",
      calories: 690,
      total_fat: 28,
      saturated_fat: 10,
      trans_fat: 0,
      cholesterol: 30,
      sodium: 1430,
      total_carbohydrates: 86,
      dietary_fiber: 12,
      total_sugars: 8,
      protein: 22,
      ingredients_text:
        "Flour tortilla, grilled peppers and onions, black beans, rice, cheese, guacamole, pico de gallo, sour cream",
    },
    {
      name: "Chips and Guacamole",
      category: "side",
      serving_size: 283,
      serving_unit: "g",
      calories: 780,
      total_fat: 42,
      saturated_fat: 6,
      trans_fat: 0,
      cholesterol: 0,
      sodium: 710,
      total_carbohydrates: 88,
      dietary_fiber: 12,
      total_sugars: 3,
      protein: 10,
      ingredients_text:
        "Tortilla chips (corn, vegetable oil, salt), guacamole (avocado, lime juice, cilantro, onion, jalapeño, salt)",
    },
    {
      name: "Ensalada (Chicken)",
      category: "salad",
      serving_size: 420,
      serving_unit: "g",
      calories: 490,
      total_fat: 24,
      saturated_fat: 8,
      trans_fat: 0,
      cholesterol: 90,
      sodium: 1080,
      total_carbohydrates: 34,
      dietary_fiber: 9,
      total_sugars: 5,
      protein: 40,
      ingredients_text:
        "Romaine lettuce, grilled chicken, black beans, corn, cheese, pico de gallo, guacamole, tortilla strips, salsa verde dressing",
    },
  ],
};

// ─── Taco Cabana ─────────────────────────────────────────────────────────────
// Source: tacocabana.com/nutrition

const tacoCabana: ChainData = {
  chain: "Taco Cabana",
  items: [
    {
      name: "Cabana Bowl (Chicken)",
      category: "entree",
      serving_size: 425,
      serving_unit: "g",
      calories: 570,
      total_fat: 20,
      saturated_fat: 7,
      trans_fat: 0,
      cholesterol: 90,
      sodium: 1380,
      total_carbohydrates: 60,
      dietary_fiber: 8,
      total_sugars: 4,
      protein: 38,
      ingredients_text:
        "Cilantro lime rice, grilled chicken (chicken, water, seasoning), black beans, shredded cheese (cheddar, jack; milk, cultures, salt, enzymes), pico de gallo, guacamole, sour cream",
    },
    {
      name: "Street Tacos (Chicken, 3pc)",
      category: "entree",
      serving_size: 270,
      serving_unit: "g",
      calories: 450,
      total_fat: 18,
      saturated_fat: 4,
      trans_fat: 0,
      cholesterol: 75,
      sodium: 980,
      total_carbohydrates: 42,
      dietary_fiber: 5,
      total_sugars: 3,
      protein: 30,
      ingredients_text:
        "Corn tortillas (ground corn, water, lime), grilled chicken, cilantro, onion, salsa verde",
    },
    {
      name: "Beef Fajita Plate",
      category: "entree",
      serving_size: 510,
      serving_unit: "g",
      calories: 820,
      total_fat: 36,
      saturated_fat: 12,
      trans_fat: 0.5,
      cholesterol: 110,
      sodium: 1720,
      total_carbohydrates: 78,
      dietary_fiber: 8,
      total_sugars: 5,
      protein: 42,
      ingredients_text:
        "Beef fajita (beef, seasoning, lime), flour tortillas (enriched flour, water, shortening, salt), rice, beans, pico de gallo, sour cream, guacamole",
    },
    {
      name: "Bean and Cheese Burrito",
      category: "entree",
      serving_size: 265,
      serving_unit: "g",
      calories: 470,
      total_fat: 17,
      saturated_fat: 8,
      trans_fat: 0,
      cholesterol: 30,
      sodium: 1140,
      total_carbohydrates: 59,
      dietary_fiber: 8,
      total_sugars: 2,
      protein: 18,
      ingredients_text:
        "Flour tortilla (enriched flour, water, shortening, salt), refried beans (pinto beans, vegetable oil, salt), shredded cheese (cheddar, jack; milk, cultures, salt, enzymes)",
    },
    {
      name: "Chicken Quesadilla",
      category: "entree",
      serving_size: 285,
      serving_unit: "g",
      calories: 710,
      total_fat: 38,
      saturated_fat: 18,
      trans_fat: 0.5,
      cholesterol: 120,
      sodium: 1460,
      total_carbohydrates: 48,
      dietary_fiber: 3,
      total_sugars: 2,
      protein: 40,
      ingredients_text:
        "Flour tortilla, grilled chicken, shredded cheese (cheddar, jack; milk, cultures, salt, enzymes), pico de gallo, sour cream, guacamole",
    },
    {
      name: "Chicken Flautas (3pc)",
      category: "entree",
      serving_size: 240,
      serving_unit: "g",
      calories: 580,
      total_fat: 30,
      saturated_fat: 8,
      trans_fat: 0,
      cholesterol: 70,
      sodium: 990,
      total_carbohydrates: 48,
      dietary_fiber: 3,
      total_sugars: 2,
      protein: 28,
      ingredients_text:
        "Corn tortillas, chicken, cheese, frying oil (soybean oil), sour cream, guacamole",
    },
    {
      name: "Chips and Queso",
      category: "side",
      serving_size: 198,
      serving_unit: "g",
      calories: 460,
      total_fat: 26,
      saturated_fat: 10,
      trans_fat: 0,
      cholesterol: 35,
      sodium: 1020,
      total_carbohydrates: 46,
      dietary_fiber: 3,
      total_sugars: 2,
      protein: 12,
      ingredients_text:
        "Tortilla chips (corn, vegetable oil, salt), queso (water, cheddar cheese, milk, sodium phosphate, jalapeños, salt)",
    },
    {
      name: "Chicken Enchilada Plate (2pc)",
      category: "entree",
      serving_size: 445,
      serving_unit: "g",
      calories: 680,
      total_fat: 30,
      saturated_fat: 14,
      trans_fat: 0,
      cholesterol: 100,
      sodium: 1640,
      total_carbohydrates: 62,
      dietary_fiber: 6,
      total_sugars: 4,
      protein: 36,
      ingredients_text:
        "Corn tortillas, chicken, cheese, enchilada sauce (tomatoes, chili peppers, onion, garlic, salt), rice, refried beans",
    },
    {
      name: "Breakfast Taco (Bacon, Egg & Cheese)",
      category: "breakfast",
      serving_size: 130,
      serving_unit: "g",
      calories: 280,
      total_fat: 15,
      saturated_fat: 6,
      trans_fat: 0,
      cholesterol: 130,
      sodium: 560,
      total_carbohydrates: 22,
      dietary_fiber: 1,
      total_sugars: 1,
      protein: 13,
      ingredients_text:
        "Flour tortilla, scrambled eggs, bacon (cured pork, salt, sugar, sodium nitrite), shredded cheese",
    },
  ],
};

// ─── Torchy's Tacos ──────────────────────────────────────────────────────────
// Source: torchystacos.com/nutrition

const torchys: ChainData = {
  chain: "Torchy's Tacos",
  items: [
    {
      name: "Trailer Park (Trashy)",
      category: "entree",
      serving_size: 195,
      serving_unit: "g",
      calories: 540,
      total_fat: 34,
      saturated_fat: 10,
      trans_fat: 0,
      cholesterol: 75,
      sodium: 1050,
      total_carbohydrates: 32,
      dietary_fiber: 2,
      total_sugars: 2,
      protein: 26,
      ingredients_text:
        "Flour tortilla, fried chicken strip (chicken, wheat flour, spices, salt, frying oil), green chiles, lettuce, pico de gallo, shredded cheese, poblano ranch (soybean oil, buttermilk, poblano, egg yolk, vinegar)",
    },
    {
      name: "Democrat",
      category: "entree",
      serving_size: 198,
      serving_unit: "g",
      calories: 390,
      total_fat: 22,
      saturated_fat: 6,
      trans_fat: 0,
      cholesterol: 55,
      sodium: 830,
      total_carbohydrates: 30,
      dietary_fiber: 3,
      total_sugars: 3,
      protein: 18,
      ingredients_text:
        "Flour tortilla, seasoned ground beef, avocado, shredded cheese, pico de gallo, cilantro, lime, green salsa",
    },
    {
      name: "Crossroads",
      category: "entree",
      serving_size: 210,
      serving_unit: "g",
      calories: 420,
      total_fat: 24,
      saturated_fat: 7,
      trans_fat: 0,
      cholesterol: 60,
      sodium: 890,
      total_carbohydrates: 31,
      dietary_fiber: 3,
      total_sugars: 4,
      protein: 20,
      ingredients_text:
        "Flour tortilla, smoked beef brisket, grilled onions, cheddar cheese, pickles, poblano ranch",
    },
    {
      name: "Green Chile Queso (Cup)",
      category: "side",
      serving_size: 113,
      serving_unit: "g",
      calories: 220,
      total_fat: 16,
      saturated_fat: 8,
      trans_fat: 0,
      cholesterol: 40,
      sodium: 760,
      total_carbohydrates: 8,
      dietary_fiber: 0,
      total_sugars: 3,
      protein: 10,
      ingredients_text:
        "Cheddar cheese (milk, cultures, salt, enzymes), cream, green chiles, jalapeños, onion, garlic, salt, spices",
    },
    {
      name: "Brushfire",
      category: "entree",
      serving_size: 195,
      serving_unit: "g",
      calories: 430,
      total_fat: 24,
      saturated_fat: 8,
      trans_fat: 0,
      cholesterol: 70,
      sodium: 1020,
      total_carbohydrates: 28,
      dietary_fiber: 2,
      total_sugars: 5,
      protein: 24,
      ingredients_text:
        "Flour tortilla, grilled Jamaican jerk chicken, grilled jalapeños, sour cream, pico de gallo, diablo sauce",
    },
    {
      name: "Tipsy Chick",
      category: "entree",
      serving_size: 205,
      serving_unit: "g",
      calories: 490,
      total_fat: 28,
      saturated_fat: 8,
      trans_fat: 0,
      cholesterol: 75,
      sodium: 960,
      total_carbohydrates: 34,
      dietary_fiber: 2,
      total_sugars: 6,
      protein: 26,
      ingredients_text:
        "Flour tortilla, marinated grilled chicken, mango, shredded cheese, pickled onions, cilantro, chipotle sauce",
    },
    {
      name: "Mr. Orange",
      category: "entree",
      serving_size: 190,
      serving_unit: "g",
      calories: 380,
      total_fat: 20,
      saturated_fat: 5,
      trans_fat: 0,
      cholesterol: 45,
      sodium: 780,
      total_carbohydrates: 32,
      dietary_fiber: 3,
      total_sugars: 4,
      protein: 18,
      ingredients_text:
        "Flour tortilla, smoked salmon, avocado, pico de gallo, cilantro, arbol salsa",
    },
    {
      name: "Chips and Guac",
      category: "side",
      serving_size: 255,
      serving_unit: "g",
      calories: 680,
      total_fat: 38,
      saturated_fat: 5,
      trans_fat: 0,
      cholesterol: 0,
      sodium: 590,
      total_carbohydrates: 78,
      dietary_fiber: 10,
      total_sugars: 3,
      protein: 8,
      ingredients_text:
        "Tortilla chips (corn, vegetable oil, salt), guacamole (avocado, lime juice, cilantro, onion, jalapeño, salt)",
    },
    {
      name: "Ace of Spades",
      category: "entree",
      serving_size: 210,
      serving_unit: "g",
      calories: 460,
      total_fat: 26,
      saturated_fat: 9,
      trans_fat: 0,
      cholesterol: 65,
      sodium: 910,
      total_carbohydrates: 30,
      dietary_fiber: 3,
      total_sugars: 3,
      protein: 24,
      ingredients_text:
        "Flour tortilla, blackened salmon, avocado, refried black beans, pico de gallo, cheese, chipotle mayo",
    },
    {
      name: "Churro (1pc)",
      category: "dessert",
      serving_size: 90,
      serving_unit: "g",
      calories: 320,
      total_fat: 16,
      saturated_fat: 3,
      trans_fat: 0,
      cholesterol: 15,
      sodium: 220,
      total_carbohydrates: 42,
      dietary_fiber: 1,
      total_sugars: 18,
      protein: 4,
      ingredients_text:
        "Enriched flour, water, butter, sugar, eggs, salt, cinnamon sugar coating, chocolate dipping sauce",
    },
  ],
};

// ─── Pei Wei ─────────────────────────────────────────────────────────────────
// Source: peiwei.com/nutrition

const peiWei: ChainData = {
  chain: "Pei Wei",
  items: [
    {
      name: "Original Pad Thai (Chicken)",
      category: "entree",
      serving_size: 420,
      serving_unit: "g",
      calories: 790,
      total_fat: 22,
      saturated_fat: 4,
      trans_fat: 0,
      cholesterol: 90,
      sodium: 2110,
      total_carbohydrates: 108,
      dietary_fiber: 4,
      total_sugars: 28,
      protein: 38,
      ingredients_text:
        "Rice noodles (rice flour, water), chicken breast, pad Thai sauce (sugar, fish sauce, tamarind, rice vinegar, chili paste), bean sprouts, green onion, peanuts, egg, lime, cilantro",
    },
    {
      name: "Kung Pao Chicken",
      category: "entree",
      serving_size: 400,
      serving_unit: "g",
      calories: 650,
      total_fat: 28,
      saturated_fat: 4.5,
      trans_fat: 0,
      cholesterol: 85,
      sodium: 1810,
      total_carbohydrates: 62,
      dietary_fiber: 4,
      total_sugars: 18,
      protein: 36,
      ingredients_text:
        "Chicken breast, kung pao sauce (soy sauce, sugar, rice vinegar, sesame oil, chili paste, garlic), steamed rice, peanuts, celery, red bell pepper, dried red chili peppers, green onion",
    },
    {
      name: "Orange Chicken",
      category: "entree",
      serving_size: 396,
      serving_unit: "g",
      calories: 770,
      total_fat: 26,
      saturated_fat: 4,
      trans_fat: 0,
      cholesterol: 80,
      sodium: 1580,
      total_carbohydrates: 96,
      dietary_fiber: 3,
      total_sugars: 40,
      protein: 36,
      ingredients_text:
        "Chicken breast (chicken, water, salt), tempura batter (wheat flour, corn starch, salt, leavening), orange sauce (sugar, orange juice, soy sauce, rice vinegar, ginger, garlic, chili flakes), steamed rice",
    },
    {
      name: "Fried Rice (Chicken)",
      category: "entree",
      serving_size: 380,
      serving_unit: "g",
      calories: 680,
      total_fat: 20,
      saturated_fat: 3.5,
      trans_fat: 0,
      cholesterol: 130,
      sodium: 1650,
      total_carbohydrates: 88,
      dietary_fiber: 3,
      total_sugars: 6,
      protein: 32,
      ingredients_text:
        "Rice, chicken breast, egg, soy sauce, peas, carrots, green onion, sesame oil, garlic, vegetable oil",
    },
    {
      name: "Mongolian Beef",
      category: "entree",
      serving_size: 396,
      serving_unit: "g",
      calories: 710,
      total_fat: 24,
      saturated_fat: 6,
      trans_fat: 0,
      cholesterol: 75,
      sodium: 1920,
      total_carbohydrates: 82,
      dietary_fiber: 3,
      total_sugars: 30,
      protein: 36,
      ingredients_text:
        "Beef (flank steak), Mongolian sauce (soy sauce, brown sugar, hoisin sauce, garlic, ginger, chili flakes), steamed rice, green onion",
    },
    {
      name: "Honey Seared Chicken",
      category: "entree",
      serving_size: 400,
      serving_unit: "g",
      calories: 720,
      total_fat: 20,
      saturated_fat: 3.5,
      trans_fat: 0,
      cholesterol: 85,
      sodium: 1510,
      total_carbohydrates: 98,
      dietary_fiber: 3,
      total_sugars: 36,
      protein: 34,
      ingredients_text:
        "Chicken breast, honey sauce (honey, soy sauce, rice vinegar, garlic, ginger), steamed rice, broccoli, carrots",
    },
    {
      name: "Thai Dynamite Shrimp",
      category: "appetizer",
      serving_size: 180,
      serving_unit: "g",
      calories: 440,
      total_fat: 22,
      saturated_fat: 4,
      trans_fat: 0,
      cholesterol: 130,
      sodium: 1120,
      total_carbohydrates: 40,
      dietary_fiber: 2,
      total_sugars: 12,
      protein: 20,
      ingredients_text:
        "Shrimp (shrimp, water, salt), tempura batter (wheat flour, corn starch, salt), Thai dynamite sauce (mayo, sriracha, sweet chili sauce, lime), lettuce",
    },
    {
      name: "Edamame",
      category: "side",
      serving_size: 142,
      serving_unit: "g",
      calories: 160,
      total_fat: 7,
      saturated_fat: 1,
      trans_fat: 0,
      cholesterol: 0,
      sodium: 580,
      total_carbohydrates: 11,
      dietary_fiber: 6,
      total_sugars: 3,
      protein: 14,
      ingredients_text:
        "Soybeans, salt, kosher salt",
    },
    {
      name: "Chicken Lettuce Wraps",
      category: "appetizer",
      serving_size: 240,
      serving_unit: "g",
      calories: 350,
      total_fat: 14,
      saturated_fat: 2.5,
      trans_fat: 0,
      cholesterol: 70,
      sodium: 1340,
      total_carbohydrates: 32,
      dietary_fiber: 3,
      total_sugars: 12,
      protein: 24,
      ingredients_text:
        "Butter lettuce cups, chicken breast, water chestnuts, mushrooms, green onion, soy sauce, hoisin sauce, rice vinegar, garlic, ginger, sesame oil",
    },
    {
      name: "Lo Mein (Chicken)",
      category: "entree",
      serving_size: 410,
      serving_unit: "g",
      calories: 720,
      total_fat: 22,
      saturated_fat: 4,
      trans_fat: 0,
      cholesterol: 85,
      sodium: 2020,
      total_carbohydrates: 92,
      dietary_fiber: 5,
      total_sugars: 14,
      protein: 36,
      ingredients_text:
        "Lo mein noodles (wheat flour, water, salt), chicken breast, lo mein sauce (soy sauce, oyster sauce, sesame oil, sugar), cabbage, carrots, broccoli, mushrooms, bean sprouts",
    },
  ],
};

// ─── Buc-ee's ────────────────────────────────────────────────────────────────
// Source: Buc-ee's in-store nutrition labels (limited published data online)

const bucees: ChainData = {
  chain: "Buc-ee's",
  items: [
    {
      name: "Brisket Sandwich",
      category: "sandwich",
      serving_size: 280,
      serving_unit: "g",
      calories: 560,
      total_fat: 22,
      saturated_fat: 8,
      trans_fat: 0,
      cholesterol: 100,
      sodium: 1180,
      total_carbohydrates: 48,
      dietary_fiber: 2,
      total_sugars: 8,
      protein: 38,
      ingredients_text:
        "Smoked beef brisket (beef, salt, pepper, garlic), brioche bun (enriched flour, water, sugar, butter, eggs, yeast, salt), BBQ sauce (tomato paste, vinegar, sugar, molasses, spices), pickles, onion",
    },
    {
      name: "Chopped Beef Sandwich",
      category: "sandwich",
      serving_size: 260,
      serving_unit: "g",
      calories: 520,
      total_fat: 20,
      saturated_fat: 7,
      trans_fat: 0,
      cholesterol: 90,
      sodium: 1050,
      total_carbohydrates: 48,
      dietary_fiber: 2,
      total_sugars: 10,
      protein: 34,
      ingredients_text:
        "Chopped smoked beef brisket, bun (enriched flour, water, sugar, yeast, salt), BBQ sauce, pickles, onion",
    },
    {
      name: "Pulled Pork Sandwich",
      category: "sandwich",
      serving_size: 265,
      serving_unit: "g",
      calories: 490,
      total_fat: 16,
      saturated_fat: 5,
      trans_fat: 0,
      cholesterol: 85,
      sodium: 1130,
      total_carbohydrates: 52,
      dietary_fiber: 2,
      total_sugars: 14,
      protein: 32,
      ingredients_text:
        "Smoked pulled pork (pork, salt, pepper, paprika), bun (enriched flour, water, sugar, yeast, salt), BBQ sauce, coleslaw",
    },
    {
      name: "Beaver Nuggets (1 bag, 4oz)",
      category: "snack",
      serving_size: 113,
      serving_unit: "g",
      calories: 480,
      total_fat: 16,
      saturated_fat: 2,
      trans_fat: 0,
      cholesterol: 0,
      sodium: 340,
      total_carbohydrates: 80,
      dietary_fiber: 1,
      total_sugars: 38,
      protein: 4,
      ingredients_text:
        "Corn puffs (corn meal, vegetable oil), caramel coating (sugar, corn syrup, butter, baking soda, salt, vanilla)",
    },
    {
      name: "Kolache (Sausage, Egg & Cheese)",
      category: "breakfast",
      serving_size: 175,
      serving_unit: "g",
      calories: 420,
      total_fat: 22,
      saturated_fat: 9,
      trans_fat: 0,
      cholesterol: 130,
      sodium: 940,
      total_carbohydrates: 34,
      dietary_fiber: 1,
      total_sugars: 6,
      protein: 20,
      ingredients_text:
        "Kolache dough (enriched flour, water, sugar, butter, eggs, yeast, salt, milk), sausage (pork, salt, spices, sugar, dextrose), egg, American cheese (milk, cream, salt)",
    },
    {
      name: "Kolache (Jalapeño Sausage & Cheese)",
      category: "breakfast",
      serving_size: 160,
      serving_unit: "g",
      calories: 390,
      total_fat: 20,
      saturated_fat: 8,
      trans_fat: 0,
      cholesterol: 55,
      sodium: 890,
      total_carbohydrates: 34,
      dietary_fiber: 1,
      total_sugars: 6,
      protein: 16,
      ingredients_text:
        "Kolache dough (enriched flour, water, sugar, butter, eggs, yeast, salt), jalapeño cheddar sausage (pork, cheddar cheese, jalapeño, salt, spices)",
    },
    {
      name: "Turkey Sandwich",
      category: "sandwich",
      serving_size: 280,
      serving_unit: "g",
      calories: 430,
      total_fat: 14,
      saturated_fat: 4,
      trans_fat: 0,
      cholesterol: 70,
      sodium: 1240,
      total_carbohydrates: 48,
      dietary_fiber: 3,
      total_sugars: 6,
      protein: 28,
      ingredients_text:
        "Smoked turkey breast (turkey, water, salt, dextrose), bun (enriched flour, water, sugar, yeast, salt), lettuce, tomato, mayo, mustard",
    },
    {
      name: "Fudge (Chocolate, 2pc)",
      category: "dessert",
      serving_size: 56,
      serving_unit: "g",
      calories: 240,
      total_fat: 10,
      saturated_fat: 6,
      trans_fat: 0,
      cholesterol: 10,
      sodium: 55,
      total_carbohydrates: 36,
      dietary_fiber: 1,
      total_sugars: 32,
      protein: 2,
      ingredients_text:
        "Sugar, chocolate (cocoa, sugar, cocoa butter), butter, cream, vanilla extract, salt",
    },
    {
      name: "Beef Jerky (Original, 3.5oz)",
      category: "snack",
      serving_size: 99,
      serving_unit: "g",
      calories: 270,
      total_fat: 5,
      saturated_fat: 2,
      trans_fat: 0,
      cholesterol: 60,
      sodium: 1960,
      total_carbohydrates: 24,
      dietary_fiber: 0,
      total_sugars: 20,
      protein: 36,
      ingredients_text:
        "Beef, sugar, soy sauce (water, wheat, soybeans, salt), water, Worcestershire sauce (vinegar, molasses, sugar, salt, anchovies, tamarind, garlic), vinegar, salt, garlic powder, onion powder, black pepper, red pepper",
    },
    {
      name: "Brisket Breakfast Taco",
      category: "breakfast",
      serving_size: 170,
      serving_unit: "g",
      calories: 380,
      total_fat: 18,
      saturated_fat: 7,
      trans_fat: 0,
      cholesterol: 150,
      sodium: 820,
      total_carbohydrates: 28,
      dietary_fiber: 2,
      total_sugars: 2,
      protein: 24,
      ingredients_text:
        "Flour tortilla, chopped brisket, scrambled eggs, shredded cheese, salsa",
    },
  ],
};

// ─── Sweetgreen ──────────────────────────────────────────────────────────────
// Source: sweetgreen.com/menu

const sweetgreen: ChainData = {
  chain: "Sweetgreen",
  items: [
    {
      name: "Harvest Bowl",
      category: "salad",
      serving_size: 386,
      serving_unit: "g",
      calories: 600,
      total_fat: 29,
      saturated_fat: 7,
      trans_fat: 0,
      cholesterol: 80,
      sodium: 520,
      total_carbohydrates: 49,
      dietary_fiber: 8,
      total_sugars: 11,
      protein: 34,
      ingredients_text:
        "Warm wild rice, roasted chicken (chicken, olive oil, salt, pepper), roasted sweet potatoes, apples, goat cheese (pasteurized goat milk, cultures, salt, enzymes), shredded kale, balsamic vinaigrette (balsamic vinegar, olive oil, shallots, dijon mustard, honey)",
    },
    {
      name: "Kale Caesar",
      category: "salad",
      serving_size: 340,
      serving_unit: "g",
      calories: 490,
      total_fat: 26,
      saturated_fat: 6,
      trans_fat: 0,
      cholesterol: 100,
      sodium: 850,
      total_carbohydrates: 28,
      dietary_fiber: 5,
      total_sugars: 4,
      protein: 36,
      ingredients_text:
        "Chopped romaine, shredded kale, roasted chicken, Parmesan cheese (milk, cultures, salt, enzymes), tomatoes, breadcrumbs (enriched flour, butter, garlic, salt), lime squeeze Caesar dressing (olive oil, Parmesan, lemon juice, anchovy, garlic, dijon mustard)",
    },
    {
      name: "Guacamole Greens",
      category: "salad",
      serving_size: 380,
      serving_unit: "g",
      calories: 530,
      total_fat: 33,
      saturated_fat: 6,
      trans_fat: 0,
      cholesterol: 75,
      sodium: 650,
      total_carbohydrates: 30,
      dietary_fiber: 10,
      total_sugars: 5,
      protein: 32,
      ingredients_text:
        "Spring mix, roasted chicken, avocado, tortilla chips, tomatoes, red onion, lime cilantro jalapeño vinaigrette (lime juice, olive oil, cilantro, jalapeño, honey)",
    },
    {
      name: "Hot Honey Chicken Plate",
      category: "entree",
      serving_size: 415,
      serving_unit: "g",
      calories: 650,
      total_fat: 24,
      saturated_fat: 5,
      trans_fat: 0,
      cholesterol: 85,
      sodium: 830,
      total_carbohydrates: 70,
      dietary_fiber: 7,
      total_sugars: 14,
      protein: 38,
      ingredients_text:
        "Warm wild rice, hot honey chicken (chicken, hot honey, spices), roasted broccoli, pickled onions, goat cheese, hot honey mustard sauce",
    },
    {
      name: "Shroomami",
      category: "salad",
      serving_size: 380,
      serving_unit: "g",
      calories: 520,
      total_fat: 27,
      saturated_fat: 5,
      trans_fat: 0,
      cholesterol: 0,
      sodium: 780,
      total_carbohydrates: 55,
      dietary_fiber: 8,
      total_sugars: 8,
      protein: 16,
      ingredients_text:
        "Warm wild rice, raw beets, roasted sesame tofu (tofu, soy sauce, sesame oil), cucumbers, basil, shredded cabbage, miso sesame ginger dressing (miso, sesame oil, rice vinegar, ginger, honey)",
    },
    {
      name: "Buffalo Chicken Bowl",
      category: "salad",
      serving_size: 370,
      serving_unit: "g",
      calories: 510,
      total_fat: 22,
      saturated_fat: 6,
      trans_fat: 0,
      cholesterol: 90,
      sodium: 1100,
      total_carbohydrates: 42,
      dietary_fiber: 6,
      total_sugars: 5,
      protein: 36,
      ingredients_text:
        "Warm wild rice, blackened chicken, shredded kale, tomatoes, blue cheese (milk, cultures, salt, enzymes, Penicillium roqueforti), celery, Buffalo sauce, ranch dressing",
    },
    {
      name: "Chicken Pesto Parm Plate",
      category: "entree",
      serving_size: 400,
      serving_unit: "g",
      calories: 640,
      total_fat: 30,
      saturated_fat: 8,
      trans_fat: 0,
      cholesterol: 95,
      sodium: 870,
      total_carbohydrates: 52,
      dietary_fiber: 6,
      total_sugars: 6,
      protein: 40,
      ingredients_text:
        "Warm wild rice, roasted chicken, roasted sweet potatoes, tomatoes, Parmesan cheese, pesto (basil, olive oil, pine nuts, garlic, Parmesan, salt), spicy cashew dressing",
    },
    {
      name: "Super Green Goddess",
      category: "salad",
      serving_size: 360,
      serving_unit: "g",
      calories: 480,
      total_fat: 26,
      saturated_fat: 4,
      trans_fat: 0,
      cholesterol: 0,
      sodium: 640,
      total_carbohydrates: 48,
      dietary_fiber: 10,
      total_sugars: 6,
      protein: 14,
      ingredients_text:
        "Spring mix, shredded kale, warm wild rice, avocado, cucumbers, broccoli, spicy broccoli, green goddess ranch (avocado, buttermilk, herbs, lemon, garlic)",
    },
    {
      name: "Crispy Rice Bowl",
      category: "entree",
      serving_size: 395,
      serving_unit: "g",
      calories: 590,
      total_fat: 25,
      saturated_fat: 5,
      trans_fat: 0,
      cholesterol: 80,
      sodium: 910,
      total_carbohydrates: 58,
      dietary_fiber: 5,
      total_sugars: 10,
      protein: 34,
      ingredients_text:
        "Crispy rice, blackened chicken, shredded cabbage, cucumbers, cilantro, spicy cashew dressing, sesame seeds, lime",
    },
    {
      name: "Steakhouse Chopped Salad",
      category: "salad",
      serving_size: 380,
      serving_unit: "g",
      calories: 580,
      total_fat: 30,
      saturated_fat: 8,
      trans_fat: 0,
      cholesterol: 70,
      sodium: 690,
      total_carbohydrates: 38,
      dietary_fiber: 7,
      total_sugars: 8,
      protein: 36,
      ingredients_text:
        "Chopped romaine, roasted steak, roasted sweet potatoes, blue cheese, pickled onions, crispy onions, balsamic vinaigrette",
    },
  ],
};

// ─── Moe's Southwest Grill is already defined above ──────────────────────────

// ═══════════════════════════════════════════════════════════════════════════════
// All Chains
// ═══════════════════════════════════════════════════════════════════════════════

const allChains: ChainData[] = [
  popeyes,
  hardees,
  rallysCheckers,
  moes,
  mcalisters,
  jasonsDeli,
  marcosPizza,
  dunkin,
  hooters,
  yardHouse,
  bajaFresh,
  tacoCabana,
  torchys,
  peiWei,
  bucees,
  sweetgreen,
];

// ═══════════════════════════════════════════════════════════════════════════════
// Main
// ═══════════════════════════════════════════════════════════════════════════════

function main() {
  console.log("=== Restaurant Chain Nutrition Import — Remaining Major Chains ===\n");
  console.log("Chains: Popeyes, Hardee's, Rally's/Checkers, Moe's Southwest Grill,");
  console.log("        McAlister's Deli, Jason's Deli, Marco's Pizza, Dunkin',");
  console.log("        Hooters, Yard House, Baja Fresh, Taco Cabana, Torchy's Tacos,");
  console.log("        Pei Wei, Buc-ee's, Sweetgreen\n");
  console.log("NOTE: Existing chains from prior imports are NOT duplicated here.\n");

  let totalItems = 0;
  let totalChains = 0;

  const beforeCount = (
    db.prepare("SELECT COUNT(*) as c FROM foods WHERE source = 'vendor'").get() as any
  ).c;

  const importAll = db.transaction(() => {
    for (const chain of allChains) {
      const chainSlug = slugify(chain.chain);
      const vendorId = `chain-${chainSlug}`;

      // Create vendor record
      upsertVendor.run({
        id: vendorId,
        name: chain.chain,
        type: "restaurant",
        api_key: generateApiKey(),
      });

      console.log(`  ${chain.chain}: ${chain.items.length} items`);

      // Import each menu item
      for (const item of chain.items) {
        const record = buildFoodRecord(item, chain.chain, vendorId);
        upsertFood.run(record);
      }

      totalItems += chain.items.length;
      totalChains++;
    }
  });

  importAll();

  // Rebuild FTS index
  console.log("\nRebuilding search index...");
  db.exec("INSERT INTO foods_fts(foods_fts) VALUES('rebuild')");

  const afterCount = (
    db.prepare("SELECT COUNT(*) as c FROM foods WHERE source = 'vendor'").get() as any
  ).c;

  console.log(`\n=== Done! ===`);
  console.log(`Chains imported: ${totalChains}`);
  console.log(`Menu items processed: ${totalItems}`);
  console.log(`Vendor foods before: ${beforeCount}`);
  console.log(`Vendor foods after: ${afterCount}`);
  console.log(`New items added: ${afterCount - beforeCount}`);
}

main();
