/**
 * Restaurant Chain Nutrition Data Import - Batch 1 (Fast Food)
 *
 * Imports manually curated nutrition data for fast food chains:
 * Burger King, KFC, Five Guys, In-N-Out, Shake Shack, Sonic,
 * Jack in the Box, Whataburger, Raising Cane's
 *
 * Usage:
 *   npx ts-node scripts/import-chains-batch1.ts
 */

import { v4 as uuidv4 } from "uuid";
import db from "../src/data/database";
import { calculateNutriScore } from "../src/services/nutrition-score";
import { calculatePersonalHealthScore } from "../src/services/health-score";
import { detectAllergens, detectDietaryTags } from "../src/services/food-analysis";
import { generateApiKey } from "../src/middleware/auth";

interface ChainMenuItem {
  name: string;
  category: string;
  serving_size: number;
  serving_unit: string;
  calories: number;
  total_fat: number;
  saturated_fat: number;
  trans_fat: number;
  cholesterol: number;
  sodium: number;
  total_carbohydrates: number;
  dietary_fiber: number;
  total_sugars: number;
  protein: number;
  ingredients_text?: string;
}

interface ChainData {
  chain: string;
  items: ChainMenuItem[];
}

// ---------------------------------------------------------------------------
// Chain menu data
// ---------------------------------------------------------------------------

const chains: ChainData[] = [
  // ======================== BURGER KING ========================
  {
    chain: "Burger King",
    items: [
      {
        name: "Whopper",
        category: "burger",
        serving_size: 290,
        serving_unit: "g",
        calories: 660,
        total_fat: 40,
        saturated_fat: 12,
        trans_fat: 1.5,
        cholesterol: 90,
        sodium: 980,
        total_carbohydrates: 49,
        dietary_fiber: 2,
        total_sugars: 11,
        protein: 28,
        ingredients_text:
          "Beef patty, sesame seed bun (enriched flour, water, sugar, soybean oil, yeast, salt), lettuce, tomato, onion, pickles, ketchup, mayonnaise",
      },
      {
        name: "Whopper Jr",
        category: "burger",
        serving_size: 153,
        serving_unit: "g",
        calories: 310,
        total_fat: 18,
        saturated_fat: 6,
        trans_fat: 0.5,
        cholesterol: 40,
        sodium: 490,
        total_carbohydrates: 27,
        dietary_fiber: 1,
        total_sugars: 7,
        protein: 13,
        ingredients_text:
          "Beef patty, sesame seed bun (enriched flour, water, sugar, soybean oil, yeast, salt), lettuce, tomato, onion, pickles, ketchup, mayonnaise",
      },
      {
        name: "Chicken Fries",
        category: "chicken",
        serving_size: 85,
        serving_unit: "g",
        calories: 280,
        total_fat: 17,
        saturated_fat: 3,
        trans_fat: 0,
        cholesterol: 30,
        sodium: 780,
        total_carbohydrates: 20,
        dietary_fiber: 1,
        total_sugars: 0,
        protein: 13,
        ingredients_text:
          "Chicken breast with rib meat, water, seasoning (salt, sodium phosphates, modified food starch), bleached wheat flour, salt, spices, dextrose, soybean oil",
      },
      {
        name: "Original Chicken Sandwich",
        category: "sandwich",
        serving_size: 198,
        serving_unit: "g",
        calories: 660,
        total_fat: 40,
        saturated_fat: 7,
        trans_fat: 0,
        cholesterol: 50,
        sodium: 1170,
        total_carbohydrates: 52,
        dietary_fiber: 3,
        total_sugars: 5,
        protein: 24,
        ingredients_text:
          "Breaded chicken patty (chicken breast with rib meat, water, salt, sodium phosphates, wheat flour, modified corn starch, soybean oil), sesame seed bun, lettuce, mayonnaise",
      },
      {
        name: "Onion Rings",
        category: "side",
        serving_size: 113,
        serving_unit: "g",
        calories: 320,
        total_fat: 16,
        saturated_fat: 3,
        trans_fat: 0,
        cholesterol: 0,
        sodium: 460,
        total_carbohydrates: 41,
        dietary_fiber: 2,
        total_sugars: 4,
        protein: 4,
        ingredients_text:
          "Onion, bleached wheat flour, water, modified corn starch, yellow corn flour, salt, soybean oil, dextrose, leavening (sodium acid pyrophosphate, sodium bicarbonate)",
      },
      {
        name: "French Fries",
        category: "side",
        serving_size: 128,
        serving_unit: "g",
        calories: 380,
        total_fat: 17,
        saturated_fat: 3,
        trans_fat: 0,
        cholesterol: 0,
        sodium: 570,
        total_carbohydrates: 53,
        dietary_fiber: 4,
        total_sugars: 0,
        protein: 5,
        ingredients_text:
          "Potatoes, soybean oil, dextrose, sodium acid pyrophosphate, salt",
      },
      {
        name: "Big Fish Sandwich",
        category: "sandwich",
        serving_size: 224,
        serving_unit: "g",
        calories: 510,
        total_fat: 28,
        saturated_fat: 5,
        trans_fat: 0,
        cholesterol: 45,
        sodium: 1050,
        total_carbohydrates: 51,
        dietary_fiber: 2,
        total_sugars: 7,
        protein: 16,
        ingredients_text:
          "Breaded fish patty (pollock, wheat flour, water, modified corn starch, salt, soybean oil), brioche bun, tartar sauce, lettuce",
      },
      {
        name: "Double Whopper",
        category: "burger",
        serving_size: 374,
        serving_unit: "g",
        calories: 900,
        total_fat: 56,
        saturated_fat: 20,
        trans_fat: 3,
        cholesterol: 175,
        sodium: 1050,
        total_carbohydrates: 49,
        dietary_fiber: 2,
        total_sugars: 11,
        protein: 48,
        ingredients_text:
          "Beef patties (2), sesame seed bun (enriched flour, water, sugar, soybean oil, yeast, salt), lettuce, tomato, onion, pickles, ketchup, mayonnaise",
      },
      {
        name: "Impossible Whopper",
        category: "burger",
        serving_size: 276,
        serving_unit: "g",
        calories: 630,
        total_fat: 34,
        saturated_fat: 11,
        trans_fat: 0,
        cholesterol: 10,
        sodium: 1080,
        total_carbohydrates: 58,
        dietary_fiber: 4,
        total_sugars: 12,
        protein: 25,
        ingredients_text:
          "Impossible patty (water, soy protein concentrate, coconut oil, sunflower oil, natural flavors, methylcellulose, soy leghemoglobin), sesame seed bun, lettuce, tomato, onion, pickles, ketchup, mayonnaise",
      },
      {
        name: "Chicken Nuggets 8pc",
        category: "chicken",
        serving_size: 114,
        serving_unit: "g",
        calories: 380,
        total_fat: 23,
        saturated_fat: 4,
        trans_fat: 0,
        cholesterol: 45,
        sodium: 760,
        total_carbohydrates: 24,
        dietary_fiber: 1,
        total_sugars: 0,
        protein: 19,
        ingredients_text:
          "White meat chicken, water, wheat flour, modified corn starch, salt, seasoning (yeast extract, salt, wheat starch, natural flavoring, safflower oil, dextrose), sodium phosphates, soybean oil",
      },
      {
        name: "BK Veggie Burger",
        category: "burger",
        serving_size: 211,
        serving_unit: "g",
        calories: 390,
        total_fat: 17,
        saturated_fat: 2.5,
        trans_fat: 0,
        cholesterol: 10,
        sodium: 900,
        total_carbohydrates: 44,
        dietary_fiber: 4,
        total_sugars: 8,
        protein: 21,
        ingredients_text:
          "Veggie patty (vegetables, grains, spices), sesame seed bun (enriched wheat flour, water, sugar, soybean oil, yeast, salt), lettuce, tomato, onion, pickles, ketchup, mayonnaise",
      },
      {
        name: "Hershey's Sundae Pie",
        category: "dessert",
        serving_size: 79,
        serving_unit: "g",
        calories: 310,
        total_fat: 18,
        saturated_fat: 11,
        trans_fat: 0,
        cholesterol: 10,
        sodium: 220,
        total_carbohydrates: 37,
        dietary_fiber: 1,
        total_sugars: 22,
        protein: 3,
        ingredients_text:
          "Chocolate cookie crust (wheat flour, sugar, palm oil, cocoa, salt), chocolate pudding (water, sugar, modified corn starch, cocoa, milk, salt), whipped topping (water, hydrogenated vegetable oil, sugar, corn syrup, milk)",
      },
      {
        name: "Chocolate Shake",
        category: "beverage",
        serving_size: 411,
        serving_unit: "ml",
        calories: 590,
        total_fat: 18,
        saturated_fat: 12,
        trans_fat: 0.5,
        cholesterol: 60,
        sodium: 380,
        total_carbohydrates: 96,
        dietary_fiber: 2,
        total_sugars: 84,
        protein: 11,
        ingredients_text:
          "Vanilla soft serve (milk, sugar, cream, nonfat milk, corn syrup solids, whey, mono and diglycerides, guar gum, vanilla), chocolate syrup (water, sugar, cocoa, corn syrup)",
      },
      {
        name: "Vanilla Shake",
        category: "beverage",
        serving_size: 411,
        serving_unit: "ml",
        calories: 560,
        total_fat: 17,
        saturated_fat: 11,
        trans_fat: 0.5,
        cholesterol: 60,
        sodium: 330,
        total_carbohydrates: 87,
        dietary_fiber: 0,
        total_sugars: 78,
        protein: 11,
        ingredients_text:
          "Vanilla soft serve (milk, sugar, cream, nonfat milk, corn syrup solids, whey, mono and diglycerides, guar gum, vanilla extract)",
      },
      {
        name: "Breakfast Croissanwich with Sausage Egg and Cheese",
        category: "breakfast",
        serving_size: 160,
        serving_unit: "g",
        calories: 470,
        total_fat: 31,
        saturated_fat: 13,
        trans_fat: 0,
        cholesterol: 195,
        sodium: 880,
        total_carbohydrates: 27,
        dietary_fiber: 1,
        total_sugars: 5,
        protein: 19,
        ingredients_text:
          "Croissant (enriched wheat flour, butter, water, sugar, yeast, salt, milk, eggs), sausage patty (pork, water, salt, spices, sugar, dextrose), egg, American cheese (milk, water, milkfat, sodium citrate, salt, enzymes)",
      },
    ],
  },

  // ======================== KFC ========================
  {
    chain: "KFC",
    items: [
      {
        name: "Original Recipe Chicken Breast",
        category: "chicken",
        serving_size: 161,
        serving_unit: "g",
        calories: 390,
        total_fat: 21,
        saturated_fat: 4,
        trans_fat: 0,
        cholesterol: 120,
        sodium: 1190,
        total_carbohydrates: 11,
        dietary_fiber: 0,
        total_sugars: 0,
        protein: 39,
        ingredients_text:
          "Chicken breast, wheat flour, salt, monosodium glutamate, spices, garlic powder, dried egg whites, nonfat dry milk, soybean oil",
      },
      {
        name: "Original Recipe Chicken Thigh",
        category: "chicken",
        serving_size: 126,
        serving_unit: "g",
        calories: 280,
        total_fat: 17,
        saturated_fat: 3.5,
        trans_fat: 0,
        cholesterol: 95,
        sodium: 790,
        total_carbohydrates: 8,
        dietary_fiber: 0,
        total_sugars: 0,
        protein: 22,
        ingredients_text:
          "Chicken thigh, wheat flour, salt, monosodium glutamate, spices, garlic powder, dried egg whites, nonfat dry milk, soybean oil",
      },
      {
        name: "Original Recipe Drumstick",
        category: "chicken",
        serving_size: 72,
        serving_unit: "g",
        calories: 130,
        total_fat: 7,
        saturated_fat: 1.5,
        trans_fat: 0,
        cholesterol: 55,
        sodium: 430,
        total_carbohydrates: 4,
        dietary_fiber: 0,
        total_sugars: 0,
        protein: 13,
        ingredients_text:
          "Chicken drumstick, wheat flour, salt, monosodium glutamate, spices, garlic powder, dried egg whites, nonfat dry milk, soybean oil",
      },
      {
        name: "Extra Crispy Chicken Breast",
        category: "chicken",
        serving_size: 176,
        serving_unit: "g",
        calories: 530,
        total_fat: 35,
        saturated_fat: 6,
        trans_fat: 0,
        cholesterol: 105,
        sodium: 1150,
        total_carbohydrates: 18,
        dietary_fiber: 1,
        total_sugars: 0,
        protein: 35,
        ingredients_text:
          "Chicken breast, wheat flour, water, salt, modified corn starch, monosodium glutamate, spices, garlic powder, soybean oil, leavening (sodium acid pyrophosphate, sodium bicarbonate), dried egg whites, nonfat dry milk",
      },
      {
        name: "Chicken Sandwich",
        category: "sandwich",
        serving_size: 213,
        serving_unit: "g",
        calories: 650,
        total_fat: 35,
        saturated_fat: 7,
        trans_fat: 0,
        cholesterol: 65,
        sodium: 1450,
        total_carbohydrates: 51,
        dietary_fiber: 2,
        total_sugars: 8,
        protein: 30,
        ingredients_text:
          "Breaded chicken fillet (chicken breast, wheat flour, water, salt, spices, soybean oil, monosodium glutamate, leavening), brioche bun, pickles, mayonnaise, butter",
      },
      {
        name: "Popcorn Chicken",
        category: "chicken",
        serving_size: 114,
        serving_unit: "g",
        calories: 380,
        total_fat: 23,
        saturated_fat: 3.5,
        trans_fat: 0,
        cholesterol: 45,
        sodium: 1160,
        total_carbohydrates: 22,
        dietary_fiber: 1,
        total_sugars: 0,
        protein: 20,
        ingredients_text:
          "Chicken breast with rib meat, water, wheat flour, modified corn starch, salt, monosodium glutamate, spices, garlic powder, soybean oil, dried egg whites",
      },
      {
        name: "Mac and Cheese",
        category: "side",
        serving_size: 136,
        serving_unit: "g",
        calories: 170,
        total_fat: 8,
        saturated_fat: 3.5,
        trans_fat: 0,
        cholesterol: 20,
        sodium: 680,
        total_carbohydrates: 18,
        dietary_fiber: 1,
        total_sugars: 3,
        protein: 7,
        ingredients_text:
          "Cooked macaroni (enriched wheat flour, water), cheese sauce (water, cheddar cheese, milk, modified food starch, whey, butter, salt, sodium phosphate, annatto color)",
      },
      {
        name: "Coleslaw",
        category: "side",
        serving_size: 128,
        serving_unit: "g",
        calories: 170,
        total_fat: 10,
        saturated_fat: 1.5,
        trans_fat: 0,
        cholesterol: 15,
        sodium: 180,
        total_carbohydrates: 21,
        dietary_fiber: 2,
        total_sugars: 14,
        protein: 1,
        ingredients_text:
          "Chopped cabbage, carrots, sugar, soybean oil, distilled vinegar, corn syrup, egg yolks, salt, celery seed, mustard, onion powder",
      },
      {
        name: "Mashed Potatoes with Gravy",
        category: "side",
        serving_size: 153,
        serving_unit: "g",
        calories: 120,
        total_fat: 4.5,
        saturated_fat: 1,
        trans_fat: 0,
        cholesterol: 0,
        sodium: 530,
        total_carbohydrates: 18,
        dietary_fiber: 1,
        total_sugars: 0,
        protein: 2,
        ingredients_text:
          "Potato flakes (potatoes, mono and diglycerides, sodium acid pyrophosphate, citric acid), water, whole milk, butter, salt, chicken gravy (water, modified corn starch, chicken fat, salt, seasoning)",
      },
      {
        name: "Biscuit",
        category: "side",
        serving_size: 56,
        serving_unit: "g",
        calories: 180,
        total_fat: 8,
        saturated_fat: 4,
        trans_fat: 0,
        cholesterol: 0,
        sodium: 530,
        total_carbohydrates: 23,
        dietary_fiber: 1,
        total_sugars: 2,
        protein: 3,
        ingredients_text:
          "Enriched wheat flour (flour, niacin, reduced iron, thiamine mononitrate, riboflavin, folic acid), buttermilk, palm oil, sugar, baking powder, salt, soybean oil",
      },
      {
        name: "Chicken Pot Pie",
        category: "entree",
        serving_size: 384,
        serving_unit: "g",
        calories: 720,
        total_fat: 41,
        saturated_fat: 17,
        trans_fat: 0,
        cholesterol: 60,
        sodium: 1750,
        total_carbohydrates: 62,
        dietary_fiber: 3,
        total_sugars: 7,
        protein: 26,
        ingredients_text:
          "Pie crust (enriched wheat flour, palm oil, water, salt), chicken breast, potatoes, peas, carrots, celery, cream sauce (water, modified corn starch, cream, butter, chicken fat, salt, spices)",
      },
      {
        name: "Famous Bowl",
        category: "entree",
        serving_size: 369,
        serving_unit: "g",
        calories: 740,
        total_fat: 34,
        saturated_fat: 8,
        trans_fat: 0,
        cholesterol: 55,
        sodium: 2350,
        total_carbohydrates: 79,
        dietary_fiber: 6,
        total_sugars: 3,
        protein: 27,
        ingredients_text:
          "Mashed potatoes, popcorn chicken (chicken breast, wheat flour, soybean oil, spices), sweet corn, chicken gravy (water, modified corn starch, chicken fat, salt), shredded cheese (cheddar, milk, enzymes, annatto color)",
      },
      {
        name: "Corn on the Cob",
        category: "side",
        serving_size: 162,
        serving_unit: "g",
        calories: 70,
        total_fat: 0.5,
        saturated_fat: 0,
        trans_fat: 0,
        cholesterol: 0,
        sodium: 0,
        total_carbohydrates: 16,
        dietary_fiber: 2,
        total_sugars: 4,
        protein: 2,
        ingredients_text: "Sweet corn, water",
      },
      {
        name: "Green Beans",
        category: "side",
        serving_size: 100,
        serving_unit: "g",
        calories: 25,
        total_fat: 0,
        saturated_fat: 0,
        trans_fat: 0,
        cholesterol: 0,
        sodium: 290,
        total_carbohydrates: 4,
        dietary_fiber: 2,
        total_sugars: 1,
        protein: 1,
        ingredients_text: "Green beans, water, salt, soybean oil, onion, garlic",
      },
      {
        name: "Cole Slaw",
        category: "side",
        serving_size: 128,
        serving_unit: "g",
        calories: 170,
        total_fat: 10,
        saturated_fat: 1.5,
        trans_fat: 0,
        cholesterol: 15,
        sodium: 180,
        total_carbohydrates: 21,
        dietary_fiber: 2,
        total_sugars: 14,
        protein: 1,
        ingredients_text:
          "Chopped cabbage, carrots, sugar, soybean oil, distilled vinegar, corn syrup, egg yolks, salt, celery seed",
      },
    ],
  },

  // ======================== FIVE GUYS ========================
  {
    chain: "Five Guys",
    items: [
      {
        name: "Hamburger",
        category: "burger",
        serving_size: 302,
        serving_unit: "g",
        calories: 700,
        total_fat: 43,
        saturated_fat: 17,
        trans_fat: 1.5,
        cholesterol: 125,
        sodium: 430,
        total_carbohydrates: 39,
        dietary_fiber: 2,
        total_sugars: 8,
        protein: 39,
        ingredients_text:
          "Beef patties (2), sesame seed bun (enriched wheat flour, water, sugar, soybean oil, yeast, salt), lettuce, tomato, onion, pickles, ketchup, mustard",
      },
      {
        name: "Cheeseburger",
        category: "burger",
        serving_size: 336,
        serving_unit: "g",
        calories: 840,
        total_fat: 55,
        saturated_fat: 24,
        trans_fat: 2,
        cholesterol: 165,
        sodium: 1050,
        total_carbohydrates: 40,
        dietary_fiber: 2,
        total_sugars: 9,
        protein: 47,
        ingredients_text:
          "Beef patties (2), American cheese (milk, water, milkfat, sodium citrate, salt, enzymes), sesame seed bun, lettuce, tomato, onion, pickles, ketchup, mustard",
      },
      {
        name: "Little Hamburger",
        category: "burger",
        serving_size: 196,
        serving_unit: "g",
        calories: 480,
        total_fat: 26,
        saturated_fat: 10,
        trans_fat: 1,
        cholesterol: 65,
        sodium: 380,
        total_carbohydrates: 39,
        dietary_fiber: 2,
        total_sugars: 8,
        protein: 23,
        ingredients_text:
          "Beef patty, sesame seed bun (enriched wheat flour, water, sugar, soybean oil, yeast, salt), lettuce, tomato, onion, pickles, ketchup, mustard",
      },
      {
        name: "Little Cheeseburger",
        category: "burger",
        serving_size: 213,
        serving_unit: "g",
        calories: 550,
        total_fat: 32,
        saturated_fat: 15,
        trans_fat: 1,
        cholesterol: 90,
        sodium: 690,
        total_carbohydrates: 40,
        dietary_fiber: 2,
        total_sugars: 8,
        protein: 27,
        ingredients_text:
          "Beef patty, American cheese (milk, water, milkfat, sodium citrate, salt, enzymes), sesame seed bun, lettuce, tomato, onion, pickles, ketchup, mustard",
      },
      {
        name: "Bacon Burger",
        category: "burger",
        serving_size: 319,
        serving_unit: "g",
        calories: 780,
        total_fat: 50,
        saturated_fat: 19,
        trans_fat: 1.5,
        cholesterol: 140,
        sodium: 780,
        total_carbohydrates: 39,
        dietary_fiber: 2,
        total_sugars: 8,
        protein: 44,
        ingredients_text:
          "Beef patties (2), smoked bacon (pork, water, salt, sugar, sodium phosphate, sodium nitrite), sesame seed bun, lettuce, tomato, onion, pickles, ketchup, mustard",
      },
      {
        name: "Bacon Cheese Dog",
        category: "hot dog",
        serving_size: 212,
        serving_unit: "g",
        calories: 695,
        total_fat: 48,
        saturated_fat: 19,
        trans_fat: 0,
        cholesterol: 95,
        sodium: 1380,
        total_carbohydrates: 40,
        dietary_fiber: 2,
        total_sugars: 8,
        protein: 27,
        ingredients_text:
          "Beef hot dog (beef, water, salt, spices, paprika, garlic powder, sodium nitrite), American cheese, smoked bacon, sesame seed bun",
      },
      {
        name: "Veggie Sandwich",
        category: "sandwich",
        serving_size: 283,
        serving_unit: "g",
        calories: 440,
        total_fat: 15,
        saturated_fat: 6,
        trans_fat: 0,
        cholesterol: 25,
        sodium: 1040,
        total_carbohydrates: 60,
        dietary_fiber: 5,
        total_sugars: 12,
        protein: 16,
        ingredients_text:
          "Sesame seed bun (enriched wheat flour, water, sugar, soybean oil, yeast, salt), grilled mushrooms, grilled onions, grilled green peppers, American cheese, lettuce, tomato",
      },
      {
        name: "Regular Fries",
        category: "side",
        serving_size: 411,
        serving_unit: "g",
        calories: 953,
        total_fat: 41,
        saturated_fat: 7,
        trans_fat: 0,
        cholesterol: 0,
        sodium: 962,
        total_carbohydrates: 131,
        dietary_fiber: 13,
        total_sugars: 3,
        protein: 15,
        ingredients_text: "Potatoes, peanut oil, salt",
      },
      {
        name: "Little Fries",
        category: "side",
        serving_size: 227,
        serving_unit: "g",
        calories: 526,
        total_fat: 23,
        saturated_fat: 4,
        trans_fat: 0,
        cholesterol: 0,
        sodium: 531,
        total_carbohydrates: 72,
        dietary_fiber: 7,
        total_sugars: 2,
        protein: 8,
        ingredients_text: "Potatoes, peanut oil, salt",
      },
      {
        name: "Cajun Fries",
        category: "side",
        serving_size: 411,
        serving_unit: "g",
        calories: 953,
        total_fat: 41,
        saturated_fat: 7,
        trans_fat: 0,
        cholesterol: 0,
        sodium: 1456,
        total_carbohydrates: 131,
        dietary_fiber: 13,
        total_sugars: 3,
        protein: 15,
        ingredients_text:
          "Potatoes, peanut oil, cajun seasoning (salt, garlic, paprika, black pepper, onion, cayenne pepper, oregano, thyme)",
      },
      {
        name: "Grilled Cheese",
        category: "sandwich",
        serving_size: 170,
        serving_unit: "g",
        calories: 470,
        total_fat: 26,
        saturated_fat: 12,
        trans_fat: 0.5,
        cholesterol: 55,
        sodium: 715,
        total_carbohydrates: 41,
        dietary_fiber: 2,
        total_sugars: 8,
        protein: 17,
        ingredients_text:
          "Sesame seed bun (enriched wheat flour, water, sugar, soybean oil, yeast, salt), American cheese (milk, water, milkfat, sodium citrate, salt, enzymes), butter",
      },
      {
        name: "BLT",
        category: "sandwich",
        serving_size: 198,
        serving_unit: "g",
        calories: 430,
        total_fat: 22,
        saturated_fat: 8,
        trans_fat: 0,
        cholesterol: 35,
        sodium: 750,
        total_carbohydrates: 39,
        dietary_fiber: 2,
        total_sugars: 9,
        protein: 17,
        ingredients_text:
          "Sesame seed bun, smoked bacon (pork, water, salt, sugar, sodium phosphate, sodium nitrite), lettuce, tomato, mayonnaise",
      },
      {
        name: "Chocolate Shake",
        category: "beverage",
        serving_size: 591,
        serving_unit: "ml",
        calories: 820,
        total_fat: 48,
        saturated_fat: 24,
        trans_fat: 1,
        cholesterol: 150,
        sodium: 420,
        total_carbohydrates: 83,
        dietary_fiber: 3,
        total_sugars: 74,
        protein: 18,
        ingredients_text:
          "Milk, cream, sugar, cocoa, corn syrup, whey, nonfat milk solids, vanilla extract, mono and diglycerides, guar gum, carrageenan",
      },
      {
        name: "Vanilla Shake",
        category: "beverage",
        serving_size: 591,
        serving_unit: "ml",
        calories: 790,
        total_fat: 47,
        saturated_fat: 23,
        trans_fat: 1,
        cholesterol: 150,
        sodium: 380,
        total_carbohydrates: 78,
        dietary_fiber: 0,
        total_sugars: 70,
        protein: 18,
        ingredients_text:
          "Milk, cream, sugar, corn syrup, whey, nonfat milk solids, vanilla extract, mono and diglycerides, guar gum, carrageenan",
      },
      {
        name: "Peanut Butter Shake",
        category: "beverage",
        serving_size: 591,
        serving_unit: "ml",
        calories: 880,
        total_fat: 54,
        saturated_fat: 24,
        trans_fat: 1,
        cholesterol: 145,
        sodium: 510,
        total_carbohydrates: 79,
        dietary_fiber: 3,
        total_sugars: 68,
        protein: 24,
        ingredients_text:
          "Milk, cream, sugar, peanut butter (peanuts, salt, hydrogenated vegetable oil), corn syrup, whey, nonfat milk solids, vanilla extract, mono and diglycerides, guar gum",
      },
    ],
  },

  // ======================== IN-N-OUT ========================
  {
    chain: "In-N-Out",
    items: [
      {
        name: "Double-Double",
        category: "burger",
        serving_size: 330,
        serving_unit: "g",
        calories: 670,
        total_fat: 41,
        saturated_fat: 18,
        trans_fat: 1,
        cholesterol: 120,
        sodium: 1440,
        total_carbohydrates: 39,
        dietary_fiber: 3,
        total_sugars: 10,
        protein: 37,
        ingredients_text:
          "Beef patties (2), American cheese (2 slices), freshly baked bun (flour, water, sugar, yeast, soybean oil, salt), hand-leafed lettuce, tomato, spread (soybean oil, egg yolks, vinegar, sugar, mustard, salt), onion",
      },
      {
        name: "Cheeseburger",
        category: "burger",
        serving_size: 268,
        serving_unit: "g",
        calories: 480,
        total_fat: 27,
        saturated_fat: 10,
        trans_fat: 0.5,
        cholesterol: 60,
        sodium: 1000,
        total_carbohydrates: 39,
        dietary_fiber: 3,
        total_sugars: 10,
        protein: 22,
        ingredients_text:
          "Beef patty, American cheese, freshly baked bun (flour, water, sugar, yeast, soybean oil, salt), hand-leafed lettuce, tomato, spread, onion",
      },
      {
        name: "Hamburger",
        category: "burger",
        serving_size: 243,
        serving_unit: "g",
        calories: 390,
        total_fat: 19,
        saturated_fat: 5,
        trans_fat: 0,
        cholesterol: 40,
        sodium: 650,
        total_carbohydrates: 39,
        dietary_fiber: 3,
        total_sugars: 10,
        protein: 16,
        ingredients_text:
          "Beef patty, freshly baked bun (flour, water, sugar, yeast, soybean oil, salt), hand-leafed lettuce, tomato, spread, onion",
      },
      {
        name: "Protein Style Burger",
        category: "burger",
        serving_size: 300,
        serving_unit: "g",
        calories: 330,
        total_fat: 25,
        saturated_fat: 9,
        trans_fat: 0,
        cholesterol: 60,
        sodium: 720,
        total_carbohydrates: 11,
        dietary_fiber: 3,
        total_sugars: 7,
        protein: 18,
        ingredients_text:
          "Beef patty, American cheese, hand-leafed lettuce wrap, tomato, spread (soybean oil, egg yolks, vinegar, sugar, mustard, salt), onion",
      },
      {
        name: "Animal Style Fries",
        category: "side",
        serving_size: 311,
        serving_unit: "g",
        calories: 750,
        total_fat: 52,
        saturated_fat: 16,
        trans_fat: 0.5,
        cholesterol: 40,
        sodium: 1090,
        total_carbohydrates: 56,
        dietary_fiber: 3,
        total_sugars: 3,
        protein: 16,
        ingredients_text:
          "Potatoes (cut fresh daily, cooked in sunflower oil), American cheese, spread (soybean oil, egg yolks, vinegar, sugar, mustard, salt), grilled onions",
      },
      {
        name: "French Fries",
        category: "side",
        serving_size: 198,
        serving_unit: "g",
        calories: 395,
        total_fat: 18,
        saturated_fat: 5,
        trans_fat: 0,
        cholesterol: 0,
        sodium: 245,
        total_carbohydrates: 54,
        dietary_fiber: 2,
        total_sugars: 0,
        protein: 7,
        ingredients_text: "Potatoes (cut fresh daily), sunflower oil, salt",
      },
      {
        name: "Chocolate Shake",
        category: "beverage",
        serving_size: 425,
        serving_unit: "ml",
        calories: 590,
        total_fat: 29,
        saturated_fat: 19,
        trans_fat: 1,
        cholesterol: 95,
        sodium: 350,
        total_carbohydrates: 72,
        dietary_fiber: 1,
        total_sugars: 62,
        protein: 9,
        ingredients_text:
          "Real ice cream (milk, cream, sugar, nonfat milk solids, vanilla extract), cocoa, milk",
      },
      {
        name: "Vanilla Shake",
        category: "beverage",
        serving_size: 425,
        serving_unit: "ml",
        calories: 580,
        total_fat: 31,
        saturated_fat: 20,
        trans_fat: 1,
        cholesterol: 100,
        sodium: 350,
        total_carbohydrates: 67,
        dietary_fiber: 0,
        total_sugars: 57,
        protein: 9,
        ingredients_text:
          "Real ice cream (milk, cream, sugar, nonfat milk solids, vanilla extract), milk",
      },
      {
        name: "Strawberry Shake",
        category: "beverage",
        serving_size: 425,
        serving_unit: "ml",
        calories: 590,
        total_fat: 27,
        saturated_fat: 18,
        trans_fat: 1,
        cholesterol: 85,
        sodium: 280,
        total_carbohydrates: 78,
        dietary_fiber: 0,
        total_sugars: 72,
        protein: 8,
        ingredients_text:
          "Real ice cream (milk, cream, sugar, nonfat milk solids, vanilla extract), strawberry puree, milk",
      },
      {
        name: "Grilled Cheese",
        category: "sandwich",
        serving_size: 153,
        serving_unit: "g",
        calories: 380,
        total_fat: 18,
        saturated_fat: 9,
        trans_fat: 0.5,
        cholesterol: 30,
        sodium: 1150,
        total_carbohydrates: 39,
        dietary_fiber: 2,
        total_sugars: 10,
        protein: 16,
        ingredients_text:
          "Freshly baked bun (flour, water, sugar, yeast, soybean oil, salt), American cheese (2 slices), hand-leafed lettuce, tomato, spread",
      },
      {
        name: "3x3",
        category: "burger",
        serving_size: 397,
        serving_unit: "g",
        calories: 860,
        total_fat: 56,
        saturated_fat: 25,
        trans_fat: 1.5,
        cholesterol: 175,
        sodium: 1880,
        total_carbohydrates: 39,
        dietary_fiber: 3,
        total_sugars: 10,
        protein: 52,
        ingredients_text:
          "Beef patties (3), American cheese (3 slices), freshly baked bun, hand-leafed lettuce, tomato, spread, onion",
      },
      {
        name: "4x4",
        category: "burger",
        serving_size: 462,
        serving_unit: "g",
        calories: 1050,
        total_fat: 71,
        saturated_fat: 32,
        trans_fat: 2,
        cholesterol: 230,
        sodium: 2320,
        total_carbohydrates: 40,
        dietary_fiber: 3,
        total_sugars: 10,
        protein: 68,
        ingredients_text:
          "Beef patties (4), American cheese (4 slices), freshly baked bun, hand-leafed lettuce, tomato, spread, onion",
      },
      {
        name: "Neapolitan Shake",
        category: "beverage",
        serving_size: 425,
        serving_unit: "ml",
        calories: 590,
        total_fat: 28,
        saturated_fat: 19,
        trans_fat: 1,
        cholesterol: 90,
        sodium: 320,
        total_carbohydrates: 75,
        dietary_fiber: 0,
        total_sugars: 64,
        protein: 9,
        ingredients_text:
          "Real ice cream (milk, cream, sugar, nonfat milk solids, vanilla extract), cocoa, strawberry puree, milk",
      },
      {
        name: "Root Beer Float",
        category: "beverage",
        serving_size: 473,
        serving_unit: "ml",
        calories: 290,
        total_fat: 10,
        saturated_fat: 7,
        trans_fat: 0,
        cholesterol: 40,
        sodium: 110,
        total_carbohydrates: 49,
        dietary_fiber: 0,
        total_sugars: 46,
        protein: 3,
        ingredients_text:
          "Root beer (carbonated water, sugar, caramel color, natural and artificial flavors), vanilla ice cream (milk, cream, sugar, nonfat milk solids, vanilla extract)",
      },
      {
        name: "Lemonade",
        category: "beverage",
        serving_size: 473,
        serving_unit: "ml",
        calories: 180,
        total_fat: 0,
        saturated_fat: 0,
        trans_fat: 0,
        cholesterol: 0,
        sodium: 25,
        total_carbohydrates: 47,
        dietary_fiber: 0,
        total_sugars: 42,
        protein: 0,
        ingredients_text: "Water, lemon juice, sugar",
      },
    ],
  },

  // ======================== SHAKE SHACK ========================
  {
    chain: "Shake Shack",
    items: [
      {
        name: "ShackBurger",
        category: "burger",
        serving_size: 256,
        serving_unit: "g",
        calories: 530,
        total_fat: 33,
        saturated_fat: 13,
        trans_fat: 1,
        cholesterol: 95,
        sodium: 1280,
        total_carbohydrates: 28,
        dietary_fiber: 1,
        total_sugars: 7,
        protein: 28,
        ingredients_text:
          "Angus beef patty, Martin's potato roll (enriched wheat flour, water, sugar, soybean oil, yeast, potato flour, salt, milk), American cheese, lettuce, tomato, ShackSauce (mayonnaise, mustard, ketchup, spices, vinegar)",
      },
      {
        name: "SmokeShack",
        category: "burger",
        serving_size: 286,
        serving_unit: "g",
        calories: 610,
        total_fat: 39,
        saturated_fat: 15,
        trans_fat: 1,
        cholesterol: 110,
        sodium: 1510,
        total_carbohydrates: 28,
        dietary_fiber: 1,
        total_sugars: 7,
        protein: 35,
        ingredients_text:
          "Angus beef patty, Martin's potato roll, American cheese, applewood-smoked bacon (pork, water, salt, sugar, sodium phosphate, sodium nitrite), chopped cherry peppers, ShackSauce",
      },
      {
        name: "Shack-cago Dog",
        category: "hot dog",
        serving_size: 199,
        serving_unit: "g",
        calories: 440,
        total_fat: 27,
        saturated_fat: 11,
        trans_fat: 0,
        cholesterol: 55,
        sodium: 1630,
        total_carbohydrates: 32,
        dietary_fiber: 2,
        total_sugars: 5,
        protein: 16,
        ingredients_text:
          "Vienna beef hot dog (beef, water, salt, spices, paprika, garlic powder, sodium nitrite), Martin's potato roll, relish, onion, cucumber, pickle, sport peppers, tomato, celery salt, mustard",
      },
      {
        name: "Chicken Shack",
        category: "sandwich",
        serving_size: 263,
        serving_unit: "g",
        calories: 580,
        total_fat: 27,
        saturated_fat: 6,
        trans_fat: 0,
        cholesterol: 100,
        sodium: 1260,
        total_carbohydrates: 52,
        dietary_fiber: 3,
        total_sugars: 8,
        protein: 33,
        ingredients_text:
          "Breaded chicken breast (chicken, wheat flour, water, salt, spices, soybean oil, leavening), Martin's potato roll, lettuce, pickles, buttermilk herb mayo",
      },
      {
        name: "Shroom Burger",
        category: "burger",
        serving_size: 272,
        serving_unit: "g",
        calories: 580,
        total_fat: 34,
        saturated_fat: 14,
        trans_fat: 0,
        cholesterol: 55,
        sodium: 940,
        total_carbohydrates: 46,
        dietary_fiber: 3,
        total_sugars: 9,
        protein: 20,
        ingredients_text:
          "Crispy fried portobello mushroom, muenster cheese, cheddar cheese, Martin's potato roll, lettuce, tomato, ShackSauce",
      },
      {
        name: "Fries",
        category: "side",
        serving_size: 156,
        serving_unit: "g",
        calories: 420,
        total_fat: 19,
        saturated_fat: 3,
        trans_fat: 0,
        cholesterol: 0,
        sodium: 840,
        total_carbohydrates: 56,
        dietary_fiber: 5,
        total_sugars: 0,
        protein: 5,
        ingredients_text:
          "Potatoes, vegetable oil (canola, soybean), salt",
      },
      {
        name: "Cheese Fries",
        category: "side",
        serving_size: 184,
        serving_unit: "g",
        calories: 580,
        total_fat: 32,
        saturated_fat: 10,
        trans_fat: 0,
        cholesterol: 30,
        sodium: 1270,
        total_carbohydrates: 56,
        dietary_fiber: 5,
        total_sugars: 1,
        protein: 13,
        ingredients_text:
          "Potatoes, vegetable oil (canola, soybean), cheese sauce (cheddar cheese, milk, water, modified food starch, salt, sodium phosphate), salt",
      },
      {
        name: "Chocolate Shake",
        category: "beverage",
        serving_size: 454,
        serving_unit: "ml",
        calories: 640,
        total_fat: 35,
        saturated_fat: 22,
        trans_fat: 1,
        cholesterol: 105,
        sodium: 330,
        total_carbohydrates: 72,
        dietary_fiber: 2,
        total_sugars: 63,
        protein: 12,
        ingredients_text:
          "Vanilla frozen custard (milk, cream, sugar, egg yolks, vanilla), chocolate sauce (water, sugar, cocoa, corn syrup), milk",
      },
      {
        name: "Vanilla Shake",
        category: "beverage",
        serving_size: 454,
        serving_unit: "ml",
        calories: 610,
        total_fat: 34,
        saturated_fat: 22,
        trans_fat: 1,
        cholesterol: 110,
        sodium: 290,
        total_carbohydrates: 65,
        dietary_fiber: 0,
        total_sugars: 58,
        protein: 12,
        ingredients_text:
          "Vanilla frozen custard (milk, cream, sugar, egg yolks, vanilla extract), milk",
      },
      {
        name: "Concrete Custard",
        category: "dessert",
        serving_size: 227,
        serving_unit: "g",
        calories: 420,
        total_fat: 24,
        saturated_fat: 14,
        trans_fat: 0.5,
        cholesterol: 115,
        sodium: 170,
        total_carbohydrates: 44,
        dietary_fiber: 0,
        total_sugars: 39,
        protein: 8,
        ingredients_text:
          "Frozen custard (milk, cream, sugar, egg yolks, vanilla), mix-in toppings",
      },
      {
        name: "Chicken Bites",
        category: "chicken",
        serving_size: 170,
        serving_unit: "g",
        calories: 480,
        total_fat: 26,
        saturated_fat: 5,
        trans_fat: 0,
        cholesterol: 85,
        sodium: 1120,
        total_carbohydrates: 30,
        dietary_fiber: 2,
        total_sugars: 1,
        protein: 32,
        ingredients_text:
          "Chicken breast pieces, wheat flour, water, salt, spices, soybean oil, leavening (sodium acid pyrophosphate, sodium bicarbonate), garlic powder",
      },
      {
        name: "Hot Dog",
        category: "hot dog",
        serving_size: 165,
        serving_unit: "g",
        calories: 370,
        total_fat: 24,
        saturated_fat: 10,
        trans_fat: 0,
        cholesterol: 45,
        sodium: 1060,
        total_carbohydrates: 24,
        dietary_fiber: 1,
        total_sugars: 5,
        protein: 14,
        ingredients_text:
          "Vienna beef hot dog (beef, water, salt, spices, paprika, garlic powder, sodium nitrite), Martin's potato roll",
      },
      {
        name: "Lemonade",
        category: "beverage",
        serving_size: 473,
        serving_unit: "ml",
        calories: 170,
        total_fat: 0,
        saturated_fat: 0,
        trans_fat: 0,
        cholesterol: 0,
        sodium: 10,
        total_carbohydrates: 44,
        dietary_fiber: 0,
        total_sugars: 40,
        protein: 0,
        ingredients_text: "Water, cane sugar, lemon juice",
      },
      {
        name: "Iced Tea",
        category: "beverage",
        serving_size: 473,
        serving_unit: "ml",
        calories: 0,
        total_fat: 0,
        saturated_fat: 0,
        trans_fat: 0,
        cholesterol: 0,
        sodium: 0,
        total_carbohydrates: 0,
        dietary_fiber: 0,
        total_sugars: 0,
        protein: 0,
        ingredients_text: "Brewed tea, water",
      },
      {
        name: "Chocolate Chip Cookie",
        category: "dessert",
        serving_size: 85,
        serving_unit: "g",
        calories: 390,
        total_fat: 19,
        saturated_fat: 11,
        trans_fat: 0,
        cholesterol: 50,
        sodium: 310,
        total_carbohydrates: 52,
        dietary_fiber: 1,
        total_sugars: 33,
        protein: 4,
        ingredients_text:
          "Enriched wheat flour, butter, sugar, brown sugar, eggs, chocolate chips (sugar, chocolate liquor, cocoa butter, soy lecithin, vanilla), baking soda, salt, vanilla extract",
      },
    ],
  },

  // ======================== SONIC ========================
  {
    chain: "Sonic",
    items: [
      {
        name: "Classic Burger",
        category: "burger",
        serving_size: 249,
        serving_unit: "g",
        calories: 570,
        total_fat: 32,
        saturated_fat: 11,
        trans_fat: 1,
        cholesterol: 70,
        sodium: 880,
        total_carbohydrates: 44,
        dietary_fiber: 2,
        total_sugars: 10,
        protein: 26,
        ingredients_text:
          "Beef patty, sesame seed bun (enriched wheat flour, water, sugar, soybean oil, yeast, salt), lettuce, tomato, onion, pickles, ketchup, mustard, mayonnaise",
      },
      {
        name: "SuperSonic Bacon Double Cheeseburger",
        category: "burger",
        serving_size: 381,
        serving_unit: "g",
        calories: 980,
        total_fat: 64,
        saturated_fat: 25,
        trans_fat: 2.5,
        cholesterol: 180,
        sodium: 1520,
        total_carbohydrates: 44,
        dietary_fiber: 2,
        total_sugars: 10,
        protein: 56,
        ingredients_text:
          "Beef patties (2), American cheese (2 slices), bacon (pork, water, salt, sugar, sodium phosphate, sodium nitrite), sesame seed bun, lettuce, tomato, onion, pickles, ketchup, mustard, mayonnaise",
      },
      {
        name: "Popcorn Chicken",
        category: "chicken",
        serving_size: 142,
        serving_unit: "g",
        calories: 380,
        total_fat: 21,
        saturated_fat: 3.5,
        trans_fat: 0,
        cholesterol: 45,
        sodium: 1120,
        total_carbohydrates: 27,
        dietary_fiber: 1,
        total_sugars: 1,
        protein: 19,
        ingredients_text:
          "Chicken breast with rib meat, water, wheat flour, modified corn starch, salt, spices, garlic powder, soybean oil, leavening, dried egg whites",
      },
      {
        name: "Corn Dog",
        category: "hot dog",
        serving_size: 106,
        serving_unit: "g",
        calories: 230,
        total_fat: 13,
        saturated_fat: 3,
        trans_fat: 0,
        cholesterol: 25,
        sodium: 580,
        total_carbohydrates: 23,
        dietary_fiber: 1,
        total_sugars: 5,
        protein: 6,
        ingredients_text:
          "Hot dog (beef, pork, water, salt, spices, sodium nitrite), corn batter (enriched wheat flour, corn meal, sugar, water, soybean oil, baking powder, salt, eggs)",
      },
      {
        name: "Chili Cheese Coney",
        category: "hot dog",
        serving_size: 195,
        serving_unit: "g",
        calories: 380,
        total_fat: 23,
        saturated_fat: 10,
        trans_fat: 0.5,
        cholesterol: 55,
        sodium: 1180,
        total_carbohydrates: 27,
        dietary_fiber: 2,
        total_sugars: 5,
        protein: 16,
        ingredients_text:
          "Beef hot dog (beef, water, salt, spices, paprika, sodium nitrite), bun (enriched wheat flour, water, sugar, yeast, salt), chili (beef, water, tomato paste, spices, modified corn starch), shredded cheddar cheese, onion",
      },
      {
        name: "Tater Tots",
        category: "side",
        serving_size: 142,
        serving_unit: "g",
        calories: 330,
        total_fat: 19,
        saturated_fat: 3,
        trans_fat: 0,
        cholesterol: 0,
        sodium: 760,
        total_carbohydrates: 36,
        dietary_fiber: 3,
        total_sugars: 0,
        protein: 3,
        ingredients_text:
          "Potatoes, vegetable oil (soybean, canola), salt, modified food starch, dehydrated onion, dextrose",
      },
      {
        name: "Onion Rings",
        category: "side",
        serving_size: 128,
        serving_unit: "g",
        calories: 440,
        total_fat: 26,
        saturated_fat: 4,
        trans_fat: 0,
        cholesterol: 0,
        sodium: 430,
        total_carbohydrates: 47,
        dietary_fiber: 2,
        total_sugars: 5,
        protein: 5,
        ingredients_text:
          "Onion, bleached wheat flour, water, modified corn starch, salt, soybean oil, dextrose, leavening (sodium acid pyrophosphate, sodium bicarbonate)",
      },
      {
        name: "Mozzarella Sticks",
        category: "side",
        serving_size: 113,
        serving_unit: "g",
        calories: 380,
        total_fat: 21,
        saturated_fat: 8,
        trans_fat: 0,
        cholesterol: 35,
        sodium: 920,
        total_carbohydrates: 32,
        dietary_fiber: 1,
        total_sugars: 2,
        protein: 15,
        ingredients_text:
          "Mozzarella cheese (pasteurized milk, cultures, salt, enzymes), wheat flour, water, modified corn starch, salt, soybean oil, leavening",
      },
      {
        name: "Vanilla Shake",
        category: "beverage",
        serving_size: 411,
        serving_unit: "ml",
        calories: 540,
        total_fat: 18,
        saturated_fat: 12,
        trans_fat: 0.5,
        cholesterol: 60,
        sodium: 310,
        total_carbohydrates: 84,
        dietary_fiber: 0,
        total_sugars: 72,
        protein: 10,
        ingredients_text:
          "Vanilla ice cream (milk, cream, sugar, nonfat milk solids, corn syrup, vanilla extract), milk, whipped topping",
      },
      {
        name: "Oreo Shake",
        category: "beverage",
        serving_size: 411,
        serving_unit: "ml",
        calories: 620,
        total_fat: 22,
        saturated_fat: 13,
        trans_fat: 0.5,
        cholesterol: 55,
        sodium: 480,
        total_carbohydrates: 96,
        dietary_fiber: 1,
        total_sugars: 76,
        protein: 11,
        ingredients_text:
          "Vanilla ice cream (milk, cream, sugar, nonfat milk solids, corn syrup, vanilla extract), Oreo cookie pieces (wheat flour, sugar, palm oil, cocoa, corn syrup, salt, soy lecithin), milk, whipped topping",
      },
      {
        name: "Cherry Limeade",
        category: "beverage",
        serving_size: 591,
        serving_unit: "ml",
        calories: 170,
        total_fat: 0,
        saturated_fat: 0,
        trans_fat: 0,
        cholesterol: 0,
        sodium: 35,
        total_carbohydrates: 46,
        dietary_fiber: 0,
        total_sugars: 45,
        protein: 0,
        ingredients_text:
          "Water, sugar, lime juice concentrate, cherry syrup (high fructose corn syrup, water, citric acid, natural flavors, red 40)",
      },
      {
        name: "Slush",
        category: "beverage",
        serving_size: 591,
        serving_unit: "ml",
        calories: 200,
        total_fat: 0,
        saturated_fat: 0,
        trans_fat: 0,
        cholesterol: 0,
        sodium: 15,
        total_carbohydrates: 52,
        dietary_fiber: 0,
        total_sugars: 50,
        protein: 0,
        ingredients_text:
          "Water, sugar, high fructose corn syrup, citric acid, natural and artificial flavors, sodium benzoate",
      },
      {
        name: "Breakfast Burrito",
        category: "breakfast",
        serving_size: 218,
        serving_unit: "g",
        calories: 510,
        total_fat: 28,
        saturated_fat: 10,
        trans_fat: 0,
        cholesterol: 230,
        sodium: 1140,
        total_carbohydrates: 39,
        dietary_fiber: 2,
        total_sugars: 3,
        protein: 25,
        ingredients_text:
          "Flour tortilla (enriched wheat flour, water, vegetable shortening, salt, baking powder), scrambled eggs, sausage crumbles (pork, water, salt, spices, sugar), cheddar cheese, tomato, onion, jalapeno",
      },
      {
        name: "French Toast Sticks",
        category: "breakfast",
        serving_size: 113,
        serving_unit: "g",
        calories: 390,
        total_fat: 16,
        saturated_fat: 3,
        trans_fat: 0,
        cholesterol: 30,
        sodium: 510,
        total_carbohydrates: 54,
        dietary_fiber: 2,
        total_sugars: 14,
        protein: 7,
        ingredients_text:
          "Enriched wheat flour bread (wheat flour, water, sugar, soybean oil, yeast, salt, eggs, milk), egg batter, cinnamon sugar coating, soybean oil",
      },
      {
        name: "Jr Burger",
        category: "burger",
        serving_size: 136,
        serving_unit: "g",
        calories: 330,
        total_fat: 17,
        saturated_fat: 6,
        trans_fat: 0.5,
        cholesterol: 40,
        sodium: 530,
        total_carbohydrates: 29,
        dietary_fiber: 1,
        total_sugars: 6,
        protein: 14,
        ingredients_text:
          "Beef patty, sesame seed bun (enriched wheat flour, water, sugar, soybean oil, yeast, salt), lettuce, tomato, onion, pickles, ketchup, mustard",
      },
    ],
  },

  // ======================== JACK IN THE BOX ========================
  {
    chain: "Jack in the Box",
    items: [
      {
        name: "Jumbo Jack",
        category: "burger",
        serving_size: 261,
        serving_unit: "g",
        calories: 540,
        total_fat: 30,
        saturated_fat: 10,
        trans_fat: 1,
        cholesterol: 60,
        sodium: 870,
        total_carbohydrates: 43,
        dietary_fiber: 2,
        total_sugars: 9,
        protein: 24,
        ingredients_text:
          "Beef patty, sesame seed bun (enriched wheat flour, water, sugar, soybean oil, yeast, salt), lettuce, tomato, onion, pickles, ketchup, mayonnaise, mustard",
      },
      {
        name: "Sourdough Jack",
        category: "burger",
        serving_size: 286,
        serving_unit: "g",
        calories: 710,
        total_fat: 45,
        saturated_fat: 16,
        trans_fat: 1.5,
        cholesterol: 105,
        sodium: 1180,
        total_carbohydrates: 38,
        dietary_fiber: 2,
        total_sugars: 6,
        protein: 35,
        ingredients_text:
          "Beef patty, sourdough bread (wheat flour, water, salt, yeast, malted barley flour), Swiss cheese, bacon (pork, water, salt, sugar, sodium phosphate, sodium nitrite), tomato, ketchup, mayonnaise",
      },
      {
        name: "Ultimate Cheeseburger",
        category: "burger",
        serving_size: 323,
        serving_unit: "g",
        calories: 910,
        total_fat: 59,
        saturated_fat: 24,
        trans_fat: 2.5,
        cholesterol: 165,
        sodium: 1520,
        total_carbohydrates: 44,
        dietary_fiber: 2,
        total_sugars: 9,
        protein: 50,
        ingredients_text:
          "Beef patties (2), American cheese (2 slices), Swiss cheese, sesame seed bun, lettuce, tomato, onion, pickles, ketchup, mayonnaise, mustard",
      },
      {
        name: "Chicken Sandwich",
        category: "sandwich",
        serving_size: 236,
        serving_unit: "g",
        calories: 610,
        total_fat: 32,
        saturated_fat: 6,
        trans_fat: 0,
        cholesterol: 55,
        sodium: 1250,
        total_carbohydrates: 53,
        dietary_fiber: 3,
        total_sugars: 8,
        protein: 27,
        ingredients_text:
          "Breaded chicken fillet (chicken breast, wheat flour, water, salt, spices, soybean oil, leavening), bun, lettuce, mayonnaise",
      },
      {
        name: "Tacos 2pc",
        category: "snack",
        serving_size: 138,
        serving_unit: "g",
        calories: 340,
        total_fat: 20,
        saturated_fat: 5,
        trans_fat: 0,
        cholesterol: 25,
        sodium: 660,
        total_carbohydrates: 30,
        dietary_fiber: 4,
        total_sugars: 2,
        protein: 12,
        ingredients_text:
          "Corn tortilla (corn, water, lime), seasoned beef (beef, water, textured vegetable protein, seasoning, salt, spices), American cheese, lettuce, taco sauce",
      },
      {
        name: "Egg Rolls 3pc",
        category: "snack",
        serving_size: 170,
        serving_unit: "g",
        calories: 400,
        total_fat: 20,
        saturated_fat: 5,
        trans_fat: 0,
        cholesterol: 20,
        sodium: 810,
        total_carbohydrates: 44,
        dietary_fiber: 3,
        total_sugars: 3,
        protein: 12,
        ingredients_text:
          "Wheat flour wrapper (wheat flour, water, salt), pork, cabbage, carrots, celery, green onion, soy sauce, sesame oil, garlic, ginger, soybean oil",
      },
      {
        name: "Curly Fries",
        category: "side",
        serving_size: 125,
        serving_unit: "g",
        calories: 310,
        total_fat: 15,
        saturated_fat: 2.5,
        trans_fat: 0,
        cholesterol: 0,
        sodium: 590,
        total_carbohydrates: 40,
        dietary_fiber: 3,
        total_sugars: 0,
        protein: 4,
        ingredients_text:
          "Potatoes, vegetable oil (canola, soybean, cottonseed, sunflower), enriched wheat flour, salt, corn starch, onion powder, garlic powder, spices, dextrose",
      },
      {
        name: "Onion Rings",
        category: "side",
        serving_size: 120,
        serving_unit: "g",
        calories: 380,
        total_fat: 21,
        saturated_fat: 4,
        trans_fat: 0,
        cholesterol: 0,
        sodium: 560,
        total_carbohydrates: 44,
        dietary_fiber: 2,
        total_sugars: 5,
        protein: 5,
        ingredients_text:
          "Onion, bleached wheat flour, water, modified corn starch, salt, soybean oil, dextrose, leavening (sodium acid pyrophosphate, sodium bicarbonate), garlic powder",
      },
      {
        name: "Chicken Nuggets 10pc",
        category: "chicken",
        serving_size: 156,
        serving_unit: "g",
        calories: 470,
        total_fat: 27,
        saturated_fat: 5,
        trans_fat: 0,
        cholesterol: 65,
        sodium: 960,
        total_carbohydrates: 30,
        dietary_fiber: 2,
        total_sugars: 0,
        protein: 24,
        ingredients_text:
          "Chicken breast with rib meat, water, wheat flour, modified corn starch, salt, spices, garlic powder, soybean oil, leavening, dried egg whites",
      },
      {
        name: "Jr Jack",
        category: "burger",
        serving_size: 174,
        serving_unit: "g",
        calories: 400,
        total_fat: 22,
        saturated_fat: 7,
        trans_fat: 0.5,
        cholesterol: 40,
        sodium: 670,
        total_carbohydrates: 33,
        dietary_fiber: 1,
        total_sugars: 7,
        protein: 17,
        ingredients_text:
          "Beef patty, sesame seed bun, American cheese, lettuce, tomato, onion, pickles, ketchup, mustard, mayonnaise",
      },
      {
        name: "Breakfast Jack",
        category: "breakfast",
        serving_size: 131,
        serving_unit: "g",
        calories: 350,
        total_fat: 18,
        saturated_fat: 7,
        trans_fat: 0,
        cholesterol: 215,
        sodium: 760,
        total_carbohydrates: 30,
        dietary_fiber: 1,
        total_sugars: 4,
        protein: 17,
        ingredients_text:
          "Bun (enriched wheat flour, water, sugar, yeast, salt), egg, ham (cured with water, salt, sugar, sodium phosphate, sodium nitrite), American cheese",
      },
      {
        name: "Mini Pancakes",
        category: "breakfast",
        serving_size: 113,
        serving_unit: "g",
        calories: 310,
        total_fat: 11,
        saturated_fat: 2.5,
        trans_fat: 0,
        cholesterol: 25,
        sodium: 550,
        total_carbohydrates: 47,
        dietary_fiber: 1,
        total_sugars: 13,
        protein: 6,
        ingredients_text:
          "Enriched wheat flour, water, sugar, soybean oil, eggs, nonfat dry milk, baking powder, salt, butter flavor, maple syrup (corn syrup, sugar, water, natural flavor, caramel color)",
      },
      {
        name: "Churros 5pc",
        category: "dessert",
        serving_size: 127,
        serving_unit: "g",
        calories: 390,
        total_fat: 17,
        saturated_fat: 4,
        trans_fat: 0,
        cholesterol: 10,
        sodium: 360,
        total_carbohydrates: 55,
        dietary_fiber: 1,
        total_sugars: 18,
        protein: 4,
        ingredients_text:
          "Enriched wheat flour, water, soybean oil, sugar, salt, cinnamon sugar coating (sugar, cinnamon), leavening (sodium acid pyrophosphate, sodium bicarbonate)",
      },
      {
        name: "Oreo Shake",
        category: "beverage",
        serving_size: 473,
        serving_unit: "ml",
        calories: 710,
        total_fat: 32,
        saturated_fat: 20,
        trans_fat: 1,
        cholesterol: 85,
        sodium: 440,
        total_carbohydrates: 94,
        dietary_fiber: 1,
        total_sugars: 78,
        protein: 13,
        ingredients_text:
          "Vanilla ice cream (milk, cream, sugar, corn syrup, whey, nonfat milk solids, vanilla), Oreo cookie pieces (wheat flour, sugar, palm oil, cocoa, salt, soy lecithin), milk, whipped topping",
      },
      {
        name: "Chocolate Shake",
        category: "beverage",
        serving_size: 473,
        serving_unit: "ml",
        calories: 670,
        total_fat: 30,
        saturated_fat: 19,
        trans_fat: 1,
        cholesterol: 80,
        sodium: 370,
        total_carbohydrates: 88,
        dietary_fiber: 2,
        total_sugars: 74,
        protein: 13,
        ingredients_text:
          "Vanilla ice cream (milk, cream, sugar, corn syrup, whey, nonfat milk solids, vanilla), chocolate syrup (water, sugar, cocoa, corn syrup), milk, whipped topping",
      },
    ],
  },

  // ======================== WHATABURGER ========================
  {
    chain: "Whataburger",
    items: [
      {
        name: "Whataburger",
        category: "burger",
        serving_size: 316,
        serving_unit: "g",
        calories: 590,
        total_fat: 25,
        saturated_fat: 9,
        trans_fat: 1,
        cholesterol: 70,
        sodium: 1220,
        total_carbohydrates: 62,
        dietary_fiber: 2,
        total_sugars: 12,
        protein: 27,
        ingredients_text:
          "Beef patty, toasted five-inch bun (enriched wheat flour, water, sugar, soybean oil, yeast, salt), mustard, lettuce, tomato, dill pickles, onion",
      },
      {
        name: "Double Meat Whataburger",
        category: "burger",
        serving_size: 427,
        serving_unit: "g",
        calories: 830,
        total_fat: 42,
        saturated_fat: 16,
        trans_fat: 2,
        cholesterol: 145,
        sodium: 1410,
        total_carbohydrates: 62,
        dietary_fiber: 2,
        total_sugars: 12,
        protein: 47,
        ingredients_text:
          "Beef patties (2), toasted five-inch bun (enriched wheat flour, water, sugar, soybean oil, yeast, salt), mustard, lettuce, tomato, dill pickles, onion",
      },
      {
        name: "Honey BBQ Chicken Strip Sandwich",
        category: "sandwich",
        serving_size: 301,
        serving_unit: "g",
        calories: 690,
        total_fat: 29,
        saturated_fat: 5,
        trans_fat: 0,
        cholesterol: 55,
        sodium: 1590,
        total_carbohydrates: 78,
        dietary_fiber: 3,
        total_sugars: 21,
        protein: 31,
        ingredients_text:
          "Breaded chicken strips (chicken breast, wheat flour, water, salt, spices, soybean oil, leavening), honey BBQ sauce (high fructose corn syrup, tomato paste, vinegar, honey, spices), bun, lettuce, tomato",
      },
      {
        name: "Patty Melt",
        category: "burger",
        serving_size: 274,
        serving_unit: "g",
        calories: 710,
        total_fat: 38,
        saturated_fat: 16,
        trans_fat: 1.5,
        cholesterol: 105,
        sodium: 1400,
        total_carbohydrates: 52,
        dietary_fiber: 2,
        total_sugars: 7,
        protein: 38,
        ingredients_text:
          "Beef patty, Texas toast (enriched wheat flour, butter, water, sugar, yeast, salt), American cheese (2 slices), grilled onions, creamy pepper sauce",
      },
      {
        name: "Grilled Chicken Sandwich",
        category: "sandwich",
        serving_size: 260,
        serving_unit: "g",
        calories: 420,
        total_fat: 14,
        saturated_fat: 2.5,
        trans_fat: 0,
        cholesterol: 85,
        sodium: 1240,
        total_carbohydrates: 41,
        dietary_fiber: 2,
        total_sugars: 9,
        protein: 32,
        ingredients_text:
          "Grilled chicken breast (chicken breast, water, seasoning, salt, garlic powder), bun (enriched wheat flour, water, sugar, soybean oil, yeast, salt), lettuce, tomato, mayonnaise",
      },
      {
        name: "French Fries",
        category: "side",
        serving_size: 142,
        serving_unit: "g",
        calories: 400,
        total_fat: 19,
        saturated_fat: 3,
        trans_fat: 0,
        cholesterol: 0,
        sodium: 250,
        total_carbohydrates: 53,
        dietary_fiber: 4,
        total_sugars: 0,
        protein: 5,
        ingredients_text:
          "Potatoes, vegetable oil (canola, soybean), dextrose, sodium acid pyrophosphate, salt",
      },
      {
        name: "Onion Rings",
        category: "side",
        serving_size: 128,
        serving_unit: "g",
        calories: 390,
        total_fat: 22,
        saturated_fat: 4,
        trans_fat: 0,
        cholesterol: 0,
        sodium: 560,
        total_carbohydrates: 43,
        dietary_fiber: 2,
        total_sugars: 5,
        protein: 5,
        ingredients_text:
          "Onion, bleached wheat flour, water, modified corn starch, salt, soybean oil, dextrose, leavening (sodium acid pyrophosphate, sodium bicarbonate)",
      },
      {
        name: "Chicken Strips 3pc",
        category: "chicken",
        serving_size: 158,
        serving_unit: "g",
        calories: 430,
        total_fat: 22,
        saturated_fat: 3.5,
        trans_fat: 0,
        cholesterol: 55,
        sodium: 1470,
        total_carbohydrates: 30,
        dietary_fiber: 1,
        total_sugars: 1,
        protein: 28,
        ingredients_text:
          "Chicken breast tenderloins, wheat flour, water, salt, seasoning (salt, spices, garlic powder, onion powder), soybean oil, leavening, dried egg whites, nonfat dry milk",
      },
      {
        name: "Breakfast on a Bun with Sausage",
        category: "breakfast",
        serving_size: 193,
        serving_unit: "g",
        calories: 520,
        total_fat: 32,
        saturated_fat: 12,
        trans_fat: 0,
        cholesterol: 240,
        sodium: 1070,
        total_carbohydrates: 30,
        dietary_fiber: 1,
        total_sugars: 4,
        protein: 26,
        ingredients_text:
          "Bun (enriched wheat flour, water, sugar, soybean oil, yeast, salt), sausage patty (pork, water, salt, spices, sugar, dextrose), egg, American cheese (milk, water, milkfat, sodium citrate, salt, enzymes)",
      },
      {
        name: "Honey Butter Chicken Biscuit",
        category: "breakfast",
        serving_size: 198,
        serving_unit: "g",
        calories: 610,
        total_fat: 32,
        saturated_fat: 10,
        trans_fat: 0,
        cholesterol: 50,
        sodium: 1540,
        total_carbohydrates: 55,
        dietary_fiber: 1,
        total_sugars: 12,
        protein: 24,
        ingredients_text:
          "Buttermilk biscuit (enriched wheat flour, buttermilk, palm oil, sugar, baking powder, salt), breaded chicken fillet (chicken breast, wheat flour, water, salt, spices, soybean oil), honey butter sauce (butter, honey, sugar, salt)",
      },
      {
        name: "Taquito with Cheese",
        category: "breakfast",
        serving_size: 147,
        serving_unit: "g",
        calories: 370,
        total_fat: 21,
        saturated_fat: 7,
        trans_fat: 0,
        cholesterol: 235,
        sodium: 870,
        total_carbohydrates: 27,
        dietary_fiber: 1,
        total_sugars: 2,
        protein: 17,
        ingredients_text:
          "Flour tortilla (enriched wheat flour, water, vegetable shortening, salt, baking powder), scrambled eggs, sausage crumbles (pork, water, salt, spices), American cheese, green chiles",
      },
      {
        name: "Hot Apple Pie",
        category: "dessert",
        serving_size: 114,
        serving_unit: "g",
        calories: 350,
        total_fat: 17,
        saturated_fat: 7,
        trans_fat: 0,
        cholesterol: 0,
        sodium: 340,
        total_carbohydrates: 47,
        dietary_fiber: 1,
        total_sugars: 22,
        protein: 3,
        ingredients_text:
          "Apple filling (apples, sugar, water, modified corn starch, cinnamon, citric acid), pie crust (enriched wheat flour, palm oil, water, sugar, salt, leavening), cinnamon sugar coating",
      },
      {
        name: "Chocolate Shake",
        category: "beverage",
        serving_size: 473,
        serving_unit: "ml",
        calories: 630,
        total_fat: 17,
        saturated_fat: 11,
        trans_fat: 0.5,
        cholesterol: 60,
        sodium: 430,
        total_carbohydrates: 107,
        dietary_fiber: 2,
        total_sugars: 92,
        protein: 13,
        ingredients_text:
          "Vanilla ice cream (milk, cream, sugar, nonfat milk solids, corn syrup, vanilla), chocolate syrup (water, sugar, cocoa, corn syrup), whipped topping, milk",
      },
      {
        name: "Vanilla Shake",
        category: "beverage",
        serving_size: 473,
        serving_unit: "ml",
        calories: 580,
        total_fat: 17,
        saturated_fat: 11,
        trans_fat: 0.5,
        cholesterol: 60,
        sodium: 380,
        total_carbohydrates: 95,
        dietary_fiber: 0,
        total_sugars: 82,
        protein: 13,
        ingredients_text:
          "Vanilla ice cream (milk, cream, sugar, nonfat milk solids, corn syrup, vanilla extract), whipped topping, milk",
      },
      {
        name: "Dr Pepper Shake",
        category: "beverage",
        serving_size: 473,
        serving_unit: "ml",
        calories: 620,
        total_fat: 16,
        saturated_fat: 10,
        trans_fat: 0.5,
        cholesterol: 55,
        sodium: 370,
        total_carbohydrates: 108,
        dietary_fiber: 0,
        total_sugars: 94,
        protein: 12,
        ingredients_text:
          "Vanilla ice cream (milk, cream, sugar, nonfat milk solids, corn syrup, vanilla), Dr Pepper syrup (high fructose corn syrup, caramel color, phosphoric acid, natural and artificial flavors), whipped topping, milk",
      },
    ],
  },

  // ======================== RAISING CANE'S ========================
  {
    chain: "Raising Cane's",
    items: [
      {
        name: "The Box Combo",
        category: "combo",
        serving_size: 454,
        serving_unit: "g",
        calories: 1250,
        total_fat: 62,
        saturated_fat: 10,
        trans_fat: 0,
        cholesterol: 90,
        sodium: 2240,
        total_carbohydrates: 120,
        dietary_fiber: 4,
        total_sugars: 6,
        protein: 52,
        ingredients_text:
          "Chicken fingers (4) (chicken tenderloins, wheat flour, water, salt, spices, garlic powder, soybean oil, leavening, dried egg whites), crinkle-cut fries (potatoes, vegetable oil, salt), coleslaw (cabbage, carrots, sugar, soybean oil, vinegar, salt), Texas toast (enriched wheat flour, butter, garlic), Cane's sauce (mayonnaise, ketchup, Worcestershire, garlic, pepper, salt)",
      },
      {
        name: "3 Finger Combo",
        category: "combo",
        serving_size: 369,
        serving_unit: "g",
        calories: 960,
        total_fat: 46,
        saturated_fat: 7,
        trans_fat: 0,
        cholesterol: 65,
        sodium: 1680,
        total_carbohydrates: 92,
        dietary_fiber: 3,
        total_sugars: 4,
        protein: 38,
        ingredients_text:
          "Chicken fingers (3) (chicken tenderloins, wheat flour, water, salt, spices, garlic powder, soybean oil, leavening, dried egg whites), crinkle-cut fries, Texas toast, Cane's sauce",
      },
      {
        name: "The Caniac Combo",
        category: "combo",
        serving_size: 567,
        serving_unit: "g",
        calories: 1710,
        total_fat: 86,
        saturated_fat: 14,
        trans_fat: 0,
        cholesterol: 125,
        sodium: 3200,
        total_carbohydrates: 152,
        dietary_fiber: 6,
        total_sugars: 8,
        protein: 76,
        ingredients_text:
          "Chicken fingers (6) (chicken tenderloins, wheat flour, water, salt, spices, garlic powder, soybean oil, leavening, dried egg whites), crinkle-cut fries, coleslaw, Texas toast (2), Cane's sauce (2), large drink",
      },
      {
        name: "Chicken Fingers 3pc",
        category: "chicken",
        serving_size: 142,
        serving_unit: "g",
        calories: 360,
        total_fat: 17,
        saturated_fat: 3,
        trans_fat: 0,
        cholesterol: 65,
        sodium: 990,
        total_carbohydrates: 20,
        dietary_fiber: 1,
        total_sugars: 0,
        protein: 32,
        ingredients_text:
          "Chicken tenderloins, wheat flour, water, salt, spices, garlic powder, soybean oil, leavening (sodium acid pyrophosphate, sodium bicarbonate), dried egg whites",
      },
      {
        name: "Chicken Fingers 6pc",
        category: "chicken",
        serving_size: 284,
        serving_unit: "g",
        calories: 720,
        total_fat: 34,
        saturated_fat: 6,
        trans_fat: 0,
        cholesterol: 130,
        sodium: 1980,
        total_carbohydrates: 40,
        dietary_fiber: 2,
        total_sugars: 0,
        protein: 64,
        ingredients_text:
          "Chicken tenderloins, wheat flour, water, salt, spices, garlic powder, soybean oil, leavening (sodium acid pyrophosphate, sodium bicarbonate), dried egg whites",
      },
      {
        name: "Crinkle Cut Fries",
        category: "side",
        serving_size: 170,
        serving_unit: "g",
        calories: 430,
        total_fat: 21,
        saturated_fat: 3.5,
        trans_fat: 0,
        cholesterol: 0,
        sodium: 470,
        total_carbohydrates: 56,
        dietary_fiber: 4,
        total_sugars: 0,
        protein: 5,
        ingredients_text:
          "Potatoes, vegetable oil (canola, soybean), salt, dextrose, sodium acid pyrophosphate",
      },
      {
        name: "Coleslaw",
        category: "side",
        serving_size: 113,
        serving_unit: "g",
        calories: 180,
        total_fat: 12,
        saturated_fat: 2,
        trans_fat: 0,
        cholesterol: 15,
        sodium: 250,
        total_carbohydrates: 17,
        dietary_fiber: 2,
        total_sugars: 13,
        protein: 1,
        ingredients_text:
          "Cabbage, carrots, sugar, soybean oil, distilled vinegar, corn syrup, egg yolks, salt, celery seed",
      },
      {
        name: "Texas Toast",
        category: "side",
        serving_size: 57,
        serving_unit: "g",
        calories: 170,
        total_fat: 7,
        saturated_fat: 2,
        trans_fat: 0,
        cholesterol: 0,
        sodium: 260,
        total_carbohydrates: 22,
        dietary_fiber: 1,
        total_sugars: 2,
        protein: 4,
        ingredients_text:
          "Enriched wheat flour (wheat flour, niacin, reduced iron, thiamine mononitrate, riboflavin, folic acid), water, butter, sugar, yeast, salt, garlic powder",
      },
      {
        name: "Cane's Sauce",
        category: "sauce",
        serving_size: 28,
        serving_unit: "g",
        calories: 130,
        total_fat: 14,
        saturated_fat: 2,
        trans_fat: 0,
        cholesterol: 10,
        sodium: 220,
        total_carbohydrates: 2,
        dietary_fiber: 0,
        total_sugars: 1,
        protein: 0,
        ingredients_text:
          "Mayonnaise (soybean oil, egg yolks, vinegar, water, salt), ketchup (tomato concentrate, vinegar, high fructose corn syrup, salt), Worcestershire sauce, garlic, black pepper, salt",
      },
      {
        name: "Sweet Tea",
        category: "beverage",
        serving_size: 591,
        serving_unit: "ml",
        calories: 190,
        total_fat: 0,
        saturated_fat: 0,
        trans_fat: 0,
        cholesterol: 0,
        sodium: 15,
        total_carbohydrates: 48,
        dietary_fiber: 0,
        total_sugars: 48,
        protein: 0,
        ingredients_text: "Brewed tea, water, sugar",
      },
      {
        name: "Lemonade",
        category: "beverage",
        serving_size: 591,
        serving_unit: "ml",
        calories: 210,
        total_fat: 0,
        saturated_fat: 0,
        trans_fat: 0,
        cholesterol: 0,
        sodium: 30,
        total_carbohydrates: 56,
        dietary_fiber: 0,
        total_sugars: 52,
        protein: 0,
        ingredients_text: "Water, sugar, lemon juice concentrate, citric acid",
      },
      {
        name: "Arnold Palmer",
        category: "beverage",
        serving_size: 591,
        serving_unit: "ml",
        calories: 200,
        total_fat: 0,
        saturated_fat: 0,
        trans_fat: 0,
        cholesterol: 0,
        sodium: 20,
        total_carbohydrates: 52,
        dietary_fiber: 0,
        total_sugars: 50,
        protein: 0,
        ingredients_text: "Brewed tea, water, sugar, lemon juice concentrate, citric acid",
      },
      {
        name: "Chicken Sandwich",
        category: "sandwich",
        serving_size: 227,
        serving_unit: "g",
        calories: 580,
        total_fat: 27,
        saturated_fat: 5,
        trans_fat: 0,
        cholesterol: 75,
        sodium: 1340,
        total_carbohydrates: 46,
        dietary_fiber: 2,
        total_sugars: 5,
        protein: 36,
        ingredients_text:
          "Chicken fingers (3) (chicken tenderloins, wheat flour, water, salt, spices, soybean oil, leavening, dried egg whites), Kaiser roll (enriched wheat flour, water, sugar, yeast, salt), lettuce, Cane's sauce",
      },
      {
        name: "Kids Combo",
        category: "combo",
        serving_size: 255,
        serving_unit: "g",
        calories: 580,
        total_fat: 27,
        saturated_fat: 4.5,
        trans_fat: 0,
        cholesterol: 40,
        sodium: 1050,
        total_carbohydrates: 60,
        dietary_fiber: 2,
        total_sugars: 3,
        protein: 22,
        ingredients_text:
          "Chicken fingers (2) (chicken tenderloins, wheat flour, water, salt, spices, soybean oil, leavening, dried egg whites), crinkle-cut fries, Cane's sauce, kid's drink",
      },
      {
        name: "Extra Cane's Sauce",
        category: "sauce",
        serving_size: 28,
        serving_unit: "g",
        calories: 130,
        total_fat: 14,
        saturated_fat: 2,
        trans_fat: 0,
        cholesterol: 10,
        sodium: 220,
        total_carbohydrates: 2,
        dietary_fiber: 0,
        total_sugars: 1,
        protein: 0,
        ingredients_text:
          "Mayonnaise (soybean oil, egg yolks, vinegar, water, salt), ketchup (tomato concentrate, vinegar, high fructose corn syrup, salt), Worcestershire sauce, garlic, black pepper, salt",
      },
    ],
  },
];

// ---------------------------------------------------------------------------
// SQL statements (same as import-chains.ts)
// ---------------------------------------------------------------------------

const upsertVendor = db.prepare(`
  INSERT INTO vendors (id, name, type, api_key)
  VALUES (@id, @name, @type, @api_key)
  ON CONFLICT(id) DO UPDATE SET
    name = excluded.name,
    type = excluded.type
`);

const upsertFood = db.prepare(`
  INSERT INTO foods (id, name, brand, category, serving_size, serving_unit, source, vendor_id,
    calories, total_fat, saturated_fat, trans_fat, cholesterol, sodium,
    total_carbohydrates, dietary_fiber, total_sugars, protein,
    ingredients_text, allergens, dietary_tags, nutri_score, nutri_grade,
    updated_at)
  VALUES (@id, @name, @brand, @category, @serving_size, @serving_unit, 'vendor', @vendor_id,
    @calories, @total_fat, @saturated_fat, @trans_fat, @cholesterol, @sodium,
    @total_carbohydrates, @dietary_fiber, @total_sugars, @protein,
    @ingredients_text, @allergens, @dietary_tags, @nutri_score, @nutri_grade,
    datetime('now'))
  ON CONFLICT(id) DO UPDATE SET
    name = excluded.name,
    brand = excluded.brand,
    category = excluded.category,
    serving_size = excluded.serving_size,
    serving_unit = excluded.serving_unit,
    vendor_id = excluded.vendor_id,
    calories = excluded.calories,
    total_fat = excluded.total_fat,
    saturated_fat = excluded.saturated_fat,
    trans_fat = excluded.trans_fat,
    cholesterol = excluded.cholesterol,
    sodium = excluded.sodium,
    total_carbohydrates = excluded.total_carbohydrates,
    dietary_fiber = excluded.dietary_fiber,
    total_sugars = excluded.total_sugars,
    protein = excluded.protein,
    ingredients_text = excluded.ingredients_text,
    allergens = excluded.allergens,
    dietary_tags = excluded.dietary_tags,
    nutri_score = excluded.nutri_score,
    nutri_grade = excluded.nutri_grade,
    updated_at = datetime('now')
`);

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function slugify(name: string): string {
  return name
    .toLowerCase()
    .replace(/['']/g, "")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

function buildFoodRecord(item: ChainMenuItem, chainName: string, vendorId: string) {
  const chainSlug = slugify(chainName);
  const itemSlug = slugify(item.name);
  const id = `chain-${chainSlug}-${itemSlug}`;

  // Calculate nutri-score (needs per-100g values)
  const servingG = item.serving_unit === "g" ? item.serving_size : item.serving_size * 1;
  const factor = servingG > 0 ? 100 / servingG : 1;

  const nutriResult = calculateNutriScore(
    {
      calories: item.calories * factor,
      totalSugars: item.total_sugars * factor,
      saturatedFat: item.saturated_fat * factor,
      sodium: item.sodium * factor,
      dietaryFiber: item.dietary_fiber * factor,
      protein: item.protein * factor,
    },
    item.category
  );

  const ingredientsText = item.ingredients_text || null;
  const allergens = ingredientsText ? detectAllergens(ingredientsText) : [];
  const dietaryTags = detectDietaryTags(ingredientsText || "", {
    total_carbohydrates: item.total_carbohydrates,
    protein: item.protein,
    total_fat: item.total_fat,
    total_sugars: item.total_sugars,
    dietary_fiber: item.dietary_fiber,
  });

  return {
    id,
    name: item.name,
    brand: chainName,
    category: item.category,
    serving_size: item.serving_size,
    serving_unit: item.serving_unit,
    vendor_id: vendorId,
    calories: item.calories,
    total_fat: item.total_fat,
    saturated_fat: item.saturated_fat,
    trans_fat: item.trans_fat,
    cholesterol: item.cholesterol,
    sodium: item.sodium,
    total_carbohydrates: item.total_carbohydrates,
    dietary_fiber: item.dietary_fiber,
    total_sugars: item.total_sugars,
    protein: item.protein,
    ingredients_text: ingredientsText,
    allergens: allergens.length > 0 ? allergens.join(",") : null,
    dietary_tags: dietaryTags.length > 0 ? dietaryTags.join(",") : null,
    nutri_score: nutriResult.score,
    nutri_grade: nutriResult.grade,
  };
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

function main() {
  console.log("=== Restaurant Chain Nutrition Import - Batch 1 (Fast Food) ===\n");

  let totalItems = 0;
  let totalChains = 0;

  const beforeCount = (
    db.prepare("SELECT COUNT(*) as c FROM foods WHERE source = 'vendor'").get() as any
  ).c;

  const importAll = db.transaction(() => {
    for (const chain of chains) {
      const chainSlug = slugify(chain.chain);
      const vendorId = `chain-${chainSlug}`;

      // Create vendor record
      upsertVendor.run({
        id: vendorId,
        name: chain.chain,
        type: "restaurant",
        api_key: generateApiKey(),
      });

      console.log(`  ${chain.chain}: ${chain.items.length} items`);

      // Import each menu item
      for (const item of chain.items) {
        const record = buildFoodRecord(item, chain.chain, vendorId);
        upsertFood.run(record);
      }

      totalItems += chain.items.length;
      totalChains++;
    }
  });

  importAll();

  // Rebuild FTS index
  console.log("\nRebuilding search index...");
  db.exec("INSERT INTO foods_fts(foods_fts) VALUES('rebuild')");

  const afterCount = (
    db.prepare("SELECT COUNT(*) as c FROM foods WHERE source = 'vendor'").get() as any
  ).c;

  console.log(`\n=== Done! ===`);
  console.log(`Chains imported: ${totalChains}`);
  console.log(`Menu items processed: ${totalItems}`);
  console.log(`Vendor foods before: ${beforeCount}`);
  console.log(`Vendor foods after: ${afterCount}`);
  console.log(`New items added: ${afterCount - beforeCount}`);
}

main();
