/**
 * Restaurant Chain Nutrition Data Import - Batch 5
 *
 * Imports manually curated nutrition data for restaurant chains:
 * Arby's, Wingstop, Buffalo Wild Wings, Little Caesars, Carl's Jr,
 * Zaxby's, Del Taco, El Pollo Loco, Cookout
 *
 * Usage:
 *   npx ts-node scripts/import-chains-batch5.ts
 */

import { v4 as uuidv4 } from "uuid";
import db from "../src/data/database";
import { calculateNutriScore } from "../src/services/nutrition-score";
import { calculatePersonalHealthScore } from "../src/services/health-score";
import { detectAllergens, detectDietaryTags } from "../src/services/food-analysis";
import { generateApiKey } from "../src/middleware/auth";

interface ChainMenuItem {
  name: string;
  category: string;
  serving_size: number;
  serving_unit: string;
  calories: number;
  total_fat: number;
  saturated_fat: number;
  trans_fat: number;
  cholesterol: number;
  sodium: number;
  total_carbohydrates: number;
  dietary_fiber: number;
  total_sugars: number;
  protein: number;
  ingredients_text?: string;
}

interface ChainData {
  chain: string;
  items: ChainMenuItem[];
}

// ---------------------------------------------------------------------------
// Chain menu data
// ---------------------------------------------------------------------------

const chains: ChainData[] = [
  // ======================== ARBY'S ========================
  {
    chain: "Arby's",
    items: [
      {
        name: "Classic Roast Beef",
        category: "sandwich",
        serving_size: 154,
        serving_unit: "g",
        calories: 360,
        total_fat: 14,
        saturated_fat: 5,
        trans_fat: 0.5,
        cholesterol: 55,
        sodium: 970,
        total_carbohydrates: 37,
        dietary_fiber: 2,
        total_sugars: 5,
        protein: 23,
        ingredients_text:
          "Roast beef (beef, water, salt, sodium phosphate), sesame seed bun (enriched wheat flour, water, sugar, soybean oil, yeast, salt, sesame seeds), red ranch sauce",
      },
      {
        name: "Beef 'n Cheddar",
        category: "sandwich",
        serving_size: 195,
        serving_unit: "g",
        calories: 450,
        total_fat: 20,
        saturated_fat: 6,
        trans_fat: 1,
        cholesterol: 55,
        sodium: 1280,
        total_carbohydrates: 44,
        dietary_fiber: 2,
        total_sugars: 8,
        protein: 23,
        ingredients_text:
          "Roast beef (beef, water, salt, sodium phosphate), onion roll (enriched wheat flour, water, sugar, soybean oil, yeast, salt), cheddar cheese sauce (water, cheddar cheese, milk, sodium phosphate, salt), red ranch sauce",
      },
      {
        name: "Smokehouse Brisket",
        category: "sandwich",
        serving_size: 283,
        serving_unit: "g",
        calories: 600,
        total_fat: 29,
        saturated_fat: 10,
        trans_fat: 1,
        cholesterol: 95,
        sodium: 1650,
        total_carbohydrates: 51,
        dietary_fiber: 2,
        total_sugars: 13,
        protein: 35,
        ingredients_text:
          "Smoked beef brisket (beef, water, salt, sugar, spices, smoke flavor), star cut bun (enriched wheat flour, water, sugar, soybean oil, yeast, salt), gouda cheese, smoked cheddar, crispy onions, BBQ sauce, mayonnaise",
      },
      {
        name: "Crispy Chicken Sandwich",
        category: "sandwich",
        serving_size: 207,
        serving_unit: "g",
        calories: 530,
        total_fat: 25,
        saturated_fat: 4,
        trans_fat: 0,
        cholesterol: 55,
        sodium: 1170,
        total_carbohydrates: 52,
        dietary_fiber: 3,
        total_sugars: 7,
        protein: 25,
        ingredients_text:
          "Breaded chicken breast (chicken breast, wheat flour, water, salt, spices, soybean oil, leavening), star cut bun (enriched wheat flour, water, sugar, soybean oil, yeast, salt), lettuce, tomato, mayonnaise",
      },
      {
        name: "Chicken Tenders 5pc",
        category: "chicken",
        serving_size: 170,
        serving_unit: "g",
        calories: 470,
        total_fat: 24,
        saturated_fat: 4,
        trans_fat: 0,
        cholesterol: 80,
        sodium: 1220,
        total_carbohydrates: 32,
        dietary_fiber: 1,
        total_sugars: 0,
        protein: 31,
        ingredients_text:
          "Chicken tenderloins, wheat flour, water, salt, spices, garlic powder, soybean oil, leavening (sodium acid pyrophosphate, sodium bicarbonate), dried egg whites",
      },
      {
        name: "Jamocha Shake",
        category: "beverage",
        serving_size: 397,
        serving_unit: "ml",
        calories: 540,
        total_fat: 15,
        saturated_fat: 10,
        trans_fat: 0,
        cholesterol: 50,
        sodium: 350,
        total_carbohydrates: 88,
        dietary_fiber: 0,
        total_sugars: 74,
        protein: 13,
        ingredients_text:
          "Vanilla ice cream (milk, cream, sugar, corn syrup, whey, nonfat milk solids, vanilla), jamocha syrup (water, sugar, coffee extract, cocoa, corn syrup), milk, whipped topping",
      },
      {
        name: "Curly Fries",
        category: "side",
        serving_size: 128,
        serving_unit: "g",
        calories: 410,
        total_fat: 22,
        saturated_fat: 3,
        trans_fat: 0,
        cholesterol: 0,
        sodium: 1010,
        total_carbohydrates: 49,
        dietary_fiber: 4,
        total_sugars: 0,
        protein: 5,
        ingredients_text:
          "Potatoes, vegetable oil (canola, soybean, cottonseed, sunflower), enriched wheat flour, salt, corn starch, onion powder, garlic powder, spices, paprika, dextrose, leavening",
      },
      {
        name: "Mozzarella Sticks",
        category: "side",
        serving_size: 137,
        serving_unit: "g",
        calories: 440,
        total_fat: 22,
        saturated_fat: 9,
        trans_fat: 0,
        cholesterol: 40,
        sodium: 1290,
        total_carbohydrates: 42,
        dietary_fiber: 2,
        total_sugars: 3,
        protein: 18,
        ingredients_text:
          "Mozzarella cheese (pasteurized milk, cheese cultures, salt, enzymes), wheat flour, water, soybean oil, modified corn starch, salt, leavening, marinara sauce",
      },
      {
        name: "Turkey Gyro",
        category: "sandwich",
        serving_size: 298,
        serving_unit: "g",
        calories: 470,
        total_fat: 20,
        saturated_fat: 5,
        trans_fat: 0,
        cholesterol: 65,
        sodium: 1420,
        total_carbohydrates: 48,
        dietary_fiber: 3,
        total_sugars: 6,
        protein: 26,
        ingredients_text:
          "Turkey (turkey breast, water, salt, modified food starch, sodium phosphate), flatbread (enriched wheat flour, water, sugar, soybean oil, yeast, salt), lettuce, tomato, onion, tzatziki sauce (yogurt, cucumber, garlic, salt, dill)",
      },
      {
        name: "French Dip",
        category: "sandwich",
        serving_size: 241,
        serving_unit: "g",
        calories: 520,
        total_fat: 19,
        saturated_fat: 8,
        trans_fat: 1,
        cholesterol: 85,
        sodium: 2280,
        total_carbohydrates: 51,
        dietary_fiber: 2,
        total_sugars: 4,
        protein: 32,
        ingredients_text:
          "Roast beef (beef, water, salt, sodium phosphate), sub roll (enriched wheat flour, water, sugar, soybean oil, yeast, salt), Swiss cheese, au jus (beef broth, salt, caramel color)",
      },
      {
        name: "Loaded Italian",
        category: "sandwich",
        serving_size: 312,
        serving_unit: "g",
        calories: 640,
        total_fat: 33,
        saturated_fat: 10,
        trans_fat: 0.5,
        cholesterol: 85,
        sodium: 2260,
        total_carbohydrates: 52,
        dietary_fiber: 3,
        total_sugars: 6,
        protein: 33,
        ingredients_text:
          "Pepperoni (pork, beef, salt, spices, dextrose, lactic acid starter culture, sodium nitrite, paprika), salami, ham, provolone cheese, banana peppers, lettuce, tomato, red onion, Italian dressing, sub roll (enriched wheat flour, water, sugar, soybean oil, yeast, salt)",
      },
      {
        name: "Reuben",
        category: "sandwich",
        serving_size: 303,
        serving_unit: "g",
        calories: 660,
        total_fat: 30,
        saturated_fat: 10,
        trans_fat: 1,
        cholesterol: 105,
        sodium: 2440,
        total_carbohydrates: 55,
        dietary_fiber: 5,
        total_sugars: 10,
        protein: 40,
        ingredients_text:
          "Corned beef (beef, water, salt, sugar, sodium phosphate, sodium nitrite), marble rye bread (enriched wheat flour, rye flour, water, yeast, caraway seeds, salt, caramel color), Swiss cheese, sauerkraut (cabbage, water, salt), Thousand Island dressing",
      },
      {
        name: "Jalapeno Bites",
        category: "side",
        serving_size: 124,
        serving_unit: "g",
        calories: 300,
        total_fat: 17,
        saturated_fat: 6,
        trans_fat: 0,
        cholesterol: 30,
        sodium: 590,
        total_carbohydrates: 30,
        dietary_fiber: 2,
        total_sugars: 3,
        protein: 7,
        ingredients_text:
          "Jalapeno peppers, cream cheese (pasteurized milk and cream, cheese culture, salt, stabilizers), breading (wheat flour, water, modified corn starch, salt, leavening), soybean oil",
      },
      {
        name: "Slider",
        category: "sandwich",
        serving_size: 89,
        serving_unit: "g",
        calories: 230,
        total_fat: 12,
        saturated_fat: 5,
        trans_fat: 0.5,
        cholesterol: 40,
        sodium: 590,
        total_carbohydrates: 17,
        dietary_fiber: 1,
        total_sugars: 3,
        protein: 14,
        ingredients_text:
          "Roast beef (beef, water, salt, sodium phosphate), slider bun (enriched wheat flour, water, sugar, soybean oil, yeast, salt), cheddar cheese, red ranch sauce",
      },
      {
        name: "Apple Turnover",
        category: "dessert",
        serving_size: 128,
        serving_unit: "g",
        calories: 330,
        total_fat: 13,
        saturated_fat: 5,
        trans_fat: 0,
        cholesterol: 0,
        sodium: 280,
        total_carbohydrates: 49,
        dietary_fiber: 2,
        total_sugars: 20,
        protein: 4,
        ingredients_text:
          "Apple filling (apples, sugar, water, modified corn starch, cinnamon, citric acid), pastry dough (enriched wheat flour, butter, water, sugar, salt), icing (sugar, water, corn syrup)",
      },
    ],
  },

  // ======================== WINGSTOP ========================
  {
    chain: "Wingstop",
    items: [
      {
        name: "Classic Wings 10pc",
        category: "chicken",
        serving_size: 340,
        serving_unit: "g",
        calories: 780,
        total_fat: 50,
        saturated_fat: 14,
        trans_fat: 0,
        cholesterol: 300,
        sodium: 2150,
        total_carbohydrates: 8,
        dietary_fiber: 0,
        total_sugars: 0,
        protein: 72,
        ingredients_text:
          "Chicken wings (chicken wing sections, water, salt), seasoned flour coating (wheat flour, salt, spices, garlic powder, onion powder, paprika, soybean oil), hot sauce (aged cayenne peppers, vinegar, salt, garlic)",
      },
      {
        name: "Boneless Wings 8pc",
        category: "chicken",
        serving_size: 256,
        serving_unit: "g",
        calories: 630,
        total_fat: 30,
        saturated_fat: 6,
        trans_fat: 0,
        cholesterol: 100,
        sodium: 1870,
        total_carbohydrates: 52,
        dietary_fiber: 2,
        total_sugars: 2,
        protein: 38,
        ingredients_text:
          "Chicken breast meat, wheat flour, water, salt, spices, garlic powder, soybean oil, leavening (sodium acid pyrophosphate, sodium bicarbonate), dried egg whites, hot sauce",
      },
      {
        name: "Chicken Sandwich",
        category: "sandwich",
        serving_size: 227,
        serving_unit: "g",
        calories: 560,
        total_fat: 28,
        saturated_fat: 5,
        trans_fat: 0,
        cholesterol: 75,
        sodium: 1340,
        total_carbohydrates: 46,
        dietary_fiber: 2,
        total_sugars: 6,
        protein: 32,
        ingredients_text:
          "Breaded chicken breast (chicken breast, wheat flour, water, salt, spices, soybean oil, leavening), brioche bun (enriched wheat flour, butter, eggs, sugar, yeast, salt), pickles, mayo",
      },
      {
        name: "Thigh Bites",
        category: "chicken",
        serving_size: 170,
        serving_unit: "g",
        calories: 440,
        total_fat: 24,
        saturated_fat: 5,
        trans_fat: 0,
        cholesterol: 110,
        sodium: 1050,
        total_carbohydrates: 28,
        dietary_fiber: 1,
        total_sugars: 1,
        protein: 28,
        ingredients_text:
          "Chicken thigh meat, wheat flour, water, salt, spices, garlic powder, soybean oil, leavening (sodium acid pyrophosphate, sodium bicarbonate)",
      },
      {
        name: "Cajun Fried Corn",
        category: "side",
        serving_size: 142,
        serving_unit: "g",
        calories: 240,
        total_fat: 14,
        saturated_fat: 5,
        trans_fat: 0,
        cholesterol: 15,
        sodium: 590,
        total_carbohydrates: 26,
        dietary_fiber: 3,
        total_sugars: 5,
        protein: 5,
        ingredients_text:
          "Corn kernels, soybean oil, butter, cajun seasoning (salt, garlic powder, paprika, cayenne pepper, onion powder, black pepper, oregano, thyme)",
      },
      {
        name: "Fries Large",
        category: "side",
        serving_size: 198,
        serving_unit: "g",
        calories: 530,
        total_fat: 26,
        saturated_fat: 4,
        trans_fat: 0,
        cholesterol: 0,
        sodium: 480,
        total_carbohydrates: 68,
        dietary_fiber: 5,
        total_sugars: 0,
        protein: 7,
        ingredients_text:
          "Potatoes, vegetable oil (canola, soybean), salt, dextrose, sodium acid pyrophosphate",
      },
      {
        name: "Ranch Dip",
        category: "sauce",
        serving_size: 43,
        serving_unit: "g",
        calories: 200,
        total_fat: 21,
        saturated_fat: 3.5,
        trans_fat: 0,
        cholesterol: 15,
        sodium: 360,
        total_carbohydrates: 2,
        dietary_fiber: 0,
        total_sugars: 1,
        protein: 1,
        ingredients_text:
          "Soybean oil, buttermilk, water, egg yolks, vinegar, salt, garlic, onion, dill, parsley, spices",
      },
      {
        name: "Blue Cheese Dip",
        category: "sauce",
        serving_size: 43,
        serving_unit: "g",
        calories: 210,
        total_fat: 22,
        saturated_fat: 4,
        trans_fat: 0,
        cholesterol: 20,
        sodium: 380,
        total_carbohydrates: 2,
        dietary_fiber: 0,
        total_sugars: 1,
        protein: 2,
        ingredients_text:
          "Soybean oil, blue cheese (pasteurized milk, cheese cultures, salt, enzymes), water, egg yolks, vinegar, salt, garlic, spices",
      },
      {
        name: "Veggie Sticks",
        category: "side",
        serving_size: 85,
        serving_unit: "g",
        calories: 25,
        total_fat: 0,
        saturated_fat: 0,
        trans_fat: 0,
        cholesterol: 0,
        sodium: 25,
        total_carbohydrates: 5,
        dietary_fiber: 2,
        total_sugars: 3,
        protein: 1,
        ingredients_text: "Carrots, celery",
      },
      {
        name: "Louisiana Rub Wings 10pc",
        category: "chicken",
        serving_size: 340,
        serving_unit: "g",
        calories: 800,
        total_fat: 52,
        saturated_fat: 14,
        trans_fat: 0,
        cholesterol: 300,
        sodium: 2300,
        total_carbohydrates: 10,
        dietary_fiber: 1,
        total_sugars: 0,
        protein: 72,
        ingredients_text:
          "Chicken wings (chicken wing sections, water, salt), Louisiana dry rub (salt, garlic powder, paprika, cayenne pepper, onion powder, black pepper, oregano, thyme), soybean oil",
      },
      {
        name: "Garlic Parmesan Wings 10pc",
        category: "chicken",
        serving_size: 360,
        serving_unit: "g",
        calories: 920,
        total_fat: 62,
        saturated_fat: 16,
        trans_fat: 0,
        cholesterol: 320,
        sodium: 2440,
        total_carbohydrates: 14,
        dietary_fiber: 0,
        total_sugars: 2,
        protein: 74,
        ingredients_text:
          "Chicken wings (chicken wing sections, water, salt), garlic parmesan sauce (soybean oil, parmesan cheese, garlic, butter, salt, spices), soybean oil",
      },
      {
        name: "Mango Habanero Wings 10pc",
        category: "chicken",
        serving_size: 370,
        serving_unit: "g",
        calories: 880,
        total_fat: 50,
        saturated_fat: 14,
        trans_fat: 0,
        cholesterol: 300,
        sodium: 2200,
        total_carbohydrates: 38,
        dietary_fiber: 1,
        total_sugars: 30,
        protein: 72,
        ingredients_text:
          "Chicken wings (chicken wing sections, water, salt), mango habanero sauce (sugar, mango puree, habanero peppers, vinegar, water, salt, modified corn starch), soybean oil",
      },
      {
        name: "Lemon Pepper Wings 10pc",
        category: "chicken",
        serving_size: 340,
        serving_unit: "g",
        calories: 810,
        total_fat: 52,
        saturated_fat: 14,
        trans_fat: 0,
        cholesterol: 300,
        sodium: 2280,
        total_carbohydrates: 10,
        dietary_fiber: 0,
        total_sugars: 0,
        protein: 72,
        ingredients_text:
          "Chicken wings (chicken wing sections, water, salt), lemon pepper seasoning (salt, black pepper, lemon peel, citric acid, garlic powder, onion powder), soybean oil, butter",
      },
      {
        name: "Roll",
        category: "side",
        serving_size: 57,
        serving_unit: "g",
        calories: 170,
        total_fat: 4,
        saturated_fat: 1.5,
        trans_fat: 0,
        cholesterol: 5,
        sodium: 290,
        total_carbohydrates: 28,
        dietary_fiber: 1,
        total_sugars: 4,
        protein: 5,
        ingredients_text:
          "Enriched wheat flour (wheat flour, niacin, reduced iron, thiamine mononitrate, riboflavin, folic acid), water, sugar, butter, yeast, salt",
      },
      {
        name: "Brownie",
        category: "dessert",
        serving_size: 85,
        serving_unit: "g",
        calories: 360,
        total_fat: 18,
        saturated_fat: 8,
        trans_fat: 0,
        cholesterol: 45,
        sodium: 190,
        total_carbohydrates: 48,
        dietary_fiber: 2,
        total_sugars: 32,
        protein: 4,
        ingredients_text:
          "Sugar, wheat flour, butter, eggs, cocoa powder, chocolate chips (sugar, chocolate liquor, cocoa butter, soy lecithin, vanilla), salt, vanilla extract",
      },
    ],
  },

  // ======================== BUFFALO WILD WINGS ========================
  {
    chain: "Buffalo Wild Wings",
    items: [
      {
        name: "Traditional Wings 12pc",
        category: "chicken",
        serving_size: 408,
        serving_unit: "g",
        calories: 940,
        total_fat: 60,
        saturated_fat: 17,
        trans_fat: 0,
        cholesterol: 360,
        sodium: 2580,
        total_carbohydrates: 10,
        dietary_fiber: 0,
        total_sugars: 0,
        protein: 86,
        ingredients_text:
          "Chicken wings (chicken wing sections, water, salt), seasoned flour coating (wheat flour, salt, spices, garlic powder, paprika), soybean oil, buffalo sauce (cayenne pepper sauce, butter, vinegar, garlic)",
      },
      {
        name: "Boneless Wings 12pc",
        category: "chicken",
        serving_size: 384,
        serving_unit: "g",
        calories: 1020,
        total_fat: 52,
        saturated_fat: 10,
        trans_fat: 0,
        cholesterol: 150,
        sodium: 2810,
        total_carbohydrates: 78,
        dietary_fiber: 4,
        total_sugars: 4,
        protein: 58,
        ingredients_text:
          "Chicken breast meat, wheat flour, water, salt, spices, garlic powder, soybean oil, leavening (sodium acid pyrophosphate, sodium bicarbonate), dried egg whites, buffalo sauce",
      },
      {
        name: "Burger",
        category: "burger",
        serving_size: 340,
        serving_unit: "g",
        calories: 780,
        total_fat: 46,
        saturated_fat: 18,
        trans_fat: 1.5,
        cholesterol: 130,
        sodium: 1350,
        total_carbohydrates: 48,
        dietary_fiber: 2,
        total_sugars: 9,
        protein: 44,
        ingredients_text:
          "Beef patty, brioche bun (enriched wheat flour, butter, eggs, sugar, yeast, salt), American cheese, lettuce, tomato, onion, pickles, ketchup, mustard",
      },
      {
        name: "Chicken Wrap",
        category: "sandwich",
        serving_size: 312,
        serving_unit: "g",
        calories: 650,
        total_fat: 32,
        saturated_fat: 8,
        trans_fat: 0,
        cholesterol: 85,
        sodium: 1680,
        total_carbohydrates: 56,
        dietary_fiber: 4,
        total_sugars: 4,
        protein: 34,
        ingredients_text:
          "Flour tortilla (enriched wheat flour, water, vegetable shortening, salt), grilled chicken breast, lettuce, tomato, cheddar cheese, ranch dressing (soybean oil, buttermilk, egg yolks, vinegar, salt, spices)",
      },
      {
        name: "Street Tacos",
        category: "entree",
        serving_size: 227,
        serving_unit: "g",
        calories: 490,
        total_fat: 24,
        saturated_fat: 7,
        trans_fat: 0,
        cholesterol: 75,
        sodium: 1120,
        total_carbohydrates: 40,
        dietary_fiber: 3,
        total_sugars: 4,
        protein: 28,
        ingredients_text:
          "Corn tortillas (corn masa flour, water, lime), grilled chicken, pico de gallo (tomato, onion, cilantro, jalapeno, lime juice, salt), queso fresco, cilantro lime sauce",
      },
      {
        name: "Mozzarella Sticks",
        category: "side",
        serving_size: 170,
        serving_unit: "g",
        calories: 540,
        total_fat: 28,
        saturated_fat: 12,
        trans_fat: 0,
        cholesterol: 50,
        sodium: 1550,
        total_carbohydrates: 48,
        dietary_fiber: 2,
        total_sugars: 4,
        protein: 22,
        ingredients_text:
          "Mozzarella cheese (pasteurized milk, cheese cultures, salt, enzymes), wheat flour, water, soybean oil, modified corn starch, salt, leavening, marinara sauce (tomatoes, garlic, olive oil, basil, salt)",
      },
      {
        name: "Onion Rings",
        category: "side",
        serving_size: 170,
        serving_unit: "g",
        calories: 480,
        total_fat: 26,
        saturated_fat: 5,
        trans_fat: 0,
        cholesterol: 0,
        sodium: 780,
        total_carbohydrates: 56,
        dietary_fiber: 3,
        total_sugars: 8,
        protein: 6,
        ingredients_text:
          "Onion, bleached wheat flour, water, modified corn starch, salt, soybean oil, dextrose, leavening (sodium acid pyrophosphate, sodium bicarbonate), garlic powder",
      },
      {
        name: "Cheese Curds",
        category: "side",
        serving_size: 170,
        serving_unit: "g",
        calories: 580,
        total_fat: 36,
        saturated_fat: 16,
        trans_fat: 0,
        cholesterol: 80,
        sodium: 1340,
        total_carbohydrates: 38,
        dietary_fiber: 1,
        total_sugars: 2,
        protein: 24,
        ingredients_text:
          "Cheddar cheese curds (pasteurized milk, cheese cultures, salt, enzymes), wheat flour, water, soybean oil, modified corn starch, salt, leavening, buttermilk",
      },
      {
        name: "Garden Chicken Salad",
        category: "salad",
        serving_size: 397,
        serving_unit: "g",
        calories: 520,
        total_fat: 28,
        saturated_fat: 7,
        trans_fat: 0,
        cholesterol: 95,
        sodium: 1240,
        total_carbohydrates: 28,
        dietary_fiber: 5,
        total_sugars: 8,
        protein: 38,
        ingredients_text:
          "Mixed greens, grilled chicken breast, tomato, cucumber, shredded cheddar cheese, croutons (enriched wheat flour, soybean oil, salt, garlic), ranch dressing (soybean oil, buttermilk, egg yolks, vinegar, salt, spices)",
      },
      {
        name: "Chicken Tenders",
        category: "chicken",
        serving_size: 227,
        serving_unit: "g",
        calories: 580,
        total_fat: 28,
        saturated_fat: 5,
        trans_fat: 0,
        cholesterol: 95,
        sodium: 1620,
        total_carbohydrates: 40,
        dietary_fiber: 2,
        total_sugars: 1,
        protein: 40,
        ingredients_text:
          "Chicken breast tenderloins, wheat flour, water, salt, spices, garlic powder, soybean oil, leavening (sodium acid pyrophosphate, sodium bicarbonate), dried egg whites",
      },
      {
        name: "Nachos",
        category: "side",
        serving_size: 454,
        serving_unit: "g",
        calories: 1130,
        total_fat: 64,
        saturated_fat: 22,
        trans_fat: 0,
        cholesterol: 110,
        sodium: 2240,
        total_carbohydrates: 96,
        dietary_fiber: 8,
        total_sugars: 6,
        protein: 42,
        ingredients_text:
          "Tortilla chips (corn, vegetable oil, salt), queso (cheddar cheese, milk, water, sodium phosphate), seasoned beef, jalapenos, pico de gallo, sour cream, guacamole",
      },
      {
        name: "Loaded Tots",
        category: "side",
        serving_size: 340,
        serving_unit: "g",
        calories: 720,
        total_fat: 42,
        saturated_fat: 14,
        trans_fat: 0,
        cholesterol: 65,
        sodium: 1650,
        total_carbohydrates: 64,
        dietary_fiber: 4,
        total_sugars: 3,
        protein: 22,
        ingredients_text:
          "Tater tots (potatoes, vegetable oil, salt, dextrose), cheddar cheese sauce, bacon, sour cream, green onion",
      },
      {
        name: "Chocolate Fudge Cake",
        category: "dessert",
        serving_size: 198,
        serving_unit: "g",
        calories: 720,
        total_fat: 36,
        saturated_fat: 16,
        trans_fat: 0,
        cholesterol: 85,
        sodium: 540,
        total_carbohydrates: 92,
        dietary_fiber: 3,
        total_sugars: 68,
        protein: 8,
        ingredients_text:
          "Sugar, wheat flour, butter, eggs, cocoa powder, chocolate (sugar, chocolate liquor, cocoa butter, soy lecithin), cream, milk, vanilla extract, baking powder, salt, chocolate fudge icing",
      },
      {
        name: "Vanilla Shake",
        category: "beverage",
        serving_size: 473,
        serving_unit: "ml",
        calories: 660,
        total_fat: 28,
        saturated_fat: 18,
        trans_fat: 1,
        cholesterol: 90,
        sodium: 400,
        total_carbohydrates: 90,
        dietary_fiber: 0,
        total_sugars: 76,
        protein: 14,
        ingredients_text:
          "Vanilla ice cream (milk, cream, sugar, corn syrup, nonfat milk solids, vanilla), whipped topping, milk",
      },
      {
        name: "Caesar Salad",
        category: "salad",
        serving_size: 283,
        serving_unit: "g",
        calories: 380,
        total_fat: 24,
        saturated_fat: 5,
        trans_fat: 0,
        cholesterol: 25,
        sodium: 980,
        total_carbohydrates: 28,
        dietary_fiber: 3,
        total_sugars: 3,
        protein: 14,
        ingredients_text:
          "Romaine lettuce, parmesan cheese, croutons (enriched wheat flour, soybean oil, salt, garlic), Caesar dressing (soybean oil, parmesan cheese, anchovy paste, egg yolks, lemon juice, garlic, Worcestershire sauce, Dijon mustard, salt, black pepper)",
      },
    ],
  },

  // ======================== LITTLE CAESARS ========================
  {
    chain: "Little Caesars",
    items: [
      {
        name: "Pepperoni Pizza per slice",
        category: "pizza",
        serving_size: 113,
        serving_unit: "g",
        calories: 280,
        total_fat: 11,
        saturated_fat: 5,
        trans_fat: 0,
        cholesterol: 25,
        sodium: 580,
        total_carbohydrates: 32,
        dietary_fiber: 1,
        total_sugars: 3,
        protein: 12,
        ingredients_text:
          "Pizza dough (enriched wheat flour, water, sugar, soybean oil, yeast, salt), mozzarella cheese (pasteurized milk, cheese cultures, salt, enzymes), pizza sauce (tomatoes, water, sugar, salt, spices, garlic), pepperoni (pork, beef, salt, spices, dextrose, lactic acid starter culture, sodium nitrite, paprika)",
      },
      {
        name: "Cheese Pizza per slice",
        category: "pizza",
        serving_size: 107,
        serving_unit: "g",
        calories: 250,
        total_fat: 9,
        saturated_fat: 4.5,
        trans_fat: 0,
        cholesterol: 20,
        sodium: 480,
        total_carbohydrates: 31,
        dietary_fiber: 1,
        total_sugars: 3,
        protein: 11,
        ingredients_text:
          "Pizza dough (enriched wheat flour, water, sugar, soybean oil, yeast, salt), mozzarella cheese (pasteurized milk, cheese cultures, salt, enzymes), pizza sauce (tomatoes, water, sugar, salt, spices, garlic)",
      },
      {
        name: "ExtraMostBestest per slice",
        category: "pizza",
        serving_size: 134,
        serving_unit: "g",
        calories: 330,
        total_fat: 15,
        saturated_fat: 7,
        trans_fat: 0,
        cholesterol: 35,
        sodium: 680,
        total_carbohydrates: 32,
        dietary_fiber: 1,
        total_sugars: 3,
        protein: 15,
        ingredients_text:
          "Pizza dough (enriched wheat flour, water, sugar, soybean oil, yeast, salt), mozzarella cheese (pasteurized milk, cheese cultures, salt, enzymes), pizza sauce (tomatoes, water, sugar, salt, spices, garlic), extra pepperoni (pork, beef, salt, spices, dextrose, lactic acid starter culture, sodium nitrite, paprika), extra mozzarella cheese",
      },
      {
        name: "Deep Dish per slice",
        category: "pizza",
        serving_size: 142,
        serving_unit: "g",
        calories: 360,
        total_fat: 17,
        saturated_fat: 7,
        trans_fat: 0,
        cholesterol: 30,
        sodium: 710,
        total_carbohydrates: 36,
        dietary_fiber: 2,
        total_sugars: 4,
        protein: 14,
        ingredients_text:
          "Deep dish dough (enriched wheat flour, water, soybean oil, sugar, yeast, salt, butter flavor), mozzarella cheese, muenster cheese, pizza sauce (tomatoes, water, sugar, salt, spices), pepperoni",
      },
      {
        name: "Crazy Bread 1 stick",
        category: "side",
        serving_size: 43,
        serving_unit: "g",
        calories: 100,
        total_fat: 3,
        saturated_fat: 0.5,
        trans_fat: 0,
        cholesterol: 0,
        sodium: 150,
        total_carbohydrates: 15,
        dietary_fiber: 1,
        total_sugars: 1,
        protein: 3,
        ingredients_text:
          "Pizza dough (enriched wheat flour, water, sugar, soybean oil, yeast, salt), butter flavored topping (soybean oil, butter flavor, salt), parmesan cheese, garlic",
      },
      {
        name: "Italian Cheese Bread",
        category: "side",
        serving_size: 71,
        serving_unit: "g",
        calories: 190,
        total_fat: 8,
        saturated_fat: 3.5,
        trans_fat: 0,
        cholesterol: 15,
        sodium: 340,
        total_carbohydrates: 22,
        dietary_fiber: 1,
        total_sugars: 2,
        protein: 7,
        ingredients_text:
          "Pizza dough (enriched wheat flour, water, sugar, soybean oil, yeast, salt), mozzarella cheese, butter flavored topping, Italian seasoning (oregano, basil, garlic, parsley), parmesan cheese",
      },
      {
        name: "Caesar Wings 8pc",
        category: "chicken",
        serving_size: 272,
        serving_unit: "g",
        calories: 740,
        total_fat: 48,
        saturated_fat: 12,
        trans_fat: 0,
        cholesterol: 240,
        sodium: 1880,
        total_carbohydrates: 24,
        dietary_fiber: 1,
        total_sugars: 1,
        protein: 52,
        ingredients_text:
          "Chicken wings (chicken wing sections, water, salt), seasoned coating (wheat flour, salt, spices, garlic powder, onion powder, paprika), soybean oil",
      },
      {
        name: "Stuffed Crust per slice",
        category: "pizza",
        serving_size: 150,
        serving_unit: "g",
        calories: 380,
        total_fat: 17,
        saturated_fat: 8,
        trans_fat: 0,
        cholesterol: 40,
        sodium: 740,
        total_carbohydrates: 37,
        dietary_fiber: 2,
        total_sugars: 4,
        protein: 17,
        ingredients_text:
          "Pizza dough (enriched wheat flour, water, sugar, soybean oil, yeast, salt), mozzarella cheese (pasteurized milk, cheese cultures, salt, enzymes), string cheese (mozzarella), pizza sauce, pepperoni",
      },
      {
        name: "Thin Crust per slice",
        category: "pizza",
        serving_size: 85,
        serving_unit: "g",
        calories: 210,
        total_fat: 10,
        saturated_fat: 4.5,
        trans_fat: 0,
        cholesterol: 25,
        sodium: 420,
        total_carbohydrates: 20,
        dietary_fiber: 1,
        total_sugars: 2,
        protein: 10,
        ingredients_text:
          "Thin crust dough (enriched wheat flour, water, soybean oil, salt, yeast), mozzarella cheese, pizza sauce, pepperoni",
      },
      {
        name: "Caesar Dips Butter",
        category: "sauce",
        serving_size: 28,
        serving_unit: "g",
        calories: 110,
        total_fat: 12,
        saturated_fat: 2.5,
        trans_fat: 0,
        cholesterol: 0,
        sodium: 180,
        total_carbohydrates: 0,
        dietary_fiber: 0,
        total_sugars: 0,
        protein: 0,
        ingredients_text:
          "Soybean oil, butter (cream, salt), natural butter flavor, salt, garlic powder",
      },
      {
        name: "Crazy Sauce",
        category: "sauce",
        serving_size: 57,
        serving_unit: "g",
        calories: 25,
        total_fat: 0,
        saturated_fat: 0,
        trans_fat: 0,
        cholesterol: 0,
        sodium: 220,
        total_carbohydrates: 5,
        dietary_fiber: 1,
        total_sugars: 3,
        protein: 1,
        ingredients_text:
          "Tomato puree (water, tomato paste), sugar, salt, garlic powder, onion powder, spices, citric acid",
      },
      {
        name: "Pepperoni Cheeser per slice",
        category: "pizza",
        serving_size: 128,
        serving_unit: "g",
        calories: 320,
        total_fat: 14,
        saturated_fat: 6,
        trans_fat: 0,
        cholesterol: 30,
        sodium: 640,
        total_carbohydrates: 33,
        dietary_fiber: 1,
        total_sugars: 3,
        protein: 14,
        ingredients_text:
          "Pizza dough (enriched wheat flour, water, sugar, soybean oil, yeast, salt), mozzarella cheese, pepperoni, parmesan cheese, pizza sauce",
      },
      {
        name: "Cookie Dough Brownie",
        category: "dessert",
        serving_size: 99,
        serving_unit: "g",
        calories: 400,
        total_fat: 18,
        saturated_fat: 9,
        trans_fat: 0,
        cholesterol: 40,
        sodium: 260,
        total_carbohydrates: 56,
        dietary_fiber: 1,
        total_sugars: 38,
        protein: 4,
        ingredients_text:
          "Sugar, wheat flour, butter, eggs, cocoa powder, chocolate chips (sugar, chocolate liquor, cocoa butter, soy lecithin), cookie dough pieces (wheat flour, sugar, butter, brown sugar, eggs, vanilla, salt), salt, vanilla extract",
      },
      {
        name: "2 Liter Pepsi",
        category: "beverage",
        serving_size: 591,
        serving_unit: "ml",
        calories: 250,
        total_fat: 0,
        saturated_fat: 0,
        trans_fat: 0,
        cholesterol: 0,
        sodium: 50,
        total_carbohydrates: 69,
        dietary_fiber: 0,
        total_sugars: 69,
        protein: 0,
        ingredients_text:
          "Carbonated water, high fructose corn syrup, caramel color, sugar, phosphoric acid, caffeine, citric acid, natural flavor",
      },
      {
        name: "Classic Caesar Salad",
        category: "salad",
        serving_size: 227,
        serving_unit: "g",
        calories: 270,
        total_fat: 17,
        saturated_fat: 4,
        trans_fat: 0,
        cholesterol: 15,
        sodium: 640,
        total_carbohydrates: 20,
        dietary_fiber: 3,
        total_sugars: 3,
        protein: 10,
        ingredients_text:
          "Romaine lettuce, parmesan cheese, croutons (enriched wheat flour, soybean oil, salt, garlic), Caesar dressing (soybean oil, parmesan cheese, anchovy paste, egg yolks, lemon juice, garlic, salt, black pepper)",
      },
    ],
  },

  // ======================== CARL'S JR ========================
  {
    chain: "Carl's Jr",
    items: [
      {
        name: "Famous Star",
        category: "burger",
        serving_size: 254,
        serving_unit: "g",
        calories: 590,
        total_fat: 32,
        saturated_fat: 10,
        trans_fat: 1,
        cholesterol: 70,
        sodium: 1070,
        total_carbohydrates: 50,
        dietary_fiber: 3,
        total_sugars: 11,
        protein: 24,
        ingredients_text:
          "Beef patty, seeded bun (enriched wheat flour, water, sugar, soybean oil, yeast, sesame seeds, salt), American cheese, lettuce, tomato, onion, pickles, ketchup, mustard, mayonnaise",
      },
      {
        name: "Western Bacon Cheeseburger",
        category: "burger",
        serving_size: 278,
        serving_unit: "g",
        calories: 710,
        total_fat: 33,
        saturated_fat: 14,
        trans_fat: 1.5,
        cholesterol: 100,
        sodium: 1480,
        total_carbohydrates: 65,
        dietary_fiber: 3,
        total_sugars: 16,
        protein: 35,
        ingredients_text:
          "Beef patty, seeded bun (enriched wheat flour, water, sugar, soybean oil, yeast, sesame seeds, salt), American cheese, bacon (cured with water, salt, sugar, sodium phosphate, sodium nitrite), onion rings, BBQ sauce (high fructose corn syrup, tomato paste, vinegar, salt, spices)",
      },
      {
        name: "Super Star",
        category: "burger",
        serving_size: 348,
        serving_unit: "g",
        calories: 900,
        total_fat: 56,
        saturated_fat: 22,
        trans_fat: 2.5,
        cholesterol: 155,
        sodium: 1350,
        total_carbohydrates: 52,
        dietary_fiber: 3,
        total_sugars: 11,
        protein: 47,
        ingredients_text:
          "Beef patties (2), seeded bun (enriched wheat flour, water, sugar, soybean oil, yeast, sesame seeds, salt), American cheese (2 slices), lettuce, tomato, onion, pickles, ketchup, mustard, mayonnaise",
      },
      {
        name: "Big Hamburger",
        category: "burger",
        serving_size: 186,
        serving_unit: "g",
        calories: 460,
        total_fat: 17,
        saturated_fat: 6,
        trans_fat: 0.5,
        cholesterol: 60,
        sodium: 860,
        total_carbohydrates: 54,
        dietary_fiber: 2,
        total_sugars: 12,
        protein: 24,
        ingredients_text:
          "Beef patty, seeded bun (enriched wheat flour, water, sugar, soybean oil, yeast, sesame seeds, salt), lettuce, tomato, onion, pickles, ketchup, mustard",
      },
      {
        name: "Charbroiled Chicken Club",
        category: "sandwich",
        serving_size: 284,
        serving_unit: "g",
        calories: 560,
        total_fat: 25,
        saturated_fat: 8,
        trans_fat: 0,
        cholesterol: 105,
        sodium: 1410,
        total_carbohydrates: 43,
        dietary_fiber: 3,
        total_sugars: 9,
        protein: 42,
        ingredients_text:
          "Grilled chicken breast (chicken breast, water, seasoning, salt, garlic powder), bun (enriched wheat flour, water, sugar, soybean oil, yeast, salt), Swiss cheese, bacon, lettuce, tomato, mayonnaise",
      },
      {
        name: "Chicken Tenders 5pc",
        category: "chicken",
        serving_size: 170,
        serving_unit: "g",
        calories: 450,
        total_fat: 22,
        saturated_fat: 3.5,
        trans_fat: 0,
        cholesterol: 60,
        sodium: 1140,
        total_carbohydrates: 36,
        dietary_fiber: 2,
        total_sugars: 0,
        protein: 26,
        ingredients_text:
          "Chicken breast tenderloins, wheat flour, water, salt, spices, garlic powder, soybean oil, leavening (sodium acid pyrophosphate, sodium bicarbonate), dried egg whites",
      },
      {
        name: "Criss-Cut Fries",
        category: "side",
        serving_size: 139,
        serving_unit: "g",
        calories: 430,
        total_fat: 24,
        saturated_fat: 4,
        trans_fat: 0,
        cholesterol: 0,
        sodium: 890,
        total_carbohydrates: 50,
        dietary_fiber: 4,
        total_sugars: 0,
        protein: 5,
        ingredients_text:
          "Potatoes, vegetable oil (canola, soybean, cottonseed, sunflower), enriched wheat flour, salt, corn starch, onion powder, garlic powder, spices, dextrose, leavening",
      },
      {
        name: "Onion Rings",
        category: "side",
        serving_size: 128,
        serving_unit: "g",
        calories: 430,
        total_fat: 22,
        saturated_fat: 4.5,
        trans_fat: 0,
        cholesterol: 0,
        sodium: 640,
        total_carbohydrates: 53,
        dietary_fiber: 3,
        total_sugars: 7,
        protein: 6,
        ingredients_text:
          "Onion, bleached wheat flour, water, modified corn starch, salt, soybean oil, dextrose, leavening (sodium acid pyrophosphate, sodium bicarbonate), garlic powder",
      },
      {
        name: "Natural Cut Fries",
        category: "side",
        serving_size: 142,
        serving_unit: "g",
        calories: 380,
        total_fat: 18,
        saturated_fat: 2.5,
        trans_fat: 0,
        cholesterol: 0,
        sodium: 440,
        total_carbohydrates: 50,
        dietary_fiber: 4,
        total_sugars: 0,
        protein: 5,
        ingredients_text:
          "Potatoes, vegetable oil (canola, soybean), salt, dextrose, sodium acid pyrophosphate",
      },
      {
        name: "Hand-Breaded Chicken",
        category: "sandwich",
        serving_size: 241,
        serving_unit: "g",
        calories: 620,
        total_fat: 32,
        saturated_fat: 6,
        trans_fat: 0,
        cholesterol: 70,
        sodium: 1280,
        total_carbohydrates: 54,
        dietary_fiber: 3,
        total_sugars: 8,
        protein: 30,
        ingredients_text:
          "Breaded chicken breast (chicken breast, wheat flour, water, salt, spices, soybean oil, leavening, dried egg whites, buttermilk), bun (enriched wheat flour, water, sugar, soybean oil, yeast, salt), pickles, mayonnaise",
      },
      {
        name: "Biscuit N Gravy",
        category: "breakfast",
        serving_size: 227,
        serving_unit: "g",
        calories: 460,
        total_fat: 28,
        saturated_fat: 11,
        trans_fat: 0,
        cholesterol: 25,
        sodium: 1260,
        total_carbohydrates: 43,
        dietary_fiber: 1,
        total_sugars: 5,
        protein: 8,
        ingredients_text:
          "Biscuit (enriched wheat flour, buttermilk, palm oil, sugar, baking powder, salt), sausage gravy (water, pork sausage, wheat flour, soybean oil, salt, black pepper, sage)",
      },
      {
        name: "Breakfast Burger",
        category: "burger",
        serving_size: 312,
        serving_unit: "g",
        calories: 780,
        total_fat: 46,
        saturated_fat: 16,
        trans_fat: 1.5,
        cholesterol: 285,
        sodium: 1420,
        total_carbohydrates: 51,
        dietary_fiber: 2,
        total_sugars: 10,
        protein: 40,
        ingredients_text:
          "Beef patty, seeded bun (enriched wheat flour, water, sugar, soybean oil, yeast, sesame seeds, salt), fried egg, American cheese, bacon, hash rounds (potatoes, soybean oil, salt, dextrose), ketchup",
      },
      {
        name: "Chocolate Shake",
        category: "beverage",
        serving_size: 397,
        serving_unit: "ml",
        calories: 580,
        total_fat: 17,
        saturated_fat: 11,
        trans_fat: 0.5,
        cholesterol: 55,
        sodium: 360,
        total_carbohydrates: 96,
        dietary_fiber: 2,
        total_sugars: 80,
        protein: 12,
        ingredients_text:
          "Vanilla ice cream (milk, cream, sugar, corn syrup, nonfat milk solids, vanilla), chocolate syrup (water, sugar, cocoa, corn syrup), milk, whipped topping",
      },
      {
        name: "Oreo Cookie Shake",
        category: "beverage",
        serving_size: 397,
        serving_unit: "ml",
        calories: 620,
        total_fat: 22,
        saturated_fat: 13,
        trans_fat: 0.5,
        cholesterol: 60,
        sodium: 400,
        total_carbohydrates: 94,
        dietary_fiber: 1,
        total_sugars: 76,
        protein: 13,
        ingredients_text:
          "Vanilla ice cream (milk, cream, sugar, corn syrup, nonfat milk solids, vanilla), Oreo cookie pieces (wheat flour, sugar, palm oil, cocoa, salt, soy lecithin), milk, whipped topping",
      },
      {
        name: "Chocolate Chip Cookie",
        category: "dessert",
        serving_size: 71,
        serving_unit: "g",
        calories: 350,
        total_fat: 18,
        saturated_fat: 10,
        trans_fat: 0,
        cholesterol: 25,
        sodium: 280,
        total_carbohydrates: 44,
        dietary_fiber: 1,
        total_sugars: 28,
        protein: 3,
        ingredients_text:
          "Enriched wheat flour, sugar, butter, chocolate chips (sugar, chocolate liquor, cocoa butter, soy lecithin, vanilla), eggs, brown sugar, vanilla extract, baking soda, salt",
      },
    ],
  },

  // ======================== ZAXBY'S ========================
  {
    chain: "Zaxby's",
    items: [
      {
        name: "Chicken Fingerz Plate 5pc",
        category: "combo",
        serving_size: 425,
        serving_unit: "g",
        calories: 1090,
        total_fat: 52,
        saturated_fat: 9,
        trans_fat: 0,
        cholesterol: 110,
        sodium: 2680,
        total_carbohydrates: 102,
        dietary_fiber: 5,
        total_sugars: 5,
        protein: 54,
        ingredients_text:
          "Chicken fingerz (5) (chicken tenderloins, wheat flour, water, salt, spices, garlic powder, soybean oil, leavening, dried egg whites), crinkle fries (potatoes, vegetable oil, salt), Texas toast (enriched wheat flour, butter, garlic), coleslaw, Zax sauce",
      },
      {
        name: "Wings and Things",
        category: "combo",
        serving_size: 397,
        serving_unit: "g",
        calories: 1020,
        total_fat: 50,
        saturated_fat: 11,
        trans_fat: 0,
        cholesterol: 200,
        sodium: 2540,
        total_carbohydrates: 84,
        dietary_fiber: 4,
        total_sugars: 3,
        protein: 58,
        ingredients_text:
          "Chicken wings (chicken wing sections, water, salt), chicken fingerz (chicken tenderloins, wheat flour, water, salt, spices, soybean oil, leavening), crinkle fries, Texas toast, celery, Zax sauce",
      },
      {
        name: "Zalad Garden Caesar",
        category: "salad",
        serving_size: 369,
        serving_unit: "g",
        calories: 580,
        total_fat: 34,
        saturated_fat: 8,
        trans_fat: 0,
        cholesterol: 95,
        sodium: 1440,
        total_carbohydrates: 28,
        dietary_fiber: 5,
        total_sugars: 5,
        protein: 42,
        ingredients_text:
          "Romaine lettuce, grilled chicken breast, parmesan cheese, croutons (enriched wheat flour, soybean oil, salt, garlic), Caesar dressing (soybean oil, parmesan cheese, anchovy paste, egg yolks, lemon juice, garlic, salt), tomato, onion",
      },
      {
        name: "Kickin Chicken Sandwich",
        category: "sandwich",
        serving_size: 255,
        serving_unit: "g",
        calories: 620,
        total_fat: 30,
        saturated_fat: 6,
        trans_fat: 0,
        cholesterol: 80,
        sodium: 1520,
        total_carbohydrates: 54,
        dietary_fiber: 3,
        total_sugars: 7,
        protein: 34,
        ingredients_text:
          "Breaded chicken breast (chicken breast, wheat flour, water, salt, spices, soybean oil, leavening, dried egg whites), brioche bun (enriched wheat flour, butter, eggs, sugar, yeast, salt), lettuce, tomato, pickles, Tongue Torch sauce",
      },
      {
        name: "Zaxby's Club",
        category: "sandwich",
        serving_size: 298,
        serving_unit: "g",
        calories: 710,
        total_fat: 36,
        saturated_fat: 9,
        trans_fat: 0,
        cholesterol: 105,
        sodium: 1780,
        total_carbohydrates: 52,
        dietary_fiber: 3,
        total_sugars: 8,
        protein: 42,
        ingredients_text:
          "Breaded chicken breast (chicken breast, wheat flour, water, salt, spices, soybean oil, leavening), Texas toast (2 slices) (enriched wheat flour, butter, garlic), bacon, American cheese, lettuce, tomato, mayonnaise",
      },
      {
        name: "Chicken Fingerz 5pc",
        category: "chicken",
        serving_size: 213,
        serving_unit: "g",
        calories: 540,
        total_fat: 26,
        saturated_fat: 4.5,
        trans_fat: 0,
        cholesterol: 95,
        sodium: 1540,
        total_carbohydrates: 34,
        dietary_fiber: 2,
        total_sugars: 0,
        protein: 42,
        ingredients_text:
          "Chicken tenderloins, wheat flour, water, salt, spices, garlic powder, soybean oil, leavening (sodium acid pyrophosphate, sodium bicarbonate), dried egg whites",
      },
      {
        name: "Crinkle Fries",
        category: "side",
        serving_size: 170,
        serving_unit: "g",
        calories: 430,
        total_fat: 21,
        saturated_fat: 3.5,
        trans_fat: 0,
        cholesterol: 0,
        sodium: 480,
        total_carbohydrates: 56,
        dietary_fiber: 4,
        total_sugars: 0,
        protein: 5,
        ingredients_text:
          "Potatoes, vegetable oil (canola, soybean), salt, dextrose, sodium acid pyrophosphate",
      },
      {
        name: "Texas Toast",
        category: "side",
        serving_size: 57,
        serving_unit: "g",
        calories: 170,
        total_fat: 7,
        saturated_fat: 2,
        trans_fat: 0,
        cholesterol: 0,
        sodium: 260,
        total_carbohydrates: 22,
        dietary_fiber: 1,
        total_sugars: 2,
        protein: 4,
        ingredients_text:
          "Enriched wheat flour (wheat flour, niacin, reduced iron, thiamine mononitrate, riboflavin, folic acid), water, butter, sugar, yeast, salt, garlic powder",
      },
      {
        name: "Coleslaw",
        category: "side",
        serving_size: 113,
        serving_unit: "g",
        calories: 170,
        total_fat: 12,
        saturated_fat: 2,
        trans_fat: 0,
        cholesterol: 15,
        sodium: 210,
        total_carbohydrates: 15,
        dietary_fiber: 2,
        total_sugars: 11,
        protein: 1,
        ingredients_text:
          "Cabbage, carrots, sugar, soybean oil, distilled vinegar, corn syrup, egg yolks, salt, celery seed",
      },
      {
        name: "Celery",
        category: "side",
        serving_size: 85,
        serving_unit: "g",
        calories: 10,
        total_fat: 0,
        saturated_fat: 0,
        trans_fat: 0,
        cholesterol: 0,
        sodium: 50,
        total_carbohydrates: 2,
        dietary_fiber: 1,
        total_sugars: 1,
        protein: 0,
        ingredients_text: "Celery",
      },
      {
        name: "Fried White Cheddar Bites",
        category: "side",
        serving_size: 113,
        serving_unit: "g",
        calories: 380,
        total_fat: 22,
        saturated_fat: 9,
        trans_fat: 0,
        cholesterol: 40,
        sodium: 920,
        total_carbohydrates: 28,
        dietary_fiber: 1,
        total_sugars: 2,
        protein: 16,
        ingredients_text:
          "White cheddar cheese (pasteurized milk, cheese cultures, salt, enzymes), wheat flour, water, soybean oil, modified corn starch, salt, leavening, buttermilk",
      },
      {
        name: "Ranch Sauce",
        category: "sauce",
        serving_size: 43,
        serving_unit: "g",
        calories: 190,
        total_fat: 20,
        saturated_fat: 3,
        trans_fat: 0,
        cholesterol: 15,
        sodium: 340,
        total_carbohydrates: 2,
        dietary_fiber: 0,
        total_sugars: 1,
        protein: 1,
        ingredients_text:
          "Soybean oil, buttermilk, water, egg yolks, vinegar, salt, garlic, onion, dill, parsley, spices",
      },
      {
        name: "Tongue Torch Sauce",
        category: "sauce",
        serving_size: 28,
        serving_unit: "g",
        calories: 60,
        total_fat: 5,
        saturated_fat: 1,
        trans_fat: 0,
        cholesterol: 5,
        sodium: 440,
        total_carbohydrates: 3,
        dietary_fiber: 0,
        total_sugars: 2,
        protein: 0,
        ingredients_text:
          "Soybean oil, cayenne pepper sauce (aged cayenne peppers, vinegar, salt, garlic), vinegar, water, egg yolks, salt, spices",
      },
      {
        name: "Cookies and Cream Milkshake",
        category: "beverage",
        serving_size: 473,
        serving_unit: "ml",
        calories: 710,
        total_fat: 30,
        saturated_fat: 19,
        trans_fat: 1,
        cholesterol: 85,
        sodium: 420,
        total_carbohydrates: 98,
        dietary_fiber: 1,
        total_sugars: 82,
        protein: 14,
        ingredients_text:
          "Vanilla ice cream (milk, cream, sugar, corn syrup, nonfat milk solids, vanilla), Oreo cookie pieces (wheat flour, sugar, palm oil, cocoa, salt, soy lecithin), milk, whipped topping",
      },
      {
        name: "Sweet Tea",
        category: "beverage",
        serving_size: 591,
        serving_unit: "ml",
        calories: 190,
        total_fat: 0,
        saturated_fat: 0,
        trans_fat: 0,
        cholesterol: 0,
        sodium: 15,
        total_carbohydrates: 48,
        dietary_fiber: 0,
        total_sugars: 48,
        protein: 0,
        ingredients_text: "Brewed tea, water, sugar",
      },
    ],
  },

  // ======================== DEL TACO ========================
  {
    chain: "Del Taco",
    items: [
      {
        name: "Del Taco",
        category: "taco",
        serving_size: 85,
        serving_unit: "g",
        calories: 160,
        total_fat: 8,
        saturated_fat: 3,
        trans_fat: 0,
        cholesterol: 20,
        sodium: 340,
        total_carbohydrates: 14,
        dietary_fiber: 1,
        total_sugars: 1,
        protein: 8,
        ingredients_text:
          "Seasoned beef (beef, water, seasoning (chili pepper, salt, onion powder, garlic powder, cumin, paprika)), crunchy corn shell (corn masa flour, vegetable oil, salt, lime), lettuce, cheddar cheese",
      },
      {
        name: "Epic Cali Bacon Burrito",
        category: "burrito",
        serving_size: 340,
        serving_unit: "g",
        calories: 790,
        total_fat: 40,
        saturated_fat: 15,
        trans_fat: 0.5,
        cholesterol: 110,
        sodium: 1850,
        total_carbohydrates: 68,
        dietary_fiber: 5,
        total_sugars: 5,
        protein: 38,
        ingredients_text:
          "Flour tortilla (enriched wheat flour, water, vegetable shortening, salt, baking powder), seasoned beef, bacon, guacamole (avocado, lime juice, salt, cilantro, jalapeno), sour cream, cheddar cheese, pico de gallo, secret sauce",
      },
      {
        name: "Chicken Soft Taco",
        category: "taco",
        serving_size: 128,
        serving_unit: "g",
        calories: 210,
        total_fat: 10,
        saturated_fat: 3.5,
        trans_fat: 0,
        cholesterol: 35,
        sodium: 520,
        total_carbohydrates: 17,
        dietary_fiber: 1,
        total_sugars: 1,
        protein: 13,
        ingredients_text:
          "Flour tortilla (enriched wheat flour, water, vegetable shortening, salt), grilled chicken (chicken breast, water, seasoning, salt), lettuce, cheddar cheese, sour cream",
      },
      {
        name: "Bean and Cheese Burrito",
        category: "burrito",
        serving_size: 198,
        serving_unit: "g",
        calories: 430,
        total_fat: 14,
        saturated_fat: 6,
        trans_fat: 0,
        cholesterol: 20,
        sodium: 1050,
        total_carbohydrates: 59,
        dietary_fiber: 8,
        total_sugars: 3,
        protein: 17,
        ingredients_text:
          "Flour tortilla (enriched wheat flour, water, vegetable shortening, salt, baking powder), refried beans (pinto beans, water, soybean oil, salt), cheddar cheese, green sauce",
      },
      {
        name: "Crunchy Taco",
        category: "taco",
        serving_size: 78,
        serving_unit: "g",
        calories: 150,
        total_fat: 8,
        saturated_fat: 3,
        trans_fat: 0,
        cholesterol: 20,
        sodium: 310,
        total_carbohydrates: 12,
        dietary_fiber: 1,
        total_sugars: 0,
        protein: 7,
        ingredients_text:
          "Seasoned beef (beef, water, seasoning), crunchy corn shell (corn masa flour, vegetable oil, salt, lime), lettuce, cheddar cheese",
      },
      {
        name: "Quesadilla Chicken",
        category: "entree",
        serving_size: 227,
        serving_unit: "g",
        calories: 530,
        total_fat: 26,
        saturated_fat: 12,
        trans_fat: 0,
        cholesterol: 75,
        sodium: 1210,
        total_carbohydrates: 42,
        dietary_fiber: 2,
        total_sugars: 2,
        protein: 30,
        ingredients_text:
          "Flour tortilla (enriched wheat flour, water, vegetable shortening, salt), grilled chicken, cheddar cheese, mozzarella cheese, creamy chipotle sauce",
      },
      {
        name: "Crinkle Cut Fries",
        category: "side",
        serving_size: 142,
        serving_unit: "g",
        calories: 370,
        total_fat: 18,
        saturated_fat: 3,
        trans_fat: 0,
        cholesterol: 0,
        sodium: 430,
        total_carbohydrates: 48,
        dietary_fiber: 4,
        total_sugars: 0,
        protein: 4,
        ingredients_text:
          "Potatoes, vegetable oil (canola, soybean), salt, dextrose, sodium acid pyrophosphate",
      },
      {
        name: "Churros",
        category: "dessert",
        serving_size: 57,
        serving_unit: "g",
        calories: 210,
        total_fat: 10,
        saturated_fat: 2,
        trans_fat: 0,
        cholesterol: 5,
        sodium: 180,
        total_carbohydrates: 28,
        dietary_fiber: 1,
        total_sugars: 10,
        protein: 2,
        ingredients_text:
          "Enriched wheat flour, water, soybean oil, sugar, salt, cinnamon sugar coating (sugar, cinnamon), leavening (sodium acid pyrophosphate, sodium bicarbonate)",
      },
      {
        name: "Chicken Rollers 2pc",
        category: "entree",
        serving_size: 142,
        serving_unit: "g",
        calories: 320,
        total_fat: 14,
        saturated_fat: 5,
        trans_fat: 0,
        cholesterol: 40,
        sodium: 780,
        total_carbohydrates: 32,
        dietary_fiber: 1,
        total_sugars: 1,
        protein: 16,
        ingredients_text:
          "Flour tortilla (enriched wheat flour, water, vegetable shortening, salt), grilled chicken, cheddar cheese, creamy chipotle sauce",
      },
      {
        name: "Loaded Queso Fries",
        category: "side",
        serving_size: 255,
        serving_unit: "g",
        calories: 640,
        total_fat: 36,
        saturated_fat: 10,
        trans_fat: 0,
        cholesterol: 40,
        sodium: 1320,
        total_carbohydrates: 62,
        dietary_fiber: 5,
        total_sugars: 3,
        protein: 16,
        ingredients_text:
          "Crinkle cut fries (potatoes, vegetable oil, salt), queso (cheddar cheese, milk, water, sodium phosphate), seasoned beef, sour cream, pico de gallo",
      },
      {
        name: "Classic Grilled Chicken Burrito",
        category: "burrito",
        serving_size: 283,
        serving_unit: "g",
        calories: 550,
        total_fat: 22,
        saturated_fat: 8,
        trans_fat: 0,
        cholesterol: 70,
        sodium: 1480,
        total_carbohydrates: 58,
        dietary_fiber: 4,
        total_sugars: 4,
        protein: 30,
        ingredients_text:
          "Flour tortilla (enriched wheat flour, water, vegetable shortening, salt, baking powder), grilled chicken, rice (rice, water, salt, soybean oil), pinto beans, cheddar cheese, sour cream, green sauce",
      },
      {
        name: "Beyond Avocado Taco",
        category: "taco",
        serving_size: 128,
        serving_unit: "g",
        calories: 250,
        total_fat: 14,
        saturated_fat: 4,
        trans_fat: 0,
        cholesterol: 0,
        sodium: 470,
        total_carbohydrates: 24,
        dietary_fiber: 4,
        total_sugars: 2,
        protein: 11,
        ingredients_text:
          "Flour tortilla (enriched wheat flour, water, vegetable shortening, salt), Beyond Meat crumbles (water, pea protein, expeller-pressed canola oil, refined coconut oil, rice protein, spices), avocado, lettuce, tomato",
      },
      {
        name: "Vanilla Shake",
        category: "beverage",
        serving_size: 397,
        serving_unit: "ml",
        calories: 530,
        total_fat: 16,
        saturated_fat: 10,
        trans_fat: 0.5,
        cholesterol: 55,
        sodium: 320,
        total_carbohydrates: 86,
        dietary_fiber: 0,
        total_sugars: 72,
        protein: 12,
        ingredients_text:
          "Vanilla ice cream (milk, cream, sugar, corn syrup, nonfat milk solids, vanilla extract), whipped topping, milk",
      },
      {
        name: "Hash Brown Sticks",
        category: "side",
        serving_size: 71,
        serving_unit: "g",
        calories: 180,
        total_fat: 10,
        saturated_fat: 1.5,
        trans_fat: 0,
        cholesterol: 0,
        sodium: 360,
        total_carbohydrates: 21,
        dietary_fiber: 2,
        total_sugars: 0,
        protein: 2,
        ingredients_text:
          "Potatoes, vegetable oil (canola, soybean), modified food starch, salt, dextrose, sodium acid pyrophosphate",
      },
      {
        name: "Breakfast Burrito",
        category: "burrito",
        serving_size: 198,
        serving_unit: "g",
        calories: 430,
        total_fat: 22,
        saturated_fat: 8,
        trans_fat: 0,
        cholesterol: 215,
        sodium: 980,
        total_carbohydrates: 38,
        dietary_fiber: 2,
        total_sugars: 3,
        protein: 19,
        ingredients_text:
          "Flour tortilla (enriched wheat flour, water, vegetable shortening, salt, baking powder), scrambled eggs, bacon (cured with water, salt, sugar, sodium phosphate, sodium nitrite), cheddar cheese, pico de gallo",
      },
    ],
  },

  // ======================== EL POLLO LOCO ========================
  {
    chain: "El Pollo Loco",
    items: [
      {
        name: "Chicken Breast",
        category: "chicken",
        serving_size: 128,
        serving_unit: "g",
        calories: 220,
        total_fat: 9,
        saturated_fat: 2.5,
        trans_fat: 0,
        cholesterol: 130,
        sodium: 640,
        total_carbohydrates: 0,
        dietary_fiber: 0,
        total_sugars: 0,
        protein: 35,
        ingredients_text:
          "Chicken breast (chicken breast, water, salt, sodium phosphate), citrus marinade (soybean oil, lime juice, garlic, spices, salt, annatto, turmeric)",
      },
      {
        name: "Chicken Thigh",
        category: "chicken",
        serving_size: 99,
        serving_unit: "g",
        calories: 210,
        total_fat: 13,
        saturated_fat: 3.5,
        trans_fat: 0,
        cholesterol: 115,
        sodium: 500,
        total_carbohydrates: 0,
        dietary_fiber: 0,
        total_sugars: 0,
        protein: 22,
        ingredients_text:
          "Chicken thigh (chicken thigh, water, salt, sodium phosphate), citrus marinade (soybean oil, lime juice, garlic, spices, salt, annatto, turmeric)",
      },
      {
        name: "Chicken Leg",
        category: "chicken",
        serving_size: 71,
        serving_unit: "g",
        calories: 130,
        total_fat: 7,
        saturated_fat: 2,
        trans_fat: 0,
        cholesterol: 85,
        sodium: 370,
        total_carbohydrates: 0,
        dietary_fiber: 0,
        total_sugars: 0,
        protein: 16,
        ingredients_text:
          "Chicken leg (chicken drumstick, water, salt, sodium phosphate), citrus marinade (soybean oil, lime juice, garlic, spices, salt, annatto, turmeric)",
      },
      {
        name: "BRC Burrito",
        category: "burrito",
        serving_size: 241,
        serving_unit: "g",
        calories: 490,
        total_fat: 16,
        saturated_fat: 6,
        trans_fat: 0,
        cholesterol: 20,
        sodium: 1120,
        total_carbohydrates: 67,
        dietary_fiber: 7,
        total_sugars: 3,
        protein: 18,
        ingredients_text:
          "Flour tortilla (enriched wheat flour, water, vegetable shortening, salt, baking powder), refried pinto beans (pinto beans, water, soybean oil, salt), rice (rice, water, salt), cheddar cheese",
      },
      {
        name: "Classic Chicken Burrito",
        category: "burrito",
        serving_size: 312,
        serving_unit: "g",
        calories: 590,
        total_fat: 20,
        saturated_fat: 6,
        trans_fat: 0,
        cholesterol: 80,
        sodium: 1440,
        total_carbohydrates: 68,
        dietary_fiber: 6,
        total_sugars: 4,
        protein: 34,
        ingredients_text:
          "Flour tortilla (enriched wheat flour, water, vegetable shortening, salt, baking powder), fire-grilled chicken, rice, pinto beans, cheddar cheese, avocado salsa",
      },
      {
        name: "Tostada Salad",
        category: "salad",
        serving_size: 454,
        serving_unit: "g",
        calories: 680,
        total_fat: 32,
        saturated_fat: 10,
        trans_fat: 0,
        cholesterol: 85,
        sodium: 1560,
        total_carbohydrates: 60,
        dietary_fiber: 10,
        total_sugars: 6,
        protein: 38,
        ingredients_text:
          "Flour tortilla shell (enriched wheat flour, soybean oil, water, salt), fire-grilled chicken, pinto beans, romaine lettuce, cheddar cheese, sour cream, avocado, pico de gallo, creamy cilantro dressing",
      },
      {
        name: "Mexican Rice",
        category: "side",
        serving_size: 128,
        serving_unit: "g",
        calories: 160,
        total_fat: 2,
        saturated_fat: 0,
        trans_fat: 0,
        cholesterol: 0,
        sodium: 440,
        total_carbohydrates: 32,
        dietary_fiber: 1,
        total_sugars: 1,
        protein: 3,
        ingredients_text:
          "Rice, water, tomato sauce (tomatoes, salt), soybean oil, salt, onion, garlic, cumin",
      },
      {
        name: "Pinto Beans",
        category: "side",
        serving_size: 170,
        serving_unit: "g",
        calories: 180,
        total_fat: 3.5,
        saturated_fat: 1,
        trans_fat: 0,
        cholesterol: 5,
        sodium: 620,
        total_carbohydrates: 28,
        dietary_fiber: 7,
        total_sugars: 1,
        protein: 10,
        ingredients_text:
          "Pinto beans, water, soybean oil, salt, onion, garlic, cumin, chili pepper",
      },
      {
        name: "Corn Tortilla",
        category: "side",
        serving_size: 28,
        serving_unit: "g",
        calories: 60,
        total_fat: 1,
        saturated_fat: 0,
        trans_fat: 0,
        cholesterol: 0,
        sodium: 40,
        total_carbohydrates: 12,
        dietary_fiber: 1,
        total_sugars: 0,
        protein: 2,
        ingredients_text: "Corn masa flour, water, lime",
      },
      {
        name: "Flour Tortilla",
        category: "side",
        serving_size: 43,
        serving_unit: "g",
        calories: 130,
        total_fat: 4,
        saturated_fat: 1.5,
        trans_fat: 0,
        cholesterol: 0,
        sodium: 290,
        total_carbohydrates: 21,
        dietary_fiber: 1,
        total_sugars: 1,
        protein: 3,
        ingredients_text:
          "Enriched wheat flour, water, vegetable shortening (soybean oil, hydrogenated soybean oil), salt, baking powder",
      },
      {
        name: "Creamy Cilantro Dressing",
        category: "sauce",
        serving_size: 43,
        serving_unit: "g",
        calories: 190,
        total_fat: 20,
        saturated_fat: 3,
        trans_fat: 0,
        cholesterol: 10,
        sodium: 310,
        total_carbohydrates: 2,
        dietary_fiber: 0,
        total_sugars: 1,
        protein: 1,
        ingredients_text:
          "Soybean oil, water, buttermilk, cilantro, egg yolks, vinegar, salt, garlic, lime juice, spices",
      },
      {
        name: "Chips and Guac",
        category: "side",
        serving_size: 142,
        serving_unit: "g",
        calories: 370,
        total_fat: 22,
        saturated_fat: 3,
        trans_fat: 0,
        cholesterol: 0,
        sodium: 540,
        total_carbohydrates: 40,
        dietary_fiber: 6,
        total_sugars: 2,
        protein: 5,
        ingredients_text:
          "Tortilla chips (corn, vegetable oil, salt, lime), guacamole (avocado, lime juice, salt, jalapeno, cilantro, onion)",
      },
      {
        name: "Chicken Taquito 2pc",
        category: "entree",
        serving_size: 99,
        serving_unit: "g",
        calories: 230,
        total_fat: 11,
        saturated_fat: 2.5,
        trans_fat: 0,
        cholesterol: 30,
        sodium: 520,
        total_carbohydrates: 22,
        dietary_fiber: 1,
        total_sugars: 1,
        protein: 11,
        ingredients_text:
          "Corn tortilla (corn masa flour, water, lime), chicken (chicken breast, water, salt), cheddar cheese, soybean oil",
      },
      {
        name: "Churro",
        category: "dessert",
        serving_size: 57,
        serving_unit: "g",
        calories: 210,
        total_fat: 9,
        saturated_fat: 2,
        trans_fat: 0,
        cholesterol: 5,
        sodium: 160,
        total_carbohydrates: 30,
        dietary_fiber: 1,
        total_sugars: 12,
        protein: 2,
        ingredients_text:
          "Enriched wheat flour, water, soybean oil, sugar, salt, cinnamon sugar coating (sugar, cinnamon), leavening (sodium acid pyrophosphate, sodium bicarbonate)",
      },
      {
        name: "Horchata",
        category: "beverage",
        serving_size: 473,
        serving_unit: "ml",
        calories: 320,
        total_fat: 5,
        saturated_fat: 1,
        trans_fat: 0,
        cholesterol: 0,
        sodium: 110,
        total_carbohydrates: 66,
        dietary_fiber: 0,
        total_sugars: 58,
        protein: 2,
        ingredients_text:
          "Water, sugar, rice flour, cinnamon, vanilla extract, nonfat dry milk",
      },
    ],
  },

  // ======================== COOKOUT ========================
  {
    chain: "Cookout",
    items: [
      {
        name: "Big Double Burger",
        category: "burger",
        serving_size: 284,
        serving_unit: "g",
        calories: 710,
        total_fat: 42,
        saturated_fat: 18,
        trans_fat: 2,
        cholesterol: 145,
        sodium: 980,
        total_carbohydrates: 42,
        dietary_fiber: 2,
        total_sugars: 8,
        protein: 42,
        ingredients_text:
          "Beef patties (2), bun (enriched wheat flour, water, sugar, soybean oil, yeast, salt), American cheese, lettuce, tomato, onion, pickles, ketchup, mustard, mayonnaise",
      },
      {
        name: "Cookout Tray Burger",
        category: "combo",
        serving_size: 454,
        serving_unit: "g",
        calories: 1050,
        total_fat: 52,
        saturated_fat: 18,
        trans_fat: 1.5,
        cholesterol: 110,
        sodium: 1680,
        total_carbohydrates: 108,
        dietary_fiber: 6,
        total_sugars: 16,
        protein: 38,
        ingredients_text:
          "Beef patty, bun (enriched wheat flour, water, sugar, soybean oil, yeast, salt), American cheese, lettuce, tomato, onion, pickles, ketchup, mustard, french fries (potatoes, vegetable oil, salt), hush puppies (cornmeal, wheat flour, water, sugar, egg, baking powder, salt), sweet tea",
      },
      {
        name: "BBQ Sandwich",
        category: "sandwich",
        serving_size: 198,
        serving_unit: "g",
        calories: 380,
        total_fat: 12,
        saturated_fat: 4,
        trans_fat: 0,
        cholesterol: 65,
        sodium: 1080,
        total_carbohydrates: 42,
        dietary_fiber: 2,
        total_sugars: 16,
        protein: 24,
        ingredients_text:
          "Chopped pork BBQ (pork, vinegar, ketchup, sugar, salt, spices, liquid smoke), bun (enriched wheat flour, water, sugar, soybean oil, yeast, salt), coleslaw (cabbage, carrots, sugar, mayonnaise, vinegar, salt)",
      },
      {
        name: "Hot Dog",
        category: "entree",
        serving_size: 113,
        serving_unit: "g",
        calories: 310,
        total_fat: 19,
        saturated_fat: 7,
        trans_fat: 0,
        cholesterol: 40,
        sodium: 830,
        total_carbohydrates: 24,
        dietary_fiber: 1,
        total_sugars: 4,
        protein: 11,
        ingredients_text:
          "Beef hot dog (beef, water, salt, corn syrup, sodium phosphate, sodium nitrite, paprika), bun (enriched wheat flour, water, sugar, soybean oil, yeast, salt), mustard, onion, chili",
      },
      {
        name: "Corn Dog",
        category: "entree",
        serving_size: 128,
        serving_unit: "g",
        calories: 340,
        total_fat: 18,
        saturated_fat: 5,
        trans_fat: 0,
        cholesterol: 35,
        sodium: 740,
        total_carbohydrates: 32,
        dietary_fiber: 1,
        total_sugars: 7,
        protein: 10,
        ingredients_text:
          "Beef hot dog (beef, water, salt, corn syrup, sodium phosphate, sodium nitrite), cornmeal batter (cornmeal, wheat flour, sugar, baking powder, salt, eggs, milk), soybean oil",
      },
      {
        name: "Chicken Strips 3pc",
        category: "chicken",
        serving_size: 156,
        serving_unit: "g",
        calories: 420,
        total_fat: 20,
        saturated_fat: 3.5,
        trans_fat: 0,
        cholesterol: 65,
        sodium: 1120,
        total_carbohydrates: 28,
        dietary_fiber: 1,
        total_sugars: 0,
        protein: 30,
        ingredients_text:
          "Chicken breast tenderloins, wheat flour, water, salt, spices, garlic powder, soybean oil, leavening (sodium acid pyrophosphate, sodium bicarbonate), dried egg whites",
      },
      {
        name: "Quesadilla",
        category: "entree",
        serving_size: 198,
        serving_unit: "g",
        calories: 440,
        total_fat: 24,
        saturated_fat: 11,
        trans_fat: 0,
        cholesterol: 55,
        sodium: 940,
        total_carbohydrates: 34,
        dietary_fiber: 2,
        total_sugars: 2,
        protein: 22,
        ingredients_text:
          "Flour tortilla (enriched wheat flour, water, vegetable shortening, salt), grilled chicken, cheddar cheese, mozzarella cheese",
      },
      {
        name: "Cajun Fries",
        category: "side",
        serving_size: 142,
        serving_unit: "g",
        calories: 400,
        total_fat: 20,
        saturated_fat: 3,
        trans_fat: 0,
        cholesterol: 0,
        sodium: 680,
        total_carbohydrates: 52,
        dietary_fiber: 4,
        total_sugars: 0,
        protein: 5,
        ingredients_text:
          "Potatoes, vegetable oil (canola, soybean), cajun seasoning (salt, garlic powder, paprika, cayenne pepper, onion powder, black pepper), dextrose",
      },
      {
        name: "Hush Puppies",
        category: "side",
        serving_size: 85,
        serving_unit: "g",
        calories: 260,
        total_fat: 12,
        saturated_fat: 2,
        trans_fat: 0,
        cholesterol: 20,
        sodium: 480,
        total_carbohydrates: 34,
        dietary_fiber: 2,
        total_sugars: 5,
        protein: 4,
        ingredients_text:
          "Cornmeal, wheat flour, water, sugar, onion, eggs, baking powder, salt, soybean oil",
      },
      {
        name: "Onion Rings",
        category: "side",
        serving_size: 128,
        serving_unit: "g",
        calories: 390,
        total_fat: 22,
        saturated_fat: 4,
        trans_fat: 0,
        cholesterol: 0,
        sodium: 560,
        total_carbohydrates: 44,
        dietary_fiber: 2,
        total_sugars: 5,
        protein: 5,
        ingredients_text:
          "Onion, bleached wheat flour, water, modified corn starch, salt, soybean oil, dextrose, leavening (sodium acid pyrophosphate, sodium bicarbonate), garlic powder",
      },
      {
        name: "Cookout Style Burger",
        category: "burger",
        serving_size: 227,
        serving_unit: "g",
        calories: 540,
        total_fat: 28,
        saturated_fat: 10,
        trans_fat: 1,
        cholesterol: 80,
        sodium: 880,
        total_carbohydrates: 42,
        dietary_fiber: 2,
        total_sugars: 10,
        protein: 28,
        ingredients_text:
          "Beef patty, bun (enriched wheat flour, water, sugar, soybean oil, yeast, salt), chili (beef, tomato, onion, spices, salt), coleslaw (cabbage, carrots, mayonnaise, sugar, vinegar), mustard, onion",
      },
      {
        name: "Cheese Coney",
        category: "entree",
        serving_size: 156,
        serving_unit: "g",
        calories: 420,
        total_fat: 24,
        saturated_fat: 10,
        trans_fat: 0.5,
        cholesterol: 55,
        sodium: 1050,
        total_carbohydrates: 28,
        dietary_fiber: 1,
        total_sugars: 5,
        protein: 19,
        ingredients_text:
          "Beef hot dog (beef, water, salt, corn syrup, sodium phosphate, sodium nitrite), bun (enriched wheat flour, water, sugar, soybean oil, yeast, salt), chili (beef, tomato, onion, spices, salt), cheddar cheese, onion, mustard",
      },
      {
        name: "Banana Shake",
        category: "beverage",
        serving_size: 473,
        serving_unit: "ml",
        calories: 590,
        total_fat: 18,
        saturated_fat: 11,
        trans_fat: 0.5,
        cholesterol: 60,
        sodium: 340,
        total_carbohydrates: 96,
        dietary_fiber: 1,
        total_sugars: 80,
        protein: 13,
        ingredients_text:
          "Vanilla ice cream (milk, cream, sugar, corn syrup, nonfat milk solids, vanilla), banana, milk, whipped topping",
      },
      {
        name: "Oreo Shake",
        category: "beverage",
        serving_size: 473,
        serving_unit: "ml",
        calories: 680,
        total_fat: 28,
        saturated_fat: 17,
        trans_fat: 1,
        cholesterol: 75,
        sodium: 410,
        total_carbohydrates: 96,
        dietary_fiber: 1,
        total_sugars: 80,
        protein: 13,
        ingredients_text:
          "Vanilla ice cream (milk, cream, sugar, corn syrup, nonfat milk solids, vanilla), Oreo cookie pieces (wheat flour, sugar, palm oil, cocoa, salt, soy lecithin), milk, whipped topping",
      },
      {
        name: "Sweet Tea",
        category: "beverage",
        serving_size: 591,
        serving_unit: "ml",
        calories: 190,
        total_fat: 0,
        saturated_fat: 0,
        trans_fat: 0,
        cholesterol: 0,
        sodium: 15,
        total_carbohydrates: 48,
        dietary_fiber: 0,
        total_sugars: 48,
        protein: 0,
        ingredients_text: "Brewed tea, water, sugar",
      },
    ],
  },
];

// ---------------------------------------------------------------------------
// SQL statements (same as import-chains.ts)
// ---------------------------------------------------------------------------

const upsertVendor = db.prepare(`
  INSERT INTO vendors (id, name, type, api_key)
  VALUES (@id, @name, @type, @api_key)
  ON CONFLICT(id) DO UPDATE SET
    name = excluded.name,
    type = excluded.type
`);

const upsertFood = db.prepare(`
  INSERT INTO foods (id, name, brand, category, serving_size, serving_unit, source, vendor_id,
    calories, total_fat, saturated_fat, trans_fat, cholesterol, sodium,
    total_carbohydrates, dietary_fiber, total_sugars, protein,
    ingredients_text, allergens, dietary_tags, nutri_score, nutri_grade,
    updated_at)
  VALUES (@id, @name, @brand, @category, @serving_size, @serving_unit, 'vendor', @vendor_id,
    @calories, @total_fat, @saturated_fat, @trans_fat, @cholesterol, @sodium,
    @total_carbohydrates, @dietary_fiber, @total_sugars, @protein,
    @ingredients_text, @allergens, @dietary_tags, @nutri_score, @nutri_grade,
    datetime('now'))
  ON CONFLICT(id) DO UPDATE SET
    name = excluded.name,
    brand = excluded.brand,
    category = excluded.category,
    serving_size = excluded.serving_size,
    serving_unit = excluded.serving_unit,
    vendor_id = excluded.vendor_id,
    calories = excluded.calories,
    total_fat = excluded.total_fat,
    saturated_fat = excluded.saturated_fat,
    trans_fat = excluded.trans_fat,
    cholesterol = excluded.cholesterol,
    sodium = excluded.sodium,
    total_carbohydrates = excluded.total_carbohydrates,
    dietary_fiber = excluded.dietary_fiber,
    total_sugars = excluded.total_sugars,
    protein = excluded.protein,
    ingredients_text = excluded.ingredients_text,
    allergens = excluded.allergens,
    dietary_tags = excluded.dietary_tags,
    nutri_score = excluded.nutri_score,
    nutri_grade = excluded.nutri_grade,
    updated_at = datetime('now')
`);

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function slugify(name: string): string {
  return name
    .toLowerCase()
    .replace(/['']/g, "")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

function buildFoodRecord(item: ChainMenuItem, chainName: string, vendorId: string) {
  const chainSlug = slugify(chainName);
  const itemSlug = slugify(item.name);
  const id = `chain-${chainSlug}-${itemSlug}`;

  // Calculate nutri-score (needs per-100g values)
  const servingG = item.serving_unit === "g" ? item.serving_size : item.serving_size * 1;
  const factor = servingG > 0 ? 100 / servingG : 1;

  const nutriResult = calculateNutriScore(
    {
      calories: item.calories * factor,
      totalSugars: item.total_sugars * factor,
      saturatedFat: item.saturated_fat * factor,
      sodium: item.sodium * factor,
      dietaryFiber: item.dietary_fiber * factor,
      protein: item.protein * factor,
    },
    item.category
  );

  const ingredientsText = item.ingredients_text || null;
  const allergens = ingredientsText ? detectAllergens(ingredientsText) : [];
  const dietaryTags = detectDietaryTags(ingredientsText || "", {
    total_carbohydrates: item.total_carbohydrates,
    protein: item.protein,
    total_fat: item.total_fat,
    total_sugars: item.total_sugars,
    dietary_fiber: item.dietary_fiber,
  });

  return {
    id,
    name: item.name,
    brand: chainName,
    category: item.category,
    serving_size: item.serving_size,
    serving_unit: item.serving_unit,
    vendor_id: vendorId,
    calories: item.calories,
    total_fat: item.total_fat,
    saturated_fat: item.saturated_fat,
    trans_fat: item.trans_fat,
    cholesterol: item.cholesterol,
    sodium: item.sodium,
    total_carbohydrates: item.total_carbohydrates,
    dietary_fiber: item.dietary_fiber,
    total_sugars: item.total_sugars,
    protein: item.protein,
    ingredients_text: ingredientsText,
    allergens: allergens.length > 0 ? allergens.join(",") : null,
    dietary_tags: dietaryTags.length > 0 ? dietaryTags.join(",") : null,
    nutri_score: nutriResult.score,
    nutri_grade: nutriResult.grade,
  };
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

function main() {
  console.log("=== Restaurant Chain Nutrition Import - Batch 5 ===\n");

  let totalItems = 0;
  let totalChains = 0;

  const beforeCount = (
    db.prepare("SELECT COUNT(*) as c FROM foods WHERE source = 'vendor'").get() as any
  ).c;

  const importAll = db.transaction(() => {
    for (const chain of chains) {
      const chainSlug = slugify(chain.chain);
      const vendorId = `chain-${chainSlug}`;

      // Create vendor record
      upsertVendor.run({
        id: vendorId,
        name: chain.chain,
        type: "restaurant",
        api_key: generateApiKey(),
      });

      console.log(`  ${chain.chain}: ${chain.items.length} items`);

      // Import each menu item
      for (const item of chain.items) {
        const record = buildFoodRecord(item, chain.chain, vendorId);
        upsertFood.run(record);
      }

      totalItems += chain.items.length;
      totalChains++;
    }
  });

  importAll();

  // Rebuild FTS index
  console.log("\nRebuilding search index...");
  db.exec("INSERT INTO foods_fts(foods_fts) VALUES('rebuild')");

  const afterCount = (
    db.prepare("SELECT COUNT(*) as c FROM foods WHERE source = 'vendor'").get() as any
  ).c;

  console.log(`\n=== Done! ===`);
  console.log(`Chains imported: ${totalChains}`);
  console.log(`Menu items processed: ${totalItems}`);
  console.log(`Vendor foods before: ${beforeCount}`);
  console.log(`Vendor foods after: ${afterCount}`);
  console.log(`New items added: ${afterCount - beforeCount}`);
}

main();
