/**
 * Restaurant Chain Nutrition Data Import - Batch 7 (Dessert, Coffee, Fast Casual)
 *
 * Imports manually curated nutrition data for dessert, coffee, and fast casual chains:
 * Krispy Kreme, Baskin-Robbins, Cold Stone Creamery, Tim Hortons, Cinnabon,
 * Cava, MOD Pizza, Blaze Pizza, Sheetz, Auntie Anne's
 *
 * Usage:
 *   npx ts-node scripts/import-chains-batch7.ts
 */

import { v4 as uuidv4 } from "uuid";
import db from "../src/data/database";
import { calculateNutriScore } from "../src/services/nutrition-score";
import { calculatePersonalHealthScore } from "../src/services/health-score";
import { detectAllergens, detectDietaryTags } from "../src/services/food-analysis";
import { generateApiKey } from "../src/middleware/auth";

interface ChainMenuItem {
  name: string;
  category: string;
  serving_size: number;
  serving_unit: string;
  calories: number;
  total_fat: number;
  saturated_fat: number;
  trans_fat: number;
  cholesterol: number;
  sodium: number;
  total_carbohydrates: number;
  dietary_fiber: number;
  total_sugars: number;
  protein: number;
  ingredients_text?: string;
}

interface ChainData {
  chain: string;
  items: ChainMenuItem[];
}

// ---------------------------------------------------------------------------
// Chain menu data
// ---------------------------------------------------------------------------

const chains: ChainData[] = [
  // ======================== KRISPY KREME ========================
  {
    chain: "Krispy Kreme",
    items: [
      {
        name: "Original Glazed",
        category: "dessert",
        serving_size: 52,
        serving_unit: "g",
        calories: 190,
        total_fat: 11,
        saturated_fat: 5,
        trans_fat: 0,
        cholesterol: 5,
        sodium: 85,
        total_carbohydrates: 22,
        dietary_fiber: 0,
        total_sugars: 10,
        protein: 3,
        ingredients_text:
          "Enriched wheat flour, sugar, palm oil, water, soybean oil, yeast, nonfat milk, egg yolks, mono and diglycerides, soy lecithin, salt, dextrose, calcium sulfate",
      },
      {
        name: "Chocolate Iced Glazed",
        category: "dessert",
        serving_size: 60,
        serving_unit: "g",
        calories: 240,
        total_fat: 12,
        saturated_fat: 5,
        trans_fat: 0,
        cholesterol: 5,
        sodium: 100,
        total_carbohydrates: 32,
        dietary_fiber: 1,
        total_sugars: 18,
        protein: 3,
        ingredients_text:
          "Enriched wheat flour, sugar, palm oil, cocoa, water, soybean oil, yeast, nonfat milk, egg yolks, chocolate icing (sugar, cocoa, palm kernel oil, corn syrup), soy lecithin, salt",
      },
      {
        name: "Chocolate Iced Sprinkles",
        category: "dessert",
        serving_size: 64,
        serving_unit: "g",
        calories: 260,
        total_fat: 12,
        saturated_fat: 5,
        trans_fat: 0,
        cholesterol: 5,
        sodium: 100,
        total_carbohydrates: 36,
        dietary_fiber: 1,
        total_sugars: 21,
        protein: 3,
        ingredients_text:
          "Enriched wheat flour, sugar, palm oil, cocoa, water, soybean oil, yeast, nonfat milk, egg yolks, chocolate icing, sprinkles (sugar, cornstarch, palm oil, soy lecithin, confectioners glaze), salt",
      },
      {
        name: "Glazed Raspberry Filled",
        category: "dessert",
        serving_size: 86,
        serving_unit: "g",
        calories: 300,
        total_fat: 16,
        saturated_fat: 7,
        trans_fat: 0,
        cholesterol: 5,
        sodium: 135,
        total_carbohydrates: 36,
        dietary_fiber: 1,
        total_sugars: 18,
        protein: 3,
        ingredients_text:
          "Enriched wheat flour, sugar, palm oil, water, raspberry filling (sugar, water, raspberries, modified corn starch, citric acid), soybean oil, yeast, nonfat milk, egg yolks, soy lecithin, salt",
      },
      {
        name: "Cinnamon Sugar",
        category: "dessert",
        serving_size: 54,
        serving_unit: "g",
        calories: 210,
        total_fat: 12,
        saturated_fat: 5,
        trans_fat: 0,
        cholesterol: 5,
        sodium: 85,
        total_carbohydrates: 24,
        dietary_fiber: 0,
        total_sugars: 11,
        protein: 3,
        ingredients_text:
          "Enriched wheat flour, sugar, palm oil, water, soybean oil, cinnamon, yeast, nonfat milk, egg yolks, soy lecithin, salt",
      },
      {
        name: "Powdered Cake",
        category: "dessert",
        serving_size: 71,
        serving_unit: "g",
        calories: 280,
        total_fat: 14,
        saturated_fat: 6,
        trans_fat: 0,
        cholesterol: 20,
        sodium: 320,
        total_carbohydrates: 37,
        dietary_fiber: 1,
        total_sugars: 18,
        protein: 3,
        ingredients_text:
          "Enriched wheat flour, sugar, palm oil, water, eggs, powdered sugar, baking powder, soybean oil, nonfat milk, salt, soy lecithin",
      },
      {
        name: "Glazed Chocolate Cake",
        category: "dessert",
        serving_size: 80,
        serving_unit: "g",
        calories: 300,
        total_fat: 15,
        saturated_fat: 7,
        trans_fat: 0,
        cholesterol: 20,
        sodium: 350,
        total_carbohydrates: 39,
        dietary_fiber: 2,
        total_sugars: 22,
        protein: 4,
        ingredients_text:
          "Enriched wheat flour, sugar, palm oil, cocoa, water, eggs, glaze (sugar, water, corn syrup), baking powder, soybean oil, nonfat milk, salt, soy lecithin",
      },
      {
        name: "Maple Iced Glazed",
        category: "dessert",
        serving_size: 60,
        serving_unit: "g",
        calories: 240,
        total_fat: 12,
        saturated_fat: 5,
        trans_fat: 0,
        cholesterol: 5,
        sodium: 100,
        total_carbohydrates: 32,
        dietary_fiber: 0,
        total_sugars: 19,
        protein: 3,
        ingredients_text:
          "Enriched wheat flour, sugar, palm oil, water, maple icing (sugar, water, corn syrup, natural and artificial maple flavor), soybean oil, yeast, nonfat milk, egg yolks, soy lecithin, salt",
      },
      {
        name: "Original Glazed Doughnut Holes 4pc",
        category: "dessert",
        serving_size: 64,
        serving_unit: "g",
        calories: 210,
        total_fat: 10,
        saturated_fat: 5,
        trans_fat: 0,
        cholesterol: 5,
        sodium: 95,
        total_carbohydrates: 28,
        dietary_fiber: 0,
        total_sugars: 13,
        protein: 3,
        ingredients_text:
          "Enriched wheat flour, sugar, palm oil, water, soybean oil, yeast, nonfat milk, egg yolks, soy lecithin, salt, glaze (sugar, water)",
      },
      {
        name: "Coffee medium",
        category: "beverage",
        serving_size: 473,
        serving_unit: "ml",
        calories: 5,
        total_fat: 0,
        saturated_fat: 0,
        trans_fat: 0,
        cholesterol: 0,
        sodium: 10,
        total_carbohydrates: 0,
        dietary_fiber: 0,
        total_sugars: 0,
        protein: 0,
        ingredients_text: "Brewed coffee",
      },
      {
        name: "Iced Coffee medium",
        category: "beverage",
        serving_size: 473,
        serving_unit: "ml",
        calories: 190,
        total_fat: 3,
        saturated_fat: 2,
        trans_fat: 0,
        cholesterol: 10,
        sodium: 80,
        total_carbohydrates: 39,
        dietary_fiber: 0,
        total_sugars: 37,
        protein: 2,
        ingredients_text:
          "Brewed coffee, ice, milk, sugar, vanilla syrup (sugar, water, natural flavors)",
      },
      {
        name: "Latte medium",
        category: "beverage",
        serving_size: 473,
        serving_unit: "ml",
        calories: 210,
        total_fat: 7,
        saturated_fat: 4.5,
        trans_fat: 0,
        cholesterol: 30,
        sodium: 170,
        total_carbohydrates: 28,
        dietary_fiber: 0,
        total_sugars: 27,
        protein: 10,
        ingredients_text: "Espresso, steamed milk, sugar",
      },
      {
        name: "Mocha medium",
        category: "beverage",
        serving_size: 473,
        serving_unit: "ml",
        calories: 290,
        total_fat: 9,
        saturated_fat: 5,
        trans_fat: 0,
        cholesterol: 30,
        sodium: 190,
        total_carbohydrates: 44,
        dietary_fiber: 1,
        total_sugars: 40,
        protein: 10,
        ingredients_text:
          "Espresso, steamed milk, chocolate sauce (sugar, cocoa, water, corn syrup), whipped cream",
      },
      {
        name: "Frozen Lemonade",
        category: "beverage",
        serving_size: 473,
        serving_unit: "ml",
        calories: 290,
        total_fat: 0,
        saturated_fat: 0,
        trans_fat: 0,
        cholesterol: 0,
        sodium: 15,
        total_carbohydrates: 76,
        dietary_fiber: 0,
        total_sugars: 70,
        protein: 0,
        ingredients_text: "Water, sugar, lemon juice concentrate, natural flavors, citric acid",
      },
      {
        name: "Glazed Cruller",
        category: "dessert",
        serving_size: 54,
        serving_unit: "g",
        calories: 240,
        total_fat: 14,
        saturated_fat: 6,
        trans_fat: 0,
        cholesterol: 35,
        sodium: 240,
        total_carbohydrates: 26,
        dietary_fiber: 0,
        total_sugars: 14,
        protein: 3,
        ingredients_text:
          "Enriched wheat flour, water, sugar, palm oil, eggs, glaze (sugar, water, corn syrup), baking powder, salt, soy lecithin",
      },
    ],
  },

  // ======================== BASKIN-ROBBINS ========================
  {
    chain: "Baskin-Robbins",
    items: [
      {
        name: "Vanilla 1 scoop",
        category: "dessert",
        serving_size: 113,
        serving_unit: "g",
        calories: 260,
        total_fat: 14,
        saturated_fat: 9,
        trans_fat: 0.5,
        cholesterol: 60,
        sodium: 80,
        total_carbohydrates: 28,
        dietary_fiber: 0,
        total_sugars: 24,
        protein: 4,
        ingredients_text:
          "Cream, nonfat milk, sugar, corn syrup, vanilla extract, mono and diglycerides, guar gum, carrageenan",
      },
      {
        name: "Chocolate 1 scoop",
        category: "dessert",
        serving_size: 113,
        serving_unit: "g",
        calories: 270,
        total_fat: 14,
        saturated_fat: 9,
        trans_fat: 0.5,
        cholesterol: 55,
        sodium: 110,
        total_carbohydrates: 33,
        dietary_fiber: 1,
        total_sugars: 26,
        protein: 5,
        ingredients_text:
          "Cream, nonfat milk, sugar, cocoa, corn syrup, mono and diglycerides, guar gum, carrageenan",
      },
      {
        name: "Mint Chocolate Chip 1 scoop",
        category: "dessert",
        serving_size: 113,
        serving_unit: "g",
        calories: 270,
        total_fat: 16,
        saturated_fat: 10,
        trans_fat: 0.5,
        cholesterol: 60,
        sodium: 75,
        total_carbohydrates: 28,
        dietary_fiber: 0,
        total_sugars: 25,
        protein: 4,
        ingredients_text:
          "Cream, nonfat milk, sugar, chocolate chips (sugar, chocolate liquor, cocoa butter, soy lecithin), corn syrup, peppermint extract, green color, mono and diglycerides, guar gum",
      },
      {
        name: "Pralines n Cream 1 scoop",
        category: "dessert",
        serving_size: 113,
        serving_unit: "g",
        calories: 280,
        total_fat: 14,
        saturated_fat: 8,
        trans_fat: 0.5,
        cholesterol: 50,
        sodium: 130,
        total_carbohydrates: 35,
        dietary_fiber: 0,
        total_sugars: 28,
        protein: 4,
        ingredients_text:
          "Cream, nonfat milk, sugar, praline pecans (pecans, sugar, corn syrup, butter, salt), caramel ribbon (corn syrup, sugar, butter, cream, salt), mono and diglycerides, guar gum",
      },
      {
        name: "Jamoca Almond Fudge 1 scoop",
        category: "dessert",
        serving_size: 113,
        serving_unit: "g",
        calories: 270,
        total_fat: 14,
        saturated_fat: 8,
        trans_fat: 0.5,
        cholesterol: 50,
        sodium: 90,
        total_carbohydrates: 32,
        dietary_fiber: 1,
        total_sugars: 25,
        protein: 5,
        ingredients_text:
          "Cream, nonfat milk, sugar, roasted almonds, coffee extract, fudge ribbon (sugar, cocoa, corn syrup, water, cream), corn syrup, mono and diglycerides, guar gum",
      },
      {
        name: "Cookie Dough 1 scoop",
        category: "dessert",
        serving_size: 113,
        serving_unit: "g",
        calories: 300,
        total_fat: 15,
        saturated_fat: 10,
        trans_fat: 0.5,
        cholesterol: 55,
        sodium: 130,
        total_carbohydrates: 36,
        dietary_fiber: 0,
        total_sugars: 27,
        protein: 4,
        ingredients_text:
          "Cream, nonfat milk, sugar, cookie dough pieces (wheat flour, brown sugar, butter, sugar, chocolate chips, eggs, vanilla, salt), corn syrup, mono and diglycerides, guar gum",
      },
      {
        name: "Oreo Cookies n Cream Shake medium",
        category: "beverage",
        serving_size: 591,
        serving_unit: "ml",
        calories: 790,
        total_fat: 32,
        saturated_fat: 19,
        trans_fat: 1,
        cholesterol: 115,
        sodium: 430,
        total_carbohydrates: 113,
        dietary_fiber: 1,
        total_sugars: 92,
        protein: 14,
        ingredients_text:
          "Vanilla ice cream (cream, nonfat milk, sugar, corn syrup), milk, Oreo cookie pieces (wheat flour, sugar, cocoa, palm oil, soy lecithin), whipped cream",
      },
      {
        name: "Vanilla Shake medium",
        category: "beverage",
        serving_size: 591,
        serving_unit: "ml",
        calories: 720,
        total_fat: 29,
        saturated_fat: 18,
        trans_fat: 1,
        cholesterol: 115,
        sodium: 340,
        total_carbohydrates: 101,
        dietary_fiber: 0,
        total_sugars: 86,
        protein: 14,
        ingredients_text:
          "Vanilla ice cream (cream, nonfat milk, sugar, corn syrup, vanilla extract), milk, whipped cream",
      },
      {
        name: "Waffle Cone",
        category: "dessert",
        serving_size: 34,
        serving_unit: "g",
        calories: 160,
        total_fat: 4,
        saturated_fat: 1,
        trans_fat: 0,
        cholesterol: 10,
        sodium: 50,
        total_carbohydrates: 28,
        dietary_fiber: 0,
        total_sugars: 11,
        protein: 3,
        ingredients_text:
          "Enriched wheat flour, sugar, vegetable oil, eggs, brown sugar, salt, vanilla extract",
      },
      {
        name: "Sugar Cone",
        category: "dessert",
        serving_size: 14,
        serving_unit: "g",
        calories: 45,
        total_fat: 0,
        saturated_fat: 0,
        trans_fat: 0,
        cholesterol: 0,
        sodium: 35,
        total_carbohydrates: 10,
        dietary_fiber: 0,
        total_sugars: 3,
        protein: 1,
        ingredients_text: "Enriched wheat flour, sugar, tapioca starch, vegetable oil, salt",
      },
      {
        name: "Sundae Hot Fudge 1 scoop",
        category: "dessert",
        serving_size: 175,
        serving_unit: "g",
        calories: 450,
        total_fat: 20,
        saturated_fat: 13,
        trans_fat: 0.5,
        cholesterol: 70,
        sodium: 180,
        total_carbohydrates: 60,
        dietary_fiber: 2,
        total_sugars: 49,
        protein: 7,
        ingredients_text:
          "Vanilla ice cream (cream, nonfat milk, sugar), hot fudge (sugar, cocoa, cream, butter, corn syrup, water, salt), whipped cream, cherry",
      },
      {
        name: "Banana Split",
        category: "dessert",
        serving_size: 425,
        serving_unit: "g",
        calories: 950,
        total_fat: 35,
        saturated_fat: 21,
        trans_fat: 1,
        cholesterol: 120,
        sodium: 250,
        total_carbohydrates: 152,
        dietary_fiber: 4,
        total_sugars: 120,
        protein: 14,
        ingredients_text:
          "Vanilla, chocolate, and strawberry ice cream, banana, hot fudge, strawberry topping, pineapple topping, whipped cream, chopped almonds, cherries",
      },
      {
        name: "Cappuccino Blast medium",
        category: "beverage",
        serving_size: 473,
        serving_unit: "ml",
        calories: 480,
        total_fat: 14,
        saturated_fat: 9,
        trans_fat: 0.5,
        cholesterol: 50,
        sodium: 200,
        total_carbohydrates: 79,
        dietary_fiber: 0,
        total_sugars: 71,
        protein: 8,
        ingredients_text:
          "Milk, ice cream (cream, nonfat milk, sugar, corn syrup), coffee extract, whipped cream",
      },
      {
        name: "Ice Cream Cake slice",
        category: "dessert",
        serving_size: 131,
        serving_unit: "g",
        calories: 340,
        total_fat: 16,
        saturated_fat: 10,
        trans_fat: 0.5,
        cholesterol: 40,
        sodium: 190,
        total_carbohydrates: 45,
        dietary_fiber: 1,
        total_sugars: 33,
        protein: 4,
        ingredients_text:
          "Vanilla ice cream (cream, nonfat milk, sugar, corn syrup), chocolate cake crunch (wheat flour, sugar, cocoa, palm oil), fudge (sugar, cocoa, cream, water), whipped icing (sugar, palm oil, water, corn syrup)",
      },
      {
        name: "Warm Cookie Sundae",
        category: "dessert",
        serving_size: 213,
        serving_unit: "g",
        calories: 620,
        total_fat: 28,
        saturated_fat: 15,
        trans_fat: 0.5,
        cholesterol: 90,
        sodium: 310,
        total_carbohydrates: 84,
        dietary_fiber: 2,
        total_sugars: 58,
        protein: 8,
        ingredients_text:
          "Chocolate chip cookie (wheat flour, butter, sugar, brown sugar, chocolate chips, eggs, vanilla, salt, baking soda), vanilla ice cream, hot fudge, whipped cream",
      },
    ],
  },

  // ======================== COLD STONE CREAMERY ========================
  {
    chain: "Cold Stone Creamery",
    items: [
      {
        name: "Sweet Cream 1 scoop Like It",
        category: "dessert",
        serving_size: 142,
        serving_unit: "g",
        calories: 320,
        total_fat: 19,
        saturated_fat: 12,
        trans_fat: 0.5,
        cholesterol: 70,
        sodium: 110,
        total_carbohydrates: 33,
        dietary_fiber: 0,
        total_sugars: 27,
        protein: 5,
        ingredients_text:
          "Cream, nonfat milk, sugar, corn syrup, vanilla extract, guar gum, cellulose gum, carrageenan",
      },
      {
        name: "Cake Batter 1 scoop",
        category: "dessert",
        serving_size: 142,
        serving_unit: "g",
        calories: 340,
        total_fat: 19,
        saturated_fat: 12,
        trans_fat: 0.5,
        cholesterol: 70,
        sodium: 170,
        total_carbohydrates: 38,
        dietary_fiber: 0,
        total_sugars: 30,
        protein: 5,
        ingredients_text:
          "Cream, nonfat milk, sugar, cake mix (enriched wheat flour, sugar, palm oil, leavening), corn syrup, vanilla extract, yellow color, guar gum, cellulose gum",
      },
      {
        name: "Chocolate 1 scoop",
        category: "dessert",
        serving_size: 142,
        serving_unit: "g",
        calories: 320,
        total_fat: 19,
        saturated_fat: 12,
        trans_fat: 0.5,
        cholesterol: 65,
        sodium: 100,
        total_carbohydrates: 35,
        dietary_fiber: 1,
        total_sugars: 28,
        protein: 5,
        ingredients_text:
          "Cream, nonfat milk, sugar, cocoa, corn syrup, guar gum, cellulose gum, carrageenan",
      },
      {
        name: "Coffee Lovers 1 scoop",
        category: "dessert",
        serving_size: 142,
        serving_unit: "g",
        calories: 310,
        total_fat: 18,
        saturated_fat: 11,
        trans_fat: 0.5,
        cholesterol: 65,
        sodium: 100,
        total_carbohydrates: 33,
        dietary_fiber: 0,
        total_sugars: 27,
        protein: 5,
        ingredients_text:
          "Cream, nonfat milk, sugar, coffee extract, corn syrup, guar gum, cellulose gum, carrageenan",
      },
      {
        name: "Birthday Cake Remix Like It",
        category: "dessert",
        serving_size: 198,
        serving_unit: "g",
        calories: 510,
        total_fat: 24,
        saturated_fat: 15,
        trans_fat: 0.5,
        cholesterol: 75,
        sodium: 230,
        total_carbohydrates: 68,
        dietary_fiber: 0,
        total_sugars: 51,
        protein: 7,
        ingredients_text:
          "Cake batter ice cream (cream, nonfat milk, sugar, cake mix, corn syrup), rainbow sprinkles, brownie pieces (wheat flour, sugar, butter, cocoa, eggs), fudge",
      },
      {
        name: "Founder's Favorite Like It",
        category: "dessert",
        serving_size: 198,
        serving_unit: "g",
        calories: 490,
        total_fat: 27,
        saturated_fat: 16,
        trans_fat: 0.5,
        cholesterol: 80,
        sodium: 210,
        total_carbohydrates: 55,
        dietary_fiber: 1,
        total_sugars: 43,
        protein: 8,
        ingredients_text:
          "Sweet cream ice cream (cream, nonfat milk, sugar, corn syrup), pecans, brownie pieces (wheat flour, sugar, butter, cocoa, eggs), fudge, caramel",
      },
      {
        name: "Mud Pie Mojo Like It",
        category: "dessert",
        serving_size: 198,
        serving_unit: "g",
        calories: 520,
        total_fat: 27,
        saturated_fat: 14,
        trans_fat: 0.5,
        cholesterol: 70,
        sodium: 250,
        total_carbohydrates: 63,
        dietary_fiber: 2,
        total_sugars: 47,
        protein: 8,
        ingredients_text:
          "Coffee ice cream (cream, nonfat milk, sugar, coffee extract), Oreo cookies (wheat flour, sugar, cocoa, palm oil), peanut butter, roasted almonds, fudge",
      },
      {
        name: "PB&C Love It",
        category: "dessert",
        serving_size: 255,
        serving_unit: "g",
        calories: 770,
        total_fat: 47,
        saturated_fat: 22,
        trans_fat: 1,
        cholesterol: 95,
        sodium: 310,
        total_carbohydrates: 74,
        dietary_fiber: 3,
        total_sugars: 57,
        protein: 16,
        ingredients_text:
          "Chocolate ice cream (cream, nonfat milk, sugar, cocoa), peanut butter (peanuts, salt), chocolate chips (sugar, chocolate liquor, cocoa butter, soy lecithin)",
      },
      {
        name: "Waffle Bowl",
        category: "dessert",
        serving_size: 57,
        serving_unit: "g",
        calories: 220,
        total_fat: 5,
        saturated_fat: 1.5,
        trans_fat: 0,
        cholesterol: 15,
        sodium: 130,
        total_carbohydrates: 40,
        dietary_fiber: 1,
        total_sugars: 16,
        protein: 4,
        ingredients_text:
          "Enriched wheat flour, sugar, vegetable oil, eggs, brown sugar, salt, vanilla extract, baking powder",
      },
      {
        name: "Waffle Cone",
        category: "dessert",
        serving_size: 38,
        serving_unit: "g",
        calories: 160,
        total_fat: 4,
        saturated_fat: 1,
        trans_fat: 0,
        cholesterol: 10,
        sodium: 60,
        total_carbohydrates: 27,
        dietary_fiber: 0,
        total_sugars: 10,
        protein: 3,
        ingredients_text:
          "Enriched wheat flour, sugar, vegetable oil, eggs, brown sugar, salt, vanilla extract",
      },
      {
        name: "Brownie",
        category: "dessert",
        serving_size: 57,
        serving_unit: "g",
        calories: 200,
        total_fat: 7,
        saturated_fat: 3.5,
        trans_fat: 0,
        cholesterol: 30,
        sodium: 120,
        total_carbohydrates: 33,
        dietary_fiber: 1,
        total_sugars: 22,
        protein: 3,
        ingredients_text:
          "Sugar, enriched wheat flour, butter, eggs, cocoa, chocolate chips, vanilla extract, salt, baking powder",
      },
      {
        name: "Cookie Dough",
        category: "dessert",
        serving_size: 42,
        serving_unit: "g",
        calories: 180,
        total_fat: 8,
        saturated_fat: 5,
        trans_fat: 0,
        cholesterol: 20,
        sodium: 110,
        total_carbohydrates: 24,
        dietary_fiber: 0,
        total_sugars: 15,
        protein: 2,
        ingredients_text:
          "Wheat flour, sugar, brown sugar, butter, chocolate chips (sugar, chocolate liquor, cocoa butter, soy lecithin), eggs, vanilla, salt",
      },
      {
        name: "Fudge Sauce",
        category: "sauce",
        serving_size: 28,
        serving_unit: "g",
        calories: 80,
        total_fat: 2.5,
        saturated_fat: 1.5,
        trans_fat: 0,
        cholesterol: 5,
        sodium: 50,
        total_carbohydrates: 15,
        dietary_fiber: 1,
        total_sugars: 12,
        protein: 1,
        ingredients_text: "Sugar, cocoa, water, cream, corn syrup, butter, salt, vanilla extract",
      },
      {
        name: "Caramel Sauce",
        category: "sauce",
        serving_size: 28,
        serving_unit: "g",
        calories: 90,
        total_fat: 2,
        saturated_fat: 1,
        trans_fat: 0,
        cholesterol: 5,
        sodium: 70,
        total_carbohydrates: 18,
        dietary_fiber: 0,
        total_sugars: 15,
        protein: 0,
        ingredients_text: "Corn syrup, sugar, water, butter, cream, salt, vanilla extract",
      },
      {
        name: "Shake Like It",
        category: "beverage",
        serving_size: 473,
        serving_unit: "ml",
        calories: 590,
        total_fat: 29,
        saturated_fat: 18,
        trans_fat: 1,
        cholesterol: 105,
        sodium: 220,
        total_carbohydrates: 74,
        dietary_fiber: 0,
        total_sugars: 62,
        protein: 10,
        ingredients_text:
          "Sweet cream ice cream (cream, nonfat milk, sugar, corn syrup), milk, whipped cream",
      },
    ],
  },

  // ======================== TIM HORTONS ========================
  {
    chain: "Tim Hortons",
    items: [
      {
        name: "Double Double Coffee medium",
        category: "beverage",
        serving_size: 425,
        serving_unit: "ml",
        calories: 230,
        total_fat: 14,
        saturated_fat: 8,
        trans_fat: 0.5,
        cholesterol: 45,
        sodium: 40,
        total_carbohydrates: 24,
        dietary_fiber: 0,
        total_sugars: 24,
        protein: 2,
        ingredients_text: "Brewed coffee, cream (18%), sugar",
      },
      {
        name: "Iced Capp medium",
        category: "beverage",
        serving_size: 473,
        serving_unit: "ml",
        calories: 360,
        total_fat: 15,
        saturated_fat: 10,
        trans_fat: 0.5,
        cholesterol: 50,
        sodium: 130,
        total_carbohydrates: 51,
        dietary_fiber: 0,
        total_sugars: 49,
        protein: 5,
        ingredients_text:
          "Coffee extract, cream, sugar, milk, water, natural and artificial flavors, carrageenan",
      },
      {
        name: "French Vanilla medium",
        category: "beverage",
        serving_size: 425,
        serving_unit: "ml",
        calories: 310,
        total_fat: 10,
        saturated_fat: 6,
        trans_fat: 0.3,
        cholesterol: 35,
        sodium: 250,
        total_carbohydrates: 49,
        dietary_fiber: 0,
        total_sugars: 45,
        protein: 5,
        ingredients_text:
          "Water, sugar, cream, milk powder, modified corn starch, natural and artificial flavors, salt, carrageenan, sodium phosphate",
      },
      {
        name: "Original Blend Coffee medium",
        category: "beverage",
        serving_size: 425,
        serving_unit: "ml",
        calories: 5,
        total_fat: 0,
        saturated_fat: 0,
        trans_fat: 0,
        cholesterol: 0,
        sodium: 5,
        total_carbohydrates: 0,
        dietary_fiber: 0,
        total_sugars: 0,
        protein: 0,
        ingredients_text: "Brewed coffee",
      },
      {
        name: "Breakfast Sandwich Bacon",
        category: "sandwich",
        serving_size: 148,
        serving_unit: "g",
        calories: 370,
        total_fat: 17,
        saturated_fat: 7,
        trans_fat: 0.3,
        cholesterol: 175,
        sodium: 860,
        total_carbohydrates: 33,
        dietary_fiber: 1,
        total_sugars: 3,
        protein: 20,
        ingredients_text:
          "English muffin (enriched wheat flour, water, yeast, sugar, salt), egg, smoked bacon (pork, water, salt, sugar, sodium phosphate, sodium nitrite), processed cheese (milk, water, milkfat, sodium citrate, salt)",
      },
      {
        name: "Farmer's Breakfast Wrap",
        category: "sandwich",
        serving_size: 237,
        serving_unit: "g",
        calories: 530,
        total_fat: 28,
        saturated_fat: 11,
        trans_fat: 0.5,
        cholesterol: 220,
        sodium: 1210,
        total_carbohydrates: 42,
        dietary_fiber: 2,
        total_sugars: 3,
        protein: 26,
        ingredients_text:
          "Flour tortilla (enriched wheat flour, water, vegetable oil, salt), eggs, bacon, sausage, hash brown, processed cheese",
      },
      {
        name: "Everything Bagel with Cream Cheese",
        category: "bread",
        serving_size: 148,
        serving_unit: "g",
        calories: 400,
        total_fat: 13,
        saturated_fat: 7,
        trans_fat: 0,
        cholesterol: 35,
        sodium: 760,
        total_carbohydrates: 57,
        dietary_fiber: 2,
        total_sugars: 6,
        protein: 14,
        ingredients_text:
          "Enriched wheat flour, water, cream cheese (pasteurized milk, cream, salt, carob bean gum), sesame seeds, poppy seeds, onion flakes, garlic, salt, yeast, malt extract",
      },
      {
        name: "Chicken Wrap",
        category: "sandwich",
        serving_size: 230,
        serving_unit: "g",
        calories: 420,
        total_fat: 14,
        saturated_fat: 4,
        trans_fat: 0,
        cholesterol: 55,
        sodium: 1010,
        total_carbohydrates: 48,
        dietary_fiber: 3,
        total_sugars: 4,
        protein: 24,
        ingredients_text:
          "Flour tortilla (enriched wheat flour, water, vegetable oil, salt), grilled chicken breast, lettuce, tomato, ranch sauce (soybean oil, buttermilk, vinegar, egg yolks, salt, garlic, onion)",
      },
      {
        name: "Turkey Bacon Club",
        category: "sandwich",
        serving_size: 250,
        serving_unit: "g",
        calories: 480,
        total_fat: 17,
        saturated_fat: 5,
        trans_fat: 0,
        cholesterol: 65,
        sodium: 1340,
        total_carbohydrates: 50,
        dietary_fiber: 3,
        total_sugars: 5,
        protein: 30,
        ingredients_text:
          "Multigrain bread (whole wheat flour, water, oats, flax seeds, sugar, yeast, salt), turkey breast, bacon, lettuce, tomato, mayonnaise",
      },
      {
        name: "Donut Chocolate Dip",
        category: "dessert",
        serving_size: 62,
        serving_unit: "g",
        calories: 230,
        total_fat: 9,
        saturated_fat: 4,
        trans_fat: 0.2,
        cholesterol: 5,
        sodium: 200,
        total_carbohydrates: 34,
        dietary_fiber: 1,
        total_sugars: 14,
        protein: 4,
        ingredients_text:
          "Enriched wheat flour, sugar, palm oil, water, chocolate coating (sugar, cocoa, palm kernel oil, soy lecithin), yeast, soy lecithin, salt",
      },
      {
        name: "Donut Boston Cream",
        category: "dessert",
        serving_size: 93,
        serving_unit: "g",
        calories: 280,
        total_fat: 9,
        saturated_fat: 4,
        trans_fat: 0.2,
        cholesterol: 15,
        sodium: 240,
        total_carbohydrates: 45,
        dietary_fiber: 1,
        total_sugars: 22,
        protein: 4,
        ingredients_text:
          "Enriched wheat flour, sugar, palm oil, water, vanilla custard filling (sugar, water, modified corn starch, cream, egg yolks, vanilla), chocolate coating (sugar, cocoa, palm kernel oil), yeast, salt",
      },
      {
        name: "Timbit Original 1",
        category: "dessert",
        serving_size: 19,
        serving_unit: "g",
        calories: 70,
        total_fat: 3,
        saturated_fat: 1.5,
        trans_fat: 0.1,
        cholesterol: 5,
        sodium: 65,
        total_carbohydrates: 10,
        dietary_fiber: 0,
        total_sugars: 4,
        protein: 1,
        ingredients_text:
          "Enriched wheat flour, sugar, palm oil, water, soybean oil, yeast, nonfat milk, salt, soy lecithin",
      },
      {
        name: "Chili medium",
        category: "soup",
        serving_size: 340,
        serving_unit: "g",
        calories: 300,
        total_fat: 11,
        saturated_fat: 4,
        trans_fat: 0.5,
        cholesterol: 40,
        sodium: 1010,
        total_carbohydrates: 30,
        dietary_fiber: 8,
        total_sugars: 6,
        protein: 21,
        ingredients_text:
          "Water, beef, kidney beans, tomatoes, onion, tomato paste, green peppers, modified corn starch, spices, chili powder, salt, garlic, sugar",
      },
      {
        name: "Wedge Potato",
        category: "side",
        serving_size: 130,
        serving_unit: "g",
        calories: 290,
        total_fat: 14,
        saturated_fat: 1.5,
        trans_fat: 0,
        cholesterol: 0,
        sodium: 560,
        total_carbohydrates: 38,
        dietary_fiber: 3,
        total_sugars: 1,
        protein: 4,
        ingredients_text:
          "Potatoes, vegetable oil, modified corn starch, salt, dextrose, spices, garlic powder, onion powder",
      },
      {
        name: "Muffin Blueberry",
        category: "dessert",
        serving_size: 131,
        serving_unit: "g",
        calories: 360,
        total_fat: 12,
        saturated_fat: 2,
        trans_fat: 0,
        cholesterol: 45,
        sodium: 430,
        total_carbohydrates: 57,
        dietary_fiber: 2,
        total_sugars: 29,
        protein: 5,
        ingredients_text:
          "Enriched wheat flour, sugar, blueberries, vegetable oil, eggs, water, modified corn starch, baking powder, salt, natural flavors",
      },
    ],
  },

  // ======================== CINNABON ========================
  {
    chain: "Cinnabon",
    items: [
      {
        name: "Classic Cinnamon Roll",
        category: "dessert",
        serving_size: 262,
        serving_unit: "g",
        calories: 880,
        total_fat: 36,
        saturated_fat: 17,
        trans_fat: 0,
        cholesterol: 50,
        sodium: 830,
        total_carbohydrates: 127,
        dietary_fiber: 3,
        total_sugars: 58,
        protein: 14,
        ingredients_text:
          "Enriched wheat flour, sugar, margarine (palm oil, water, soybean oil, salt, mono and diglycerides), cream cheese frosting (sugar, cream cheese, butter, vanilla), cinnamon, eggs, yeast, nonfat milk, salt",
      },
      {
        name: "MiniBon",
        category: "dessert",
        serving_size: 92,
        serving_unit: "g",
        calories: 350,
        total_fat: 13,
        saturated_fat: 6,
        trans_fat: 0,
        cholesterol: 20,
        sodium: 290,
        total_carbohydrates: 52,
        dietary_fiber: 1,
        total_sugars: 24,
        protein: 6,
        ingredients_text:
          "Enriched wheat flour, sugar, margarine, cream cheese frosting (sugar, cream cheese, butter, vanilla), cinnamon, eggs, yeast, nonfat milk, salt",
      },
      {
        name: "BonBites 6pc",
        category: "dessert",
        serving_size: 170,
        serving_unit: "g",
        calories: 520,
        total_fat: 19,
        saturated_fat: 9,
        trans_fat: 0,
        cholesterol: 30,
        sodium: 470,
        total_carbohydrates: 78,
        dietary_fiber: 2,
        total_sugars: 36,
        protein: 8,
        ingredients_text:
          "Enriched wheat flour, sugar, margarine, cream cheese frosting (sugar, cream cheese, butter, vanilla), cinnamon, eggs, yeast, nonfat milk, salt",
      },
      {
        name: "Caramel PecanBon",
        category: "dessert",
        serving_size: 290,
        serving_unit: "g",
        calories: 1080,
        total_fat: 50,
        saturated_fat: 19,
        trans_fat: 0,
        cholesterol: 55,
        sodium: 870,
        total_carbohydrates: 146,
        dietary_fiber: 4,
        total_sugars: 76,
        protein: 16,
        ingredients_text:
          "Enriched wheat flour, sugar, margarine, caramel (sugar, corn syrup, cream, butter, salt), pecans, cream cheese frosting, cinnamon, eggs, yeast, nonfat milk, salt",
      },
      {
        name: "Center of the Roll",
        category: "dessert",
        serving_size: 170,
        serving_unit: "g",
        calories: 580,
        total_fat: 22,
        saturated_fat: 10,
        trans_fat: 0,
        cholesterol: 35,
        sodium: 510,
        total_carbohydrates: 87,
        dietary_fiber: 2,
        total_sugars: 41,
        protein: 9,
        ingredients_text:
          "Enriched wheat flour, sugar, margarine, cream cheese frosting (sugar, cream cheese, butter, vanilla), cinnamon, eggs, yeast, nonfat milk, salt",
      },
      {
        name: "Mochalatta Chill medium",
        category: "beverage",
        serving_size: 473,
        serving_unit: "ml",
        calories: 440,
        total_fat: 18,
        saturated_fat: 11,
        trans_fat: 0,
        cholesterol: 55,
        sodium: 200,
        total_carbohydrates: 62,
        dietary_fiber: 1,
        total_sugars: 57,
        protein: 8,
        ingredients_text:
          "Milk, ice, coffee extract, chocolate sauce (sugar, cocoa, water, cream), whipped cream, sugar",
      },
      {
        name: "Cinnabon Stix 6pc",
        category: "dessert",
        serving_size: 130,
        serving_unit: "g",
        calories: 390,
        total_fat: 12,
        saturated_fat: 5,
        trans_fat: 0,
        cholesterol: 15,
        sodium: 370,
        total_carbohydrates: 63,
        dietary_fiber: 1,
        total_sugars: 26,
        protein: 6,
        ingredients_text:
          "Enriched wheat flour, sugar, margarine, cinnamon, cream cheese frosting (sugar, cream cheese, butter, vanilla), eggs, yeast, salt",
      },
      {
        name: "CinnaSweetles",
        category: "dessert",
        serving_size: 99,
        serving_unit: "g",
        calories: 340,
        total_fat: 11,
        saturated_fat: 5,
        trans_fat: 0,
        cholesterol: 15,
        sodium: 290,
        total_carbohydrates: 55,
        dietary_fiber: 1,
        total_sugars: 24,
        protein: 5,
        ingredients_text:
          "Enriched wheat flour, sugar, margarine, cinnamon sugar coating (sugar, cinnamon), eggs, yeast, nonfat milk, salt",
      },
      {
        name: "Churro Swirl",
        category: "dessert",
        serving_size: 120,
        serving_unit: "g",
        calories: 420,
        total_fat: 16,
        saturated_fat: 7,
        trans_fat: 0,
        cholesterol: 25,
        sodium: 350,
        total_carbohydrates: 63,
        dietary_fiber: 1,
        total_sugars: 28,
        protein: 6,
        ingredients_text:
          "Enriched wheat flour, sugar, margarine, cinnamon sugar, cream cheese frosting, eggs, yeast, salt, vegetable oil",
      },
      {
        name: "Cold Brew medium",
        category: "beverage",
        serving_size: 473,
        serving_unit: "ml",
        calories: 10,
        total_fat: 0,
        saturated_fat: 0,
        trans_fat: 0,
        cholesterol: 0,
        sodium: 10,
        total_carbohydrates: 2,
        dietary_fiber: 0,
        total_sugars: 0,
        protein: 0,
        ingredients_text: "Cold brewed coffee, water",
      },
      {
        name: "Cookie BonBite",
        category: "dessert",
        serving_size: 35,
        serving_unit: "g",
        calories: 140,
        total_fat: 6,
        saturated_fat: 3,
        trans_fat: 0,
        cholesterol: 10,
        sodium: 85,
        total_carbohydrates: 20,
        dietary_fiber: 0,
        total_sugars: 11,
        protein: 2,
        ingredients_text:
          "Enriched wheat flour, sugar, butter, chocolate chips (sugar, chocolate liquor, cocoa butter, soy lecithin), eggs, cream cheese frosting, vanilla, salt",
      },
      {
        name: "Strawberry CinnaBon",
        category: "dessert",
        serving_size: 275,
        serving_unit: "g",
        calories: 900,
        total_fat: 35,
        saturated_fat: 16,
        trans_fat: 0,
        cholesterol: 50,
        sodium: 810,
        total_carbohydrates: 134,
        dietary_fiber: 3,
        total_sugars: 64,
        protein: 13,
        ingredients_text:
          "Enriched wheat flour, sugar, margarine, strawberry filling (strawberries, sugar, water, modified corn starch), cream cheese frosting (sugar, cream cheese, butter, vanilla), cinnamon, eggs, yeast, nonfat milk, salt",
      },
      {
        name: "Cream Cheese Frosting cup",
        category: "sauce",
        serving_size: 38,
        serving_unit: "g",
        calories: 140,
        total_fat: 5,
        saturated_fat: 3,
        trans_fat: 0,
        cholesterol: 15,
        sodium: 85,
        total_carbohydrates: 23,
        dietary_fiber: 0,
        total_sugars: 20,
        protein: 0,
        ingredients_text:
          "Sugar, cream cheese (pasteurized milk, cream, salt, carob bean gum), butter, vanilla extract, salt",
      },
      {
        name: "Coffee medium",
        category: "beverage",
        serving_size: 473,
        serving_unit: "ml",
        calories: 5,
        total_fat: 0,
        saturated_fat: 0,
        trans_fat: 0,
        cholesterol: 0,
        sodium: 10,
        total_carbohydrates: 0,
        dietary_fiber: 0,
        total_sugars: 0,
        protein: 0,
        ingredients_text: "Brewed coffee",
      },
      {
        name: "Iced Coffee medium",
        category: "beverage",
        serving_size: 473,
        serving_unit: "ml",
        calories: 150,
        total_fat: 2,
        saturated_fat: 1.5,
        trans_fat: 0,
        cholesterol: 10,
        sodium: 60,
        total_carbohydrates: 32,
        dietary_fiber: 0,
        total_sugars: 30,
        protein: 2,
        ingredients_text:
          "Brewed coffee, ice, milk, sugar, vanilla syrup (sugar, water, natural flavors)",
      },
    ],
  },

  // ======================== CAVA ========================
  {
    chain: "Cava",
    items: [
      {
        name: "Greens and Grains Bowl",
        category: "bowl",
        serving_size: 380,
        serving_unit: "g",
        calories: 620,
        total_fat: 23,
        saturated_fat: 5,
        trans_fat: 0,
        cholesterol: 0,
        sodium: 980,
        total_carbohydrates: 84,
        dietary_fiber: 10,
        total_sugars: 6,
        protein: 18,
        ingredients_text:
          "Supergreens (arugula, spinach, romaine), basmati rice, lentils, roasted vegetables, hummus, tzatziki, lemon herb tahini, pita chips",
      },
      {
        name: "Pita Sandwich",
        category: "sandwich",
        serving_size: 310,
        serving_unit: "g",
        calories: 540,
        total_fat: 18,
        saturated_fat: 4,
        trans_fat: 0,
        cholesterol: 45,
        sodium: 1100,
        total_carbohydrates: 62,
        dietary_fiber: 5,
        total_sugars: 5,
        protein: 30,
        ingredients_text:
          "Pita bread (wheat flour, water, yeast, salt, sugar, olive oil), grilled chicken, hummus, tomato cucumber salad, pickled onions, lettuce",
      },
      {
        name: "Mini Pitas 3",
        category: "side",
        serving_size: 90,
        serving_unit: "g",
        calories: 230,
        total_fat: 2,
        saturated_fat: 0,
        trans_fat: 0,
        cholesterol: 0,
        sodium: 340,
        total_carbohydrates: 46,
        dietary_fiber: 2,
        total_sugars: 1,
        protein: 7,
        ingredients_text: "Wheat flour, water, yeast, salt, sugar, olive oil",
      },
      {
        name: "Chicken Bowl",
        category: "bowl",
        serving_size: 400,
        serving_unit: "g",
        calories: 680,
        total_fat: 25,
        saturated_fat: 5,
        trans_fat: 0,
        cholesterol: 85,
        sodium: 1150,
        total_carbohydrates: 72,
        dietary_fiber: 8,
        total_sugars: 5,
        protein: 38,
        ingredients_text:
          "Basmati rice, grilled chicken (chicken breast, olive oil, salt, spices), supergreens, hummus, roasted vegetables, tzatziki, lemon herb tahini",
      },
      {
        name: "Lamb Bowl",
        category: "bowl",
        serving_size: 400,
        serving_unit: "g",
        calories: 740,
        total_fat: 32,
        saturated_fat: 10,
        trans_fat: 0,
        cholesterol: 95,
        sodium: 1200,
        total_carbohydrates: 72,
        dietary_fiber: 8,
        total_sugars: 5,
        protein: 35,
        ingredients_text:
          "Basmati rice, braised lamb (lamb, olive oil, salt, cumin, coriander, garlic), supergreens, hummus, roasted vegetables, tzatziki, harissa",
      },
      {
        name: "Falafel Bowl",
        category: "bowl",
        serving_size: 390,
        serving_unit: "g",
        calories: 650,
        total_fat: 26,
        saturated_fat: 4,
        trans_fat: 0,
        cholesterol: 0,
        sodium: 1100,
        total_carbohydrates: 82,
        dietary_fiber: 12,
        total_sugars: 6,
        protein: 22,
        ingredients_text:
          "Basmati rice, falafel (chickpeas, onion, parsley, cilantro, garlic, cumin, salt), supergreens, hummus, roasted vegetables, tzatziki, lemon herb tahini",
      },
      {
        name: "Crazy Feta Dip",
        category: "side",
        serving_size: 57,
        serving_unit: "g",
        calories: 110,
        total_fat: 9,
        saturated_fat: 4,
        trans_fat: 0,
        cholesterol: 25,
        sodium: 280,
        total_carbohydrates: 3,
        dietary_fiber: 0,
        total_sugars: 2,
        protein: 4,
        ingredients_text:
          "Feta cheese (pasteurized milk, salt, enzymes), jalapeño, olive oil, lemon juice, garlic",
      },
      {
        name: "Hummus",
        category: "side",
        serving_size: 57,
        serving_unit: "g",
        calories: 100,
        total_fat: 6,
        saturated_fat: 1,
        trans_fat: 0,
        cholesterol: 0,
        sodium: 220,
        total_carbohydrates: 9,
        dietary_fiber: 2,
        total_sugars: 0,
        protein: 4,
        ingredients_text:
          "Chickpeas, tahini (sesame seeds), olive oil, lemon juice, garlic, salt, cumin",
      },
      {
        name: "Tzatziki",
        category: "side",
        serving_size: 57,
        serving_unit: "g",
        calories: 40,
        total_fat: 2,
        saturated_fat: 1,
        trans_fat: 0,
        cholesterol: 5,
        sodium: 130,
        total_carbohydrates: 4,
        dietary_fiber: 0,
        total_sugars: 2,
        protein: 2,
        ingredients_text:
          "Greek yogurt (pasteurized milk, live cultures), cucumber, garlic, olive oil, lemon juice, dill, salt",
      },
      {
        name: "Harissa",
        category: "sauce",
        serving_size: 28,
        serving_unit: "g",
        calories: 15,
        total_fat: 1,
        saturated_fat: 0,
        trans_fat: 0,
        cholesterol: 0,
        sodium: 160,
        total_carbohydrates: 2,
        dietary_fiber: 1,
        total_sugars: 1,
        protein: 0,
        ingredients_text:
          "Roasted red peppers, tomato, chili pepper, garlic, olive oil, caraway, coriander, salt",
      },
      {
        name: "Pita Chips",
        category: "side",
        serving_size: 42,
        serving_unit: "g",
        calories: 200,
        total_fat: 8,
        saturated_fat: 1,
        trans_fat: 0,
        cholesterol: 0,
        sodium: 310,
        total_carbohydrates: 28,
        dietary_fiber: 1,
        total_sugars: 1,
        protein: 4,
        ingredients_text: "Pita bread (wheat flour, water, yeast, salt), vegetable oil, sea salt",
      },
      {
        name: "Basmati Rice",
        category: "side",
        serving_size: 130,
        serving_unit: "g",
        calories: 210,
        total_fat: 3,
        saturated_fat: 0,
        trans_fat: 0,
        cholesterol: 0,
        sodium: 350,
        total_carbohydrates: 40,
        dietary_fiber: 1,
        total_sugars: 0,
        protein: 4,
        ingredients_text: "Basmati rice, water, olive oil, salt",
      },
      {
        name: "Supergreens",
        category: "side",
        serving_size: 85,
        serving_unit: "g",
        calories: 15,
        total_fat: 0,
        saturated_fat: 0,
        trans_fat: 0,
        cholesterol: 0,
        sodium: 10,
        total_carbohydrates: 2,
        dietary_fiber: 1,
        total_sugars: 1,
        protein: 2,
        ingredients_text: "Arugula, spinach, romaine lettuce",
      },
      {
        name: "Roasted Vegetables",
        category: "side",
        serving_size: 85,
        serving_unit: "g",
        calories: 50,
        total_fat: 2,
        saturated_fat: 0,
        trans_fat: 0,
        cholesterol: 0,
        sodium: 180,
        total_carbohydrates: 7,
        dietary_fiber: 2,
        total_sugars: 3,
        protein: 1,
        ingredients_text:
          "Sweet potatoes, red peppers, onions, olive oil, salt, pepper, cumin",
      },
      {
        name: "Lentil Soup",
        category: "soup",
        serving_size: 340,
        serving_unit: "g",
        calories: 230,
        total_fat: 6,
        saturated_fat: 1,
        trans_fat: 0,
        cholesterol: 0,
        sodium: 820,
        total_carbohydrates: 34,
        dietary_fiber: 8,
        total_sugars: 4,
        protein: 12,
        ingredients_text:
          "Red lentils, water, onion, carrots, celery, olive oil, tomato paste, cumin, coriander, garlic, salt, lemon juice",
      },
    ],
  },

  // ======================== MOD PIZZA ========================
  {
    chain: "MOD Pizza",
    items: [
      {
        name: "11 inch Mega Dough Cheese per slice",
        category: "pizza",
        serving_size: 128,
        serving_unit: "g",
        calories: 290,
        total_fat: 10,
        saturated_fat: 5,
        trans_fat: 0,
        cholesterol: 20,
        sodium: 580,
        total_carbohydrates: 38,
        dietary_fiber: 1,
        total_sugars: 4,
        protein: 12,
        ingredients_text:
          "Pizza dough (enriched wheat flour, water, sugar, olive oil, yeast, salt), mozzarella cheese (pasteurized milk, salt, enzymes), tomato sauce (tomatoes, salt, garlic, basil, oregano)",
      },
      {
        name: "Mad Dog per slice",
        category: "pizza",
        serving_size: 158,
        serving_unit: "g",
        calories: 360,
        total_fat: 16,
        saturated_fat: 7,
        trans_fat: 0,
        cholesterol: 40,
        sodium: 850,
        total_carbohydrates: 38,
        dietary_fiber: 2,
        total_sugars: 4,
        protein: 16,
        ingredients_text:
          "Pizza dough (enriched wheat flour, water, sugar, olive oil, yeast, salt), mozzarella cheese, pepperoni (pork, beef, salt, spices, paprika, garlic, sodium nitrite), Italian sausage, red sauce, red onion",
      },
      {
        name: "Dominic per slice",
        category: "pizza",
        serving_size: 150,
        serving_unit: "g",
        calories: 340,
        total_fat: 14,
        saturated_fat: 6,
        trans_fat: 0,
        cholesterol: 35,
        sodium: 780,
        total_carbohydrates: 39,
        dietary_fiber: 2,
        total_sugars: 4,
        protein: 14,
        ingredients_text:
          "Pizza dough (enriched wheat flour, water, sugar, olive oil, yeast, salt), mozzarella cheese, salami (pork, salt, spices, garlic, sodium nitrite), red sauce, tomatoes, oregano",
      },
      {
        name: "Lucy Sunshine per slice",
        category: "pizza",
        serving_size: 148,
        serving_unit: "g",
        calories: 330,
        total_fat: 14,
        saturated_fat: 6,
        trans_fat: 0,
        cholesterol: 30,
        sodium: 720,
        total_carbohydrates: 38,
        dietary_fiber: 2,
        total_sugars: 5,
        protein: 14,
        ingredients_text:
          "Pizza dough (enriched wheat flour, water, sugar, olive oil, yeast, salt), mozzarella cheese, pesto (basil, olive oil, parmesan, pine nuts, garlic), tomatoes, artichokes, garlic, red onion",
      },
      {
        name: "Tristan per slice",
        category: "pizza",
        serving_size: 155,
        serving_unit: "g",
        calories: 350,
        total_fat: 16,
        saturated_fat: 7,
        trans_fat: 0,
        cholesterol: 40,
        sodium: 830,
        total_carbohydrates: 38,
        dietary_fiber: 1,
        total_sugars: 4,
        protein: 16,
        ingredients_text:
          "Pizza dough (enriched wheat flour, water, sugar, olive oil, yeast, salt), mozzarella cheese, red sauce, pepperoni, bacon (pork, water, salt, sugar, sodium nitrite), ground beef",
      },
      {
        name: "Mini Cheese Pizza",
        category: "pizza",
        serving_size: 180,
        serving_unit: "g",
        calories: 410,
        total_fat: 14,
        saturated_fat: 7,
        trans_fat: 0,
        cholesterol: 30,
        sodium: 820,
        total_carbohydrates: 53,
        dietary_fiber: 2,
        total_sugars: 6,
        protein: 17,
        ingredients_text:
          "Pizza dough (enriched wheat flour, water, sugar, olive oil, yeast, salt), mozzarella cheese, tomato sauce",
      },
      {
        name: "Side Salad",
        category: "salad",
        serving_size: 120,
        serving_unit: "g",
        calories: 90,
        total_fat: 5,
        saturated_fat: 1.5,
        trans_fat: 0,
        cholesterol: 5,
        sodium: 210,
        total_carbohydrates: 8,
        dietary_fiber: 2,
        total_sugars: 3,
        protein: 4,
        ingredients_text:
          "Romaine lettuce, spring mix, tomatoes, cucumbers, parmesan cheese, croutons, Italian vinaigrette (olive oil, vinegar, garlic, oregano, salt)",
      },
      {
        name: "Garlic Strips",
        category: "side",
        serving_size: 85,
        serving_unit: "g",
        calories: 280,
        total_fat: 10,
        saturated_fat: 2,
        trans_fat: 0,
        cholesterol: 0,
        sodium: 480,
        total_carbohydrates: 40,
        dietary_fiber: 1,
        total_sugars: 3,
        protein: 8,
        ingredients_text:
          "Pizza dough (enriched wheat flour, water, sugar, olive oil, yeast, salt), garlic butter (butter, garlic, parsley), parmesan cheese",
      },
      {
        name: "No Name Cake",
        category: "dessert",
        serving_size: 85,
        serving_unit: "g",
        calories: 350,
        total_fat: 15,
        saturated_fat: 5,
        trans_fat: 0,
        cholesterol: 45,
        sodium: 280,
        total_carbohydrates: 50,
        dietary_fiber: 1,
        total_sugars: 33,
        protein: 4,
        ingredients_text:
          "Sugar, enriched wheat flour, butter, cocoa, eggs, chocolate frosting (sugar, cocoa, butter, milk), vanilla extract, baking soda, salt",
      },
      {
        name: "Cinnamon Strips",
        category: "dessert",
        serving_size: 85,
        serving_unit: "g",
        calories: 310,
        total_fat: 12,
        saturated_fat: 4,
        trans_fat: 0,
        cholesterol: 5,
        sodium: 350,
        total_carbohydrates: 45,
        dietary_fiber: 1,
        total_sugars: 16,
        protein: 6,
        ingredients_text:
          "Pizza dough (enriched wheat flour, water, sugar, olive oil, yeast, salt), butter, cinnamon sugar, vanilla icing (sugar, water, vanilla)",
      },
      {
        name: "Mushroom and Spinach per slice",
        category: "pizza",
        serving_size: 152,
        serving_unit: "g",
        calories: 300,
        total_fat: 11,
        saturated_fat: 5,
        trans_fat: 0,
        cholesterol: 20,
        sodium: 640,
        total_carbohydrates: 38,
        dietary_fiber: 2,
        total_sugars: 4,
        protein: 13,
        ingredients_text:
          "Pizza dough (enriched wheat flour, water, sugar, olive oil, yeast, salt), mozzarella cheese, mushrooms, spinach, garlic, red sauce, olive oil",
      },
      {
        name: "BBQ Chicken per slice",
        category: "pizza",
        serving_size: 160,
        serving_unit: "g",
        calories: 350,
        total_fat: 12,
        saturated_fat: 5,
        trans_fat: 0,
        cholesterol: 40,
        sodium: 770,
        total_carbohydrates: 42,
        dietary_fiber: 1,
        total_sugars: 8,
        protein: 18,
        ingredients_text:
          "Pizza dough (enriched wheat flour, water, sugar, olive oil, yeast, salt), mozzarella cheese, grilled chicken, BBQ sauce (tomato paste, sugar, vinegar, molasses, spices), red onion, cilantro",
      },
      {
        name: "Super Veggie per slice",
        category: "pizza",
        serving_size: 165,
        serving_unit: "g",
        calories: 300,
        total_fat: 11,
        saturated_fat: 4,
        trans_fat: 0,
        cholesterol: 15,
        sodium: 640,
        total_carbohydrates: 40,
        dietary_fiber: 3,
        total_sugars: 5,
        protein: 12,
        ingredients_text:
          "Pizza dough (enriched wheat flour, water, sugar, olive oil, yeast, salt), mozzarella cheese, mushrooms, roasted red peppers, artichokes, black olives, red onion, tomatoes, red sauce",
      },
      {
        name: "Breadsticks",
        category: "side",
        serving_size: 100,
        serving_unit: "g",
        calories: 300,
        total_fat: 9,
        saturated_fat: 2,
        trans_fat: 0,
        cholesterol: 0,
        sodium: 520,
        total_carbohydrates: 46,
        dietary_fiber: 2,
        total_sugars: 4,
        protein: 9,
        ingredients_text:
          "Pizza dough (enriched wheat flour, water, sugar, olive oil, yeast, salt), garlic butter (butter, garlic), parmesan cheese, parsley",
      },
      {
        name: "Chocolate Chip Cookie",
        category: "dessert",
        serving_size: 71,
        serving_unit: "g",
        calories: 320,
        total_fat: 15,
        saturated_fat: 8,
        trans_fat: 0,
        cholesterol: 30,
        sodium: 220,
        total_carbohydrates: 44,
        dietary_fiber: 1,
        total_sugars: 26,
        protein: 3,
        ingredients_text:
          "Enriched wheat flour, butter, sugar, brown sugar, chocolate chips (sugar, chocolate liquor, cocoa butter, soy lecithin), eggs, vanilla extract, baking soda, salt",
      },
    ],
  },

  // ======================== BLAZE PIZZA ========================
  {
    chain: "Blaze Pizza",
    items: [
      {
        name: "Build Your Own 11 inch Cheese per slice",
        category: "pizza",
        serving_size: 120,
        serving_unit: "g",
        calories: 270,
        total_fat: 9,
        saturated_fat: 4,
        trans_fat: 0,
        cholesterol: 18,
        sodium: 530,
        total_carbohydrates: 36,
        dietary_fiber: 1,
        total_sugars: 3,
        protein: 11,
        ingredients_text:
          "Pizza dough (enriched wheat flour, water, olive oil, sugar, yeast, salt), mozzarella cheese (pasteurized milk, salt, enzymes), red sauce (tomatoes, salt, garlic, basil)",
      },
      {
        name: "Green Stripe per slice",
        category: "pizza",
        serving_size: 145,
        serving_unit: "g",
        calories: 310,
        total_fat: 13,
        saturated_fat: 5,
        trans_fat: 0,
        cholesterol: 25,
        sodium: 680,
        total_carbohydrates: 36,
        dietary_fiber: 2,
        total_sugars: 3,
        protein: 13,
        ingredients_text:
          "Pizza dough (enriched wheat flour, water, olive oil, sugar, yeast, salt), mozzarella cheese, pesto drizzle (basil, olive oil, parmesan, garlic, pine nuts), chicken, roasted garlic, tomatoes, oregano",
      },
      {
        name: "Red Vine per slice",
        category: "pizza",
        serving_size: 152,
        serving_unit: "g",
        calories: 330,
        total_fat: 14,
        saturated_fat: 6,
        trans_fat: 0,
        cholesterol: 30,
        sodium: 750,
        total_carbohydrates: 37,
        dietary_fiber: 2,
        total_sugars: 4,
        protein: 14,
        ingredients_text:
          "Pizza dough (enriched wheat flour, water, olive oil, sugar, yeast, salt), mozzarella cheese, red sauce, pepperoni (pork, beef, salt, spices), Italian sausage, red onion, mushrooms",
      },
      {
        name: "Art Lover per slice",
        category: "pizza",
        serving_size: 148,
        serving_unit: "g",
        calories: 310,
        total_fat: 12,
        saturated_fat: 5,
        trans_fat: 0,
        cholesterol: 22,
        sodium: 680,
        total_carbohydrates: 37,
        dietary_fiber: 2,
        total_sugars: 4,
        protein: 13,
        ingredients_text:
          "Pizza dough (enriched wheat flour, water, olive oil, sugar, yeast, salt), mozzarella cheese, ricotta (milk, whey, cream, vinegar, salt), red sauce, artichokes, tomatoes, garlic, basil",
      },
      {
        name: "Meat Eater per slice",
        category: "pizza",
        serving_size: 165,
        serving_unit: "g",
        calories: 380,
        total_fat: 18,
        saturated_fat: 8,
        trans_fat: 0.5,
        cholesterol: 45,
        sodium: 940,
        total_carbohydrates: 37,
        dietary_fiber: 1,
        total_sugars: 4,
        protein: 18,
        ingredients_text:
          "Pizza dough (enriched wheat flour, water, olive oil, sugar, yeast, salt), mozzarella cheese, red sauce, pepperoni, Italian sausage, meatballs (beef, pork, breadcrumbs, parmesan, egg), bacon",
      },
      {
        name: "Veg Out per slice",
        category: "pizza",
        serving_size: 155,
        serving_unit: "g",
        calories: 290,
        total_fat: 11,
        saturated_fat: 4,
        trans_fat: 0,
        cholesterol: 15,
        sodium: 600,
        total_carbohydrates: 39,
        dietary_fiber: 3,
        total_sugars: 5,
        protein: 12,
        ingredients_text:
          "Pizza dough (enriched wheat flour, water, olive oil, sugar, yeast, salt), mozzarella cheese, red sauce, mushrooms, red onion, black olives, roasted red peppers, tomatoes, oregano",
      },
      {
        name: "Simple Pie per slice",
        category: "pizza",
        serving_size: 130,
        serving_unit: "g",
        calories: 280,
        total_fat: 10,
        saturated_fat: 5,
        trans_fat: 0,
        cholesterol: 20,
        sodium: 570,
        total_carbohydrates: 36,
        dietary_fiber: 1,
        total_sugars: 3,
        protein: 12,
        ingredients_text:
          "Pizza dough (enriched wheat flour, water, olive oil, sugar, yeast, salt), mozzarella cheese, red sauce, fresh basil, olive oil drizzle",
      },
      {
        name: "S'more Pie slice",
        category: "dessert",
        serving_size: 105,
        serving_unit: "g",
        calories: 380,
        total_fat: 14,
        saturated_fat: 7,
        trans_fat: 0,
        cholesterol: 15,
        sodium: 260,
        total_carbohydrates: 58,
        dietary_fiber: 2,
        total_sugars: 34,
        protein: 5,
        ingredients_text:
          "Pizza dough, Nutella (sugar, palm oil, hazelnuts, cocoa, skim milk, soy lecithin), marshmallow, graham cracker crumble (wheat flour, sugar, palm oil, honey, cinnamon)",
      },
      {
        name: "Chocolate Chip Cookie",
        category: "dessert",
        serving_size: 71,
        serving_unit: "g",
        calories: 310,
        total_fat: 14,
        saturated_fat: 8,
        trans_fat: 0,
        cholesterol: 25,
        sodium: 200,
        total_carbohydrates: 43,
        dietary_fiber: 1,
        total_sugars: 24,
        protein: 3,
        ingredients_text:
          "Enriched wheat flour, butter, sugar, brown sugar, chocolate chips (sugar, chocolate liquor, cocoa butter, soy lecithin), eggs, vanilla, baking soda, salt",
      },
      {
        name: "Blood Orange Lemonade",
        category: "beverage",
        serving_size: 473,
        serving_unit: "ml",
        calories: 180,
        total_fat: 0,
        saturated_fat: 0,
        trans_fat: 0,
        cholesterol: 0,
        sodium: 10,
        total_carbohydrates: 46,
        dietary_fiber: 0,
        total_sugars: 44,
        protein: 0,
        ingredients_text:
          "Water, sugar, lemon juice concentrate, blood orange juice concentrate, natural flavors, citric acid",
      },
      {
        name: "Side Salad",
        category: "salad",
        serving_size: 115,
        serving_unit: "g",
        calories: 80,
        total_fat: 4,
        saturated_fat: 1.5,
        trans_fat: 0,
        cholesterol: 5,
        sodium: 190,
        total_carbohydrates: 7,
        dietary_fiber: 2,
        total_sugars: 3,
        protein: 4,
        ingredients_text:
          "Romaine lettuce, cherry tomatoes, red onion, parmesan cheese, Italian dressing (olive oil, vinegar, garlic, herbs, salt)",
      },
      {
        name: "Garlic Bread",
        category: "side",
        serving_size: 90,
        serving_unit: "g",
        calories: 270,
        total_fat: 10,
        saturated_fat: 3,
        trans_fat: 0,
        cholesterol: 5,
        sodium: 450,
        total_carbohydrates: 38,
        dietary_fiber: 1,
        total_sugars: 3,
        protein: 8,
        ingredients_text:
          "Pizza dough (enriched wheat flour, water, olive oil, sugar, yeast, salt), garlic butter (butter, garlic, parsley), parmesan cheese",
      },
      {
        name: "White Top per slice",
        category: "pizza",
        serving_size: 148,
        serving_unit: "g",
        calories: 340,
        total_fat: 16,
        saturated_fat: 7,
        trans_fat: 0,
        cholesterol: 30,
        sodium: 680,
        total_carbohydrates: 36,
        dietary_fiber: 1,
        total_sugars: 3,
        protein: 15,
        ingredients_text:
          "Pizza dough (enriched wheat flour, water, olive oil, sugar, yeast, salt), mozzarella cheese, ricotta, white cream sauce (cream, butter, parmesan, garlic), garlic, oregano, basil",
      },
      {
        name: "BBQ Chkn per slice",
        category: "pizza",
        serving_size: 158,
        serving_unit: "g",
        calories: 340,
        total_fat: 12,
        saturated_fat: 5,
        trans_fat: 0,
        cholesterol: 40,
        sodium: 760,
        total_carbohydrates: 41,
        dietary_fiber: 1,
        total_sugars: 8,
        protein: 17,
        ingredients_text:
          "Pizza dough (enriched wheat flour, water, olive oil, sugar, yeast, salt), mozzarella cheese, grilled chicken, BBQ sauce (tomato paste, sugar, vinegar, molasses, spices), red onion, banana peppers",
      },
      {
        name: "Hot Link per slice",
        category: "pizza",
        serving_size: 158,
        serving_unit: "g",
        calories: 370,
        total_fat: 17,
        saturated_fat: 7,
        trans_fat: 0,
        cholesterol: 40,
        sodium: 900,
        total_carbohydrates: 37,
        dietary_fiber: 2,
        total_sugars: 4,
        protein: 16,
        ingredients_text:
          "Pizza dough (enriched wheat flour, water, olive oil, sugar, yeast, salt), mozzarella cheese, red sauce, Italian sausage, pepperoni, banana peppers, red onion, jalapeños",
      },
    ],
  },

  // ======================== SHEETZ ========================
  {
    chain: "Sheetz",
    items: [
      {
        name: "Classic Sub",
        category: "sandwich",
        serving_size: 300,
        serving_unit: "g",
        calories: 620,
        total_fat: 28,
        saturated_fat: 10,
        trans_fat: 0.5,
        cholesterol: 80,
        sodium: 1640,
        total_carbohydrates: 56,
        dietary_fiber: 3,
        total_sugars: 7,
        protein: 32,
        ingredients_text:
          "Sub roll (enriched wheat flour, water, sugar, yeast, soybean oil, salt), ham, turkey, American cheese, lettuce, tomato, onion, Italian dressing, oil, vinegar",
      },
      {
        name: "Boom Boom Chicken Sandwich",
        category: "sandwich",
        serving_size: 260,
        serving_unit: "g",
        calories: 680,
        total_fat: 34,
        saturated_fat: 6,
        trans_fat: 0,
        cholesterol: 70,
        sodium: 1420,
        total_carbohydrates: 62,
        dietary_fiber: 2,
        total_sugars: 8,
        protein: 30,
        ingredients_text:
          "Brioche bun (enriched wheat flour, butter, sugar, eggs, yeast, salt), breaded chicken breast (chicken, wheat flour, corn starch, spices, salt), boom boom sauce (mayonnaise, sweet chili sauce, garlic), pickles, lettuce",
      },
      {
        name: "Burger",
        category: "burger",
        serving_size: 250,
        serving_unit: "g",
        calories: 590,
        total_fat: 32,
        saturated_fat: 12,
        trans_fat: 1,
        cholesterol: 90,
        sodium: 980,
        total_carbohydrates: 42,
        dietary_fiber: 2,
        total_sugars: 8,
        protein: 28,
        ingredients_text:
          "Beef patty (beef, salt, pepper), sesame seed bun (enriched wheat flour, water, sugar, yeast, soybean oil, sesame seeds, salt), American cheese, lettuce, tomato, onion, pickles, ketchup, mustard",
      },
      {
        name: "Hot Dog",
        category: "sandwich",
        serving_size: 170,
        serving_unit: "g",
        calories: 380,
        total_fat: 22,
        saturated_fat: 9,
        trans_fat: 0.5,
        cholesterol: 50,
        sodium: 1060,
        total_carbohydrates: 30,
        dietary_fiber: 1,
        total_sugars: 5,
        protein: 14,
        ingredients_text:
          "Beef hot dog (beef, water, salt, spices, paprika, garlic, sodium nitrite), hot dog bun (enriched wheat flour, water, sugar, yeast, soybean oil, salt), mustard, ketchup",
      },
      {
        name: "Mac and Cheese Bites",
        category: "side",
        serving_size: 140,
        serving_unit: "g",
        calories: 420,
        total_fat: 22,
        saturated_fat: 8,
        trans_fat: 0,
        cholesterol: 35,
        sodium: 860,
        total_carbohydrates: 44,
        dietary_fiber: 1,
        total_sugars: 3,
        protein: 12,
        ingredients_text:
          "Macaroni (enriched wheat flour, water), cheddar cheese sauce (milk, cheddar cheese, water, butter, modified food starch, salt), breading (wheat flour, corn starch, salt, spices), vegetable oil",
      },
      {
        name: "Mozzarella Sticks",
        category: "side",
        serving_size: 120,
        serving_unit: "g",
        calories: 380,
        total_fat: 20,
        saturated_fat: 9,
        trans_fat: 0,
        cholesterol: 40,
        sodium: 780,
        total_carbohydrates: 34,
        dietary_fiber: 1,
        total_sugars: 2,
        protein: 16,
        ingredients_text:
          "Mozzarella cheese (pasteurized milk, salt, enzymes), breading (enriched wheat flour, corn starch, salt, spices), vegetable oil, marinara sauce",
      },
      {
        name: "Tater Tots",
        category: "side",
        serving_size: 142,
        serving_unit: "g",
        calories: 340,
        total_fat: 18,
        saturated_fat: 2.5,
        trans_fat: 0,
        cholesterol: 0,
        sodium: 640,
        total_carbohydrates: 42,
        dietary_fiber: 3,
        total_sugars: 1,
        protein: 3,
        ingredients_text:
          "Potatoes, vegetable oil, salt, dextrose, modified food starch, sodium acid pyrophosphate",
      },
      {
        name: "Pretzel",
        category: "side",
        serving_size: 130,
        serving_unit: "g",
        calories: 340,
        total_fat: 3,
        saturated_fat: 1,
        trans_fat: 0,
        cholesterol: 0,
        sodium: 820,
        total_carbohydrates: 68,
        dietary_fiber: 2,
        total_sugars: 4,
        protein: 10,
        ingredients_text:
          "Enriched wheat flour, water, sugar, salt, yeast, soybean oil, sodium bicarbonate",
      },
      {
        name: "Breakfast Burrito",
        category: "sandwich",
        serving_size: 280,
        serving_unit: "g",
        calories: 580,
        total_fat: 28,
        saturated_fat: 10,
        trans_fat: 0.5,
        cholesterol: 230,
        sodium: 1280,
        total_carbohydrates: 52,
        dietary_fiber: 3,
        total_sugars: 4,
        protein: 28,
        ingredients_text:
          "Flour tortilla (enriched wheat flour, water, vegetable oil, salt), eggs, sausage (pork, salt, spices, sugar), cheddar cheese, hash browns (potatoes, vegetable oil, salt), salsa",
      },
      {
        name: "Shmuffin Sausage",
        category: "sandwich",
        serving_size: 170,
        serving_unit: "g",
        calories: 420,
        total_fat: 24,
        saturated_fat: 10,
        trans_fat: 0.5,
        cholesterol: 190,
        sodium: 940,
        total_carbohydrates: 30,
        dietary_fiber: 1,
        total_sugars: 3,
        protein: 20,
        ingredients_text:
          "English muffin (enriched wheat flour, water, yeast, sugar, salt), sausage patty (pork, salt, spices, sugar), egg, American cheese (milk, water, milkfat, sodium citrate, salt)",
      },
      {
        name: "Coffee medium",
        category: "beverage",
        serving_size: 473,
        serving_unit: "ml",
        calories: 5,
        total_fat: 0,
        saturated_fat: 0,
        trans_fat: 0,
        cholesterol: 0,
        sodium: 10,
        total_carbohydrates: 0,
        dietary_fiber: 0,
        total_sugars: 0,
        protein: 0,
        ingredients_text: "Brewed coffee",
      },
      {
        name: "Smoothie Strawberry Banana",
        category: "beverage",
        serving_size: 473,
        serving_unit: "ml",
        calories: 320,
        total_fat: 1,
        saturated_fat: 0,
        trans_fat: 0,
        cholesterol: 0,
        sodium: 35,
        total_carbohydrates: 76,
        dietary_fiber: 3,
        total_sugars: 62,
        protein: 3,
        ingredients_text:
          "Strawberries, banana, apple juice concentrate, ice, yogurt powder (nonfat milk, cultures), sugar",
      },
      {
        name: "Fries",
        category: "side",
        serving_size: 170,
        serving_unit: "g",
        calories: 380,
        total_fat: 18,
        saturated_fat: 3,
        trans_fat: 0,
        cholesterol: 0,
        sodium: 530,
        total_carbohydrates: 50,
        dietary_fiber: 4,
        total_sugars: 1,
        protein: 5,
        ingredients_text: "Potatoes, vegetable oil, salt",
      },
      {
        name: "Cookie",
        category: "dessert",
        serving_size: 71,
        serving_unit: "g",
        calories: 310,
        total_fat: 14,
        saturated_fat: 8,
        trans_fat: 0,
        cholesterol: 25,
        sodium: 200,
        total_carbohydrates: 44,
        dietary_fiber: 1,
        total_sugars: 26,
        protein: 3,
        ingredients_text:
          "Enriched wheat flour, butter, sugar, brown sugar, chocolate chips, eggs, vanilla, baking soda, salt",
      },
      {
        name: "Fried Chicken Tenders 3pc",
        category: "chicken",
        serving_size: 170,
        serving_unit: "g",
        calories: 430,
        total_fat: 22,
        saturated_fat: 4,
        trans_fat: 0,
        cholesterol: 75,
        sodium: 1100,
        total_carbohydrates: 28,
        dietary_fiber: 1,
        total_sugars: 1,
        protein: 28,
        ingredients_text:
          "Chicken breast, enriched wheat flour, corn starch, salt, spices, garlic powder, onion powder, paprika, vegetable oil",
      },
    ],
  },

  // ======================== AUNTIE ANNE'S ========================
  {
    chain: "Auntie Anne's",
    items: [
      {
        name: "Original Pretzel",
        category: "side",
        serving_size: 120,
        serving_unit: "g",
        calories: 340,
        total_fat: 5,
        saturated_fat: 3,
        trans_fat: 0,
        cholesterol: 10,
        sodium: 900,
        total_carbohydrates: 65,
        dietary_fiber: 2,
        total_sugars: 10,
        protein: 10,
        ingredients_text:
          "Enriched wheat flour, water, sugar, salt, yeast, butter, soybean oil, sodium bicarbonate",
      },
      {
        name: "Cinnamon Sugar Pretzel",
        category: "dessert",
        serving_size: 134,
        serving_unit: "g",
        calories: 450,
        total_fat: 12,
        saturated_fat: 6,
        trans_fat: 0,
        cholesterol: 15,
        sodium: 430,
        total_carbohydrates: 74,
        dietary_fiber: 2,
        total_sugars: 26,
        protein: 9,
        ingredients_text:
          "Enriched wheat flour, water, sugar, butter, cinnamon, salt, yeast, soybean oil, sodium bicarbonate",
      },
      {
        name: "Pepperoni Pretzel",
        category: "sandwich",
        serving_size: 148,
        serving_unit: "g",
        calories: 460,
        total_fat: 16,
        saturated_fat: 7,
        trans_fat: 0,
        cholesterol: 35,
        sodium: 1180,
        total_carbohydrates: 62,
        dietary_fiber: 2,
        total_sugars: 9,
        protein: 16,
        ingredients_text:
          "Enriched wheat flour, water, pepperoni (pork, beef, salt, spices, paprika, garlic, sodium nitrite), mozzarella cheese, sugar, salt, yeast, butter, soybean oil, sodium bicarbonate",
      },
      {
        name: "Pretzel Dogs",
        category: "sandwich",
        serving_size: 120,
        serving_unit: "g",
        calories: 380,
        total_fat: 18,
        saturated_fat: 7,
        trans_fat: 0.5,
        cholesterol: 35,
        sodium: 950,
        total_carbohydrates: 42,
        dietary_fiber: 1,
        total_sugars: 6,
        protein: 12,
        ingredients_text:
          "Pretzel dough (enriched wheat flour, water, sugar, salt, yeast, butter), all-beef hot dog (beef, water, salt, spices, paprika, garlic, sodium nitrite), sodium bicarbonate",
      },
      {
        name: "Pretzel Nuggets 10pc",
        category: "side",
        serving_size: 108,
        serving_unit: "g",
        calories: 310,
        total_fat: 5,
        saturated_fat: 2.5,
        trans_fat: 0,
        cholesterol: 10,
        sodium: 800,
        total_carbohydrates: 57,
        dietary_fiber: 2,
        total_sugars: 8,
        protein: 8,
        ingredients_text:
          "Enriched wheat flour, water, sugar, salt, yeast, butter, soybean oil, sodium bicarbonate",
      },
      {
        name: "Sweet Almond Pretzel",
        category: "dessert",
        serving_size: 148,
        serving_unit: "g",
        calories: 500,
        total_fat: 14,
        saturated_fat: 5,
        trans_fat: 0,
        cholesterol: 15,
        sodium: 590,
        total_carbohydrates: 82,
        dietary_fiber: 3,
        total_sugars: 30,
        protein: 12,
        ingredients_text:
          "Enriched wheat flour, water, sugar, sliced almonds, butter, almond glaze (sugar, water, almond extract), salt, yeast, soybean oil, sodium bicarbonate",
      },
      {
        name: "Jalapeño Pretzel",
        category: "side",
        serving_size: 134,
        serving_unit: "g",
        calories: 380,
        total_fat: 8,
        saturated_fat: 4,
        trans_fat: 0,
        cholesterol: 15,
        sodium: 1050,
        total_carbohydrates: 65,
        dietary_fiber: 2,
        total_sugars: 9,
        protein: 12,
        ingredients_text:
          "Enriched wheat flour, water, jalapeño peppers, mozzarella cheese, sugar, salt, yeast, butter, soybean oil, sodium bicarbonate",
      },
      {
        name: "Mini Pretzel Dogs 5pc",
        category: "sandwich",
        serving_size: 120,
        serving_unit: "g",
        calories: 370,
        total_fat: 16,
        saturated_fat: 7,
        trans_fat: 0.5,
        cholesterol: 35,
        sodium: 900,
        total_carbohydrates: 42,
        dietary_fiber: 1,
        total_sugars: 6,
        protein: 12,
        ingredients_text:
          "Pretzel dough (enriched wheat flour, water, sugar, salt, yeast, butter), all-beef hot dog pieces (beef, water, salt, spices, paprika, garlic, sodium nitrite), sodium bicarbonate",
      },
      {
        name: "Cheese Dip",
        category: "sauce",
        serving_size: 35,
        serving_unit: "g",
        calories: 70,
        total_fat: 5,
        saturated_fat: 2,
        trans_fat: 0,
        cholesterol: 15,
        sodium: 280,
        total_carbohydrates: 3,
        dietary_fiber: 0,
        total_sugars: 1,
        protein: 2,
        ingredients_text:
          "Cheddar cheese (pasteurized milk, salt, enzymes, annatto color), water, butter, modified food starch, sodium phosphate, salt",
      },
      {
        name: "Marinara Dip",
        category: "sauce",
        serving_size: 35,
        serving_unit: "g",
        calories: 15,
        total_fat: 0,
        saturated_fat: 0,
        trans_fat: 0,
        cholesterol: 0,
        sodium: 180,
        total_carbohydrates: 3,
        dietary_fiber: 0,
        total_sugars: 2,
        protein: 0,
        ingredients_text:
          "Tomatoes (tomato puree, water), onion, garlic, olive oil, salt, sugar, basil, oregano, black pepper",
      },
      {
        name: "Lemonade medium",
        category: "beverage",
        serving_size: 473,
        serving_unit: "ml",
        calories: 250,
        total_fat: 0,
        saturated_fat: 0,
        trans_fat: 0,
        cholesterol: 0,
        sodium: 10,
        total_carbohydrates: 64,
        dietary_fiber: 0,
        total_sugars: 60,
        protein: 0,
        ingredients_text: "Water, sugar, lemon juice concentrate, citric acid, natural flavors",
      },
      {
        name: "Frozen Lemonade",
        category: "beverage",
        serving_size: 473,
        serving_unit: "ml",
        calories: 280,
        total_fat: 0,
        saturated_fat: 0,
        trans_fat: 0,
        cholesterol: 0,
        sodium: 10,
        total_carbohydrates: 72,
        dietary_fiber: 0,
        total_sugars: 66,
        protein: 0,
        ingredients_text:
          "Water, sugar, lemon juice concentrate, ice, citric acid, natural flavors",
      },
      {
        name: "Pretzel Perks Coffee",
        category: "beverage",
        serving_size: 473,
        serving_unit: "ml",
        calories: 5,
        total_fat: 0,
        saturated_fat: 0,
        trans_fat: 0,
        cholesterol: 0,
        sodium: 10,
        total_carbohydrates: 0,
        dietary_fiber: 0,
        total_sugars: 0,
        protein: 0,
        ingredients_text: "Brewed coffee",
      },
      {
        name: "Caramel Dip",
        category: "sauce",
        serving_size: 42,
        serving_unit: "g",
        calories: 120,
        total_fat: 3,
        saturated_fat: 1.5,
        trans_fat: 0,
        cholesterol: 5,
        sodium: 100,
        total_carbohydrates: 23,
        dietary_fiber: 0,
        total_sugars: 18,
        protein: 1,
        ingredients_text:
          "Corn syrup, sugar, water, butter (cream, salt), nonfat milk, modified food starch, salt, natural flavor, caramel color",
      },
      {
        name: "Sweet Cream Cheese Dip",
        category: "sauce",
        serving_size: 42,
        serving_unit: "g",
        calories: 110,
        total_fat: 7,
        saturated_fat: 4.5,
        trans_fat: 0,
        cholesterol: 25,
        sodium: 110,
        total_carbohydrates: 10,
        dietary_fiber: 0,
        total_sugars: 8,
        protein: 2,
        ingredients_text:
          "Cream cheese (pasteurized milk, cream, salt, carob bean gum), sugar, sour cream, vanilla extract",
      },
    ],
  },
];

// ---------------------------------------------------------------------------
// SQL statements (same as import-chains.ts)
// ---------------------------------------------------------------------------

const upsertVendor = db.prepare(`
  INSERT INTO vendors (id, name, type, api_key)
  VALUES (@id, @name, @type, @api_key)
  ON CONFLICT(id) DO UPDATE SET
    name = excluded.name,
    type = excluded.type
`);

const upsertFood = db.prepare(`
  INSERT INTO foods (id, name, brand, category, serving_size, serving_unit, source, vendor_id,
    calories, total_fat, saturated_fat, trans_fat, cholesterol, sodium,
    total_carbohydrates, dietary_fiber, total_sugars, protein,
    ingredients_text, allergens, dietary_tags, nutri_score, nutri_grade,
    updated_at)
  VALUES (@id, @name, @brand, @category, @serving_size, @serving_unit, 'vendor', @vendor_id,
    @calories, @total_fat, @saturated_fat, @trans_fat, @cholesterol, @sodium,
    @total_carbohydrates, @dietary_fiber, @total_sugars, @protein,
    @ingredients_text, @allergens, @dietary_tags, @nutri_score, @nutri_grade,
    datetime('now'))
  ON CONFLICT(id) DO UPDATE SET
    name = excluded.name,
    brand = excluded.brand,
    category = excluded.category,
    serving_size = excluded.serving_size,
    serving_unit = excluded.serving_unit,
    vendor_id = excluded.vendor_id,
    calories = excluded.calories,
    total_fat = excluded.total_fat,
    saturated_fat = excluded.saturated_fat,
    trans_fat = excluded.trans_fat,
    cholesterol = excluded.cholesterol,
    sodium = excluded.sodium,
    total_carbohydrates = excluded.total_carbohydrates,
    dietary_fiber = excluded.dietary_fiber,
    total_sugars = excluded.total_sugars,
    protein = excluded.protein,
    ingredients_text = excluded.ingredients_text,
    allergens = excluded.allergens,
    dietary_tags = excluded.dietary_tags,
    nutri_score = excluded.nutri_score,
    nutri_grade = excluded.nutri_grade,
    updated_at = datetime('now')
`);

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function slugify(name: string): string {
  return name
    .toLowerCase()
    .replace(/['']/g, "")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

function buildFoodRecord(item: ChainMenuItem, chainName: string, vendorId: string) {
  const chainSlug = slugify(chainName);
  const itemSlug = slugify(item.name);
  const id = `chain-${chainSlug}-${itemSlug}`;

  // Calculate nutri-score (needs per-100g values)
  const servingG = item.serving_unit === "g" ? item.serving_size : item.serving_size * 1;
  const factor = servingG > 0 ? 100 / servingG : 1;

  const nutriResult = calculateNutriScore(
    {
      calories: item.calories * factor,
      totalSugars: item.total_sugars * factor,
      saturatedFat: item.saturated_fat * factor,
      sodium: item.sodium * factor,
      dietaryFiber: item.dietary_fiber * factor,
      protein: item.protein * factor,
    },
    item.category
  );

  const ingredientsText = item.ingredients_text || null;
  const allergens = ingredientsText ? detectAllergens(ingredientsText) : [];
  const dietaryTags = detectDietaryTags(ingredientsText || "", {
    total_carbohydrates: item.total_carbohydrates,
    protein: item.protein,
    total_fat: item.total_fat,
    total_sugars: item.total_sugars,
    dietary_fiber: item.dietary_fiber,
  });

  return {
    id,
    name: item.name,
    brand: chainName,
    category: item.category,
    serving_size: item.serving_size,
    serving_unit: item.serving_unit,
    vendor_id: vendorId,
    calories: item.calories,
    total_fat: item.total_fat,
    saturated_fat: item.saturated_fat,
    trans_fat: item.trans_fat,
    cholesterol: item.cholesterol,
    sodium: item.sodium,
    total_carbohydrates: item.total_carbohydrates,
    dietary_fiber: item.dietary_fiber,
    total_sugars: item.total_sugars,
    protein: item.protein,
    ingredients_text: ingredientsText,
    allergens: allergens.length > 0 ? allergens.join(",") : null,
    dietary_tags: dietaryTags.length > 0 ? dietaryTags.join(",") : null,
    nutri_score: nutriResult.score,
    nutri_grade: nutriResult.grade,
  };
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

function main() {
  console.log("=== Restaurant Chain Nutrition Import - Batch 7 (Dessert, Coffee, Fast Casual) ===\n");

  let totalItems = 0;
  let totalChains = 0;

  const beforeCount = (
    db.prepare("SELECT COUNT(*) as c FROM foods WHERE source = 'vendor'").get() as any
  ).c;

  const importAll = db.transaction(() => {
    for (const chain of chains) {
      const chainSlug = slugify(chain.chain);
      const vendorId = `chain-${chainSlug}`;

      // Create vendor record
      upsertVendor.run({
        id: vendorId,
        name: chain.chain,
        type: "restaurant",
        api_key: generateApiKey(),
      });

      console.log(`  ${chain.chain}: ${chain.items.length} items`);

      // Import each menu item
      for (const item of chain.items) {
        const record = buildFoodRecord(item, chain.chain, vendorId);
        upsertFood.run(record);
      }

      totalItems += chain.items.length;
      totalChains++;
    }
  });

  importAll();

  // Rebuild FTS index
  console.log("\nRebuilding search index...");
  db.exec("INSERT INTO foods_fts(foods_fts) VALUES('rebuild')");

  const afterCount = (
    db.prepare("SELECT COUNT(*) as c FROM foods WHERE source = 'vendor'").get() as any
  ).c;

  console.log(`\n=== Done! ===`);
  console.log(`Chains imported: ${totalChains}`);
  console.log(`Menu items processed: ${totalItems}`);
  console.log(`Vendor foods before: ${beforeCount}`);
  console.log(`Vendor foods after: ${afterCount}`);
  console.log(`New items added: ${afterCount - beforeCount}`);
}

main();
