/**
 * Restaurant Chain Nutrition Data Import - Batch 6 (Sit-Down)
 *
 * Imports manually curated nutrition data for sit-down restaurant chains:
 * Texas Roadhouse, Outback Steakhouse, Red Lobster, Cheesecake Factory,
 * Red Robin, TGI Fridays, LongHorn Steakhouse, Golden Corral, Bob Evans,
 * P.F. Chang's
 *
 * Usage:
 *   npx ts-node scripts/import-chains-batch6.ts
 */

import { v4 as uuidv4 } from "uuid";
import db from "../src/data/database";
import { calculateNutriScore } from "../src/services/nutrition-score";
import { calculatePersonalHealthScore } from "../src/services/health-score";
import { detectAllergens, detectDietaryTags } from "../src/services/food-analysis";
import { generateApiKey } from "../src/middleware/auth";

interface ChainMenuItem {
  name: string;
  category: string;
  serving_size: number;
  serving_unit: string;
  calories: number;
  total_fat: number;
  saturated_fat: number;
  trans_fat: number;
  cholesterol: number;
  sodium: number;
  total_carbohydrates: number;
  dietary_fiber: number;
  total_sugars: number;
  protein: number;
  ingredients_text?: string;
}

interface ChainData {
  chain: string;
  items: ChainMenuItem[];
}

// ---------------------------------------------------------------------------
// Chain menu data
// ---------------------------------------------------------------------------

const chains: ChainData[] = [
  // ======================== TEXAS ROADHOUSE ========================
  {
    chain: "Texas Roadhouse",
    items: [
      {
        name: "6oz Sirloin",
        category: "steak",
        serving_size: 170,
        serving_unit: "g",
        calories: 250,
        total_fat: 10,
        saturated_fat: 4,
        trans_fat: 0,
        cholesterol: 90,
        sodium: 370,
        total_carbohydrates: 0,
        dietary_fiber: 0,
        total_sugars: 0,
        protein: 39,
        ingredients_text:
          "USDA Choice sirloin steak, seasoning (salt, black pepper, garlic powder)",
      },
      {
        name: "Ribeye 10oz",
        category: "steak",
        serving_size: 283,
        serving_unit: "g",
        calories: 690,
        total_fat: 50,
        saturated_fat: 22,
        trans_fat: 1.5,
        cholesterol: 175,
        sodium: 520,
        total_carbohydrates: 0,
        dietary_fiber: 0,
        total_sugars: 0,
        protein: 57,
        ingredients_text:
          "USDA Choice ribeye steak, seasoning (salt, black pepper, garlic powder)",
      },
      {
        name: "Grilled Chicken Salad",
        category: "salad",
        serving_size: 397,
        serving_unit: "g",
        calories: 430,
        total_fat: 21,
        saturated_fat: 8,
        trans_fat: 0,
        cholesterol: 105,
        sodium: 980,
        total_carbohydrates: 24,
        dietary_fiber: 4,
        total_sugars: 8,
        protein: 38,
        ingredients_text:
          "Grilled chicken breast, mixed greens, shredded cheese (milk, enzymes, salt), tomatoes, croutons (enriched wheat flour, oil, garlic), hard-boiled egg, ranch dressing (soybean oil, buttermilk, egg yolks, vinegar, salt)",
      },
      {
        name: "Country Fried Sirloin",
        category: "entree",
        serving_size: 340,
        serving_unit: "g",
        calories: 900,
        total_fat: 56,
        saturated_fat: 18,
        trans_fat: 1,
        cholesterol: 130,
        sodium: 2120,
        total_carbohydrates: 58,
        dietary_fiber: 2,
        total_sugars: 4,
        protein: 42,
        ingredients_text:
          "Sirloin steak, breading (enriched wheat flour, salt, spices, leavening), cream gravy (milk, wheat flour, butter, salt, black pepper), frying oil (soybean oil)",
      },
      {
        name: "Pulled Pork Dinner",
        category: "entree",
        serving_size: 312,
        serving_unit: "g",
        calories: 530,
        total_fat: 22,
        saturated_fat: 8,
        trans_fat: 0,
        cholesterol: 125,
        sodium: 1350,
        total_carbohydrates: 42,
        dietary_fiber: 1,
        total_sugars: 24,
        protein: 40,
        ingredients_text:
          "Smoked pulled pork (pork shoulder, salt, spices, brown sugar), BBQ sauce (tomato paste, vinegar, brown sugar, molasses, spices), brioche bun (enriched wheat flour, butter, eggs, sugar)",
      },
      {
        name: "Grilled Chicken",
        category: "entree",
        serving_size: 227,
        serving_unit: "g",
        calories: 310,
        total_fat: 10,
        saturated_fat: 3,
        trans_fat: 0,
        cholesterol: 145,
        sodium: 680,
        total_carbohydrates: 2,
        dietary_fiber: 0,
        total_sugars: 1,
        protein: 52,
        ingredients_text:
          "Chicken breast, seasoning (salt, black pepper, garlic powder, paprika, onion powder)",
      },
      {
        name: "Fried Catfish",
        category: "entree",
        serving_size: 255,
        serving_unit: "g",
        calories: 520,
        total_fat: 28,
        saturated_fat: 5,
        trans_fat: 0,
        cholesterol: 95,
        sodium: 1140,
        total_carbohydrates: 36,
        dietary_fiber: 1,
        total_sugars: 2,
        protein: 30,
        ingredients_text:
          "Catfish fillets, cornmeal breading (cornmeal, enriched wheat flour, salt, spices, leavening), frying oil (soybean oil)",
      },
      {
        name: "Loaded Baked Potato",
        category: "side",
        serving_size: 369,
        serving_unit: "g",
        calories: 470,
        total_fat: 21,
        saturated_fat: 13,
        trans_fat: 0.5,
        cholesterol: 55,
        sodium: 580,
        total_carbohydrates: 57,
        dietary_fiber: 5,
        total_sugars: 4,
        protein: 14,
        ingredients_text:
          "Russet potato, butter (cream, salt), sour cream (milk, cream, cultures), cheddar cheese (milk, enzymes, salt), smoked bacon (pork, water, salt, sugar, sodium nitrite), chives",
      },
      {
        name: "Seasoned Rice",
        category: "side",
        serving_size: 142,
        serving_unit: "g",
        calories: 210,
        total_fat: 4,
        saturated_fat: 1,
        trans_fat: 0,
        cholesterol: 0,
        sodium: 460,
        total_carbohydrates: 39,
        dietary_fiber: 1,
        total_sugars: 1,
        protein: 4,
        ingredients_text:
          "Long grain rice, butter (cream, salt), seasoning (salt, garlic powder, onion powder, parsley)",
      },
      {
        name: "Green Beans",
        category: "side",
        serving_size: 113,
        serving_unit: "g",
        calories: 60,
        total_fat: 3,
        saturated_fat: 1,
        trans_fat: 0,
        cholesterol: 5,
        sodium: 340,
        total_carbohydrates: 7,
        dietary_fiber: 3,
        total_sugars: 3,
        protein: 2,
        ingredients_text:
          "Green beans, butter (cream, salt), seasoning (salt, garlic powder, black pepper)",
      },
      {
        name: "Caesar Salad",
        category: "salad",
        serving_size: 198,
        serving_unit: "g",
        calories: 280,
        total_fat: 20,
        saturated_fat: 4,
        trans_fat: 0,
        cholesterol: 20,
        sodium: 620,
        total_carbohydrates: 16,
        dietary_fiber: 2,
        total_sugars: 3,
        protein: 8,
        ingredients_text:
          "Romaine lettuce, parmesan cheese (milk, enzymes, salt), croutons (enriched wheat flour, oil, garlic, salt), Caesar dressing (soybean oil, parmesan cheese, anchovy paste, lemon juice, egg yolks, garlic, Worcestershire sauce)",
      },
      {
        name: "Rolls with Butter",
        category: "side",
        serving_size: 85,
        serving_unit: "g",
        calories: 227,
        total_fat: 9,
        saturated_fat: 4,
        trans_fat: 0,
        cholesterol: 15,
        sodium: 310,
        total_carbohydrates: 32,
        dietary_fiber: 1,
        total_sugars: 5,
        protein: 4,
        ingredients_text:
          "Enriched wheat flour, water, sugar, yeast, soybean oil, honey, salt, cinnamon butter (butter, cinnamon, sugar, honey)",
      },
      {
        name: "Grilled Shrimp",
        category: "entree",
        serving_size: 170,
        serving_unit: "g",
        calories: 190,
        total_fat: 7,
        saturated_fat: 2,
        trans_fat: 0,
        cholesterol: 240,
        sodium: 790,
        total_carbohydrates: 3,
        dietary_fiber: 0,
        total_sugars: 1,
        protein: 28,
        ingredients_text:
          "Shrimp, butter (cream, salt), seasoning (salt, garlic powder, paprika, black pepper, lemon zest)",
      },
      {
        name: "Cactus Blossom",
        category: "appetizer",
        serving_size: 567,
        serving_unit: "g",
        calories: 1960,
        total_fat: 134,
        saturated_fat: 24,
        trans_fat: 2,
        cholesterol: 55,
        sodium: 4280,
        total_carbohydrates: 162,
        dietary_fiber: 10,
        total_sugars: 18,
        protein: 26,
        ingredients_text:
          "Onion, breading (enriched wheat flour, cornstarch, salt, spices, leavening), frying oil (soybean oil), dipping sauce (mayonnaise, ketchup, horseradish, cayenne pepper)",
      },
      {
        name: "Strawberry Cake",
        category: "dessert",
        serving_size: 227,
        serving_unit: "g",
        calories: 730,
        total_fat: 28,
        saturated_fat: 14,
        trans_fat: 0,
        cholesterol: 85,
        sodium: 420,
        total_carbohydrates: 112,
        dietary_fiber: 1,
        total_sugars: 88,
        protein: 7,
        ingredients_text:
          "Enriched wheat flour, sugar, butter (cream, salt), eggs, strawberries, cream cheese (milk, cream, salt, cultures), powdered sugar, vanilla extract, milk",
      },
    ],
  },

  // ======================== OUTBACK STEAKHOUSE ========================
  {
    chain: "Outback Steakhouse",
    items: [
      {
        name: "Bloomin Onion",
        category: "appetizer",
        serving_size: 510,
        serving_unit: "g",
        calories: 1950,
        total_fat: 122,
        saturated_fat: 42,
        trans_fat: 3,
        cholesterol: 120,
        sodium: 3840,
        total_carbohydrates: 164,
        dietary_fiber: 10,
        total_sugars: 22,
        protein: 36,
        ingredients_text:
          "Onion, breading (enriched wheat flour, cornstarch, salt, spices, leavening), frying oil (soybean oil), bloom sauce (mayonnaise, ketchup, horseradish, paprika, cayenne pepper)",
      },
      {
        name: "Alice Springs Chicken",
        category: "entree",
        serving_size: 340,
        serving_unit: "g",
        calories: 970,
        total_fat: 54,
        saturated_fat: 22,
        trans_fat: 0.5,
        cholesterol: 220,
        sodium: 2140,
        total_carbohydrates: 30,
        dietary_fiber: 3,
        total_sugars: 10,
        protein: 86,
        ingredients_text:
          "Grilled chicken breast, smoked bacon (pork, water, salt, sugar, sodium nitrite), sauteed mushrooms, honey mustard sauce (honey, mustard, mayonnaise, vinegar), Monterey Jack cheese (milk, enzymes, salt), cheddar cheese (milk, enzymes, salt)",
      },
      {
        name: "Outback Special 9oz",
        category: "steak",
        serving_size: 255,
        serving_unit: "g",
        calories: 480,
        total_fat: 25,
        saturated_fat: 11,
        trans_fat: 1,
        cholesterol: 155,
        sodium: 620,
        total_carbohydrates: 0,
        dietary_fiber: 0,
        total_sugars: 0,
        protein: 60,
        ingredients_text:
          "USDA Choice sirloin steak, seasoning (salt, cracked black pepper, garlic, paprika)",
      },
      {
        name: "Victoria's Filet 6oz",
        category: "steak",
        serving_size: 170,
        serving_unit: "g",
        calories: 350,
        total_fat: 18,
        saturated_fat: 8,
        trans_fat: 0.5,
        cholesterol: 130,
        sodium: 480,
        total_carbohydrates: 0,
        dietary_fiber: 0,
        total_sugars: 0,
        protein: 45,
        ingredients_text:
          "USDA Choice filet mignon, seasoning (salt, cracked black pepper, garlic)",
      },
      {
        name: "Baby Back Ribs Full",
        category: "entree",
        serving_size: 510,
        serving_unit: "g",
        calories: 1380,
        total_fat: 92,
        saturated_fat: 34,
        trans_fat: 1,
        cholesterol: 350,
        sodium: 2260,
        total_carbohydrates: 48,
        dietary_fiber: 1,
        total_sugars: 36,
        protein: 86,
        ingredients_text:
          "Pork baby back ribs (pork ribs, water, salt, sodium phosphate), BBQ sauce (tomato paste, brown sugar, vinegar, molasses, spices, liquid smoke)",
      },
      {
        name: "Grilled Chicken on the Barbie",
        category: "entree",
        serving_size: 283,
        serving_unit: "g",
        calories: 510,
        total_fat: 18,
        saturated_fat: 5,
        trans_fat: 0,
        cholesterol: 170,
        sodium: 1420,
        total_carbohydrates: 18,
        dietary_fiber: 2,
        total_sugars: 10,
        protein: 68,
        ingredients_text:
          "Grilled chicken breast, BBQ glaze (brown sugar, tomato paste, vinegar, spices), seasonal vegetables",
      },
      {
        name: "Aussie Cheese Fries",
        category: "appetizer",
        serving_size: 454,
        serving_unit: "g",
        calories: 1740,
        total_fat: 108,
        saturated_fat: 46,
        trans_fat: 2,
        cholesterol: 185,
        sodium: 2990,
        total_carbohydrates: 132,
        dietary_fiber: 10,
        total_sugars: 6,
        protein: 52,
        ingredients_text:
          "French fries (potatoes, vegetable oil, salt), Monterey Jack cheese (milk, enzymes, salt), cheddar cheese (milk, enzymes, salt), smoked bacon (pork, water, salt, sugar, sodium nitrite), ranch dressing (soybean oil, buttermilk, egg yolks, vinegar, salt)",
      },
      {
        name: "Coconut Shrimp",
        category: "appetizer",
        serving_size: 198,
        serving_unit: "g",
        calories: 580,
        total_fat: 32,
        saturated_fat: 14,
        trans_fat: 0,
        cholesterol: 165,
        sodium: 830,
        total_carbohydrates: 50,
        dietary_fiber: 3,
        total_sugars: 18,
        protein: 22,
        ingredients_text:
          "Shrimp, coconut breading (shredded coconut, enriched wheat flour, cornstarch, salt, sugar), frying oil (soybean oil), creole marmalade dipping sauce (orange marmalade, horseradish, mustard)",
      },
      {
        name: "Caesar Salad",
        category: "salad",
        serving_size: 205,
        serving_unit: "g",
        calories: 340,
        total_fat: 25,
        saturated_fat: 5,
        trans_fat: 0,
        cholesterol: 25,
        sodium: 740,
        total_carbohydrates: 18,
        dietary_fiber: 3,
        total_sugars: 3,
        protein: 10,
        ingredients_text:
          "Romaine lettuce, parmesan cheese (milk, enzymes, salt), croutons (enriched wheat flour, oil, garlic, salt), Caesar dressing (soybean oil, parmesan cheese, anchovy paste, lemon juice, egg yolks, garlic)",
      },
      {
        name: "Loaded Baked Potato",
        category: "side",
        serving_size: 369,
        serving_unit: "g",
        calories: 480,
        total_fat: 22,
        saturated_fat: 14,
        trans_fat: 0.5,
        cholesterol: 60,
        sodium: 620,
        total_carbohydrates: 58,
        dietary_fiber: 5,
        total_sugars: 4,
        protein: 15,
        ingredients_text:
          "Russet potato, butter (cream, salt), sour cream (milk, cream, cultures), cheddar cheese (milk, enzymes, salt), smoked bacon (pork, water, salt, sugar, sodium nitrite), chives",
      },
      {
        name: "Sweet Potato",
        category: "side",
        serving_size: 255,
        serving_unit: "g",
        calories: 340,
        total_fat: 10,
        saturated_fat: 6,
        trans_fat: 0,
        cholesterol: 25,
        sodium: 180,
        total_carbohydrates: 58,
        dietary_fiber: 6,
        total_sugars: 24,
        protein: 4,
        ingredients_text:
          "Sweet potato, brown sugar butter (butter, brown sugar, cinnamon), marshmallow topping",
      },
      {
        name: "Steamed Broccoli",
        category: "side",
        serving_size: 142,
        serving_unit: "g",
        calories: 50,
        total_fat: 1,
        saturated_fat: 0,
        trans_fat: 0,
        cholesterol: 0,
        sodium: 35,
        total_carbohydrates: 8,
        dietary_fiber: 4,
        total_sugars: 2,
        protein: 4,
        ingredients_text: "Broccoli, salt",
      },
      {
        name: "Chocolate Thunder from Down Under",
        category: "dessert",
        serving_size: 312,
        serving_unit: "g",
        calories: 1560,
        total_fat: 82,
        saturated_fat: 42,
        trans_fat: 1,
        cholesterol: 180,
        sodium: 860,
        total_carbohydrates: 193,
        dietary_fiber: 5,
        total_sugars: 140,
        protein: 18,
        ingredients_text:
          "Pecan brownie (enriched wheat flour, sugar, butter, eggs, cocoa, pecans), vanilla ice cream (milk, cream, sugar, vanilla), chocolate sauce (sugar, cocoa, cream, butter), whipped cream, chocolate shavings",
      },
      {
        name: "New South Wales",
        category: "steak",
        serving_size: 397,
        serving_unit: "g",
        calories: 560,
        total_fat: 28,
        saturated_fat: 12,
        trans_fat: 1,
        cholesterol: 180,
        sodium: 740,
        total_carbohydrates: 2,
        dietary_fiber: 0,
        total_sugars: 0,
        protein: 72,
        ingredients_text:
          "USDA Choice NY strip steak, seasoning (salt, cracked black pepper, garlic, paprika)",
      },
      {
        name: "Grilled Salmon",
        category: "entree",
        serving_size: 227,
        serving_unit: "g",
        calories: 470,
        total_fat: 26,
        saturated_fat: 6,
        trans_fat: 0,
        cholesterol: 125,
        sodium: 600,
        total_carbohydrates: 8,
        dietary_fiber: 0,
        total_sugars: 6,
        protein: 50,
        ingredients_text:
          "Atlantic salmon fillet, Toowoomba topping (shrimp, mushrooms, cream, garlic, herbs), seasoning (salt, black pepper, lemon zest)",
      },
    ],
  },

  // ======================== RED LOBSTER ========================
  {
    chain: "Red Lobster",
    items: [
      {
        name: "Cheddar Bay Biscuit",
        category: "side",
        serving_size: 48,
        serving_unit: "g",
        calories: 160,
        total_fat: 8,
        saturated_fat: 4,
        trans_fat: 0,
        cholesterol: 15,
        sodium: 350,
        total_carbohydrates: 17,
        dietary_fiber: 0,
        total_sugars: 2,
        protein: 3,
        ingredients_text:
          "Enriched wheat flour, buttermilk, butter (cream, salt), cheddar cheese (milk, enzymes, salt), garlic, baking powder, salt, Old Bay seasoning, parsley",
      },
      {
        name: "Shrimp Scampi",
        category: "entree",
        serving_size: 283,
        serving_unit: "g",
        calories: 540,
        total_fat: 26,
        saturated_fat: 12,
        trans_fat: 0.5,
        cholesterol: 310,
        sodium: 1480,
        total_carbohydrates: 42,
        dietary_fiber: 2,
        total_sugars: 3,
        protein: 32,
        ingredients_text:
          "Shrimp, linguine pasta (semolina wheat flour, water), garlic butter sauce (butter, garlic, white wine, lemon juice, parsley, salt)",
      },
      {
        name: "Garlic Shrimp",
        category: "entree",
        serving_size: 198,
        serving_unit: "g",
        calories: 370,
        total_fat: 20,
        saturated_fat: 10,
        trans_fat: 0.5,
        cholesterol: 280,
        sodium: 1190,
        total_carbohydrates: 12,
        dietary_fiber: 0,
        total_sugars: 2,
        protein: 36,
        ingredients_text:
          "Shrimp, garlic butter (butter, garlic, white wine, parsley, salt, black pepper)",
      },
      {
        name: "Admiral's Feast",
        category: "entree",
        serving_size: 454,
        serving_unit: "g",
        calories: 1280,
        total_fat: 68,
        saturated_fat: 14,
        trans_fat: 1,
        cholesterol: 340,
        sodium: 3450,
        total_carbohydrates: 104,
        dietary_fiber: 4,
        total_sugars: 8,
        protein: 62,
        ingredients_text:
          "Fried shrimp, fried clam strips, fried flounder, seafood stuffing (bread crumbs, crab meat, butter, celery, onion, seasoning), breading (enriched wheat flour, cornstarch, salt, spices), frying oil (soybean oil)",
      },
      {
        name: "Sailor's Platter",
        category: "entree",
        serving_size: 397,
        serving_unit: "g",
        calories: 1050,
        total_fat: 52,
        saturated_fat: 10,
        trans_fat: 0.5,
        cholesterol: 260,
        sodium: 2680,
        total_carbohydrates: 94,
        dietary_fiber: 3,
        total_sugars: 6,
        protein: 48,
        ingredients_text:
          "Fried shrimp, fried clam strips, fried flounder, breading (enriched wheat flour, cornstarch, salt, spices), frying oil (soybean oil), cocktail sauce, tartar sauce",
      },
      {
        name: "Live Maine Lobster 1.25lb",
        category: "entree",
        serving_size: 567,
        serving_unit: "g",
        calories: 450,
        total_fat: 9,
        saturated_fat: 2,
        trans_fat: 0,
        cholesterol: 540,
        sodium: 1780,
        total_carbohydrates: 2,
        dietary_fiber: 0,
        total_sugars: 0,
        protein: 88,
        ingredients_text:
          "Whole Maine lobster, drawn butter (butter, salt)",
      },
      {
        name: "Lobster Tail",
        category: "entree",
        serving_size: 170,
        serving_unit: "g",
        calories: 220,
        total_fat: 8,
        saturated_fat: 4,
        trans_fat: 0,
        cholesterol: 200,
        sodium: 690,
        total_carbohydrates: 1,
        dietary_fiber: 0,
        total_sugars: 0,
        protein: 36,
        ingredients_text:
          "Rock lobster tail, drawn butter (butter, salt)",
      },
      {
        name: "Fish and Chips",
        category: "entree",
        serving_size: 397,
        serving_unit: "g",
        calories: 1030,
        total_fat: 54,
        saturated_fat: 8,
        trans_fat: 0.5,
        cholesterol: 90,
        sodium: 2280,
        total_carbohydrates: 100,
        dietary_fiber: 5,
        total_sugars: 4,
        protein: 38,
        ingredients_text:
          "Cod fillet, beer batter (enriched wheat flour, beer, cornstarch, salt, leavening), french fries (potatoes, vegetable oil, salt), frying oil (soybean oil), tartar sauce, coleslaw",
      },
      {
        name: "Clam Chowder cup",
        category: "soup",
        serving_size: 227,
        serving_unit: "g",
        calories: 230,
        total_fat: 14,
        saturated_fat: 7,
        trans_fat: 0,
        cholesterol: 50,
        sodium: 890,
        total_carbohydrates: 18,
        dietary_fiber: 1,
        total_sugars: 2,
        protein: 8,
        ingredients_text:
          "Clams, potatoes, heavy cream (cream, milk), butter (cream, salt), onion, celery, enriched wheat flour, salt, black pepper, thyme",
      },
      {
        name: "Caesar Salad",
        category: "salad",
        serving_size: 198,
        serving_unit: "g",
        calories: 290,
        total_fat: 22,
        saturated_fat: 4,
        trans_fat: 0,
        cholesterol: 20,
        sodium: 640,
        total_carbohydrates: 14,
        dietary_fiber: 2,
        total_sugars: 3,
        protein: 8,
        ingredients_text:
          "Romaine lettuce, parmesan cheese (milk, enzymes, salt), croutons (enriched wheat flour, oil, garlic, salt), Caesar dressing (soybean oil, parmesan cheese, anchovy paste, lemon juice, egg yolks, garlic)",
      },
      {
        name: "Crunchy Popcorn Shrimp",
        category: "appetizer",
        serving_size: 198,
        serving_unit: "g",
        calories: 540,
        total_fat: 30,
        saturated_fat: 5,
        trans_fat: 0,
        cholesterol: 180,
        sodium: 1420,
        total_carbohydrates: 42,
        dietary_fiber: 1,
        total_sugars: 3,
        protein: 22,
        ingredients_text:
          "Shrimp, breading (enriched wheat flour, cornstarch, salt, spices, leavening), frying oil (soybean oil), cocktail sauce (tomato paste, horseradish, vinegar, sugar, salt)",
      },
      {
        name: "Bar Harbor Lobster Bake",
        category: "entree",
        serving_size: 510,
        serving_unit: "g",
        calories: 730,
        total_fat: 30,
        saturated_fat: 14,
        trans_fat: 0.5,
        cholesterol: 380,
        sodium: 2380,
        total_carbohydrates: 56,
        dietary_fiber: 4,
        total_sugars: 6,
        protein: 58,
        ingredients_text:
          "Lobster tail, shrimp, mussels, corn on the cob, red potatoes, linguine pasta (semolina wheat flour, water), garlic butter (butter, garlic, salt)",
      },
      {
        name: "Surf and Turf",
        category: "entree",
        serving_size: 369,
        serving_unit: "g",
        calories: 640,
        total_fat: 32,
        saturated_fat: 14,
        trans_fat: 1,
        cholesterol: 320,
        sodium: 1480,
        total_carbohydrates: 4,
        dietary_fiber: 0,
        total_sugars: 1,
        protein: 82,
        ingredients_text:
          "NY strip steak, Maine lobster tail, drawn butter (butter, salt), seasoning (salt, black pepper, garlic)",
      },
      {
        name: "Vanilla Bean Cheesecake",
        category: "dessert",
        serving_size: 198,
        serving_unit: "g",
        calories: 580,
        total_fat: 38,
        saturated_fat: 22,
        trans_fat: 1,
        cholesterol: 150,
        sodium: 380,
        total_carbohydrates: 50,
        dietary_fiber: 0,
        total_sugars: 38,
        protein: 8,
        ingredients_text:
          "Cream cheese (milk, cream, salt, cultures), sugar, eggs, sour cream (milk, cream, cultures), vanilla bean, graham cracker crust (graham flour, sugar, butter, cinnamon)",
      },
      {
        name: "Key Lime Pie",
        category: "dessert",
        serving_size: 170,
        serving_unit: "g",
        calories: 480,
        total_fat: 22,
        saturated_fat: 12,
        trans_fat: 0,
        cholesterol: 100,
        sodium: 290,
        total_carbohydrates: 66,
        dietary_fiber: 1,
        total_sugars: 50,
        protein: 6,
        ingredients_text:
          "Key lime juice, sweetened condensed milk (milk, sugar), eggs, graham cracker crust (graham flour, sugar, butter, cinnamon), whipped cream (cream, sugar)",
      },
    ],
  },

  // ======================== CHEESECAKE FACTORY ========================
  {
    chain: "Cheesecake Factory",
    items: [
      {
        name: "Original Cheesecake slice",
        category: "dessert",
        serving_size: 227,
        serving_unit: "g",
        calories: 830,
        total_fat: 54,
        saturated_fat: 30,
        trans_fat: 1.5,
        cholesterol: 215,
        sodium: 470,
        total_carbohydrates: 72,
        dietary_fiber: 1,
        total_sugars: 56,
        protein: 14,
        ingredients_text:
          "Cream cheese (milk, cream, salt, cultures), sugar, eggs, sour cream (milk, cream, cultures), vanilla extract, graham cracker crust (graham flour, sugar, butter, cinnamon)",
      },
      {
        name: "Avocado Eggrolls",
        category: "appetizer",
        serving_size: 340,
        serving_unit: "g",
        calories: 1120,
        total_fat: 78,
        saturated_fat: 14,
        trans_fat: 1,
        cholesterol: 30,
        sodium: 1620,
        total_carbohydrates: 86,
        dietary_fiber: 12,
        total_sugars: 14,
        protein: 18,
        ingredients_text:
          "Avocado, sun-dried tomatoes, red onion, cilantro, wonton wrappers (enriched wheat flour, water, egg, salt), frying oil (soybean oil), tamarind cashew dipping sauce (tamarind, cashews, sugar, vinegar, soy sauce)",
      },
      {
        name: "Chicken Madeira",
        category: "entree",
        serving_size: 454,
        serving_unit: "g",
        calories: 1540,
        total_fat: 86,
        saturated_fat: 38,
        trans_fat: 1.5,
        cholesterol: 310,
        sodium: 2680,
        total_carbohydrates: 72,
        dietary_fiber: 6,
        total_sugars: 12,
        protein: 112,
        ingredients_text:
          "Chicken breast, Madeira wine sauce (Madeira wine, butter, cream, mushrooms, beef stock), mozzarella cheese (milk, cultures, enzymes, salt), asparagus, mashed potatoes (potatoes, butter, cream, salt)",
      },
      {
        name: "Pasta Da Vinci",
        category: "pasta",
        serving_size: 454,
        serving_unit: "g",
        calories: 1490,
        total_fat: 80,
        saturated_fat: 36,
        trans_fat: 1,
        cholesterol: 260,
        sodium: 2380,
        total_carbohydrates: 112,
        dietary_fiber: 6,
        total_sugars: 10,
        protein: 68,
        ingredients_text:
          "Penne pasta (semolina wheat flour, water), chicken breast, mushrooms, cream sauce (heavy cream, butter, garlic, parmesan cheese, onion, salt, black pepper)",
      },
      {
        name: "Louisiana Chicken Pasta",
        category: "pasta",
        serving_size: 510,
        serving_unit: "g",
        calories: 1780,
        total_fat: 102,
        saturated_fat: 44,
        trans_fat: 1.5,
        cholesterol: 320,
        sodium: 3070,
        total_carbohydrates: 120,
        dietary_fiber: 8,
        total_sugars: 14,
        protein: 82,
        ingredients_text:
          "Bow-tie pasta (semolina wheat flour, water, eggs), blackened chicken breast (chicken, Cajun seasoning), shrimp, mushrooms, peppers, onion, New Orleans sauce (cream, butter, Cajun spices, garlic, parmesan cheese)",
      },
      {
        name: "Glamburger",
        category: "burger",
        serving_size: 425,
        serving_unit: "g",
        calories: 1290,
        total_fat: 78,
        saturated_fat: 30,
        trans_fat: 2,
        cholesterol: 195,
        sodium: 2140,
        total_carbohydrates: 72,
        dietary_fiber: 4,
        total_sugars: 18,
        protein: 72,
        ingredients_text:
          "Beef patty (ground beef, salt, black pepper), American cheese (milk, enzymes, salt), lettuce, tomato, onion, pickles, brioche bun (enriched wheat flour, butter, eggs, sugar, yeast, salt), special sauce, french fries (potatoes, vegetable oil, salt)",
      },
      {
        name: "Fish Tacos",
        category: "entree",
        serving_size: 369,
        serving_unit: "g",
        calories: 920,
        total_fat: 48,
        saturated_fat: 8,
        trans_fat: 0.5,
        cholesterol: 75,
        sodium: 1580,
        total_carbohydrates: 84,
        dietary_fiber: 6,
        total_sugars: 10,
        protein: 38,
        ingredients_text:
          "Battered fish (cod, enriched wheat flour, beer, cornstarch, salt), corn tortillas (corn, water, lime), cabbage slaw, avocado, pico de gallo (tomato, onion, cilantro, lime, jalapeno), chipotle mayo (mayonnaise, chipotle peppers), rice",
      },
      {
        name: "Caesar Salad",
        category: "salad",
        serving_size: 312,
        serving_unit: "g",
        calories: 720,
        total_fat: 54,
        saturated_fat: 10,
        trans_fat: 0,
        cholesterol: 40,
        sodium: 1280,
        total_carbohydrates: 32,
        dietary_fiber: 6,
        total_sugars: 6,
        protein: 18,
        ingredients_text:
          "Romaine lettuce, parmesan cheese (milk, enzymes, salt), croutons (enriched wheat flour, oil, garlic, salt), Caesar dressing (soybean oil, parmesan cheese, anchovy paste, lemon juice, egg yolks, garlic)",
      },
      {
        name: "Chicken Lettuce Wraps",
        category: "appetizer",
        serving_size: 312,
        serving_unit: "g",
        calories: 680,
        total_fat: 32,
        saturated_fat: 6,
        trans_fat: 0,
        cholesterol: 120,
        sodium: 1840,
        total_carbohydrates: 54,
        dietary_fiber: 4,
        total_sugars: 22,
        protein: 44,
        ingredients_text:
          "Chicken breast, butter lettuce, water chestnuts, shiitake mushrooms, green onion, rice sticks (rice flour, water), soy sauce, garlic, ginger, sesame oil, chili paste, lime",
      },
      {
        name: "SkinnyLicious Chicken",
        category: "entree",
        serving_size: 340,
        serving_unit: "g",
        calories: 570,
        total_fat: 16,
        saturated_fat: 3,
        trans_fat: 0,
        cholesterol: 130,
        sodium: 1280,
        total_carbohydrates: 54,
        dietary_fiber: 8,
        total_sugars: 8,
        protein: 52,
        ingredients_text:
          "Grilled chicken breast, fresh vegetables (asparagus, green beans, squash), brown rice, lemon sauce (lemon juice, olive oil, garlic, herbs, salt)",
      },
      {
        name: "Factory Nachos",
        category: "appetizer",
        serving_size: 510,
        serving_unit: "g",
        calories: 1820,
        total_fat: 112,
        saturated_fat: 44,
        trans_fat: 2,
        cholesterol: 180,
        sodium: 3240,
        total_carbohydrates: 136,
        dietary_fiber: 14,
        total_sugars: 12,
        protein: 62,
        ingredients_text:
          "Tortilla chips (corn, vegetable oil, salt), spicy chicken, melted cheese (cheddar, Monterey Jack), guacamole (avocado, lime, salt, cilantro), sour cream, salsa (tomato, onion, jalapeno, cilantro), black beans, green onion",
      },
      {
        name: "Crispy Chicken Costoletta",
        category: "entree",
        serving_size: 397,
        serving_unit: "g",
        calories: 1620,
        total_fat: 98,
        saturated_fat: 30,
        trans_fat: 1,
        cholesterol: 210,
        sodium: 2240,
        total_carbohydrates: 104,
        dietary_fiber: 6,
        total_sugars: 16,
        protein: 72,
        ingredients_text:
          "Chicken breast, panko breading (panko bread crumbs, enriched wheat flour, eggs, salt), parmesan cheese (milk, enzymes, salt), lemon sauce (butter, lemon juice, capers, garlic), arugula, tomato, mashed potatoes (potatoes, butter, cream, salt), frying oil (soybean oil)",
      },
      {
        name: "Miso Salmon",
        category: "entree",
        serving_size: 340,
        serving_unit: "g",
        calories: 920,
        total_fat: 42,
        saturated_fat: 10,
        trans_fat: 0,
        cholesterol: 140,
        sodium: 1680,
        total_carbohydrates: 68,
        dietary_fiber: 4,
        total_sugars: 28,
        protein: 62,
        ingredients_text:
          "Atlantic salmon fillet, miso glaze (white miso, sake, mirin, sugar, soy sauce), white rice, vegetables (snap peas, shiitake mushrooms, edamame)",
      },
      {
        name: "Oreo Dream Cheesecake",
        category: "dessert",
        serving_size: 255,
        serving_unit: "g",
        calories: 1040,
        total_fat: 62,
        saturated_fat: 34,
        trans_fat: 1.5,
        cholesterol: 220,
        sodium: 640,
        total_carbohydrates: 108,
        dietary_fiber: 3,
        total_sugars: 82,
        protein: 14,
        ingredients_text:
          "Cream cheese (milk, cream, salt, cultures), sugar, eggs, Oreo cookies (enriched wheat flour, sugar, cocoa, palm oil, soy lecithin), chocolate fudge cake, whipped cream (cream, sugar)",
      },
      {
        name: "Godiva Chocolate Cheesecake",
        category: "dessert",
        serving_size: 270,
        serving_unit: "g",
        calories: 1140,
        total_fat: 72,
        saturated_fat: 40,
        trans_fat: 2,
        cholesterol: 240,
        sodium: 560,
        total_carbohydrates: 112,
        dietary_fiber: 4,
        total_sugars: 90,
        protein: 16,
        ingredients_text:
          "Cream cheese (milk, cream, salt, cultures), Godiva chocolate (sugar, cocoa butter, milk, cocoa, soy lecithin, vanilla), sugar, eggs, chocolate cake, ganache (chocolate, cream), whipped cream (cream, sugar)",
      },
    ],
  },

  // ======================== RED ROBIN ========================
  {
    chain: "Red Robin",
    items: [
      {
        name: "Gourmet Cheeseburger",
        category: "burger",
        serving_size: 340,
        serving_unit: "g",
        calories: 880,
        total_fat: 54,
        saturated_fat: 22,
        trans_fat: 2,
        cholesterol: 155,
        sodium: 1420,
        total_carbohydrates: 48,
        dietary_fiber: 3,
        total_sugars: 10,
        protein: 50,
        ingredients_text:
          "Beef patty (ground beef, salt, black pepper), American cheese (milk, enzymes, salt), lettuce, tomato, pickles, onion, sesame seed bun (enriched wheat flour, water, sugar, soybean oil, yeast, salt), mayo, mustard, ketchup",
      },
      {
        name: "Royal Red Robin",
        category: "burger",
        serving_size: 397,
        serving_unit: "g",
        calories: 1070,
        total_fat: 68,
        saturated_fat: 26,
        trans_fat: 2.5,
        cholesterol: 290,
        sodium: 1680,
        total_carbohydrates: 52,
        dietary_fiber: 3,
        total_sugars: 12,
        protein: 62,
        ingredients_text:
          "Beef patty (ground beef, salt, black pepper), American cheese (milk, enzymes, salt), fried egg (egg, butter), smoked bacon (pork, water, salt, sugar, sodium nitrite), lettuce, tomato, sesame seed bun (enriched wheat flour, water, sugar, soybean oil, yeast, salt), mayo",
      },
      {
        name: "Whiskey River BBQ Burger",
        category: "burger",
        serving_size: 397,
        serving_unit: "g",
        calories: 1050,
        total_fat: 58,
        saturated_fat: 24,
        trans_fat: 2,
        cholesterol: 165,
        sodium: 1940,
        total_carbohydrates: 74,
        dietary_fiber: 4,
        total_sugars: 24,
        protein: 54,
        ingredients_text:
          "Beef patty (ground beef, salt, black pepper), cheddar cheese (milk, enzymes, salt), crispy onion straws (onion, enriched wheat flour, buttermilk, salt), Whiskey River BBQ sauce (brown sugar, tomato paste, vinegar, whiskey, spices), lettuce, tomato, sesame seed bun",
      },
      {
        name: "Banzai Burger",
        category: "burger",
        serving_size: 369,
        serving_unit: "g",
        calories: 990,
        total_fat: 52,
        saturated_fat: 20,
        trans_fat: 2,
        cholesterol: 155,
        sodium: 1780,
        total_carbohydrates: 78,
        dietary_fiber: 3,
        total_sugars: 30,
        protein: 52,
        ingredients_text:
          "Beef patty (ground beef, salt, black pepper), cheddar cheese (milk, enzymes, salt), teriyaki sauce (soy sauce, sugar, mirin, ginger, garlic), grilled pineapple, lettuce, tomato, mayo, sesame seed bun",
      },
      {
        name: "Bottomless Steak Fries",
        category: "side",
        serving_size: 227,
        serving_unit: "g",
        calories: 430,
        total_fat: 20,
        saturated_fat: 3,
        trans_fat: 0,
        cholesterol: 0,
        sodium: 840,
        total_carbohydrates: 58,
        dietary_fiber: 5,
        total_sugars: 1,
        protein: 6,
        ingredients_text:
          "Potatoes, vegetable oil (soybean oil, canola oil), seasoning (salt, garlic powder, onion powder, paprika)",
      },
      {
        name: "Chicken Tenders",
        category: "chicken",
        serving_size: 227,
        serving_unit: "g",
        calories: 520,
        total_fat: 26,
        saturated_fat: 4,
        trans_fat: 0,
        cholesterol: 95,
        sodium: 1180,
        total_carbohydrates: 36,
        dietary_fiber: 1,
        total_sugars: 2,
        protein: 34,
        ingredients_text:
          "Chicken tenderloins, breading (enriched wheat flour, cornstarch, salt, spices, leavening), frying oil (soybean oil), honey mustard dipping sauce (honey, mustard, mayonnaise)",
      },
      {
        name: "Wedge Salad",
        category: "salad",
        serving_size: 283,
        serving_unit: "g",
        calories: 360,
        total_fat: 28,
        saturated_fat: 10,
        trans_fat: 0,
        cholesterol: 40,
        sodium: 820,
        total_carbohydrates: 12,
        dietary_fiber: 3,
        total_sugars: 6,
        protein: 14,
        ingredients_text:
          "Iceberg lettuce wedge, smoked bacon (pork, water, salt, sugar, sodium nitrite), blue cheese crumbles (milk, cultures, enzymes, salt), tomato, blue cheese dressing (soybean oil, blue cheese, buttermilk, vinegar, egg yolks, salt)",
      },
      {
        name: "Onion Rings",
        category: "side",
        serving_size: 198,
        serving_unit: "g",
        calories: 540,
        total_fat: 30,
        saturated_fat: 5,
        trans_fat: 0.5,
        cholesterol: 10,
        sodium: 940,
        total_carbohydrates: 60,
        dietary_fiber: 3,
        total_sugars: 8,
        protein: 8,
        ingredients_text:
          "Onion rings, beer batter (enriched wheat flour, beer, cornstarch, salt, leavening), frying oil (soybean oil), campfire sauce",
      },
      {
        name: "Clucks and Fries",
        category: "chicken",
        serving_size: 340,
        serving_unit: "g",
        calories: 760,
        total_fat: 38,
        saturated_fat: 6,
        trans_fat: 0,
        cholesterol: 95,
        sodium: 1640,
        total_carbohydrates: 64,
        dietary_fiber: 4,
        total_sugars: 4,
        protein: 38,
        ingredients_text:
          "Chicken tenders (chicken tenderloins, breading, frying oil), steak fries (potatoes, vegetable oil, seasoning), ranch dipping sauce (soybean oil, buttermilk, egg yolks, vinegar, salt)",
      },
      {
        name: "Buzz Clucks",
        category: "chicken",
        serving_size: 283,
        serving_unit: "g",
        calories: 620,
        total_fat: 28,
        saturated_fat: 5,
        trans_fat: 0,
        cholesterol: 100,
        sodium: 1520,
        total_carbohydrates: 52,
        dietary_fiber: 2,
        total_sugars: 18,
        protein: 36,
        ingredients_text:
          "Chicken tenders (chicken tenderloins, breading, frying oil), Buzz sauce (honey, sriracha, soy sauce, garlic, ginger, sesame oil), sesame seeds",
      },
      {
        name: "Mac and Cheese",
        category: "side",
        serving_size: 198,
        serving_unit: "g",
        calories: 420,
        total_fat: 24,
        saturated_fat: 14,
        trans_fat: 0.5,
        cholesterol: 65,
        sodium: 840,
        total_carbohydrates: 34,
        dietary_fiber: 1,
        total_sugars: 4,
        protein: 16,
        ingredients_text:
          "Elbow pasta (semolina wheat flour, water), cheese sauce (cheddar cheese, milk, butter, enriched wheat flour, salt, mustard powder)",
      },
      {
        name: "Broccoli",
        category: "side",
        serving_size: 142,
        serving_unit: "g",
        calories: 45,
        total_fat: 1,
        saturated_fat: 0,
        trans_fat: 0,
        cholesterol: 0,
        sodium: 30,
        total_carbohydrates: 7,
        dietary_fiber: 4,
        total_sugars: 2,
        protein: 4,
        ingredients_text: "Steamed broccoli, salt",
      },
      {
        name: "Monster Shake",
        category: "beverage",
        serving_size: 591,
        serving_unit: "ml",
        calories: 1090,
        total_fat: 52,
        saturated_fat: 32,
        trans_fat: 1.5,
        cholesterol: 160,
        sodium: 520,
        total_carbohydrates: 140,
        dietary_fiber: 2,
        total_sugars: 118,
        protein: 20,
        ingredients_text:
          "Vanilla ice cream (milk, cream, sugar, vanilla), milk, whipped cream (cream, sugar), chocolate sauce (sugar, cocoa, cream, butter), cookie crumbles (enriched wheat flour, sugar, butter, chocolate chips)",
      },
      {
        name: "Brownie",
        category: "dessert",
        serving_size: 198,
        serving_unit: "g",
        calories: 680,
        total_fat: 32,
        saturated_fat: 16,
        trans_fat: 0.5,
        cholesterol: 110,
        sodium: 340,
        total_carbohydrates: 96,
        dietary_fiber: 3,
        total_sugars: 68,
        protein: 8,
        ingredients_text:
          "Enriched wheat flour, sugar, butter (cream, salt), eggs, cocoa, chocolate chips (sugar, chocolate liquor, cocoa butter, soy lecithin), vanilla extract, salt, vanilla ice cream (milk, cream, sugar, vanilla)",
      },
      {
        name: "Fish and Chips",
        category: "entree",
        serving_size: 397,
        serving_unit: "g",
        calories: 980,
        total_fat: 52,
        saturated_fat: 7,
        trans_fat: 0.5,
        cholesterol: 80,
        sodium: 2060,
        total_carbohydrates: 92,
        dietary_fiber: 5,
        total_sugars: 4,
        protein: 34,
        ingredients_text:
          "Cod fillet, beer batter (enriched wheat flour, beer, cornstarch, salt, leavening), steak fries (potatoes, vegetable oil, seasoning), frying oil (soybean oil), tartar sauce (mayonnaise, pickles, onion, lemon juice), coleslaw",
      },
    ],
  },

  // ======================== TGI FRIDAYS ========================
  {
    chain: "TGI Fridays",
    items: [
      {
        name: "Jack Daniels Burger",
        category: "burger",
        serving_size: 369,
        serving_unit: "g",
        calories: 1050,
        total_fat: 62,
        saturated_fat: 24,
        trans_fat: 2,
        cholesterol: 170,
        sodium: 1840,
        total_carbohydrates: 64,
        dietary_fiber: 3,
        total_sugars: 22,
        protein: 56,
        ingredients_text:
          "Beef patty (ground beef, salt, black pepper), Jack Daniel's glaze (Jack Daniel's whiskey, brown sugar, tomato paste, vinegar, spices), pepper jack cheese (milk, jalapeno peppers, enzymes, salt), smoked bacon (pork, water, salt, sugar, sodium nitrite), lettuce, tomato, onion rings, brioche bun",
      },
      {
        name: "Fridays Burger",
        category: "burger",
        serving_size: 340,
        serving_unit: "g",
        calories: 860,
        total_fat: 50,
        saturated_fat: 20,
        trans_fat: 2,
        cholesterol: 145,
        sodium: 1380,
        total_carbohydrates: 52,
        dietary_fiber: 3,
        total_sugars: 10,
        protein: 48,
        ingredients_text:
          "Beef patty (ground beef, salt, black pepper), American cheese (milk, enzymes, salt), lettuce, tomato, pickles, onion, sesame seed bun (enriched wheat flour, water, sugar, soybean oil, yeast, salt), mayo, mustard, ketchup",
      },
      {
        name: "Sesame Jack Chicken Strips",
        category: "appetizer",
        serving_size: 283,
        serving_unit: "g",
        calories: 820,
        total_fat: 38,
        saturated_fat: 6,
        trans_fat: 0,
        cholesterol: 110,
        sodium: 1960,
        total_carbohydrates: 76,
        dietary_fiber: 3,
        total_sugars: 28,
        protein: 38,
        ingredients_text:
          "Chicken tenders (chicken breast, enriched wheat flour, cornstarch, salt, spices), sesame Jack Daniel's glaze (soy sauce, brown sugar, Jack Daniel's whiskey, sesame oil, garlic, ginger), sesame seeds, green onion",
      },
      {
        name: "Loaded Potato Skins",
        category: "appetizer",
        serving_size: 312,
        serving_unit: "g",
        calories: 850,
        total_fat: 52,
        saturated_fat: 24,
        trans_fat: 1,
        cholesterol: 120,
        sodium: 1620,
        total_carbohydrates: 56,
        dietary_fiber: 4,
        total_sugars: 4,
        protein: 38,
        ingredients_text:
          "Potato skins (russet potato, vegetable oil), cheddar cheese (milk, enzymes, salt), smoked bacon (pork, water, salt, sugar, sodium nitrite), sour cream (milk, cream, cultures), chives",
      },
      {
        name: "Mozzarella Sticks",
        category: "appetizer",
        serving_size: 227,
        serving_unit: "g",
        calories: 690,
        total_fat: 38,
        saturated_fat: 16,
        trans_fat: 0.5,
        cholesterol: 60,
        sodium: 1580,
        total_carbohydrates: 56,
        dietary_fiber: 3,
        total_sugars: 8,
        protein: 28,
        ingredients_text:
          "Mozzarella cheese (milk, cultures, enzymes, salt), breading (enriched wheat flour, cornstarch, salt, spices, leavening), frying oil (soybean oil), marinara sauce (tomatoes, garlic, olive oil, basil, oregano, salt, sugar)",
      },
      {
        name: "Chicken Fingers",
        category: "chicken",
        serving_size: 255,
        serving_unit: "g",
        calories: 630,
        total_fat: 32,
        saturated_fat: 5,
        trans_fat: 0,
        cholesterol: 105,
        sodium: 1420,
        total_carbohydrates: 44,
        dietary_fiber: 2,
        total_sugars: 3,
        protein: 40,
        ingredients_text:
          "Chicken breast tenderloins, breading (enriched wheat flour, cornstarch, salt, spices, leavening), frying oil (soybean oil), honey mustard sauce (honey, mustard, mayonnaise, vinegar)",
      },
      {
        name: "Caesar Salad",
        category: "salad",
        serving_size: 198,
        serving_unit: "g",
        calories: 310,
        total_fat: 24,
        saturated_fat: 5,
        trans_fat: 0,
        cholesterol: 25,
        sodium: 680,
        total_carbohydrates: 14,
        dietary_fiber: 2,
        total_sugars: 3,
        protein: 9,
        ingredients_text:
          "Romaine lettuce, parmesan cheese (milk, enzymes, salt), croutons (enriched wheat flour, oil, garlic, salt), Caesar dressing (soybean oil, parmesan cheese, anchovy paste, lemon juice, egg yolks, garlic)",
      },
      {
        name: "Dragon-Glaze Salmon",
        category: "entree",
        serving_size: 283,
        serving_unit: "g",
        calories: 640,
        total_fat: 30,
        saturated_fat: 8,
        trans_fat: 0,
        cholesterol: 120,
        sodium: 1380,
        total_carbohydrates: 48,
        dietary_fiber: 4,
        total_sugars: 22,
        protein: 46,
        ingredients_text:
          "Atlantic salmon fillet, dragon glaze (soy sauce, brown sugar, ginger, garlic, sriracha, rice vinegar), rice, steamed broccoli",
      },
      {
        name: "Cajun Shrimp Pasta",
        category: "pasta",
        serving_size: 397,
        serving_unit: "g",
        calories: 1120,
        total_fat: 56,
        saturated_fat: 24,
        trans_fat: 1,
        cholesterol: 240,
        sodium: 2480,
        total_carbohydrates: 98,
        dietary_fiber: 5,
        total_sugars: 8,
        protein: 48,
        ingredients_text:
          "Penne pasta (semolina wheat flour, water), shrimp, Cajun Alfredo sauce (heavy cream, butter, parmesan cheese, Cajun seasoning, garlic), bell peppers, onion, tomato",
      },
      {
        name: "Steak",
        category: "steak",
        serving_size: 283,
        serving_unit: "g",
        calories: 580,
        total_fat: 32,
        saturated_fat: 14,
        trans_fat: 1,
        cholesterol: 165,
        sodium: 820,
        total_carbohydrates: 2,
        dietary_fiber: 0,
        total_sugars: 0,
        protein: 68,
        ingredients_text:
          "USDA Choice sirloin steak, seasoning (salt, black pepper, garlic powder), butter (cream, salt)",
      },
      {
        name: "Pot Stickers",
        category: "appetizer",
        serving_size: 227,
        serving_unit: "g",
        calories: 480,
        total_fat: 20,
        saturated_fat: 5,
        trans_fat: 0,
        cholesterol: 55,
        sodium: 1240,
        total_carbohydrates: 52,
        dietary_fiber: 2,
        total_sugars: 10,
        protein: 18,
        ingredients_text:
          "Wonton wrappers (enriched wheat flour, water, egg, salt), chicken (ground chicken, green onion, ginger, garlic, soy sauce, sesame oil), dipping sauce (soy sauce, rice vinegar, sesame oil, chili flakes)",
      },
      {
        name: "Whiskey Glaze",
        category: "entree",
        serving_size: 312,
        serving_unit: "g",
        calories: 740,
        total_fat: 28,
        saturated_fat: 10,
        trans_fat: 0,
        cholesterol: 185,
        sodium: 1580,
        total_carbohydrates: 54,
        dietary_fiber: 3,
        total_sugars: 28,
        protein: 62,
        ingredients_text:
          "Grilled chicken breast, Jack Daniel's glaze (Jack Daniel's whiskey, brown sugar, tomato paste, vinegar, spices), mashed potatoes (potatoes, butter, cream, salt), seasonal vegetables",
      },
      {
        name: "Brownie Obsession",
        category: "dessert",
        serving_size: 283,
        serving_unit: "g",
        calories: 1010,
        total_fat: 46,
        saturated_fat: 22,
        trans_fat: 1,
        cholesterol: 130,
        sodium: 420,
        total_carbohydrates: 140,
        dietary_fiber: 4,
        total_sugars: 102,
        protein: 12,
        ingredients_text:
          "Chocolate brownie (enriched wheat flour, sugar, butter, eggs, cocoa, chocolate chips), vanilla ice cream (milk, cream, sugar, vanilla), hot fudge (sugar, cocoa, cream, butter), whipped cream (cream, sugar), pecans",
      },
      {
        name: "Oreo Shake",
        category: "beverage",
        serving_size: 473,
        serving_unit: "ml",
        calories: 780,
        total_fat: 38,
        saturated_fat: 22,
        trans_fat: 1,
        cholesterol: 110,
        sodium: 460,
        total_carbohydrates: 98,
        dietary_fiber: 2,
        total_sugars: 80,
        protein: 14,
        ingredients_text:
          "Vanilla ice cream (milk, cream, sugar, vanilla), milk, Oreo cookies (enriched wheat flour, sugar, cocoa, palm oil, soy lecithin), whipped cream (cream, sugar)",
      },
      {
        name: "Vanilla Bean Cheesecake",
        category: "dessert",
        serving_size: 198,
        serving_unit: "g",
        calories: 570,
        total_fat: 36,
        saturated_fat: 20,
        trans_fat: 1,
        cholesterol: 145,
        sodium: 370,
        total_carbohydrates: 50,
        dietary_fiber: 0,
        total_sugars: 38,
        protein: 8,
        ingredients_text:
          "Cream cheese (milk, cream, salt, cultures), sugar, eggs, sour cream (milk, cream, cultures), vanilla bean, graham cracker crust (graham flour, sugar, butter, cinnamon), strawberry sauce (strawberries, sugar)",
      },
    ],
  },

  // ======================== LONGHORN STEAKHOUSE ========================
  {
    chain: "LongHorn Steakhouse",
    items: [
      {
        name: "Flo's Filet 6oz",
        category: "steak",
        serving_size: 170,
        serving_unit: "g",
        calories: 330,
        total_fat: 16,
        saturated_fat: 7,
        trans_fat: 0.5,
        cholesterol: 125,
        sodium: 460,
        total_carbohydrates: 0,
        dietary_fiber: 0,
        total_sugars: 0,
        protein: 44,
        ingredients_text:
          "USDA Choice filet mignon, seasoning (salt, cracked black pepper, garlic)",
      },
      {
        name: "Outlaw Ribeye 18oz",
        category: "steak",
        serving_size: 510,
        serving_unit: "g",
        calories: 1220,
        total_fat: 90,
        saturated_fat: 40,
        trans_fat: 2.5,
        cholesterol: 320,
        sodium: 940,
        total_carbohydrates: 0,
        dietary_fiber: 0,
        total_sugars: 0,
        protein: 100,
        ingredients_text:
          "USDA Choice bone-in ribeye steak, seasoning (salt, cracked black pepper, garlic)",
      },
      {
        name: "Renegade Top Sirloin 8oz",
        category: "steak",
        serving_size: 227,
        serving_unit: "g",
        calories: 370,
        total_fat: 16,
        saturated_fat: 7,
        trans_fat: 0.5,
        cholesterol: 130,
        sodium: 540,
        total_carbohydrates: 0,
        dietary_fiber: 0,
        total_sugars: 0,
        protein: 54,
        ingredients_text:
          "USDA Choice top sirloin steak, seasoning (salt, cracked black pepper, garlic powder)",
      },
      {
        name: "Parmesan Crusted Chicken",
        category: "entree",
        serving_size: 340,
        serving_unit: "g",
        calories: 890,
        total_fat: 48,
        saturated_fat: 18,
        trans_fat: 0.5,
        cholesterol: 210,
        sodium: 1920,
        total_carbohydrates: 42,
        dietary_fiber: 3,
        total_sugars: 6,
        protein: 70,
        ingredients_text:
          "Chicken breast, parmesan crust (parmesan cheese, bread crumbs, butter, garlic), ranch sauce (buttermilk, soybean oil, egg yolks, vinegar, garlic, herbs), mashed potatoes (potatoes, butter, cream, salt)",
      },
      {
        name: "LongHorn Salmon",
        category: "entree",
        serving_size: 255,
        serving_unit: "g",
        calories: 510,
        total_fat: 28,
        saturated_fat: 7,
        trans_fat: 0,
        cholesterol: 120,
        sodium: 680,
        total_carbohydrates: 12,
        dietary_fiber: 1,
        total_sugars: 8,
        protein: 52,
        ingredients_text:
          "Atlantic salmon fillet, lemon butter sauce (butter, lemon juice, garlic, herbs, salt), seasonal vegetables",
      },
      {
        name: "Grilled White Cheddar Burger",
        category: "burger",
        serving_size: 369,
        serving_unit: "g",
        calories: 960,
        total_fat: 58,
        saturated_fat: 24,
        trans_fat: 2,
        cholesterol: 165,
        sodium: 1580,
        total_carbohydrates: 52,
        dietary_fiber: 3,
        total_sugars: 10,
        protein: 56,
        ingredients_text:
          "Beef patty (ground beef, salt, black pepper), white cheddar cheese (milk, enzymes, salt), lettuce, tomato, onion, pickles, brioche bun (enriched wheat flour, butter, eggs, sugar, yeast, salt), LongHorn sauce (mayonnaise, ketchup, mustard, spices)",
      },
      {
        name: "Wild West Shrimp",
        category: "appetizer",
        serving_size: 227,
        serving_unit: "g",
        calories: 590,
        total_fat: 30,
        saturated_fat: 5,
        trans_fat: 0,
        cholesterol: 200,
        sodium: 1680,
        total_carbohydrates: 48,
        dietary_fiber: 2,
        total_sugars: 12,
        protein: 26,
        ingredients_text:
          "Shrimp, crispy breading (enriched wheat flour, cornstarch, salt, spices), frying oil (soybean oil), spicy sauce (mayonnaise, sriracha, honey, lime juice)",
      },
      {
        name: "Steakhouse Mac and Cheese",
        category: "side",
        serving_size: 227,
        serving_unit: "g",
        calories: 480,
        total_fat: 28,
        saturated_fat: 16,
        trans_fat: 0.5,
        cholesterol: 75,
        sodium: 940,
        total_carbohydrates: 38,
        dietary_fiber: 1,
        total_sugars: 4,
        protein: 18,
        ingredients_text:
          "Cavatappi pasta (semolina wheat flour, water), cheese sauce (cheddar cheese, Monterey Jack cheese, milk, butter, enriched wheat flour, salt), bread crumb topping (panko bread crumbs, butter, parmesan cheese)",
      },
      {
        name: "Seasoned Rice",
        category: "side",
        serving_size: 142,
        serving_unit: "g",
        calories: 200,
        total_fat: 3,
        saturated_fat: 1,
        trans_fat: 0,
        cholesterol: 0,
        sodium: 420,
        total_carbohydrates: 38,
        dietary_fiber: 1,
        total_sugars: 1,
        protein: 4,
        ingredients_text:
          "Long grain rice, butter (cream, salt), seasoning (salt, garlic powder, onion powder, parsley)",
      },
      {
        name: "Steamed Broccoli",
        category: "side",
        serving_size: 142,
        serving_unit: "g",
        calories: 45,
        total_fat: 1,
        saturated_fat: 0,
        trans_fat: 0,
        cholesterol: 0,
        sodium: 30,
        total_carbohydrates: 7,
        dietary_fiber: 4,
        total_sugars: 2,
        protein: 4,
        ingredients_text: "Broccoli, salt",
      },
      {
        name: "Caesar Salad",
        category: "salad",
        serving_size: 198,
        serving_unit: "g",
        calories: 300,
        total_fat: 22,
        saturated_fat: 4,
        trans_fat: 0,
        cholesterol: 20,
        sodium: 640,
        total_carbohydrates: 14,
        dietary_fiber: 2,
        total_sugars: 3,
        protein: 9,
        ingredients_text:
          "Romaine lettuce, parmesan cheese (milk, enzymes, salt), croutons (enriched wheat flour, oil, garlic, salt), Caesar dressing (soybean oil, parmesan cheese, anchovy paste, lemon juice, egg yolks, garlic)",
      },
      {
        name: "Loaded Baked Potato",
        category: "side",
        serving_size: 369,
        serving_unit: "g",
        calories: 460,
        total_fat: 20,
        saturated_fat: 12,
        trans_fat: 0.5,
        cholesterol: 55,
        sodium: 560,
        total_carbohydrates: 56,
        dietary_fiber: 5,
        total_sugars: 4,
        protein: 14,
        ingredients_text:
          "Russet potato, butter (cream, salt), sour cream (milk, cream, cultures), cheddar cheese (milk, enzymes, salt), smoked bacon (pork, water, salt, sugar, sodium nitrite), chives",
      },
      {
        name: "Texas Tonion",
        category: "appetizer",
        serving_size: 482,
        serving_unit: "g",
        calories: 1720,
        total_fat: 114,
        saturated_fat: 22,
        trans_fat: 2,
        cholesterol: 50,
        sodium: 3640,
        total_carbohydrates: 142,
        dietary_fiber: 8,
        total_sugars: 16,
        protein: 24,
        ingredients_text:
          "Onion, breading (enriched wheat flour, cornstarch, salt, spices, leavening), frying oil (soybean oil), creamy chili sauce (sour cream, mayonnaise, chili peppers, garlic, spices)",
      },
      {
        name: "Molten Lava Cake",
        category: "dessert",
        serving_size: 227,
        serving_unit: "g",
        calories: 780,
        total_fat: 38,
        saturated_fat: 20,
        trans_fat: 0.5,
        cholesterol: 160,
        sodium: 380,
        total_carbohydrates: 102,
        dietary_fiber: 3,
        total_sugars: 76,
        protein: 10,
        ingredients_text:
          "Enriched wheat flour, sugar, butter (cream, salt), eggs, chocolate (sugar, chocolate liquor, cocoa butter, soy lecithin), cocoa, vanilla ice cream (milk, cream, sugar, vanilla), whipped cream (cream, sugar)",
      },
      {
        name: "Chocolate Stampede",
        category: "dessert",
        serving_size: 340,
        serving_unit: "g",
        calories: 1340,
        total_fat: 64,
        saturated_fat: 36,
        trans_fat: 1.5,
        cholesterol: 200,
        sodium: 580,
        total_carbohydrates: 182,
        dietary_fiber: 6,
        total_sugars: 136,
        protein: 16,
        ingredients_text:
          "Chocolate cake (enriched wheat flour, sugar, butter, eggs, cocoa), chocolate brownie, vanilla ice cream (milk, cream, sugar, vanilla), chocolate sauce (sugar, cocoa, cream, butter), caramel sauce (sugar, butter, cream), whipped cream (cream, sugar), pecans",
      },
    ],
  },

  // ======================== GOLDEN CORRAL ========================
  {
    chain: "Golden Corral",
    items: [
      {
        name: "Fried Chicken Breast",
        category: "chicken",
        serving_size: 198,
        serving_unit: "g",
        calories: 420,
        total_fat: 22,
        saturated_fat: 5,
        trans_fat: 0,
        cholesterol: 130,
        sodium: 980,
        total_carbohydrates: 18,
        dietary_fiber: 1,
        total_sugars: 0,
        protein: 38,
        ingredients_text:
          "Chicken breast (bone-in), breading (enriched wheat flour, salt, spices, garlic powder, onion powder, leavening), frying oil (soybean oil)",
      },
      {
        name: "Pot Roast",
        category: "entree",
        serving_size: 227,
        serving_unit: "g",
        calories: 360,
        total_fat: 16,
        saturated_fat: 6,
        trans_fat: 0.5,
        cholesterol: 120,
        sodium: 840,
        total_carbohydrates: 14,
        dietary_fiber: 2,
        total_sugars: 4,
        protein: 40,
        ingredients_text:
          "Beef chuck roast, onion, carrots, celery, beef broth (water, beef stock, salt), potatoes, salt, black pepper, garlic, thyme",
      },
      {
        name: "Meatloaf",
        category: "entree",
        serving_size: 227,
        serving_unit: "g",
        calories: 380,
        total_fat: 22,
        saturated_fat: 8,
        trans_fat: 0.5,
        cholesterol: 115,
        sodium: 920,
        total_carbohydrates: 18,
        dietary_fiber: 1,
        total_sugars: 6,
        protein: 28,
        ingredients_text:
          "Ground beef, bread crumbs (enriched wheat flour, salt), eggs, onion, ketchup (tomato concentrate, vinegar, high fructose corn syrup, salt), salt, black pepper, garlic powder, Worcestershire sauce",
      },
      {
        name: "Fried Shrimp 6pc",
        category: "entree",
        serving_size: 170,
        serving_unit: "g",
        calories: 340,
        total_fat: 18,
        saturated_fat: 3,
        trans_fat: 0,
        cholesterol: 160,
        sodium: 780,
        total_carbohydrates: 28,
        dietary_fiber: 1,
        total_sugars: 2,
        protein: 18,
        ingredients_text:
          "Shrimp, breading (enriched wheat flour, cornstarch, salt, spices, leavening), frying oil (soybean oil), cocktail sauce",
      },
      {
        name: "Baked Fish",
        category: "entree",
        serving_size: 198,
        serving_unit: "g",
        calories: 220,
        total_fat: 8,
        saturated_fat: 2,
        trans_fat: 0,
        cholesterol: 80,
        sodium: 480,
        total_carbohydrates: 6,
        dietary_fiber: 0,
        total_sugars: 1,
        protein: 32,
        ingredients_text:
          "Pollock fillet, butter (cream, salt), lemon juice, seasoning (salt, black pepper, paprika, garlic powder)",
      },
      {
        name: "Mac and Cheese",
        category: "side",
        serving_size: 170,
        serving_unit: "g",
        calories: 310,
        total_fat: 16,
        saturated_fat: 8,
        trans_fat: 0,
        cholesterol: 40,
        sodium: 680,
        total_carbohydrates: 30,
        dietary_fiber: 1,
        total_sugars: 4,
        protein: 12,
        ingredients_text:
          "Elbow pasta (semolina wheat flour, water), cheese sauce (cheddar cheese, milk, butter, enriched wheat flour, salt)",
      },
      {
        name: "Mashed Potatoes",
        category: "side",
        serving_size: 170,
        serving_unit: "g",
        calories: 200,
        total_fat: 8,
        saturated_fat: 4,
        trans_fat: 0,
        cholesterol: 20,
        sodium: 460,
        total_carbohydrates: 28,
        dietary_fiber: 2,
        total_sugars: 2,
        protein: 4,
        ingredients_text:
          "Potatoes, butter (cream, salt), milk, salt, black pepper",
      },
      {
        name: "Green Beans",
        category: "side",
        serving_size: 113,
        serving_unit: "g",
        calories: 50,
        total_fat: 2,
        saturated_fat: 1,
        trans_fat: 0,
        cholesterol: 5,
        sodium: 280,
        total_carbohydrates: 6,
        dietary_fiber: 3,
        total_sugars: 2,
        protein: 2,
        ingredients_text:
          "Green beans, butter (cream, salt), seasoning (salt, garlic powder, black pepper)",
      },
      {
        name: "Corn on Cob",
        category: "side",
        serving_size: 155,
        serving_unit: "g",
        calories: 160,
        total_fat: 4,
        saturated_fat: 2,
        trans_fat: 0,
        cholesterol: 10,
        sodium: 180,
        total_carbohydrates: 28,
        dietary_fiber: 3,
        total_sugars: 8,
        protein: 5,
        ingredients_text: "Sweet corn, butter (cream, salt), salt",
      },
      {
        name: "Yeast Roll",
        category: "side",
        serving_size: 57,
        serving_unit: "g",
        calories: 160,
        total_fat: 4,
        saturated_fat: 2,
        trans_fat: 0,
        cholesterol: 10,
        sodium: 240,
        total_carbohydrates: 26,
        dietary_fiber: 1,
        total_sugars: 4,
        protein: 4,
        ingredients_text:
          "Enriched wheat flour, water, sugar, yeast, butter (cream, salt), salt, eggs",
      },
      {
        name: "Salad Bar plate",
        category: "salad",
        serving_size: 227,
        serving_unit: "g",
        calories: 260,
        total_fat: 14,
        saturated_fat: 4,
        trans_fat: 0,
        cholesterol: 20,
        sodium: 520,
        total_carbohydrates: 24,
        dietary_fiber: 4,
        total_sugars: 8,
        protein: 10,
        ingredients_text:
          "Mixed greens (iceberg lettuce, romaine, spinach), tomatoes, cucumbers, shredded carrots, croutons (enriched wheat flour, oil, garlic), shredded cheese (milk, enzymes, salt), ranch dressing (soybean oil, buttermilk, egg yolks, vinegar, salt)",
      },
      {
        name: "Pizza slice",
        category: "pizza",
        serving_size: 142,
        serving_unit: "g",
        calories: 340,
        total_fat: 14,
        saturated_fat: 6,
        trans_fat: 0,
        cholesterol: 30,
        sodium: 720,
        total_carbohydrates: 38,
        dietary_fiber: 2,
        total_sugars: 4,
        protein: 14,
        ingredients_text:
          "Pizza dough (enriched wheat flour, water, sugar, yeast, soybean oil, salt), pizza sauce (tomatoes, garlic, oregano, basil, salt, sugar), mozzarella cheese (milk, cultures, enzymes, salt), pepperoni (pork, beef, salt, spices, sodium nitrite)",
      },
      {
        name: "Chocolate Cake",
        category: "dessert",
        serving_size: 142,
        serving_unit: "g",
        calories: 420,
        total_fat: 20,
        saturated_fat: 8,
        trans_fat: 0.5,
        cholesterol: 55,
        sodium: 380,
        total_carbohydrates: 58,
        dietary_fiber: 2,
        total_sugars: 42,
        protein: 5,
        ingredients_text:
          "Enriched wheat flour, sugar, butter (cream, salt), eggs, cocoa, chocolate frosting (sugar, cocoa, butter, cream, vanilla), baking powder, salt, vanilla extract",
      },
      {
        name: "Banana Pudding",
        category: "dessert",
        serving_size: 170,
        serving_unit: "g",
        calories: 280,
        total_fat: 10,
        saturated_fat: 5,
        trans_fat: 0,
        cholesterol: 40,
        sodium: 220,
        total_carbohydrates: 44,
        dietary_fiber: 1,
        total_sugars: 32,
        protein: 4,
        ingredients_text:
          "Vanilla pudding (milk, sugar, cornstarch, eggs, vanilla extract, salt), bananas, vanilla wafers (enriched wheat flour, sugar, palm oil, eggs, vanilla), whipped cream (cream, sugar)",
      },
      {
        name: "Cotton Candy",
        category: "dessert",
        serving_size: 28,
        serving_unit: "g",
        calories: 110,
        total_fat: 0,
        saturated_fat: 0,
        trans_fat: 0,
        cholesterol: 0,
        sodium: 0,
        total_carbohydrates: 28,
        dietary_fiber: 0,
        total_sugars: 28,
        protein: 0,
        ingredients_text: "Sugar, artificial colors (Red 40, Blue 1)",
      },
    ],
  },

  // ======================== BOB EVANS ========================
  {
    chain: "Bob Evans",
    items: [
      {
        name: "Farmhouse Garden Salad",
        category: "salad",
        serving_size: 255,
        serving_unit: "g",
        calories: 220,
        total_fat: 12,
        saturated_fat: 5,
        trans_fat: 0,
        cholesterol: 25,
        sodium: 480,
        total_carbohydrates: 18,
        dietary_fiber: 3,
        total_sugars: 6,
        protein: 10,
        ingredients_text:
          "Mixed greens (iceberg lettuce, romaine), tomatoes, cucumbers, shredded cheddar cheese (milk, enzymes, salt), croutons (enriched wheat flour, oil, garlic), ranch dressing (soybean oil, buttermilk, egg yolks, vinegar, salt)",
      },
      {
        name: "Country Fried Steak",
        category: "entree",
        serving_size: 340,
        serving_unit: "g",
        calories: 810,
        total_fat: 48,
        saturated_fat: 14,
        trans_fat: 1,
        cholesterol: 120,
        sodium: 2040,
        total_carbohydrates: 54,
        dietary_fiber: 2,
        total_sugars: 4,
        protein: 38,
        ingredients_text:
          "Beef cutlet, breading (enriched wheat flour, salt, spices, leavening), frying oil (soybean oil), country gravy (milk, enriched wheat flour, butter, salt, black pepper, sausage drippings)",
      },
      {
        name: "Slow-Roasted Turkey",
        category: "entree",
        serving_size: 283,
        serving_unit: "g",
        calories: 390,
        total_fat: 12,
        saturated_fat: 4,
        trans_fat: 0,
        cholesterol: 140,
        sodium: 1180,
        total_carbohydrates: 22,
        dietary_fiber: 2,
        total_sugars: 4,
        protein: 48,
        ingredients_text:
          "Turkey breast (turkey, water, salt, sodium phosphate), turkey gravy (turkey stock, enriched wheat flour, butter, salt, black pepper), bread and celery dressing",
      },
      {
        name: "Grilled Chicken Breast",
        category: "entree",
        serving_size: 198,
        serving_unit: "g",
        calories: 280,
        total_fat: 8,
        saturated_fat: 2,
        trans_fat: 0,
        cholesterol: 130,
        sodium: 620,
        total_carbohydrates: 2,
        dietary_fiber: 0,
        total_sugars: 1,
        protein: 50,
        ingredients_text:
          "Chicken breast, seasoning (salt, black pepper, garlic powder, paprika, onion powder)",
      },
      {
        name: "Homestyle Meatloaf",
        category: "entree",
        serving_size: 255,
        serving_unit: "g",
        calories: 530,
        total_fat: 30,
        saturated_fat: 12,
        trans_fat: 1,
        cholesterol: 145,
        sodium: 1280,
        total_carbohydrates: 28,
        dietary_fiber: 2,
        total_sugars: 10,
        protein: 36,
        ingredients_text:
          "Ground beef, bread crumbs (enriched wheat flour, salt), eggs, onion, ketchup glaze (ketchup, brown sugar, mustard), Worcestershire sauce, garlic, salt, black pepper",
      },
      {
        name: "Pot Pie",
        category: "entree",
        serving_size: 340,
        serving_unit: "g",
        calories: 680,
        total_fat: 38,
        saturated_fat: 18,
        trans_fat: 1,
        cholesterol: 90,
        sodium: 1520,
        total_carbohydrates: 58,
        dietary_fiber: 3,
        total_sugars: 6,
        protein: 26,
        ingredients_text:
          "Pie crust (enriched wheat flour, butter, water, salt), chicken breast, peas, carrots, celery, onion, cream sauce (heavy cream, chicken broth, enriched wheat flour, butter, salt, black pepper)",
      },
      {
        name: "Farmhouse Scramble",
        category: "breakfast",
        serving_size: 340,
        serving_unit: "g",
        calories: 620,
        total_fat: 42,
        saturated_fat: 16,
        trans_fat: 0.5,
        cholesterol: 480,
        sodium: 1380,
        total_carbohydrates: 18,
        dietary_fiber: 2,
        total_sugars: 4,
        protein: 42,
        ingredients_text:
          "Eggs, sausage (pork, salt, spices, sage), smoked bacon (pork, water, salt, sugar, sodium nitrite), ham (pork, water, salt, sodium phosphate), cheddar cheese (milk, enzymes, salt), bell peppers, onion, mushrooms, butter (cream, salt)",
      },
      {
        name: "Biscuit",
        category: "side",
        serving_size: 85,
        serving_unit: "g",
        calories: 280,
        total_fat: 12,
        saturated_fat: 6,
        trans_fat: 0,
        cholesterol: 15,
        sodium: 620,
        total_carbohydrates: 36,
        dietary_fiber: 1,
        total_sugars: 4,
        protein: 5,
        ingredients_text:
          "Enriched wheat flour, buttermilk, butter (cream, salt), baking powder, sugar, salt",
      },
      {
        name: "Mashed Potatoes",
        category: "side",
        serving_size: 170,
        serving_unit: "g",
        calories: 210,
        total_fat: 9,
        saturated_fat: 5,
        trans_fat: 0,
        cholesterol: 25,
        sodium: 480,
        total_carbohydrates: 28,
        dietary_fiber: 2,
        total_sugars: 2,
        protein: 4,
        ingredients_text:
          "Potatoes, butter (cream, salt), milk, salt, black pepper",
      },
      {
        name: "Coleslaw",
        category: "side",
        serving_size: 113,
        serving_unit: "g",
        calories: 180,
        total_fat: 12,
        saturated_fat: 2,
        trans_fat: 0,
        cholesterol: 10,
        sodium: 240,
        total_carbohydrates: 16,
        dietary_fiber: 2,
        total_sugars: 12,
        protein: 1,
        ingredients_text:
          "Cabbage, carrots, coleslaw dressing (mayonnaise, sugar, vinegar, celery seed, salt, black pepper)",
      },
      {
        name: "Green Beans",
        category: "side",
        serving_size: 113,
        serving_unit: "g",
        calories: 50,
        total_fat: 2,
        saturated_fat: 1,
        trans_fat: 0,
        cholesterol: 5,
        sodium: 300,
        total_carbohydrates: 6,
        dietary_fiber: 3,
        total_sugars: 2,
        protein: 2,
        ingredients_text:
          "Green beans, butter (cream, salt), seasoning (salt, garlic powder, black pepper), smoked ham pieces",
      },
      {
        name: "Bread and Celery Dressing",
        category: "side",
        serving_size: 142,
        serving_unit: "g",
        calories: 240,
        total_fat: 10,
        saturated_fat: 4,
        trans_fat: 0,
        cholesterol: 30,
        sodium: 680,
        total_carbohydrates: 32,
        dietary_fiber: 2,
        total_sugars: 4,
        protein: 6,
        ingredients_text:
          "Bread cubes (enriched wheat flour, water, sugar, yeast, salt), celery, onion, butter (cream, salt), chicken broth, eggs, sage, thyme, salt, black pepper",
      },
      {
        name: "Coconut Cream Pie",
        category: "dessert",
        serving_size: 198,
        serving_unit: "g",
        calories: 540,
        total_fat: 28,
        saturated_fat: 18,
        trans_fat: 0.5,
        cholesterol: 70,
        sodium: 340,
        total_carbohydrates: 66,
        dietary_fiber: 2,
        total_sugars: 44,
        protein: 6,
        ingredients_text:
          "Coconut cream filling (coconut milk, sugar, cornstarch, eggs, vanilla, shredded coconut), pie crust (enriched wheat flour, butter, water, salt), whipped cream (cream, sugar), toasted coconut",
      },
      {
        name: "Peanut Butter Brownie",
        category: "dessert",
        serving_size: 198,
        serving_unit: "g",
        calories: 620,
        total_fat: 34,
        saturated_fat: 12,
        trans_fat: 0.5,
        cholesterol: 80,
        sodium: 360,
        total_carbohydrates: 72,
        dietary_fiber: 3,
        total_sugars: 52,
        protein: 10,
        ingredients_text:
          "Enriched wheat flour, sugar, butter (cream, salt), eggs, cocoa, peanut butter (roasted peanuts, salt, sugar, hydrogenated vegetable oil), chocolate chips (sugar, chocolate liquor, cocoa butter, soy lecithin), vanilla extract",
      },
      {
        name: "Coffee",
        category: "beverage",
        serving_size: 355,
        serving_unit: "ml",
        calories: 5,
        total_fat: 0,
        saturated_fat: 0,
        trans_fat: 0,
        cholesterol: 0,
        sodium: 5,
        total_carbohydrates: 0,
        dietary_fiber: 0,
        total_sugars: 0,
        protein: 0,
        ingredients_text: "Brewed coffee (water, ground coffee beans)",
      },
    ],
  },

  // ======================== P.F. CHANG'S ========================
  {
    chain: "P.F. Chang's",
    items: [
      {
        name: "Chang's Chicken Lettuce Wraps",
        category: "appetizer",
        serving_size: 312,
        serving_unit: "g",
        calories: 590,
        total_fat: 24,
        saturated_fat: 4,
        trans_fat: 0,
        cholesterol: 110,
        sodium: 2040,
        total_carbohydrates: 52,
        dietary_fiber: 3,
        total_sugars: 18,
        protein: 40,
        ingredients_text:
          "Chicken breast (minced), butter lettuce, water chestnuts, shiitake mushrooms, green onion, rice sticks (rice flour, water), soy sauce (water, soybeans, wheat, salt), garlic, ginger, sesame oil, chili paste",
      },
      {
        name: "Mongolian Beef",
        category: "entree",
        serving_size: 340,
        serving_unit: "g",
        calories: 790,
        total_fat: 36,
        saturated_fat: 12,
        trans_fat: 0.5,
        cholesterol: 120,
        sodium: 2280,
        total_carbohydrates: 68,
        dietary_fiber: 3,
        total_sugars: 42,
        protein: 46,
        ingredients_text:
          "Flank steak (sliced), scallions, garlic, Mongolian sauce (soy sauce, brown sugar, hoisin sauce, rice wine, sesame oil, cornstarch), soybean oil",
      },
      {
        name: "Kung Pao Chicken",
        category: "entree",
        serving_size: 340,
        serving_unit: "g",
        calories: 680,
        total_fat: 32,
        saturated_fat: 6,
        trans_fat: 0,
        cholesterol: 110,
        sodium: 1980,
        total_carbohydrates: 52,
        dietary_fiber: 4,
        total_sugars: 20,
        protein: 46,
        ingredients_text:
          "Chicken breast (diced), peanuts, dried chili peppers, bell peppers, zucchini, green onion, Kung Pao sauce (soy sauce, rice vinegar, sugar, chili paste, garlic, cornstarch, sesame oil), soybean oil",
      },
      {
        name: "Orange Chicken",
        category: "entree",
        serving_size: 340,
        serving_unit: "g",
        calories: 820,
        total_fat: 34,
        saturated_fat: 6,
        trans_fat: 0,
        cholesterol: 100,
        sodium: 1640,
        total_carbohydrates: 88,
        dietary_fiber: 2,
        total_sugars: 46,
        protein: 38,
        ingredients_text:
          "Chicken breast (battered, fried), orange sauce (orange juice, sugar, soy sauce, rice vinegar, garlic, ginger, chili flakes, cornstarch), breading (enriched wheat flour, cornstarch, salt, leavening), frying oil (soybean oil)",
      },
      {
        name: "Lo Mein Chicken",
        category: "entree",
        serving_size: 397,
        serving_unit: "g",
        calories: 820,
        total_fat: 28,
        saturated_fat: 5,
        trans_fat: 0,
        cholesterol: 90,
        sodium: 2340,
        total_carbohydrates: 96,
        dietary_fiber: 5,
        total_sugars: 14,
        protein: 42,
        ingredients_text:
          "Lo mein noodles (wheat flour, water, egg), chicken breast (sliced), cabbage, bean sprouts, carrots, scallions, lo mein sauce (soy sauce, oyster sauce, sesame oil, garlic, ginger, sugar, cornstarch), soybean oil",
      },
      {
        name: "Fried Rice",
        category: "side",
        serving_size: 283,
        serving_unit: "g",
        calories: 520,
        total_fat: 16,
        saturated_fat: 3,
        trans_fat: 0,
        cholesterol: 95,
        sodium: 1280,
        total_carbohydrates: 72,
        dietary_fiber: 2,
        total_sugars: 4,
        protein: 18,
        ingredients_text:
          "White rice, eggs, scallions, bean sprouts, soy sauce (water, soybeans, wheat, salt), sesame oil, soybean oil, salt",
      },
      {
        name: "Chang's Spicy Chicken",
        category: "entree",
        serving_size: 340,
        serving_unit: "g",
        calories: 740,
        total_fat: 30,
        saturated_fat: 5,
        trans_fat: 0,
        cholesterol: 105,
        sodium: 2180,
        total_carbohydrates: 72,
        dietary_fiber: 4,
        total_sugars: 30,
        protein: 42,
        ingredients_text:
          "Chicken breast (diced), dried chili peppers, peanuts, bell peppers, onion, garlic, ginger, spicy sauce (soy sauce, chili paste, sugar, rice vinegar, sesame oil, cornstarch), soybean oil",
      },
      {
        name: "Dynamite Shrimp",
        category: "appetizer",
        serving_size: 198,
        serving_unit: "g",
        calories: 480,
        total_fat: 26,
        saturated_fat: 4,
        trans_fat: 0,
        cholesterol: 140,
        sodium: 1120,
        total_carbohydrates: 40,
        dietary_fiber: 1,
        total_sugars: 14,
        protein: 22,
        ingredients_text:
          "Shrimp, crispy batter (enriched wheat flour, cornstarch, salt, leavening), frying oil (soybean oil), dynamite sauce (mayonnaise, sriracha, honey, lime juice, garlic)",
      },
      {
        name: "Egg Drop Soup",
        category: "soup",
        serving_size: 227,
        serving_unit: "g",
        calories: 60,
        total_fat: 2,
        saturated_fat: 0.5,
        trans_fat: 0,
        cholesterol: 55,
        sodium: 820,
        total_carbohydrates: 6,
        dietary_fiber: 0,
        total_sugars: 1,
        protein: 4,
        ingredients_text:
          "Chicken broth (water, chicken stock, salt), eggs, cornstarch, scallions, sesame oil, white pepper",
      },
      {
        name: "Hot and Sour Soup",
        category: "soup",
        serving_size: 227,
        serving_unit: "g",
        calories: 110,
        total_fat: 4,
        saturated_fat: 1,
        trans_fat: 0,
        cholesterol: 45,
        sodium: 980,
        total_carbohydrates: 12,
        dietary_fiber: 1,
        total_sugars: 2,
        protein: 6,
        ingredients_text:
          "Chicken broth (water, chicken stock, salt), tofu (soybeans, water, calcium sulfate), bamboo shoots, shiitake mushrooms, eggs, rice vinegar, soy sauce, chili paste, cornstarch, sesame oil, white pepper, scallions",
      },
      {
        name: "Spring Rolls",
        category: "appetizer",
        serving_size: 170,
        serving_unit: "g",
        calories: 380,
        total_fat: 18,
        saturated_fat: 3,
        trans_fat: 0,
        cholesterol: 15,
        sodium: 820,
        total_carbohydrates: 46,
        dietary_fiber: 3,
        total_sugars: 6,
        protein: 10,
        ingredients_text:
          "Spring roll wrapper (enriched wheat flour, water, salt), cabbage, carrots, celery, shiitake mushrooms, glass noodles, soy sauce, sesame oil, frying oil (soybean oil), plum sauce (plums, sugar, vinegar, ginger, salt)",
      },
      {
        name: "Crispy Green Beans",
        category: "appetizer",
        serving_size: 198,
        serving_unit: "g",
        calories: 420,
        total_fat: 24,
        saturated_fat: 4,
        trans_fat: 0,
        cholesterol: 10,
        sodium: 1340,
        total_carbohydrates: 40,
        dietary_fiber: 4,
        total_sugars: 14,
        protein: 10,
        ingredients_text:
          "Green beans, light batter (rice flour, cornstarch, salt), frying oil (soybean oil), spicy sauce (soy sauce, chili paste, garlic, sugar, rice vinegar, sesame oil)",
      },
      {
        name: "The Great Wall of Chocolate",
        category: "dessert",
        serving_size: 312,
        serving_unit: "g",
        calories: 1520,
        total_fat: 72,
        saturated_fat: 40,
        trans_fat: 1.5,
        cholesterol: 200,
        sodium: 620,
        total_carbohydrates: 210,
        dietary_fiber: 8,
        total_sugars: 162,
        protein: 18,
        ingredients_text:
          "Chocolate cake (enriched wheat flour, sugar, butter, eggs, cocoa, chocolate), chocolate mousse (chocolate, cream, eggs, sugar), chocolate ganache (chocolate, cream), raspberry sauce (raspberries, sugar), whipped cream (cream, sugar)",
      },
      {
        name: "Banana Spring Rolls",
        category: "dessert",
        serving_size: 198,
        serving_unit: "g",
        calories: 560,
        total_fat: 22,
        saturated_fat: 8,
        trans_fat: 0,
        cholesterol: 30,
        sodium: 320,
        total_carbohydrates: 84,
        dietary_fiber: 3,
        total_sugars: 48,
        protein: 6,
        ingredients_text:
          "Bananas, spring roll wrapper (enriched wheat flour, water, salt), coconut pineapple ice cream (coconut milk, cream, sugar, pineapple), frying oil (soybean oil), honey, sesame seeds, powdered sugar",
      },
      {
        name: "Edamame",
        category: "appetizer",
        serving_size: 142,
        serving_unit: "g",
        calories: 160,
        total_fat: 8,
        saturated_fat: 1,
        trans_fat: 0,
        cholesterol: 0,
        sodium: 580,
        total_carbohydrates: 10,
        dietary_fiber: 5,
        total_sugars: 3,
        protein: 14,
        ingredients_text:
          "Edamame (soybeans in pods), kosher salt, sesame oil",
      },
    ],
  },
];

// ---------------------------------------------------------------------------
// SQL statements (same as import-chains.ts)
// ---------------------------------------------------------------------------

const upsertVendor = db.prepare(`
  INSERT INTO vendors (id, name, type, api_key)
  VALUES (@id, @name, @type, @api_key)
  ON CONFLICT(id) DO UPDATE SET
    name = excluded.name,
    type = excluded.type
`);

const upsertFood = db.prepare(`
  INSERT INTO foods (id, name, brand, category, serving_size, serving_unit, source, vendor_id,
    calories, total_fat, saturated_fat, trans_fat, cholesterol, sodium,
    total_carbohydrates, dietary_fiber, total_sugars, protein,
    ingredients_text, allergens, dietary_tags, nutri_score, nutri_grade,
    updated_at)
  VALUES (@id, @name, @brand, @category, @serving_size, @serving_unit, 'vendor', @vendor_id,
    @calories, @total_fat, @saturated_fat, @trans_fat, @cholesterol, @sodium,
    @total_carbohydrates, @dietary_fiber, @total_sugars, @protein,
    @ingredients_text, @allergens, @dietary_tags, @nutri_score, @nutri_grade,
    datetime('now'))
  ON CONFLICT(id) DO UPDATE SET
    name = excluded.name,
    brand = excluded.brand,
    category = excluded.category,
    serving_size = excluded.serving_size,
    serving_unit = excluded.serving_unit,
    vendor_id = excluded.vendor_id,
    calories = excluded.calories,
    total_fat = excluded.total_fat,
    saturated_fat = excluded.saturated_fat,
    trans_fat = excluded.trans_fat,
    cholesterol = excluded.cholesterol,
    sodium = excluded.sodium,
    total_carbohydrates = excluded.total_carbohydrates,
    dietary_fiber = excluded.dietary_fiber,
    total_sugars = excluded.total_sugars,
    protein = excluded.protein,
    ingredients_text = excluded.ingredients_text,
    allergens = excluded.allergens,
    dietary_tags = excluded.dietary_tags,
    nutri_score = excluded.nutri_score,
    nutri_grade = excluded.nutri_grade,
    updated_at = datetime('now')
`);

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function slugify(name: string): string {
  return name
    .toLowerCase()
    .replace(/['']/g, "")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

function buildFoodRecord(item: ChainMenuItem, chainName: string, vendorId: string) {
  const chainSlug = slugify(chainName);
  const itemSlug = slugify(item.name);
  const id = `chain-${chainSlug}-${itemSlug}`;

  // Calculate nutri-score (needs per-100g values)
  const servingG = item.serving_unit === "g" ? item.serving_size : item.serving_size * 1;
  const factor = servingG > 0 ? 100 / servingG : 1;

  const nutriResult = calculateNutriScore(
    {
      calories: item.calories * factor,
      totalSugars: item.total_sugars * factor,
      saturatedFat: item.saturated_fat * factor,
      sodium: item.sodium * factor,
      dietaryFiber: item.dietary_fiber * factor,
      protein: item.protein * factor,
    },
    item.category
  );

  const ingredientsText = item.ingredients_text || null;
  const allergens = ingredientsText ? detectAllergens(ingredientsText) : [];
  const dietaryTags = detectDietaryTags(ingredientsText || "", {
    total_carbohydrates: item.total_carbohydrates,
    protein: item.protein,
    total_fat: item.total_fat,
    total_sugars: item.total_sugars,
    dietary_fiber: item.dietary_fiber,
  });

  return {
    id,
    name: item.name,
    brand: chainName,
    category: item.category,
    serving_size: item.serving_size,
    serving_unit: item.serving_unit,
    vendor_id: vendorId,
    calories: item.calories,
    total_fat: item.total_fat,
    saturated_fat: item.saturated_fat,
    trans_fat: item.trans_fat,
    cholesterol: item.cholesterol,
    sodium: item.sodium,
    total_carbohydrates: item.total_carbohydrates,
    dietary_fiber: item.dietary_fiber,
    total_sugars: item.total_sugars,
    protein: item.protein,
    ingredients_text: ingredientsText,
    allergens: allergens.length > 0 ? allergens.join(",") : null,
    dietary_tags: dietaryTags.length > 0 ? dietaryTags.join(",") : null,
    nutri_score: nutriResult.score,
    nutri_grade: nutriResult.grade,
  };
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

function main() {
  console.log("=== Restaurant Chain Nutrition Import - Batch 6 (Sit-Down) ===\n");

  let totalItems = 0;
  let totalChains = 0;

  const beforeCount = (
    db.prepare("SELECT COUNT(*) as c FROM foods WHERE source = 'vendor'").get() as any
  ).c;

  const importAll = db.transaction(() => {
    for (const chain of chains) {
      const chainSlug = slugify(chain.chain);
      const vendorId = `chain-${chainSlug}`;

      // Create vendor record
      upsertVendor.run({
        id: vendorId,
        name: chain.chain,
        type: "restaurant",
        api_key: generateApiKey(),
      });

      console.log(`  ${chain.chain}: ${chain.items.length} items`);

      // Import each menu item
      for (const item of chain.items) {
        const record = buildFoodRecord(item, chain.chain, vendorId);
        upsertFood.run(record);
      }

      totalItems += chain.items.length;
      totalChains++;
    }
  });

  importAll();

  // Rebuild FTS index
  console.log("\nRebuilding search index...");
  db.exec("INSERT INTO foods_fts(foods_fts) VALUES('rebuild')");

  const afterCount = (
    db.prepare("SELECT COUNT(*) as c FROM foods WHERE source = 'vendor'").get() as any
  ).c;

  console.log(`\n=== Done! ===`);
  console.log(`Chains imported: ${totalChains}`);
  console.log(`Menu items processed: ${totalItems}`);
  console.log(`Vendor foods before: ${beforeCount}`);
  console.log(`Vendor foods after: ${afterCount}`);
  console.log(`New items added: ${afterCount - beforeCount}`);
}

main();
